### ISSUE TITLE
No map is available in-game.

### ISSUE THREAD

**Issue by AtSomeonee** [tModLoader/tModLoader#1000]
The title says it all. There is no minimap on TmodLoader as well as no button in the inventory to open the map, either. I'm not sure if it's part of one of the mods that I'm using, but I'm highly doubtful about that, since when playing with my friend on a modded world he had access to it while I didn't.

**Comment by JavidPack** [comment]
The game disables the minimap when it thinks your computer can't handle it, to enable it again, go to Settings->General->Map Disabled/Enabled and make it enabled, then go back to the main menu. I'm not sure if you need to restart or not for it to take effect.
