### ISSUE TITLE
Crash after entering mushroom biome

### ISSUE THREAD

**Issue by SimplyRobotic** [tModLoader/tModLoader#1003]
### Description
Crash occurs after entering a mushroom biome. It might be a problem with one of my mods. 

### Log file
[client.log](https://github.com/tModLoader/tModLoader/files/4855862/client.log)

### Steps to reproduce

1. Log into world, descend into mushroom biome
2. break a few blocks/tiles
3. crash occurs

### Expected behavior 
Crash should not happen

### Actual behavior
Software gives error message and closes.

### Reproduction frequency
Every time I try going back into the biome.

### Additional Information
mods loaded: Thorium, Elements Awoken, Magic Storage, Reduced Grinding, Imksushi's mod, AFKPets, AlchemistNPC, Banner Bonanza, Builder essentials, Lootbags, Faster Tools, MrPlague's Authentic Races, Player location saving, Subworld Library, Autotrash, Boss Checklist, Recipe Browser, Omniswing, No More Tombs, Max Stack Plus Extra, Luiafk, Boss Cursor, Yet Another Boss Health Bar, Begone, Evil!, Veinminer.

mods unloaded: Mod of Redemption, Randomizer mod, Cheat Sheet, HERO's Mod

**Comment by JavidPack** [comment]
You'll have to narrow this down to the mod causing the issue by disabling mods until you discover which mod is at fault. The log doesn't give a good hint unfortunately.

**Comment by JavidPack** [comment]
Judging by the hooks I see registered by mods, it seems like SubworldLibrary is a good candidate

**Comment by SimplyRobotic** [comment]
alright, I'll turn it off and see if it does it again. It was a weird issue
because it was this specific mushroom biome. Thank you for your help :)
