### ISSUE TITLE
Wrong version

### ISSUE THREAD

**Issue by Nimond** [tModLoader/tModLoader#1016]
### Description
When I start tModLoader starts terraria v1.3.5.3  

### Log file
[https://gist.github.com/Nimond/da0a4f60d3da20229e19938d12f291f5](log)  

### Steps to reproduce
1. Install Terraia from Steam
2. Install tModLoader from steam or github
3. Copy `steam_appid`, `steam_api.dll` and `CSteamworks.dll` in tModLoader folder
4. Run .exe from tModLoader dir

### Expected behavior 
1.4.0.5 version like in steam terraria

### Actual behavior
1.3.5.3 version

### Reproduction frequency
2 times with steam tModLoader and 2 times with tModLoader from github

### Additional Information
windows 10

**Comment by Itorius** [comment]
tModLoader hasn't been updated to 1.4 yet.

**Comment by Jofairden** [comment]
Your confusion may come from the fact you have 1.4 Terraria installed and installed TML onto that
But TML is still separate. We do actually need the 1.4 Files so TML works with your 1.4 installation, but TML itself is not 1.4 yet. I hope that clarifies things.

**Comment by Nimond** [comment]
@Jofairden  @Itorius 
If I will build and install from 1.4 branch would it work? Or it's still raw?
When will be the release?

**Comment by Jofairden** [comment]
Using the 1.4 branch is far from recommended as it's being worked on daily, and well quite frankly, breaks like at least every 5 minutes. Most of the hooks don't even work.
