### ISSUE TITLE
My tModLoader (GOG version) isn't working in any way!

### ISSUE THREAD

**Issue by FakeTheModder** [tModLoader/tModLoader#1021]
I'm new on using mods in Terraria, so I just wanted to install tModLoader for the first time.

I followed all the steps for the GOG version installation, but when I open the tModLoader exe, this happens:

".. \Terraria\Terraria.exe is not the unmodified Terraria executable.

GOG installs must have the unmodified Terraria executable to function.

If you patched the .exe, you can create a copy of the original exe and name it 'Terraria_v<VERSION>.exe"

My vanilla Terraria is 1.4.0.4, so I thought I should bring a 1.3.5.3 Terraria.exe to the tModLoader folder, but this didn't work and the same issue happens.

I don't know what to do, I really want to mod my Terraria.

[2020-07-16-5.zip](https://github.com/tModLoader/tModLoader/files/4935324/2020-07-16-5.zip)

**Comment by FakeTheModder** [comment]
Sorry, I think this is the log.
[client.log](https://github.com/tModLoader/tModLoader/files/4935336/client.log)

**Comment by Mirsario** [comment]
tML currently requires 1.4.0.**5** vanilla, with no backwards compatibility in terms of hash-checks. Install that version, and tML next to it in 'tModLoader' folder, and it'll work.

**Comment by FakeTheModder** [comment]
Do I just need to change the .exe or do I have to reinstall the game?

**Comment by Mirsario** [comment]
Exe should be enough.
