### ISSUE TITLE
mod browser issue in linux

### ISSUE THREAD

**Issue by houku** [tModLoader/tModLoader#1022]
i know the title might throw off the wrong impression, like "who plays games in linux" or "who is a terraria player in linux", well, i am, and im getting an issue in which i would imagine doesnt exist in windows or mac, and is a thow away problem because "who uses linux to play games", well, my issue is that the mod browser works fine, but when i try to download mods, it shows the load, but doesnt download, when i go to http://javid.ddns.net/tModLoader/DirectModDownloadListing.php i can see MOST of the mods, but not all of them, some of the main ones i use, and it downloads fine, but i DONT want to go to the site and look at mods that dont have pics so i can see info about them when it doesnt have pictures, and i cant see any info without opening a new tab, which is annoying for me, plz fix it, i love playing terraria with mods,
and yes, i am the small linux community that plays terraria, so what? im still a terraria player, no less then anyone else

**Comment by JavidPack** [comment]
We are aware of the issue. You can see workarounds here : https://github.com/tModLoader/tModLoader/issues/908

Duplicate, closed
