### ISSUE TITLE
TML 1.4 beta multiplayer issues with locking main thread

### ISSUE THREAD

**Issue by Lanboost** [tModLoader/tModLoader#1024]
### Description

In the 1.4 beta code branch in netplay.cs.patch we change default terraria code with
```
@@ -360,7 +_,7 @@

 		private static void UpdateClient() {
 			if (Main.netMode == 1 && Connection.Socket.IsConnected() && NetMessage.buffer[256].checkBytes)
-				NetMessage.CheckBytes();
+				InvokeOnMainThread(() => NetMessage.CheckBytes());
 		}
@@ -421,6 +_,7 @@
```

Aka it is forced to invoke on the main thread. However when starting a multiplayer session this is already in the main thread and therefore locks and hangs the entire program. This change should most likely be reverted to use default Terraria behavior.

### Steps to reproduce

Use latest 1.4 beta and try to start a multiplayer session, application will hang.

### Additional Information

Im not sure if it is legacy that the change force main thread invocation (aka that was needed before) but for now it seems as if its causing issues

**Comment by Mirsario** [comment]
Reverted it, thanks. We haven't really got to testing multiplayer yet, because there are some core issues right now. Like, mods with dusts in them (ExampleMod) break servers, due to Rartrin's recent autoloading change.
