### ISSUE TITLE
Savedirectory command has no impact while debugging

### ISSUE THREAD

**Issue by Agrair** [tModLoader/tModLoader#1025]
### Description

I have “-savedirectory “D:\Terraria Saves”” in the command parameters debug field, but when actually debugging, it just builds to the normal Documents/My Games, but the debugging runs on my custom folder, so I can’t actually debug the mod unless I copy all my stuff over to Documents/My Games

### Log file

**N/A**

### Steps to reproduce

Already listed.

### Expected behavior 

I should be able to debug the mod using the custom directory, or it should at least automatically copy the mod to the desired directory I gave it.

### Actual behavior

Already listed

### Reproduction frequency

Every single time.

**Comment by Chicken-Bones** [comment]
Duplicated by #1072
