### ISSUE TITLE
Unable to download specific mods from mod browser

### ISSUE THREAD

**Issue by Pkylik** [tModLoader/tModLoader#1026]
### Description

Unable to download Calamity Mod, the screen flashes saying download without any progress without downloading anything
The first time i've downloaded it it was successful but it said it was not signed by the mod browser, downloading from the web results the same
### Log file

[client.log](https://github.com/tModLoader/tModLoader/files/4975421/client.log)

### Steps to reproduce

1. Open mod browser
2. Search for calamity mod
3. Click download for Calamity Mod (no calamity music)

### Expected behavior 

It should download with no problems
### Actual behavior

The download bar stays at 0 with the screen swapping from browser to download and back really fast, does sometime stay on for a few seconds but just goes back to the browser
### Reproduction frequency

Its 100% so far
### Additional Information

I am on a Late 2011 25.5 inch iMac running on MacOS High Sierra 10.13.6, Terraria v1.3.5.3, tModLoader v0.11.7.5

**Comment by direwolf420** [comment]
https://github.com/tModLoader/tModLoader/issues/921

**Comment by Solxanich** [comment]
Closing per the comment from Mirsario in #921 .
This is fixed in tmod 1.4, and 1.3 has been moved to emergency fixes only so this won't be fixed in 1.3.

Follow the workarounds in 1.3 if needed.
