### ISSUE TITLE
tModLoader launching terraria 1.3.5.3 help

### ISSUE THREAD

**Issue by GlamboX** [tModLoader/tModLoader#1037]
I have the latest tmodloader version and the gog version of terraria, but when i start tmodloader it launches terraria 1.3.5.3 even tho i uninstalled it. I tried to do as said in another post, by reinstalling terraria 1.3.5.3, copying the terraria.exe to the tmodloader folder and renaming it, but that still doesnt work, please help.

**Comment by Mirsario** [comment]
tML for 1.4 is not yet ready, and won't be for many many months.
