### ISSUE TITLE
Modded Chests can't be mined/picked up in multiplayer

### ISSUE THREAD

**Issue by greenskye** [tModLoader/tModLoader#1039]
### Description

Placing any chest created by any mod, the chest cannot be mined/picked up again in multiplayer. The chest is empty and not locked.

### Log file

[client.log](https://github.com/tModLoader/tModLoader/files/5023184/client.log)

### Steps to reproduce

1. Install mod that adds new chest (Tested with Calamity, Thorium, Ultranium each on their own)
2. Host world with dedicated server
3. Place chest
4. Attempt to mine/pickup empty chest
5. Fail

### Expected behavior 

Empty chests should be able to be picked up

### Actual behavior

Empty chests cannot be picked up

### Reproduction frequency

100%

### Additional Information

Loading world in single player allows modded chest to be picked up

**Comment by ExterminatorX99** [comment]
The call to [active()](https://github.com/tModLoader/tModLoader/blob/master/patches/tModLoader/Terraria.ModLoader/TileLoader.cs#L340) seems to return different values on single player and server, thus causing the [`partiallyDestroyed`](https://github.com/tModLoader/tModLoader/blob/master/patches/tModLoader/Terraria.ModLoader/TileLoader.cs#L337) variable to not be set to `true`, which causes the call to [`KillMultiTile`](https://github.com/tModLoader/tModLoader/blob/master/patches/tModLoader/Terraria.ModLoader/TileLoader.cs#L358) to not be reached

**Comment by ExterminatorX99** [comment]
Any chance of this making it into release before 1.4?

**Comment by Mirsario** [comment]
The commit above is for master, which is 1.3, not 1.4. So, yes.

**Comment by ExterminatorX99** [comment]
I saw that, but is there any hint to when the update will be released?

**Comment by PseudoCoffee** [comment]
From my digging in the code I found out IF that handles chest destruction is written wrong, i took the original code and renamed the variables to be easier to understand:
                                //operationType
                                //1 is destroy vanilla chests
                                //3 is destroy dresser
                                //5 is destroy crystal chest category, same as regular chest but different sprite png maybe??
                                //101 is modded chest destroy
                                //103 is modded dresser drestroy
if (operationType == 1 && (Main.tile[x_coord, y_coord].type == 21 || (operationType == 101 && TileID.Sets.BasicChest[Main.tile[x_coord, y_coord].type])))

vanilla chests work as intended but modded ones require operation type to be BOTH 1 and 101 which is logically impossible.

previous tmodloader if had:

if ((operationType == 1 && Main.tile[x_coord, y_coord].type == 21) || (operationType == 101 && TileID.Sets.BasicChest[(int)Main.tile[x_coord, y_coord].type]))
					
which is correct.

Furthermore if the if is false next lines will attempt to spawn a dresser over the tile which it obviously fails.
