### ISSUE TITLE
Own mod won't allow 2 weapons

### ISSUE THREAD

**Issue by GalaxyS29** [tModLoader/tModLoader#1044]
My mod only allows one weapon. I don't know what I'm doing wrong, but when I create another .cs file, it's like nothing actually imports (Terraria.ID and Terraria.ModLoader) and nothing works.

**Comment by JavidPack** [comment]
If you'd like programming help, come to the discord chat. This issue tracker is for actual bugs in tModLoader, not programming help.

https://tmodloader.net/discord
