### ISSUE TITLE
Whenever i try to save to cloud (character or a world) it just ends up deleting itself. 

### ISSUE THREAD

**Issue by bruhcom** [tModLoader/tModLoader#1052]
### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [And so on...]

**Comment by JavidPack** [comment]
Most likely you are hitting the steam cloud quota, which is shared between tmod and terraria. You didn't post your logs, so I don't know. In any case, we are working on a fix, but either remove a bunch of vanilla worlds from cloud or don't use cloud for now.
