### ISSUE TITLE
Is it just on my end, or is the server down?

### ISSUE THREAD

**Issue by ForTheFail** [tModLoader/tModLoader#1054]
Sorry if this is a stupid question. Says Mod Browser OFFLINE (unknown)

**Comment by ForTheFail** [comment]
Is it compatible with the latest version?

**Comment by ForTheFail** [comment]
Looks like it is indeed down. 
https://www.isitdownrightnow.com/javid.ddns.net.html

**Comment by Mirsario** [comment]
![image](https://user-images.githubusercontent.com/6795251/90345885-2f4dcf00-e02d-11ea-846e-1e27f539a35f.png)
