### ISSUE TITLE
ModContent.TryGetTexture is super slow.

### ISSUE THREAD

**Issue by Mirsario** [tModLoader/tModLoader#1055]
![image](https://user-images.githubusercontent.com/6795251/90394181-dc126580-e09a-11ea-8b4e-d40a865bf359.png)

It seems like the changes in content management that were introduced with the steam release are now causing some pretty legit performance issues for people. From what I figured out when skimming through the code, we need to:
- Do string.IsNullOrWhitespace checks at the start of TryGetTexture.
- Optimize TMLContentManager.ImageExists with a preinitialized list of image files that exist, to avoid bugging the OS through File.Exists.

Another note: SplitName call in TryGetTexture can throw exceptions, not very welcome in a Try method.

**Comment by Chicken-Bones** [comment]
Calls to this method should be cached (outside not inside), the line int hat profile is `TryGetTexture(modProjectile.GlowTexture` which really could should be a `Texture2D` returning method with a `??= TryGet`

We could cache a list of known `ImageExists` responses in a bool dict which is faster than polling the OS, but slower than not looking up the dict at all.

In general I agree on `Try` methods not throwing for any reason, but in this case it's kinda annoying to decouple, and I think it's a good reason to throw an exception. Why request a texture with malformed path ("" excluded)

**Comment by Mirsario** [comment]
I partially fixed this for 0.11.7.6, and used a HashSet, as dynamic dictionaries could grow giant.
