### ISSUE TITLE
ModItem data wiped when dropping an item in a certain way

### ISSUE THREAD

**Issue by Rebmiami** [tModLoader/tModLoader#1060]
### Description
If a favorited item is picked up and then you try to drop it by right-clicking outside of the inventory, ModItem data (referring to variables declared in the ModItem class) mysteriously vanishes into the void.

### Log File
Not applicable.

### Steps to reproduce
1. Mark a modded item as favorite (It's best if the chosen item has some easily testable variables, like a weapon with several modes)
2. Pick up the item
3. Right click outside of the inventory

### Expected behavior
ModItem data is preserved 

### Actual behavior
ModItem data is lost (class variables are set to the value assigned when declaring the member, not to be confused with `SetDefaults()`)

### Reproduction frequency
100%

### Additional information
Here's a gif showing the issue:
![gt89VOKBoD](https://user-images.githubusercontent.com/59275598/90985109-a14f7800-e547-11ea-8122-d2fba3ac85af.gif)
This is a modded item with a few ModItem members (int `Charge`, int `MaxCharge`, and Color `BatteryColor`). They are assigned -1, 0, and Color.White on declaration, and they are "reverted" to those values. `SetDefaults()` sets them to the intended values, but it doesn't seem to be called. The "-1" changing to "0" is unrelated and should be ignored.

This is likely not caused by any specific mod, as it still happens with only Cheat Sheet, Modder's Toolkit, and an unreleased version of a content mod I'm developing enabled. (which was only used for an example)

I suspect the issue lies in `dropItemCheck()` or `DropSelectedItem()` in Player.cs.

**Comment by Solxanich** [comment]
Linking explicitly to #265  so this doesn't get lost as easily

**Comment by direwolf420** [comment]
@Rebmiami Hey, if your issue still occurs (regardless of tml version), can you post the full code of the item? It may be related to `Clone` hook misuse (or lack thereof).

**Comment by JavidPack** [comment]
We need someone to test this with a ModItem that is properly implemented. This might be modder error.

**Comment by Chicken-Bones** [comment]
Fixed as far as I can tell
