### ISSUE TITLE
Make Get/TryGet consistent across all of tML

### ISSUE THREAD

**Issue by Chicken-Bones** [tModLoader/tModLoader#1062]
### Description
The pattern has been implemented in `ModContent` now for `XType` lookup. We should replicate this pattern across the rest of our content dictionaries. 

- [x] `Mod`
- [ ] ~~Instanced `ModWorld`~~
- [x] Instanced `ModPlayer`
- [x] Instanced `GlobalX`

### What does this proposal attempt to solve or improve?
`Get` returning `null` is a gotcha. Yeah we get used to it, but having it throw an exception, and getting modders used to `TryGet` everywhere they're not sure of a result seems like a good idea to me. 

### Which (other) solutions should be considered?
Keep it the old ways, with nulls.

**Comment by davidglassborow** [comment]
Maybe too much of a large step, but c# 8 non-nullable reference type annotations might help here

**Comment by Mirsario** [comment]
> 
> 
> Maybe too much of a large step, but c# 8 non-nullable reference type annotations might help here

Yes, but we need to move to .NET Core first to allow mods to use C# 8

**Comment by davidglassborow** [comment]
You can use non-nullable (+ most other C# 8 features) on framework - https://www.infoq.com/articles/CSharp-8-Framework/
