### ISSUE TITLE
BuffDefinition for ModConfig

### ISSUE THREAD

**Issue by Rebmiami** [tModLoader/tModLoader#1068]
### Description
Add a `BuffDefinition` to ModLoader.Config. It would function like `ItemDefinition`, `NPCDefinition`, and `ProjectileDefinition`, but for buffs.

### What does this proposal attempt to solve or improve?
Specifying buffs in ModConfig is very difficult at the moment. Modders could specify a selection of hand-picked buffs, but this severely limits the number of buffs available. Modders could also allow the user to specify a buff ID, but this would require the user to look up IDs (which they may not want to do) and doesn't work with modded buffs. A `BuffDefinition` would not have any of those issues.

### Which (other) solutions should be considered?
The methods for specifying buffs listed in the above section. (modders selecting some buffs and allowing players to select one of them, or allowing users to select a buff by specifying a buff ID)

**Comment by Setnour6** [comment]
Good news, it seems that it's implemented in #3827
