### ISSUE TITLE
textures disappear - problem.

### ISSUE THREAD

**Issue by policere** [tModLoader/tModLoader#1070]
### Textures disappear - problem.
I show only screenshots, version of terraria 1.3.5.3, tModLoader version 0.11.7.5

### Log file
[client.log](https://github.com/tModLoader/tModLoader/files/5177904/client.log)

### Screenshots
![image](https://user-images.githubusercontent.com/59689715/92303025-f93fa300-ef79-11ea-8196-3fc5f8b360e2.png)
![image](https://user-images.githubusercontent.com/59689715/92303036-0197de00-ef7a-11ea-8103-9bbeb2c09c54.png)

**Comment by Mirsario** [comment]
> Executable: C:\Program Files (x86)\Terraria\tModLoader.exe
I'm guessing you just installed tML incorrectly. You need to install it into a directory that's placed next to the "Terraria" one, not just inside it. Follow this: https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#manual-installation

**Comment by JavidPack** [comment]
Stale issue, assumed to be fixed, closing.
