### ISSUE TITLE
[Bug] Terraria World Partially Resets Progress

### ISSUE THREAD

**Issue by ClintMcKenzie** [tModLoader/tModLoader#1071]
I'm having an issue where I play in a world and make changes to the world (building a boss arena etc), and I log out and close TModLoader, but when I log back into the world, changes that I made from a seemingly arbitrary and random point in time to when I saved and exited from the world are reset.  Three boss arenas have been deleted in such a fashion.  Boss progression made from that point onwards is reset as well.  So far, chests seem to retain their items (not reset), and my character is not reset.
I'm using these mods: Calamity Mod, Calamity Mod Music, Boss Checklist, Recipe Browser, Magic Storage, Veinminer, ImkSushi's Mod, and MrPlagueRaces
For the record, I am not certain that this issue is caused by TModLoader or any mods, but I have not encountered this issue before on vanilla Terraria
Strangely, this reminds me of the dupe bug where you put items in a chest, turn off autosave, and alt-f4 the tab, BUT I have autosave on and I always use 'save and exit' to exit a world
Should any other info be needed, feel free to ask.
Thank you!

**Comment by zauberparacelsus** [comment]
What that sounds like is either [A] the game is crashing while it is saving and exiting, or [B] some exception is preventing the save from going through.  I have every one of those mods (and more) and haven't experienced the issue, though, so it may not be related to them.

What operating system are you running?

**Comment by ClintMcKenzie** [comment]
I'm running Windows 10.  I haven't played Terraria before now on Windows 10, so that could be what's causing the issue.  How could I test this?  Also, if the game is crashing while saving and exiting, I am not notified of the crash.

**Comment by JavidPack** [comment]
This sounds like the calamity bug. That mod in it's current version resets world saves ever since the update. You can visit their discord for more information

**Comment by ClintMcKenzie** [comment]
Thank you Javid, I'll look into that

**Comment by ClintMcKenzie** [comment]
Yup, a known Calamity bug with a known solution.  Thank you, JavidPack!
