### ISSUE TITLE
Debugging doesn't work with custom save directory

### ISSUE THREAD

**Issue by Agrair** [tModLoader/tModLoader#1072]
### Description
When I debug my mod with the debug command arguments "-savedirectory D:\Terraria Saves", the mod will be built to the original My Games folder, which breaks debugging.

### Steps to reproduce

1. Make a mod
2. Open it in VS
3. Use a custom save dir
4. Debug

### Expected behavior 
I should be able to debug my mod, regardless of save directory. The mod should be building to D:\Terraria Saves

### Actual behavior
No symbols are loaded. Game runs fine, the mod gets built, but it can't attach to the debugger because it's in the wrong path.

### Reproduction frequency
Every single time

### Additional Information
It's a minor bug tbh. But annoying. Also it was a while since I discovered this, but I forgot to make an issue for it. It's definitely nothing new. And my description might be a bit off, I just don't really debug anymore so I don't remember precisely what happens. I copied the info off of some old Discord messages.

**Comment by Chicken-Bones** [comment]
Did you add the savedirectory flag to the build command in the csproj?

**Comment by Agrair** [comment]
No, via debug. I didn't even consider that. That'll probably fix it.

**Comment by Agrair** [comment]
Ok so that literally destroyed my VS. For whatever reason, tMLServer.exe wanted to run an actual server, and then it was just repeating the select a world prompt lmfao.
```
"$(tMLBuildServerPath)"
-build "$(ProjectDir)\" -eac "$(TargetPath)"
-savedirectory "D:\Terraria Saves"
```

**Comment by Agrair** [comment]
Ok so I moved them all on the same line and it works. Question mark. I'll get back to you once I fix the tons of bugs in my mod.

**Comment by Agrair** [comment]
Damn it worked. :+1:
