### ISSUE TITLE
.NET Core 3.1/Full FNA support

### ISSUE THREAD

**Issue by Dual-Iron** [tModLoader/tModLoader#1076]
### Description
Port the tModLoader project to .NET Core 3.1 and make Windows run on FNA.

### What does this proposal attempt to solve or improve?
It will keep the tModLoader project up-to-date and let modders/tMod utilize the latest features for the .NET/FNA programming environment.

### Which (other) solutions should be considered?
Using Monogame, I guess? We already use FNA.

**Comment by Mirsario** [comment]
This is planned, yes. I'll port windows to FNA after 1.4.1, and will look at .net core after.

**Comment by stefnotch** [comment]
Is it actually worth looking at .NET Core 3.1 with .NET 5 scheduled to release in November?

**Comment by Mirsario** [comment]
.NET 5 is still .NET Core, so updating to it is doable with a press of a button.

**Comment by Dual-Iron** [comment]
Porting to .NET Core 3.1 in PR #1086

**Comment by mburszley** [comment]
Just to note, .NET 5 represents the merging of Mono/Xamarin, so there may be more APIs available to aid in this work.

_But_ I'm not sure you actually gain anything.  .NET Framework 4.8 is feature-complete and it's not like Terraria will be built on .NET Core at any point in the future.

**Comment by Rartrin** [comment]
.NET 5.0 came out on a few days ago. Do we want to go ahead and make the jump to it, or hold off for now until more things explicitly support it?

**Comment by Dual-Iron** [comment]
> .NET 5.0 came out on a few days ago. Do we want to go ahead and make the jump to it, or hold off for now until more things explicitly support it?

I'd be fine with having it on this branch, it shouldn't conflict with the .NET Core port. Having C#9 and newer support would be nice.

Just make sure to test everything and make sure nothing breaks in the process. Again, I doubt it will, but it's worth the tiny bit of effort.
