### ISSUE TITLE
Cursor//Arrow Keys Stop Working After Mods Are Loaded

### ISSUE THREAD

**Issue by Adventurous-Spaghet** [tModLoader/tModLoader#1077]
### Description
As the title says, the controls simply stop functioning after mods are done loading... I had done a clean install of Terraria after update 1.4, so it was all vanilla no tmodloader files and I backed-up my mod list into a mod pack, I reinstalled tmoadloader (From The Steam Page) today and downloaded all my mods... after it was done initializing them and loading them I noticed the cursor wouldn't move, and keyboard also didn't work, restarted several times to the same result

### Log file
![image](https://user-images.githubusercontent.com/70969589/92507405-297a8200-f1c4-11ea-9213-eb99b4dc9b61.png) 
 HUH???

![image](https://user-images.githubusercontent.com/70969589/92507515-59298a00-f1c4-11ea-8e45-23fa78addb04.png)

![image](https://user-images.githubusercontent.com/70969589/92508253-8cb8e400-f1c5-11ea-88e4-3ac0848163d4.png)

It is a log file wth -_-

EDIT: There's something wrong with that file because even Google Drive didn't wanna take it :P

[client.log](https://github.com/tModLoader/tModLoader/files/5189977/client.log)

EDIT: I have no idea what was wrong with the file but it was like 31MB so too heavy to upload here? deleted it and let the loader create a new one, so here is it, hope it helps.

### Steps to reproduce

1. [Open game]
2. [Let mods load]
3. [Scream in frustration because you've restarted the game several times and it keeps happening]

### Expected behavior 
I would expect to be able to play the game after the mods are done loading otherwise, there's not much point to tmodloader

### Actual behavior
Not sure what's going on

### Reproduction frequency
This happens every time mods are done loading

### Additional Information
Nope... Not the I'm aware of anyway

**Comment by direwolf420** [comment]
Plug in an audio device into your computer. 
```cs
[11:28:43] [1/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.UpdateAudio()
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
```

**Comment by Adventurous-Spaghet** [comment]
What does that mean though? like literally an audio device as in an audio card? driver? those are all up to date (dedicated audio card?) My PC is using its Realtek integrated chip and it's working just fine, all games work fine with it, vanilla Terraria works fine, my headset is plugged-in so are my speaker, never had this problem before until today, not sure what am I supposed to do :c

![image](https://user-images.githubusercontent.com/70969589/92524820-fa720980-f1df-11ea-863f-07fa4f6b2423.png)
 
Sorry I have my Windows set in Spanish :P

Also, tmodloader was also working just fine when I installed it, this only started happening when the mods were installed and loaded, could it be one of them causing this issue?

This is the mod list I've been always using, changed the extension to .log so I could post it

[ModPack.json.log](https://github.com/tModLoader/tModLoader/files/5190935/ModPack.json.log)

**Comment by Mirsario** [comment]
> Could it be one of them causing this issue?

Yes, very much so. Pinpoint the issue to one mod. The two that look suspicious to me are 'EAMusic' and 'Consolaria'.

**Comment by Adventurous-Spaghet** [comment]
Alright, seems that in fact, it was the 'Consolaria' mod causing the issue... uninstalled it and it's working fine now, thanks for the help ^_^

**Comment by Hasstur** [comment]
I just tried your modpack, everything works fine to me, bruh
