### ISSUE TITLE
ModWorld.Initialize isn't called prior to NetReceive in multiplayer

### ISSUE THREAD

**Issue by direwolf420** [tModLoader/tModLoader#1087]
### Description
is it a design flaw of tml? ModWorld, in it:
`public static Dictionary<string, bool> toolEnabled;`

in the `Initialize` hook:
`toolEnabled = new Dictionary<string, bool>();`

In multiplayer, if the client just goes straight into multiplayer and joins a server, he will get stuck forever because `toolEnabled` is null during `NetReceive` (where it reads the values from the server), because `Initialize` isn't called prior. You can fix it by initializing the variable before receiving yourself though, but shouldn't `Initialize` be called atleast once before starting to receive things, as `Initialize` implies that it initializes all variables for the ModWorld to be fully usable?

Code that would freeze:
```cs
toolEnabled["first"] = reader.ReadBoolean();
```

Code that wouldn't freeze:
```cs
toolEnabled = new Dictionary<string, bool>();
toolEnabled["first"] = reader.ReadBoolean();
```

### Expected behavior 
`Initialize` hook being ran before receiving data from the server

### Actual behavior
`NetReceive` is ran before `Initialize`

**Comment by Mirsario** [comment]
@ModernMAK Dire was talking about ModWorld.NetReceive, not ModItem's.

**Comment by ModernMAK** [comment]
> @ModernMAK Dire was talking about ModWorld.NetReceive, not ModItem's.

Thanks, that would explain why I couldn't reproduce.
I was using the wiki to find out where NetRecieve was, and saw it in ModItem. But a second glance shows it's in ModWorld as well, but it isn't placed in a `code block`.
