### ISSUE TITLE
Modded chests and dressers cannot be mined in multiplayer FIX.

### ISSUE THREAD

**Issue by PseudoCoffee** [tModLoader/tModLoader#1093]
### Description

Chests/Dresser cannot be mined.

### Steps to reproduce
1. Install any mod in terraria that adds a chest or a dresser.
2. Place dresser/chest.
3. Attempting to mine it will always fail(cannot be mined) in multiplayer.

### Expected behavior 
Mining the chest and dropping an item.

### Actual behavior
Nothing happens.

### Reproduction frequency
Always on multiplayer.

### Additional Information

From my digging in the code I found out IF that handles chest destruction is written wrong, I took the original code and renamed the variables to be easier to understand:

In player.PickTile the following function is being called:

**NetMessage.SendData(34, -1, -1, null, 101, x, y, 0f, 0, Main.tile[x, y].type);**

34 is the chestsync message
-1 and -1 means it sends the message to all players
null is text which is not used here
101 is operationType which is the number used for modded chests
x is the chest tile on x axis
y is the chest tile on y axis
0f is unknown for now
0 is the chestID but is not needed for this operation since the coordinates are given
Main.tile[x, y].type is the modded chest tile type

//operationType
//1 is destroy vanilla chests
//3 is destroy dresser
//5 is destroy crystal chest category, same as regular chest but different sprite png maybe??
//101 is modded chest destroy
//103 is modded dresser destroy
if (operationType == 1 && (Main.tile[x_coord, y_coord].type == 21 || (operationType == 101 && TileID.Sets.BasicChest[Main.tile[x_coord, y_coord].type])))

Vanilla chests work as intended but modded ones require operation type to be BOTH 1 and 101 which is logically impossible.

Previous tmodloader versions had the following:

**if ((operationType == 1 && Main.tile[x_coord, y_coord].type == 21) || (operationType == 101 && TileID.Sets.BasicChest[(int)Main.tile[x_coord, y_coord].type]))**

which is correct, checks if operationType is 1 and is tile 21(chest sprite) or operation 101 and basic chest.

Furthermore if the if is false next lines will attempt to spawn a dresser over the tile which it obviously fails.

The line that attempts to destroy a dresser has issues similar to the one mentioned above.

**if ((operationType == 3 && Main.tile[x_coord, y_coord].type == 88) || (operationType == 103 && TileLoader.IsDresser((int)Main.tile[x_coord, y_coord].type)))**

using the following code will fix the issue:

**if ((operationType == 3 && Main.tile[x_coord, y_coord].type == 88) || (operationType == 103 && TileLoader.IsDresser(Main.tile[x_coord, y_coord].type)))**
					
After some testing I used HijackGetData(...) to change those 2 mentioned lines of code made the chests and dressers work as intended.

**Comment by JavidPack** [comment]
This was fixed in 99c2156c0e39c17960642692e740b1a926918fca, what's this issue for?

**Comment by PseudoCoffee** [comment]
Is that version released yet?

I only got this data from decompiling the current steam version so if it was unreleased, my bad.

**Comment by JavidPack** [comment]
No, it's not. In https://github.com/tModLoader/tModLoader/issues/1039 it shows it being closed 17 hours ago. There hasn't been a release since then.

**Comment by Chicken-Bones** [comment]
Good analysis though, thanks for giving all the information we'd need to fix it
