### ISSUE TITLE
"CanStackInWorld" hook for ModItem

### ISSUE THREAD

**Issue by TotallyNotAScalie** [tModLoader/tModLoader#1106]
### Description
A hook for ModItem which returns a boolean, and having a parameter for the item the given item instance is attempting to stack with. The return will determine if the two item instances should combine into one (stacking) with each other. It would also enable modders to create item => item collision interactions for various applications like crafting systems or NPC spawning.

### What does this proposal attempt to solve or improve?
Modders may wish to have items which have different stacking behavior in inventories and in the world, as it is currently the only way to stop items from stacking in-world is to set their maximum stack size to 1 or to hackily change it depending on it's state. This would allow for features such as drops that should visually appear seperate on the ground but stack in the inventory like currencies, more freedom in designing visuals related to item spawning, and possible applications for interactions between items in-world other than stacking.

### Which (other) solutions should be considered?
Possibly a more general hook concerning stack-ability, for additional control over the stacking behavior of items in inventories.

**Comment by Chicken-Bones** [comment]
Can you give us some specific examples of some items which could benefit from this? Rather than general possibilities?

**Comment by TotallyNotAScalie** [comment]
-An item which, when dropped, floats in a circle around a point, without combining in stack with others of the same type
-A item storing special data, such as a charge level, that can only stack with items of identical charge levels
-Some sort of "crystal shard" item that would drop in a large quantity on destroying a crystal, with unique sprites on the ground that would not stack, but would stack in the inventory under one sprite 
-Dropping some sort of "fire core" and "ice core" items on the ground together to create an explosion

**Comment by Chicken-Bones** [comment]
Excellent. Suggestion approved

**Comment by JavidPack** [comment]
So, we've had troubling discussions on how to implement a previously suggested CanStack hook (more generally, such as in the inventory.). This hook will have to come after we figure that one out, and piggy back on the logic. There are a lot of issues with stacking stackable items, and a large amount of logic that will need to be updated as well.

**Comment by Chicken-Bones** [comment]
I feel like an 'in world' stacking hook could be implemented separately though. It could only prevent items which could previously stack from stacking in the world, and allow for effects instead (if called on all disparate sets of items). The problem with general purpose can stack is that it's called in many different scenarios, but in this case it should be fine

**Comment by Itorius** [comment]
I also had the idea of implementing a CanStack hook for modded items. However due to the insane amounts of places where that would have to be implemented I decided not working on it (at least just yet).
