### ISSUE TITLE
Can't Interact with anything ingame!

### ISSUE THREAD

**Issue by poopysplinky** [tModLoader/tModLoader#1107]
i can interact with the menu and all that, but when I get into a world, i cant interact with anything

**Comment by Mirsario** [comment]
> Post your `.log` files from the following OS-dependent directory:
> 
> **On Windows:** `%userprofile%/Documents/My games/Terraria/ModLoader/Logs`
> **On Linux:** `~/.local/share/Terraria/ModLoader/Logs`
> **On Mac:** `~/Library/Application support/Terraria/ModLoader/Logs`

**Comment by poopysplinky** [comment]
how i do that?

**Comment by poopysplinky** [comment]
there are 3 thing is the logs folder, client, server and server 2

**Comment by poopysplinky** [comment]
and then an old folder

**Comment by Mirsario** [comment]
Send client.log.

**Comment by poopysplinky** [comment]
[Uploading client.log…]()

**Comment by poopysplinky** [comment]
its still uploading

**Comment by poopysplinky** [comment]
[client.log](https://github.com/tModLoader/tModLoader/files/5288691/client.log)

**Comment by poopysplinky** [comment]
there

**Comment by Mirsario** [comment]
That log has some errors caused by RecipeBrowser and "cool_jojo_stands". If removing one of those doesn't help - follow this flowchart: https://i.imgur.com/OFwbY09.png

For any additional help, it's better to talk in [tML's discord.](https://tmodloader.net/discord)

**Comment by poopysplinky** [comment]
thanks! removing the cool_jojo_stands mod fixed my game :D

**Comment by Mirsario** [comment]
@yeah-i-am The above issue has been caused by your mod. I have zero idea why you would use an SQL client inside a terraria mod.
