### ISSUE TITLE
Add new instance creation hook to ModItem to support declarative spawn sources and tables

### ISSUE THREAD

**Issue by Chicken-Bones** [tModLoader/tModLoader#1110]
## Summary
- Remove `CloneNewInstances`
- All new instances are cloned (either from the root `ModItem`, `Recipe.createItem` or a drop table, etc)
- Replace `OnCraft` with more generic `OnCreated(source, ref bool rollPrefix)`

## Details
When a player 'creates' an item by crafting, buying, opening a bag, or an item enters the world in another way such as loot drop or chest spawn, it might be time to roll some unique attributes. In vanilla, this just means prefixes, but mod items may want to randomise the colour, or add other properties. 

The tML pattern for modded content is to register a 'template' instance, normally autoloaded, and then to clone the template and attach it to the matching in world vanilla class. Modders familiar with OOP and struggling to deal with item identity, were frustrated with the restrictions of cloning (particularly the constructor being effectively ignored) and thus `CloneNewInstances` was born, defaulting to `false` the constructor and `SetDefaults` could handle the vast majority of content.

However, when creating recipes, it's sometimes desirable to make recipes which create a specific variant of an item, one with a specific prefix, or a unique name, or better stats. Recipes are declarative, with the result stored as a unique template instance which is shown in the crafting UI, and to support this declarative style, crafted items are always cloned from the recipe `createItem`, ignoring the `CloneNewInstances` flag. 

As seen in #1096 this clashes with the intended constructor pattern and requires modders to override `OnCraft` to point to their 'new variant' code. 

With tML moving to more declarative spawning mechanics (loot tables for NPCs, chests, and boss bags) we need a better solution.

I propose a new hook, `OnCreated(object source, ref bool rollPrefix)` where `source` can be one of `Recipe` `NPC` `LootBagOpen` `ChestSpawn` `PurchaseEvent` `BlockMined`. We can then remove the `CloneNewInstances` and `OnCraft` hooks, and make cloning from a template followed by a call to `OnCreated` be the default behaviour. 

Things to be discussed:
Naming
Common interface for creation sources?
How this might affect modders and their content

**Comment by Ozzatron** [comment]
There is nothing inherently special about crafting if all item creation events will be unified to cloning ModItem templates. However modders will want to know through which method the item is being created, and perhaps a lot of contextual information.

I suggest either an enum `ItemCreationContext` which would have the values `TileDrop / NPCDrop / Craft / Purchase / OpenLootBag / CreativeSpawn / Other` or a hierarchy of `ItemCreationContext` classes. The latter would allow stuffing in as much contextual data as modders would see fit into the context object, e.g. the NPC which dropped or sold the item, the tile which was mined, the Recipe instance used, and so on.

In the former case you'd simply check the enum value; in the latter the function would provide an `ItemCreationContext` abstract superclass and the modder would (if they cared) check what runtime type that instance was.

**Comment by Itorius** [comment]
Ozzatron's idea of having a `ItemCreationContext` superclass and then having derived classes seems good to me.

**Comment by Itorius** [comment]
This issue was already resolved in #1118.
