### ISSUE TITLE
Add a way to make tiles count as liquids in crafting

### ISSUE THREAD

**Issue by Mirsario** [tModLoader/tModLoader#1112]
The title. I'm not sure if this should be a Sets entry, or a hook.

**Comment by Itorius** [comment]
I think a `Sets` entry should be fine for most cases. However a hook would allow for custom behavior like fluid containers.

**Comment by Mirsario** [comment]
Of course, sets would be sufficient for those cases too, because it's always possible to do switching between 2 tile types, similar to the way doors work in vanilla.

**Comment by Chicken-Bones** [comment]
Now that `Recipe`s are based on `public static` `Condition`s which can be registered, it would be nice if there was a way to 'hook' conditions (and also tile requirements).

**Comment by Chicken-Bones** [comment]
Addressed in #1137, modded conditions can do similar, and use sets (or the coming soon tag system)
