### ISSUE TITLE
Can't create a server on Steam TMod, Gets stuck on Found Server

### ISSUE THREAD

**Issue by DuckyIsEpic** [tModLoader/tModLoader#1114]
Whenever I try to create a server on TMod it gets stuck on Found Server. I can sometimes fix this by restarting Steam but the only consistent way to do it seems to be restarting my entire PC which is a problem since it takes up to an hour to restart due to it requiring an un-completable update each time.
Whether I wait 2 mins or an hour it doesn't seem to load.

**Comment by JavidPack** [comment]
You forgot to post your logs. Most likely a mod you have is breaking the server, so the server log might have info on which mod to disable or other issues.

**Comment by Mirsario** [comment]
Closing this since it's old. Also, yeah, this is always a mod's fault, so requests for help with that best go into the discord server.
