### ISSUE TITLE
Meu tmodloader não tem som e eu não desativei ele

### ISSUE THREAD

**Issue by asbismo76** [tModLoader/tModLoader#1132]
### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [And so on...]

**Comment by Solxanich** [comment]
Future reference, title is: "My TmodLoader has no sound, and I did not disable audio myself".
Possible duplicate of other Audio issues: https://github.com/tModLoader/tModLoader/issues/1496, #1433, #998, etc.
