### ISSUE TITLE
Setup issues and wrong directories in 1.4

### ISSUE THREAD

**Issue by ajloveslily14** [tModLoader/tModLoader#1134]
### Description
When running setup.bat, all goes well until it tries to find setup.exe

When this is found, it can't be found
### Log file
No log file

### Steps to reproduce
1. Clone tModLoader
2. Click setup.bat
3. Get popup that says `Windows cannot find 'setup\bin\Debug\netcoreapp3.1\setup.exe'`

### Expected behavior 
Continue on setting things up.

### Actual behavior
setup crashes and fails

### Reproduction frequency
100%

### Additional Information
The file it's looking for is actually at `setup\bin\HPD\Debug\netcoreapp3.1\setup.exe`

**Comment by Mirsario** [comment]
I just made the bat always build to that directory. This is, however, most likely an issue with your system configuration.
https://stackoverflow.com/questions/46656363/visual-studio-code-c-sharp-project-has-incorrect-assembly-program-path-hpd

**Comment by Chicken-Bones** [comment]
This is actually a regression introduced by @Itorius in bdd11c7b0abef449a5ebafc4c7fa320fb305dd88

We should either just keep dotnet run (and maybe figure out a way to hide the console window) or find a better way to find the built location

**Comment by JavidPack** [comment]
Is this still an issue? Looks like we can add `--output <OUTPUT_DIRECTORY>`  to dotnet build or add `<OutputPath>` to setup.csproj, but I haven't seen this come up since this issue was made.

If we add a OutputPath property to the csproj, we can make the output path less nested and it won't break if we update framework at later dates.

**Comment by Chicken-Bones** [comment]
`<OutputPath>` is a desired solution. This is a low priority todo, the setup output path changes with the framework version used to run it. We should make it match the tModLoader framework version, but the issue here is that the `.bat` script needs to be updated as well, and it's easy to forget.

**Comment by JavidPack** [comment]
We've had another similar report even after the recent command line setup PR.

https://discord.com/channels/103110554649894912/1294346962807558255

Apparently HP computer set `Platform` to `MCD`, resulting in setup-gui.exe ending up in `setup\GUI\bin\MCD\Release\net8.0-windows`
