### ISSUE TITLE
TileLoader.Drop not called when destroying some tiles.

### ISSUE THREAD

**Issue by Neojin9** [tModLoader/tModLoader#1144]
### Description

TileLoader.Drop is called when destroying most tiles. Check2x2, Check3x4, etc., check TileLoader.Drop before dropping an item. The following tiles do not call TileLoader.Drop when destroyed and I am unable to stop these tiles from dropping their item: Check2x3Wall, Check3x2Wall, Check3x3Wall, Check4x3Wall, Check6x4Wall, DropDoorItem.

### What does this proposal attempt to solve or improve?

Allow code to prevent Wall Decorations and Doors from dropping their item when destroyed.

### Which (other) solutions should be considered?

Call TileLoader.Drop before dropping the tile's item.

**Comment by Mirsario** [comment]
Did you find this out about 1.3 or 1.4? There are definitely tons of this issue in 1.4, I think it was in patching TODO notes.

**Comment by Neojin9** [comment]
> Did you find this out about 1.3 or 1.4? There are definitely tons of this issue in 1.4, I think it was in patching TODO notes.

This is from tML v0.11.7.5, Terraria v1.3.5.3.

**Comment by Spiky-73** [comment]
In tML 1.4, I found other methods that do not call TileLoader.Drop :
 - Check2x1
 - Check2x5
 - Check3x5
 - Check3x6
 - CheckSunflower
 - CheckGnome
 - CheckChest

Also, there seems to be a bug in Check1x2. `TileLoader.Drop(num3, y, type)` is called but i believe it should be `num`, not `num3` as num3 is 0 or 1, not the x coord of the top-left corner.
