### ISSUE TITLE
Download a newer corlib or a newer runtime at http://www.mono-project.com/download

### ISSUE THREAD

**Issue by basictheprogram** [tModLoader/tModLoader#1145]
### Description

Download a newer corlib or a newer runtime at http://www.mono-project.com/download.

### Log file

Server is not starting so no logs to attach.

### Steps to reproduce

```
$ uname -a
Linux tmodloader 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/issue
Ubuntu 20.04.1 LTS \n \l
```
```
$ mono --version
Mono JIT compiler version 6.12.0.90 (tarball Fri Sep  4 14:02:38 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```
1. Download tModLoader.Linux.v0.11.7.7.zip
2. Download terraria-server-1411.zip
3. Unzip and put everything into /var/terraria
4. run tModLoaderServer
```
Corlib not in sync with this runtime: expected corlib version 149, found 36.
Loaded from: mscorlib.dll
Download a newer corlib or a newer runtime at http://www.mono-project.com/download.
```
5. Follow the posted [Troubleshooting](https://terraria.gamepedia.com/Server#Troubleshooting) steps

## Troubleshooting
If you encounter an error saying "Your mono runtime and class libraries are out of sync.", navigate within the Terraria directory and remove monoconfig, mscorlib.dll, and any files that begin with "Mono" or "System".
### Example instructions with Linux:
  * rm System*
  * rm Mono*
  * rm monoconfig
  * rm mscorlib.dll

6. Delete the  mscorlib.dll
7.  run tModLoaderServer (code attemps to load mscorlib.dll from /usr/lib/mono/4.5/)
```
Corlib not in sync with this runtime: expected corlib version 149, found 36.
Loaded from: /usr/lib/mono/4.5/mscorlib.dll
Download a newer corlib or a newer runtime at http://www.mono-project.com/download.
```
8. rm monoconfig
9. run tModLoaderServer
```
monoconfig not found!
```
_should probably update the troubleshooting guide_
10. touch monoconfig
11. run tModLoaderServer
```
Corlib not in sync with this runtime: expected corlib version 149, found 36.
Loaded from: /usr/lib/mono/4.5/mscorlib.dll
Download a newer corlib or a newer runtime at http://www.mono-project.com/download.
```
12. rm Mono*
13. run tModLoaderServer
```
Corlib not in sync with this runtime: expected corlib version 149, found 36.
Loaded from: /usr/lib/mono/4.5/mscorlib.dll
Download a newer corlib or a newer runtime at http://www.mono-project.com/download.
```
14.  rm System*
15.  run tModLoaderServer
```
Corlib not in sync with this runtime: expected corlib version 149, found 36.
Loaded from: /usr/lib/mono/4.5/mscorlib.dll
Download a newer corlib or a newer runtime at http://www.mono-project.com/download.
```
### Expected behavior 

tModLoaderServer should run successfull

### Actual behavior

```
Corlib not in sync with this runtime: expected corlib version 149, found 36.
Loaded from: /usr/lib/mono/4.5/mscorlib.dll
Download a newer corlib or a newer runtime at http://www.mono-project.com/download.
```

### Reproduction frequency

Every time

### Additional Information

Same results with the official Ubuntu [package](https://packages.ubuntu.com/focal/mono-devel).

**Comment by JavidPack** [comment]
There are a lot of issues here. First off, you don't need to do anything with Terraria to run a tModLoader server.

To run a tModLoader server, all you have to do is simply untar the Linux .tar file and run `./tModLoaderServer`. You can see a script here if you are interested: https://github.com/tModLoader/tModLoader/wiki/Command-Line#dedicated-server-self-hosted

By merging a Terraria server install, you are preventing the tModLoader executable from running.

If I were you, I'd delete all of what you did, then do the normal instructions. Vanilla Terraria is completely unrelated. Mono is also unrelated unless you are building mods, which you don't seem to be so don't touch Mono either.

**Comment by Mirsario** [comment]
If you do want to run system mono, you would just install it with a package manager and run `./tModLoaderServer-mono`. Zero need to mess with files.
