### ISSUE TITLE
Mod file in ModLoader didnt show up when downloaded and Mod Browser has not shown up on the title screen at all

### ISSUE THREAD

**Issue by BurntDirtyCheese** [tModLoader/tModLoader#1156]
![ModLoader Glitch 1](https://user-images.githubusercontent.com/73256583/96785741-427a7380-13bd-11eb-92c3-4fa167d0c41c.png)
![ModLoader Glitch 2](https://user-images.githubusercontent.com/73256583/96785755-460dfa80-13bd-11eb-94a3-3ab9c2be3713.png)

**Comment by JavidPack** [comment]
You have to launch tModLoader.exe, not Terraria.exe. Think of them as completely separate games. If you still have issues, post a screenshot of the install directory
