### ISSUE TITLE
Terraria: Error (tModLoader 0.11.7.7)

### ISSUE THREAD

**Issue by XiEndST** [tModLoader/tModLoader#1159]
![Screenshot_1](https://user-images.githubusercontent.com/73044503/96936220-55c93400-14ce-11eb-9cce-91f55c23e4da.png)

**Comment by JavidPack** [comment]
Please come to the discord chat, there are too many different ways that you could have messed up your install. tModLoader.net/discord

The most likely, however, is that you are running the GOG version and you have 1.4.1.1 downloaded, tmodloader needs 1.4.1 currently.
