### ISSUE TITLE
Terraria: Error (tModLoader v0.11.7.7)

### ISSUE THREAD

**Issue by XiEndST** [tModLoader/tModLoader#1160]
![Screenshot_1](https://user-images.githubusercontent.com/73044503/96936827-747bfa80-14cf-11eb-83bf-cce234300cdd.png)

**Comment by XiEndST** [comment]
version terraria 1.4.1.1

**Comment by JavidPack** [comment]
why did you open a new issue? I told you to come to discord or downgrade to 1.4.1 if you happen to be using the GOG version of the game. This issue tracker isn't the place for support, it's for tracking real bugs and feature requests.
