### ISSUE TITLE
[1.3 and 1.4] No reset of aiStyle in NPC.SetDefaults causes potential NPC MP desync 

### ISSUE THREAD

**Issue by direwolf420** [tModLoader/tModLoader#1169]
### Description
Modded NPCs that have custom AI and don't explicitely set `npc.aiStyle` to some value (usually -1 or 0), will desync for multiplayer clients after a while (when orphaned slots in `Main.npc` get filled) because on receiving `MessageID.SyncNPC`, it doesn't create a new NPC instance and instead just calls `SetDefaults`, thus "inherits" certain fields not reset in `SetDefaults` from that orphaned NPC, such as aiStyle, which is responsible for a big part of the NPCs behavior, and will desync heavily.

### Steps to reproduce
Described above

### Potential Fix
This issue occurs on both 1.3 and 1.4, I manually went through all `SetDefaults` and all of the vanilla NPCs have an aiStyle assigned. So the easiest fix would be to just add `this.aiStyle = 0;` at the start of `SetDefaults`.

### Additional Info
I went through some of the biggest content mods and seived out their NPCs without an aiStyle assigned and it's a pretty significant amount.

**Comment by Chicken-Bones** [comment]
1.3 version of fix?
