### ISSUE TITLE
Can't open Tmodloader (GOG, Mac)

### ISSUE THREAD

**Issue by linhvu-png** [tModLoader/tModLoader#1183]
Please help me open Tmodloader, I clicked the thing multiple time and it immediately closes after opening. I either put It in the wrong place or put the wrong file in there.
![Screen Shot 2020-11-08 at 00 25 07](https://user-images.githubusercontent.com/74110638/98447648-1a2e9b00-2159-11eb-9abf-e51e72f4348e.png)

**Comment by JavidPack** [comment]
The tModLoader folder should be next to the Terraria folder. Inside the terraria folder is Terraria.app, inside the tModLoader folder is tModLoader.app. 

Try the recent 0.11.7.8 release, I fixed a typo that might make the above instructions correctly work. You'll also need to make sure Terraria updates first.

**Comment by sgb** [comment]
My son is having the same problem.  I'm (amongst other things) a developer who works on Macs, so I poked a bit further and fixed some things: no execute permission on tModLoader.bin.osx, trying to find ../Terraria_1.4.1.2.exe, which doesn't exist anywhere.  I made a file with that name that was a copy of Terraria's Terraria.bin.osx, but then it claimed it wasn't the right file.

I'd come to your discord to chat about it, but the discord.me link on the project page doesn't work (404).  I'm happy to provide what assistance I can, if we can find a better way to chat.

**Comment by Mirsario** [comment]
> I'd come to your discord to chat about it, but the discord.me link on the project page doesn't work (404). I'm happy to provide what assistance I can, if we can find a better way to chat.

Use https://discord.gg/WW8XQz7



> trying to find ../Terraria_1.4.1.2.exe, which doesn't exist anywhere. I made a file with that name that was a copy of Terraria's Terraria.bin.osx, but then it claimed it wasn't the right file.

It checks Terraria.exe for being correct (via hashes), then tries Terraria_1.4.1.2.exe if the former is missing/wrong. Bin files aren't the right ones. Those are native mono binaries that are supposed to launch managed .NET Terraria.exe application from somewhere else (Mac's layout is confusing.)

**Comment by NickVolynkin** [comment]
tModLoader looks for the .exe file at this path:

```cs
vanillaPath = "../../../../Terraria/Terraria.app/Contents/MacOS/";
```

There are two errors:
* First, Terraria is usually installed just in `/Applications/Terraria.app`, without the intermediate `/Applications/Terraria/` directory. But that's easy to fix.
* Second, the `.exe` file is in `./Terraria.app/Contents/Resources`, not `./Terraria.app/Contents/MacOS`.

So here's what worked for me with [release 0.11.8](https://github.com/tModLoader/tModLoader/releases/tag/v0.11.8)

1. Create a `Terraria` directory in the `Applications`, put both Terraria.app and tModLoader.app to this directory.
2. Add an execute permission to `tModLoader.bin.osx`:

    ```bash
    chmod +x /Applications/Terraria/tModLoader.app/Contents/MacOS/tModLoader.bin.osx
    ```
3. Make a copy of the executable in Terraria.app so that tModLoader can find it.

    ```bash
    cp /Applications/Terraria/Terraria.app/Contents/Resources/Terraria.exe /Applications/Terraria/Terraria.app/Contents/MacOS
    ```

    Just in case, this didn't break the original Terraria app, it works fine.

**Comment by Mirsario** [comment]
@JavidPack see the above

**Comment by JavidPack** [comment]
I see, this would explain gog mac user issues. GOG not having the Terraria folder sure makes this an issue. I'll try to fix this later.

**Comment by NickVolynkin** [comment]
JFYI, the majority of applications on macOS are installed just in the `/Applications` directory, without nested directories.

Maybe it could work like this:

1. Determine the Terraria.app location by checking both `/Applications/Terraria.app` and /Applications/Terraria/Terraria.app`;
2. Make all other paths relative of this location. `Path.combine(app_location, "./Contents/MacOS/")`.

**Comment by JavidPack** [comment]
If anyone is on Mac using GOG, and had to do shenanigans to install, hopefully this release fixes it. It would be very beneficial if someone in that situation can try installing this version according to the normal install instructions for Mac. To reiterate the instructions, you should be able to place the tModLoader.app from the zip directly next to Terraria.app in the Applications folder. Here is a link, I'm not sure if it'll work if you aren't logged into discord: https://cdn.discordapp.com/attachments/534215632795729922/812560038970785802/tModLoader_Mac_v0.11.8.1_Beta_2.zip

**Comment by sgb** [comment]
Just tried it; we get:

Terraria: Error (tModLoader v0.11.8.1 Beta 2)

../Terraria_1.4.1.2.exe could not be found.

GOG installs must have the unmodified Terraria executable to function. This version of tModLoader expects the Terraria_1.4.1.2.exe version of Terraria, you may need to downgrade or upgrade Terraria via GOG Galaxy, or wait for tModLoader to update.

...and we ARE running Terraria 1.4.1.2

**Comment by AnyhowStep** [comment]
A friend on GOG, Mac wanted to try tModLoader.
They downloaded this,
https://github.com/tModLoader/tModLoader/releases/download/v0.11.8.3/tModLoader.Mac.v0.11.8.3.zip

They are on Terraria 1.4.1.2.

However, they can't get tModLoader.app to work.
It always just says, The application `tModLoader` can't be opened."

They have `/Applications/Terraria/Terraria.app`, `/Applications/Terraria/tModLoader.app`

**Comment by JavidPack** [comment]
They should be on Terraria 1.4.2.1 to use 0.11..8.3. I'm not sure why it would say it can't be opened, but maybe a reinstall would work. You can also double check that the execute permissions of the `tModLoader.exe`, `tModLoader.bin.osx`, and `tModLoader` script file are all there. They are inside the .app folder somewhere

**Comment by AnyhowStep** [comment]
I ended up just buying them the Steam version of Terraria. tModLoader on Steam worked fine for them.

Thanks, though =)

**Comment by Drakkus28** [comment]
So I'm on the latest edition, 0.11.8.5, using Terraria 1.4.2.3.... I've done all the meddling with the files, and nada. All I get is application can't be opened. granted, I'm also not seeing a linux executable in the osx folder, or is that just the .bin.osx file?
Again, I've applied executable to the .bin.osx file, as well as copied it, but still nothing. Any and all help is GREATLY appreciated, since I've missed playing modded for a WHILE

**Comment by Happyman12345** [comment]
> They should be on Terraria 1.4.2.1 to use 0.11..8.3. I'm not sure why it would say it can't be opened, but maybe a reinstall would work. You can also double check that the execute permissions of the `tModLoader.exe`, `tModLoader.bin.osx`, and `tModLoader` script file are all there. They are inside the .app folder somewhere

How would I get Terraria version 1.4.2.1?

**Comment by JavidPack** [comment]
> > They should be on Terraria 1.4.2.1 to use 0.11..8.3. I'm not sure why it would say it can't be opened, but maybe a reinstall would work. You can also double check that the execute permissions of the `tModLoader.exe`, `tModLoader.bin.osx`, and `tModLoader` script file are all there. They are inside the .app folder somewhere
> 
> How would I get Terraria version 1.4.2.1?

The information in this issue is extremely old, it's likely not relevant to whatever issue you are having I assume. 

If you have a support issue please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.

**Comment by Happyman12345** [comment]
Yea, I realized only after I sent it. Sorry. What would I need to do? My steam image is corrupted. My mac wont update past 10.5. I cant find a tModLoader that works, and if it does work I'm not sure if I'm following the instructions correctly. I really want to mod Terraria.
