### ISSUE TITLE
Global ValidationCallback set by UIModBrowser

### ISSUE THREAD

**Issue by ChrisDirkis** [tModLoader/tModLoader#1184]
https://github.com/tModLoader/tModLoader/blob/6a014ecf0a2d7f901c31535b028d0376cb355b9c/patches/tModLoader/Terraria/ModLoader/UI/ModBrowser/UIModBrowser.cs#L250

For Mono, setting this callback is necessary because (going from memory) Mono doesn't have access to the global security certificate cache, or something like this. However, setting it on ServicePointManager is dangerous, and means that all certificates checked by the application will be accepted as valid.

Looks like HttpClient and HttpWebRequest have [tools to set this per-client or per-request](https://stackoverflow.com/questions/20914305/best-practices-for-using-servercertificatevalidationcallback), maybe worth searching for all uses of `ServicePointManager.ServerCertificateValidationCallback` and changing them to per-request settings?

**Comment by Chicken-Bones** [comment]
Yes, the version of mono we're running doesn't work with tls1.2 which is problematic for github. Given our lack of access to a certificate cache, any request that we don't set the validation callback to true on will fail, so there's no point making it. 

This should be actually fixed when we move to .NET Core on Mac/Linux. I'll leave it open and tagged as 1.4 as a reminder.

Currently, the risk of someone spoofing an endpoint used in tML (mod browser, tML itself, a popular mod's download page) in a malicious way and going unnoticed is relatively unlikely, especially as there are no mono only endpoints. Our non windows userbase is quite small too so it's unlikely to be a worthwhile attack vector.
