### ISSUE TITLE
Tmod Loader (steam) using more cpu than usual

### ISSUE THREAD

**Issue by Pyote8** [tModLoader/tModLoader#1186]
This days i've been trying to play with my friends on tmod, we have played before and my gameplay was smooth, this last days i just host the world and in task manager my tmod is using like 40 or a little bit less of the cpu, which leads to the cpu using 100% of it, all this months using it and until now i had this problem, and I already tried unistalling and installing it

**Comment by Agrair** [comment]
Well, if you're hosting the world, your CPU usage is definitely going to spike. This isn't a bug, this is something inherent in every single multiplayer game. Unless this started before you were hosting?

**Comment by Pyote8** [comment]
> Well, if you're hosting the world, your CPU usage is definitely going to spike. This isn't a bug, this is something inherent in every single multiplayer game. Unless this started before you were hosting?

at this moment even in singleplayer in needs until 30%

**Comment by Solxanich** [comment]
Hello @Pyote8 ,
I'm currently reviewing stale issues, and would like to confirm if you are still experiencing this issue in the latest version 0.11.8.1 of tModLoader, as I believe it contains an improvement on mutliplayer cpu usage?
If not, could you please close the issue?
If so, could you please provide the most recent information from its occurrence?
Thank you for your time.
