### ISSUE TITLE
Tmodloader No Sound.

### ISSUE THREAD

**Issue by DauidBeck** [tModLoader/tModLoader#1194]
Booted up tmodloader today, No sound, volume sliders are at 100%, tried booting up terraria and it had sound. 
Conclusion: Tmodloader isn't giving off sound

**Comment by Albhis** [comment]
Having the same issue, same things. Even when loading without any mods active no sound is made.

**Comment by bababooey-source** [comment]
I'm having the same problem, everything I try doesn't help, I checked the wavebank, updated sound drivers, restarted, reinstalled, verified both tmodloader app and terraria, and restarted my computer entirely, nothing worked

**Comment by Mirsario** [comment]
Duplicate of #1190. Will be fixed very soon.

**Comment by kinemoon** [comment]
Всё фикс вышел 11 8, всё работает.

**Comment by bababooey-source** [comment]
Thank you! Take your time please
