### ISSUE TITLE
Character freezes and interacting with the game is impossible when certain point is reached on the map.

### ISSUE THREAD

**Issue by tinbolw** [tModLoader/tModLoader#1196]
### Description

Whenever a certain point on the map is reached, my character completely freezes.

### Log file

[client.log](https://github.com/tModLoader/tModLoader/files/5526482/client.log)

### Steps to reproduce

N/A, issue does not persist across worlds, but does across characters. I have no lead on why this is happening for my one specific world.

### Expected behavior 

My character should be able to traverse the world freely.

### Actual behavior

When a certain point on the map is reached, regardless of altitude, my character freezes and animations that were happening freeze as well, but armor dye is still animated. Mobs still spawn and will try to attack my character, but my character somehow at this point is immune to all damage.

### Reproduction frequency

100 percent of the time.
### Additional Information

the estimated point at which the character freezes indicated by the red line

![20201111095900_1](https://user-images.githubusercontent.com/36116384/98859121-87228900-2416-11eb-8f11-c53c4c81ba4c.jpg)

What my character looks like when frozen, hovering over gui elements still works but clicking them does nothing as the game is completely unresponsive to user input.

![20201111100054_1](https://user-images.githubusercontent.com/36116384/98859283-cbae2480-2416-11eb-9813-867f29c16c18.jpg)

**Comment by Mirsario** [comment]
This has just been fixed in 0.11.7.8.
