### ISSUE TITLE
вопрос про версию игры

### ISSUE THREAD

**Issue by kaeeli** [tModLoader/tModLoader#1200]
### Steps to reproduce

1. [First Step] как мне скачать версюь v0.11.7.7
2. [Second Step]
3. [And so on...]

**Comment by omartsokha** [comment]
https://github.com/tModLoader/tModLoader/releases

**Comment by JavidPack** [comment]
You can find old downloads here: https://github.com/tModLoader/tModLoader/releases

Note that with the recent Terraria update, you need 0.11.7.8 or later.
