### ISSUE TITLE
Having Error with Terraria Pls Help!!

### ISSUE THREAD

**Issue by DeAd-crypto** [tModLoader/tModLoader#1204]
This is my game folder.
![Capture_1](https://user-images.githubusercontent.com/65146634/99161200-c6522200-2715-11eb-94bf-6de6e83eee65.PNG)
When I try to Open TmodLauncher this is the Error i get:
![Capture](https://user-images.githubusercontent.com/65146634/99161209-d833c500-2715-11eb-9bfc-20866c0fd840.PNG)

This is the Error Log:
[client.log](https://github.com/tModLoader/tModLoader/files/5541732/client.log)

I have The Terraria Version 1.4.1 and TmodLoader 0.11.7.7
I have already tried renaming the file (as you can see in the image but it gives the same error)
Please help..

**Comment by Mirsario** [comment]
Update Terraria to 1.4.1.2 and tML to 0.11.7.8.
