### ISSUE TITLE
I have a code problem, I don't know what's wrong,

### ISSUE THREAD

**Issue by mrlimbo404error** [tModLoader/tModLoader#1217]
I have another recipe code and everything is fine, I copied this part and changed the quantity, because what I needed, but there was a bug

help, ajuda! [10:40:15] [11/ERROR] [tML]: C:\Users\david\Documents\My Games\Terraria\ModLoader\Mod Sources\extrolmod\Items\Weapons\espadamultipla.cs(33,24) : error CS0103: The name 'ItemType' does not exist in the current context
[10:40:15] [11/ERROR] [tML]: Compiling extrolmod.XNA.dll failed with 1 errors and C:\Users\david\Documents\My Games\Terraria\ModLoader\Mod Sources\extrolmod\Items\Weapons\espadamultipla.cs(33,24) : error CS0103: The name 'ItemType' does not exist in the current context warnings
![image](https://user-images.githubusercontent.com/73502509/99877761-2c8be880-2bdf-11eb-90a0-4a44d45e3cc3.png)

the code, o codigo

using Terraria.ID;
using Terraria.ModLoader;

namespace extrolmod.Items.Weapons
{
	public class espadamultipla : ModItem
	{
		public override void SetStaticDefaults() 
		{
			DisplayName.SetDefault("espada multipla"); 
			Tooltip.SetDefault("espada feita de multiplos materiais.");
		}

		public override void SetDefaults() 
		{
			item.damage = 16;
			item.melee = true;
			item.width = 60;
			item.height = 60;
			item.useTime = 20;
			item.useAnimation = 20;
			item.useStyle = 1;
			item.knockBack = 6;
			item.value = 10000;
			item.rare = 2;
			item.UseSound = SoundID.Item1;
			item.autoReuse = true;
		}

		public override void AddRecipes() 
		{
			ModRecipe recipe = new ModRecipe(mod);
			recipe.AddIngredient(ItemType<Items.Placeable.multiminerio>(), 8);
			recipe.AddTile(TileID.Anvils);
			recipe.SetResult(this);
			recipe.AddRecipe();
		}
	}
}
![image](https://user-images.githubusercontent.com/73502509/99877787-504f2e80-2bdf-11eb-92c0-652678c47b83.png)

**Comment by Mirsario** [comment]
You wrote or copied ItemType, which is a method in ModContent class. So you either append ModContent. before it, or add a `using static Terraria.ModLoader.ModContent;` statement.

This issue tracker is not the place for this kind of questions, ask them in #help-with-code channel of tML's discord: https://tmodloader.net/discord
