### ISSUE TITLE
Background walls permanently disappear 

### ISSUE THREAD

**Issue by RoBoNoxA** [tModLoader/tModLoader#1229]
### Description
Modded background walls permanently break.

### Log file
[client.log](https://github.com/tModLoader/tModLoader/files/5611135/client.log)

### Steps to reproduce

1. Enable a mod, place modded background walls in world
2.Leave world, disable mod
3. The placed modded walls (and any other naturally generating walls) will permanently break.

### Expected behavior 
All background walls don't permanently disappear, instead come back after the correct mod is loaded again just like items and more similarly blocks.

### Actual behavior
All the modded background walls of the mods that weren't enabled permanently break.

### Reproduction frequency
Every time I try to do it

### Additional Information
This may not be a bug, instead just an oversight but I felt it important to note.
Also noteable is that this may also affect chests, making naturally occouring modded chests be unopeneable. Althought that may have just been a seperate Calamity bug. Unsure.

**Comment by Solxanich** [comment]
As a side note, been looking into contributing on help with issues, found that this replicates the two issues open in issue #37  (walls and chests).
The previous issue (37) confirmed that modded chests are also expectedly broken in the same fashion (see comment by JavidPack).

**Comment by Mirsario** [comment]
Oh! I thought I remembered such an issue, but somehow couldn't find it. I'll close this one as a duplicate.
