### ISSUE TITLE
tModLoader crashes GOG Terraria

### ISSUE THREAD

**Issue by Avem231** [tModLoader/tModLoader#1233]
I'm running elementaryOS Hera 5.0, and I used wine to download the Windows version of Terraria from GOG. I then followed your installation guide, using the Windows version (as I'm running Windows Terraria from GOG under Wine), and Terraria crashed with an error:

`Microsoft.Xna.Framework.Content.ContentLoadException: Error loading "Images\TileCracks". File not found. -->`

How do I fix this? I also followed both routes of installing tModLoader beside and nested in the Terraria folder, but it still won't work.
I think I might have to wine tModLoader first.

**Comment by JavidPack** [comment]
You might want to come to the discord chat for install issues (the #support channel), as this is more for tracking real bugs: tModLoader.net/discord

When you get there, we'll need to see some screenshots of the folders and the latest client.log file

**Comment by Solxanich** [comment]
@Avem231 - were you able to get help in the discord per JavidPack's comment/solve your issue?
If so, let us know so we can look at closing this support request.
If not, appreciate dropping a line to let us know its still an issue for ya, and I'll try and help with mirroring the windows file structure and let you know the order of operations as best I can.
