### ISSUE TITLE
"Get in touch" link on home page doesn't work

### ISSUE THREAD

**Issue by sgb** [tModLoader/tModLoader#1239]
### Description

On the home page of the github project, the "Get in touch" section provides a link to your discord for further communication.  This link does not work, instead leading to a 404 on discord.me

### Steps to reproduce

1. [First Step]
Go to https://github.com/tModLoader/tModLoader
2. [Second Step]
Scroll down to the "Get in touch" section and click on the "discord server" link
3. [And so on...]
Observe 404 and no connection to your discord server

### Expected behavior 

One should be invited to join your discord server

### Actual behavior

Getting a 404 page from discord.me

### Reproduction frequency

100%

**Comment by Steviegt6** [comment]
Yep, it appears tMod was finally removed from [Discord.Me](https://discord.me/discord-servers). (Why was this link used in the first place?)
