### ISSUE TITLE
Stacked textures | **>==BUG==<**

### ISSUE THREAD

**Issue by SuperHydroman** [tModLoader/tModLoader#1241]
Hi,

So basically I have a weird **bug/glitch** going on in my game. I currently am using tModLoader 64-bit, but I am not sure if I have this bug due that, or due tModLoader overall..

So the bug I have is **_Stacked Textures_** on some items. (e.g. **_Falling Stars_**.)! I see them falling like normal, good textures etc. But as soon as they hit the ground it becomes an item, and that is when it gets weird. So do i have the same bug for other items, like: **_Sugar Cookie, Gingerbread Cookie and Eggnog_** I know so far. But these ones are different compared to the Falling Star. They start big and get smaller and smaller on every duplicate of the texture.

Here are some screenshots:

>**Falling Star:** https://prnt.sc/w6iklw | https://prnt.sc/w6ilhz
>**Cookies and Eggnog:** https://prnt.sc/w6iae2 | https://prnt.sc/w6iaqh

Anyone got an idea what might cause this?

Thanks in advance!

**Comment by Dradonhunter11** [comment]
Most likely a bad install, reinstall the game will most likely fix it.

**Comment by JavidPack** [comment]
Make sure you follow the official install instructions. These issues are caused by doing something unsupported, such as installing in the Terraria folder (as you would previously)

https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players

**Comment by SuperHydroman** [comment]
Alright, thank you. Ill try it!

**Comment by SuperHydroman** [comment]
Fixed it by reinstalling indeed. Thank you for the support.
