### ISSUE TITLE
[1.4] Hovering over memory estimates crashes the game

### ISSUE THREAD

**Issue by Chik3r** [tModLoader/tModLoader#1244]
### Description
On branch `1.4_mergedtesting`, when hovering over the memory estimates bar, the game crashes:
Video (imgur killed the quality): https://imgur.com/a/nPZjekI

### Log file
[client.log](https://github.com/tModLoader/tModLoader/files/5732877/client.log)

### Steps to reproduce
1. Go to settings.
2. Enable the memory estimates bar.
3. Go to the `Mods` menu.
4. Hover over the memory estimates bar.

### Expected behavior 
There should be no crash and the memory estimates should appear

### Actual behavior
It's crashing

### Reproduction frequency
Everytime I hover it crashes

### Additional Information
Make sure you're on `1.4_mergedtesting`

**Comment by Chicken-Bones** [comment]
Fixed in #1255
