### ISSUE TITLE
tModLoader not launching (Steam)

### ISSUE THREAD

**Issue by MeliodasNsc** [tModLoader/tModLoader#1265]
When I launch it, it says that tModLoader's working. But nothing happens. It just doesn't open. The issue started when the last, but one update happened. Since then, I tried to reinstall it, reboot the computer, etc. Does somebody have the same trouble? Please, help me to solve this.

**Comment by JavidPack** [comment]
The most common reason for this is failing to update Terraria to 1.4.1.1. Make sure steam updates Terraria to the latest version, and finishes the download, before running tmodloader. You may need to restart your computer after Terraria updates.

**Comment by MeliodasNsc** [comment]
I couldn't even suppose that tModLoader is somehow connected to Terraria and that I have to update one another to work. Thanks for help!
