### ISSUE TITLE
WorldGen.KillTile's 'noItem' parameter is ignored (at least for furniture items?)

### ISSUE THREAD

**Issue by hamstar0** [tModLoader/tModLoader#1269]
### Description
See title.

### Steps to reproduce
See title.

### Expected behavior 
No item drops.

### Actual behavior
Items drop.

### Reproduction frequency
Apparently always. Only tested it for furniture, so far.

**Comment by fakelag** [comment]
Is this for 1.3 or 1.4?

Also, I'm not sure furniture is considered a tile

**Comment by JavidPack** [comment]
I assume you already figured this out, but I just came across this issue and updated the docs to clarify that the `noItem` parameter only affects 1x1 tiles. Modders looking to prevent multitile drops will have to use `GlobalTile.Drop` in some manner.
