### ISSUE TITLE
Delete mod button

### ISSUE THREAD

**Issue by goldern** [tModLoader/tModLoader#1271]
### Description
As it's a hassle to be forced to: 
1. Disable the desired mod
2. Enter in "More info" at every single mod
3. Press **Delete** at every single mod, which turns into a headache fast
(if you disable tons of mods and then reload and try to remember which mods have been disabled to delete instead of disabled to _not_ be deleted)
Which is easier if you just close the game, go to the folders and delete manually every desired mod, but that's outside tModloader 

**I got an interesting idea**: to implement a button that marks the mod as **to be deleted** and be _greyed out_ 
until you press **Reload Mods**, which then it will start mass deleting all the mods in the **to be deleted** state.

### What does this proposal attempt to solve or improve?
It will make easier to correct mistakes if many mods are added but aren't what the player is looking for, changing multiple mods or making little changes in the mod list more clear and facilitating new users tmodloader experience, also it adds a way inside the game to delete multiple mods in less time.

### Sketch of the concept
![dumbterraridea](https://user-images.githubusercontent.com/5741155/103833845-b7765480-5060-11eb-992b-62f8b7ef58a3.png)
imgur: [https://imgur.com/GBcpKvP](url)

### How it works:
1. Press the trash icon in _each mod_ you want to delete, it will make said mod get the **to be deleted** state and have a lower opacity, can be undone by clicking again in the trash icon, restoring the 100% opacity]
2. Once "Reload mods" is pressed, it will delete all mods with the **to be deleted** state, and proceed to reload the remaining not deleted mods.

_The sketch button is just a suggestion, as I'm not very creative with buttons or design, it could be moved to another place, made smaller, whatever fits._

**Comment by Mirsario** [comment]
Better than marking for deletion, imo it's better to just have the button clasicaly redirect to a deletion confirmation dialogue, which will be skippable if you hold something like Shift. Like deleting messages in Discord.

**Comment by goldern** [comment]
The issue with direct deletion is that it will always trigger mod reload, else,  if the player directly deletes the mod and tries to play while it's loaded, the game would crash as it's referring to the previous content that was deleted, which in turn would lose time by constant reloads instead of deleting everything and reloading in one go.

**Comment by Mirsario** [comment]
It doesn't sound like an issue to only allow deleting disabled mods.

**Comment by Chicken-Bones** [comment]
I approve of the suggestion as is
You're welcome to PR it
However please note you can delete mods from the mods folder much more easily when the game is closed

**Comment by Mirsario** [comment]
Implemented with #1311. Not exactly the design described here, but it should be good enough?
