### ISSUE TITLE
Report mod button

### ISSUE THREAD

**Issue by goldern** [tModLoader/tModLoader#1273]
### Description
Proposal to add a 'report mod' button, to help clean useless mods that break the community guidelines.

### What does this proposal attempt to solve or improve?
Removal of useless mods that aren't being worked anymore/were created by mistake/break community guidelines.

### Sketch of the concept
![dumbterraridea2](https://user-images.githubusercontent.com/5741155/104011326-a9255700-518c-11eb-9f13-6dd70b5822c8.png)

**Comment by steviegt6** [comment]
> useless mods that aren't being worked anymore

What?? Plenty of old mods still work.

**Comment by steviegt6** [comment]
Anyway, just report mods to jopojelly directly, this could be very easily abused and would 100% get because of all the people using tML. Calamity would undoubtedly have at least 50 reports within a day of this feature being added.

**Comment by JavidPack** [comment]
In terms of breaking rules, those should be reported on the workshop now. We are still considering a functionality to track bug reports in some similar manner.
