### ISSUE TITLE
memory capacity

### ISSUE THREAD

**Issue by rasm921i** [tModLoader/tModLoader#1283]
in the newest update of tmodloader i only have 4 gb to work with and in the previus one i had 8 gb to work with not sure if it a bug or not just wanted to know if theres a way to get more gb bc im playing with 5 mods and they cant run like they should bc i have 880 mb ca. to play with the mods

**Comment by Mirsario** [comment]
All official Windows tML releases are 32-bit, meaning that 4GB RAM usage limitations apply to them. If you had unofficial 64-bit tML and steam autoupdate overwrote it - just reinstall - https://github.com/Dradonhunter11/tModLoader64bit/releases
