### ISSUE TITLE
Make mods only available some worlds / players

### ISSUE THREAD

**Issue by Kimi-Arthur** [tModLoader/tModLoader#129]
Hi
Currently, we can only enable mods globally, either available in all worlds / players or not.
However, if I want to only mod A in world I, and mod B, C in world II, and mod D for Player III, I cannot do it now.
This will happen when we have multiple worlds with different setups so that we switch back and forth. Currently, we have to change what mods are enabled when we switch between these worlds.

Thanks!

**Comment by Chicken-Bones** [comment]
There will probably be support for this at some time in the future. For now we recommend running a dedicated server (even locally) because you can change the directory the server uses (and as such it can have different mods folders), and the server will automatically sync these with the client.

**Comment by JavidPack** [comment]
Using modpacks to switch between sets of mods quickly is what I'd recommend you do for now.

**Comment by Kimi-Arthur** [comment]
Thanks for the workarounds. They are useful.

Still would like to see the feature sometime in the future.

**Comment by Jofairden** [comment]
Don't think this warrants an actual feature, using ModPacks should be sufficient.
