### ISSUE TITLE
When i open my tmod loader an error message comes up, and ive tried everything to fix it, here is the error i get 

### ISSUE THREAD

**Issue by Tubby110** [tModLoader/tModLoader#1291]
### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [And so on...]

**Comment by Tubby110** [comment]
![image](https://user-images.githubusercontent.com/77643185/104962030-db7a5400-59d7-11eb-8113-c034ead8a949.png)

**Comment by Mirsario** [comment]
Uninstall OneDrive, or create a `savehere.txt` (text document) file in tML's folder.

**Comment by Tubby110** [comment]
> Uninstall OneDrive, or create a `savehere.txt` (text document) file in tML's folder.

Doesnt work, tried both..
