### ISSUE TITLE
Tmodloader x64 bit Object reference not set to an instance of an object error when a player joins a server.

### ISSUE THREAD

**Issue by TahoeBennie** [tModLoader/tModLoader#1296]
### Description
Whenever I try to join a tmodloader 64 bit server hosted locally, the server gives an error of "Object reference not set to an instance of an object" and the player cannot interact with anything, making the game unplayable. (this is not client side, it happens when my friend tries to join as well)

### Log file
[client.log](https://github.com/tModLoader/tModLoader/files/5860918/client.log)
[server.log](https://github.com/tModLoader/tModLoader/files/5860919/server.log)
The error that I am after comes at 11:15:27 in the server.log file.

### Steps to reproduce
Step 1: Host tmodloader 64 bit server
Step 2: Join tmodloader 64 bit server
Step 3: Go find the error in the server console while its running and a player has joined

### Expected behavior 
Whoever joins the world should be able to play like normal, and progress just like you normally would with mods.

### Actual behavior
The player cannot interact with the world and cannot progress, and if whoever joined attempts to kill an enemy, the enemy comes back to life and is immortal for as long as the error keeps continuing.

### Reproduction frequency
Every single time

### Additional Information
I'm using tmodloader x64 bit game version v1.3.5.3 and tmodloader version v0.11.8.

**Comment by JavidPack** [comment]
First, this isn't the 64 bit github.

As for your error, it seems to be caused by ElementsAwoken, so you'll need to disable the mod.
