### ISSUE TITLE
tModLoader Dev Setup: Setup problem

### ISSUE THREAD

**Issue by ZEPHYR-9487** [tModLoader/tModLoader#1297]
I have a problem at tML Dev setup. When the setup is compiling tModLoader.FNA.exe, a window popped up. It says:" Failed to compile tModLoader.FNA.exe  Just build it from the tModLoader solution." how do I solve that?

![Setup window](https://user-images.githubusercontent.com/77919989/105628251-e0775180-5e76-11eb-8f97-2f26d927df7e.PNG)
![MSBuild Error window](https://user-images.githubusercontent.com/77919989/105628229-bd4ca200-5e76-11eb-9abf-135d22c35ea4.PNG)

**Comment by Solxanich** [comment]
I've gotten this before; all it means is you either 
A) recently changed branches while there was pending changes (ie, had changes in a branch, changed branch, hit diff tmodloader, then hit setup). Always setup after changing the branch is a lesson I learned. 
B) something similar to a)

To fix: if you have visual studio installed, just build the solution after opening tmodloader.sln from your local files. Then rediff tmodloader, then when you click setup again should work fine

**Comment by Chicken-Bones** [comment]
More specifically, this means that there are compile errors in the tModLoader.sln, either just on Mac, or on all platforms. This might be because someone pushed a broken commit, or because you have some local changes which no longer compile.

You can ignore this error and get to work, just know that you'll need to compile the "MacRelease" configuration from VS or run "solutions/buildDebugAndMac.bat" before you can build mods.

**Comment by ZEPHYR-9487** [comment]
> More specifically, this means that there are compile errors in the tModLoader.sln, either just on Mac, or on all platforms. This might be because someone pushed a broken commit, or because you have some local changes which no longer compile.
> 
> You can ignore this error and get to work, just know that you'll need to compile the "MacRelease" configuration from VS or run "solutions/buildDebugAndMac.bat" before you can build mods.

Well, my platform is Windows 7. I used Visual Studio to compile the solution, but it failed. The solution can't load Terraria.csproj.

**Comment by Solxanich** [comment]
@ZEPHYR-9487 - to clarify, did you open terraria.sln or tmodloader.sln?
The latter is the one that *should* compile, the former is a different matter

**Comment by ZEPHYR-9487** [comment]
If I skip the step, run the CompleteRelease.bat directly, it can only pass first step "Building Windows Release". After I start the game, it works fine. But it can't play multiplayer, because tModLoaderServer.exe is 1.3.5.3.

**Comment by Solxanich** [comment]
Hmm. I'm going to recommend you drop a line in tML discord support - this isn't a quick troubleshoot. Its easier to talk continual there.

As an aside, 1.4 dev environment doesn't generate 1.4 server files natively from the setup tool, so it isn't surprising there.

My guess is your src/ folder is missing files and/or the setup tool is off.

To confirm: are you trying to do 1.3 development or 1.4 development?

**Comment by ZEPHYR-9487** [comment]
> @ZEPHYR-9487 - to clarify, did you open terraria.sln or tmodloader.sln?
> The latter is the one that _should_ compile, the former is a different matter.
> Edit: nvm read wrong.
> CB: Windows 7 right? CB, is there any issue with generating src/ in 7?
> Zephyr: if you enter the src/ folder in your local files, is it empty?

Yeah, I opened tModLoader.sln, but it always failed on build the solution. The src\ folder isn't empty.

**Comment by Chicken-Bones** [comment]
You'll need to give us an actual error log from build. Also let us know if you're on the master or 1.4 branch. Pulling the latest version may also help

**Comment by JavidPack** [comment]
Stale issue, probably fixed, closing.
