### ISSUE TITLE
"Assumed pirating"

### ISSUE THREAD

**Issue by ILikeProgramming101** [tModLoader/tModLoader#1298]
When i try to start the tmodloader it says "Assumed pirating" and takes me to the terraria store page, even though i've bought the game on steam (Where im trying to use the mod loader)

**Comment by JavidPack** [comment]
I'd suggest clearing out both install folders, then verifying game integrity via steam (for both tmodloader and terraria, wait for both to finish checking and downloading). If your issue persists, we can more effectively help on the discord: tModLoader.net/discord
