### ISSUE TITLE
Lighting bug

### ISSUE THREAD

**Issue by Mh3gfreak1** [tModLoader/tModLoader#1305]
I have this bug that randomly started 2 days ago. i've been searching for a way to fix this but nothing seems to work. help on this subject would be greatly appreciated. the lighting looks really blocky. Here's a picture so you understand what's going on.
![image](https://user-images.githubusercontent.com/78171672/106184027-02bae900-616f-11eb-868e-cbd86defff85.png)

**Comment by Solxanich** [comment]
Did you perchance change the lighting mode settings in video?
That lighting style looks like one of:
Lighting mode retro
Ligthing mode trippy
Lighting mode white

All three have blocky lighting. 
If that isn't it, let us know!

**Comment by Mh3gfreak1** [comment]
I tried to change them using F9 but it doesnt change the fact that it looks blocky. Used to look smoother and less aggressive black

**Comment by Mh3gfreak1** [comment]
But why would it suddenly do that after 1 month of gameplay?

**Comment by Solxanich** [comment]
Its entirely possible that it could be based on a particular condition having occurred in a mod, and it inadvertently changing the lighting - for example, several mods generate their own biomes after beating a boss within the mod. 
tModLoader itself hasn't updated in over a month, so it's hard pressed to believe its coming from there, and instead is coming from a improperly handled event from a mod.
Also it doesn't to hurt to confirm on that note - is this issue specific to the world?

**Comment by Mh3gfreak1** [comment]
So I started a fresh new worlds with half mods and it works now. Anyways I had too much to begin with. I'll be happy with what I have. Thanks for the help!

**Comment by Solxanich** [comment]
Yeah, glad to help.
If you have time, it would be helpful to know which mod in the other half was causing it, so we can forward them the issue. Likely you can still use most if you rinse repeat adding half back and verifying it works and be able to play more of what you wanted.
If not, no worries, glad could help with getting around the problem

**Comment by Mirsario** [comment]
This is controlled by the generic vanilla "Quality" option.
