### ISSUE TITLE
Combine client and server - post .NET Core

### ISSUE THREAD

**Issue by Chicken-Bones** [tModLoader/tModLoader#1313]
### Description
We could simplify distribution size significantly by having a single dll. With the .NET Core release, we no longer have the .FNA build for compiling mods either. Windows build could use a separate project for the server with output type <Exe> which launches the console window. Other platforms just need a custom launch script.

This would make downloading builds from the CI easier.

**Comment by Solxanich** [comment]
This was completed during #1086  where we trimmed to a single CI build for everyone.
Still have to fix launch scripts, but that be in a separate issue.
