### ISSUE TITLE
Crash after latest Steam Linux update

### ISSUE THREAD

**Issue by V10lator** [tModLoader/tModLoader#1318]
### Description
Crash after latest Steam Linux update.

### Log file
[client-crashlog.txt](https://github.com/tModLoader/tModLoader/files/5937268/client-crashlog.txt)

### Steps to reproduce
1. Update your Steam client to newest Linux beta.
2. Start tModLoader

### Expected behavior 
The game should just start.

### Actual behavior
Steam shows that it's loading the game but no window opens and finally Steam shows the game as not running.

### Reproduction frequency
Every time.

### Additional Information
Normal Terraria works just fine.

**Comment by V10lator** [comment]
After looking at the code the problem is most likely here: https://github.com/tModLoader/tModLoader/blob/master/patches/tModLoader/Terraria.ModLoader.Engine/Steam.cs#L39 - The variable terrariaInstallLocation has never been defined (so is NULL). A quick fix could be to add `string terrariaInstallLocation;` to line 21. Sadly I'm not experienced with C# and no compiler wants to work for me, so I can't confirm the fix / do a pull request.

**Comment by Solxanich** [comment]
Thanks for posting this and looking into it a little.

Unfortunately, the variable terrariaInstallLocation is set within "SteamApps.GetAppInstallDir" and output from that external function as a usable string (hence keyword OUT in the call).

This is most likely caused by the Steam beta breaking the behavior of their external api Steamworks, and in particular: Steamworks.SteamApps.GetAppInstallDir.

This means that, unless steam is changing its api purposefully without letting dev community know, this is a bug with the steam beta itself.

**Comment by JavidPack** [comment]
My guess is Terraria isn't currently installed via steam on your computer. A lot of people uninstall the game and forget that is required for tmodloader.

**Comment by V10lator** [comment]
@Solxanich: Thanks for explaining. As told I'm not experienced in C# but all examples I saw defined the variable before giving it to another function as OUT. Also in C you have to malloc() (or otherwise define) a variable given as a out parameter (as it's just a pointer and if you give NULL as out pointer things will break. Remember: NULL is a pointer to 0x00000000). Anyway, I'm sure you know better than me, so I will report this to Steam itself. :)

@JavidPack Terraria is installed on Steam. I played tML before the update, stopped the game, got out with the dog, saw the Steam client update, updated, tried to restart tML. Also: Terraria itself works just fine.

My Steam version:
![image](https://user-images.githubusercontent.com/1312422/107127077-f6900380-68b3-11eb-9171-44fe36390e16.png)Not sure where you got "0.11.8" from, I can't find any similar number at my steam installation. Anyway, you're right: I'm NOT in steam beta right now! So that's weird...

**Comment by JavidPack** [comment]
Ah, I thought you were referring to the tmodloader beta channel, I see. Well, if the issue really is the latest update to steam itself, that's not good. 

If anyone has the same issue, please comment as well.

**Comment by V10lator** [comment]
I asked on Discord and two other Linux players told me all is working fine.
That really starts to confuse me and I would love to at least try to add to line 21 what I told above but I can't. That said: Would anyone be kind enough to compile a test version with that one line added and handle it over to me?

**Comment by V10lator** [comment]
Never mind, we found a fix on Discord: Reinstall both, Terraria and tML.

**Comment by sgkoishi** [comment]
>
> @Solxanich: Thanks for explaining. As told I'm not experienced in C# but all examples I saw defined the variable before giving it to another function as OUT. Also in C you have to malloc() (or otherwise define) a variable given as a out parameter (as it's just a pointer and if you give NULL as out pointer things will break. Remember: NULL is a pointer to 0x00000000). Anyway, I'm sure you know better than me, so I will report this to Steam itself. :)
> 

Not quite related to the problem: the `out [type] [variable name]` is syntactic sugar in C# 7.
`Method(out string foo);` is equivalent to `string foo; Method(out foo);` (no initial value is given/required, the `Method` will set the value)

[Document MSDN](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/out-parameter-modifier#calling-a-method-with-an-out-argument)

**Comment by Trisscar05** [comment]
Showing this behavior a year later on the 1.4 beta. Both TE and TMod have been reinstalled through steam, TE works but TMod does not unless run through Proton, at which point it still does not work but at least actually logs something.
