### ISSUE TITLE
[Feature Proposal] Import and export enabled mods buttons

### ISSUE THREAD

**Issue by GoodPro712** [tModLoader/tModLoader#1319]
### Description

Buttons on the mod menu page that can export and import modpacks (the enabled.json)

### What does this proposal attempt to solve or improve?

This would help people in the support channel with mod related errors, as well as having an easier way to load other player's mods

### Which (other) solutions should be considered?

Not sure

**Comment by JavidPack** [comment]
Is there a reason this was closed? it's a reasonable suggestion

**Comment by Mirsario** [comment]
@JavidPack I heard in discord that it's obsolete due to log files containing mod lists, multiple and timestamped.
