### ISSUE TITLE
[1.4 alpha] Mod Browser is extremely slow, recalculates children too much

### ISSUE THREAD

**Issue by Solxanich** [tModLoader/tModLoader#1328]
### Description
When opening the Mod Browser in the dev/alpha version, the UI will lag and stutter significantly.

### Log file
![image](https://user-images.githubusercontent.com/59670736/107691305-88a75b80-6c68-11eb-82fc-2ad9a477b45c.png)
^UI List

### Steps to reproduce
n/a

### Expected behavior 
Framerate should be smooth like 1.3 Mod Browser

### Actual behavior
Framerate is smooth like a mountain range.

### Reproduction frequency
100% reoccurence

### Additional Information
We should probably disable the Mod Browser button in 1.4's main menu for now, and look into fixing it when it makes sense be it in SW environment or otherwise.

**Comment by cozykoko** [comment]
Isnt this closable now?

**Comment by Solxanich** [comment]
This has been confirmed closable, we think
