### ISSUE TITLE
I can't get 1.4 alpha for Mac since it's all .bat files.

### ISSUE THREAD

**Issue by StupidRepo** [tModLoader/tModLoader#1333]
This is not a bug but I want some early 1.4 please :(

Can I get it for Mac somehow or can't you just release as a beta on Steam?

**Comment by Solxanich** [comment]
The alpha is available here, less .bat files:
https://github.com/Chik3r/tModLoader/releases

Check the Discord for supported mods, and note you have to download according to the pin in the Journey End channel. If you have additional questions, feel free to ask there as well.

**Comment by Mirsario** [comment]
There are no public Mac/Linux nightly builds for now, and you'll need windows to compile them.

**Comment by Mirsario** [comment]
> Don't the Mac versions of Terraria and tModLoader somehow make use of .exe files?

Yes, but these exes, even though managed, are still different on each OS. This will change with the .net 5 branch of TML, after which we'll have a single binary (.dll) for all systems, with just runtimes having to differ.
