### ISSUE TITLE
Worlds randomly becoming 1.4 worlds.

### ISSUE THREAD

**Issue by ReadeFrog** [tModLoader/tModLoader#1334]
### Description
2 days ago i was playing with my friend on a modded 1.3 world. Then we quit, and today we logged in and found this: 
![20210218_192054](https://user-images.githubusercontent.com/79291933/108443666-955f1d00-722f-11eb-8128-fd7b8328c7f0.jpg)
We couldn't enter the world, all it said was that "1.4 worlds are not supported". We didn't do anything at all on tmodloader during those 2 days, which means that it was probably a bug.

Logs: 
[message.txt](https://github.com/tModLoader/tModLoader/files/6007002/message.txt)

>

**Comment by JavidPack** [comment]
Stale issue, probably fixed, closing.
