### ISSUE TITLE
MusicStreamingWav doesn't support the 'junk' chunk.

### ISSUE THREAD

**Issue by Mirsario** [tModLoader/tModLoader#1338]
Yoraiz0r:
> So uhm, not a big thing at all - but while facing some problems with adding wav support for music for resource packs I got a bit mad and decided to check the TML version. It appears that the TML version of wav files doesn't support 'junk' chunk reading. just figured I'd let you know (a chunk that may contain any even amount of bytes, may come before the fmt chunk)

From looking at the code (which is very, VERY barebones), it seems to just assume one exact order of WAV chunks, and a 'JUNK' chunk being in front of 'FMT' will ruin everything.

**Comment by Mirsario** [comment]
Closing, looks like all that code has been nuked in favor of what yorai wrote for vanilla.

**Comment by absoluteAquarian** [comment]
Some clarification:  the extra entry isn't "JUNK", it's a "LIST" of metadata that's usually used for things like authors, genre, etc.
