### ISSUE TITLE
Input string was not in a correct format.

### ISSUE THREAD

**Issue by kamalyaka** [tModLoader/tModLoader#1344]
As i try to launch my terraria server, i get this weird error. 
![image](https://user-images.githubusercontent.com/60985540/109389860-aa623d00-790e-11eb-82e7-4dda61e1a3b7.png)
here is the full log of the error. 
[server.log](https://github.com/tModLoader/tModLoader/files/6054586/server.log)

**Comment by kamalyaka** [comment]
i realized there was a number next to each word

**Comment by Mirsario** [comment]
This happens frequently due to very finicky parsing of vanilla server configuration files. You have to always ensure that there's no extra spaces anywhere.
