### ISSUE TITLE
[1.4] Fix and Add onto ConvertiblePlants (ModTree, ModCactus, ModPalmTree)

### ISSUE THREAD

**Issue by kittenchilly** [tModLoader/tModLoader#1347]
Nothing has been done to these since the 1.4 repo went up, and they don't work currently. Needs more research done to know exactly why it's broken.
Preferably should be overhauled as well, merging ModTree, ModCactus, and ModPalmTree into one class as well as accounting for tree wind physics, tree shaking, and whatever else new vanilla does.

**Comment by Steviegt6** [comment]
What similarities are actually shared between `ModTree`, `ModCactus` and `ModPalmTree`? Do they all work similarly?

**Comment by Mirsario** [comment]
short ModPalmTree to ModTree diff:

```diff
-public abstract class ModTree
+public abstract class ModPalmTree
 {
 	public virtual int CreateDust()
-		=> 7;
+		=> 215;
 
 	public virtual int GrowthFXGore()
 		=> -1;
 
 	public abstract int DropWood();
 
-	public virtual bool CanDropAcorn()
-		=> true;
-
 	public abstract Texture2D GetTexture();
 
-	public abstract Texture2D GetTopTextures(int i, int j, ref int frame, ref int frameWidth, ref int frameHeight, ref int xOffsetLeft, ref int yOffset);
-
-	public abstract Texture2D GetBranchTextures(int i, int j, int trunkOffset, ref int frame);
+	public abstract Texture2D GetTopTextures();
 }
```

Cacti are just:
```cs
public abstract class ModCactus
{
	public abstract Texture2D GetTexture();
}
```

**Comment by Solxanich** [comment]
Some other requested stuff:
1) Gem Tree support?
2) Custom Tree Library integration
3) Sakura/Willow 'epic' trees?

**Comment by dragon3025** [comment]
The original post also said tree wind physics, which I'd also like to see as well as support for wind physics for other tiles larger than 1 block. I was told on the modding support that they don't think it's supported for tiles similar to vanilla ones like Hanging Herbs, Trees, or Chandeliers.

EDIT: A feature request for this was made after I posted this comment. Here's a link to it if anyone is looking for this: https://github.com/tModLoader/tModLoader/issues/2975
