### ISSUE TITLE
(Modded) Cactus destroyed during unloading process.

### ISSUE THREAD

**Issue by Solxanich** [tModLoader/tModLoader#1348]
### Description
Modded cactus destroyed due to placeholder tiles during unload placeholder process.

### Log file
Before: 
![image](https://user-images.githubusercontent.com/59670736/109856628-f36c0700-7c16-11eb-90a9-8dca37f3eee6.png)

During:  
![image](https://user-images.githubusercontent.com/59670736/109856640-f5ce6100-7c16-11eb-93b8-5ad22c895d11.png)

After: 
![image](https://user-images.githubusercontent.com/59670736/109856649-f830bb00-7c16-11eb-8f45-ad03bda64a81.png)

### Steps to reproduce
1. Load a world with Ancients Awakened and Cheat Sheet
2. Spray with clentaminator two cactuses with mire solution and/or inferno solution
3. Save&Exit
4. Unload AA
5. Enter world, save and exit
6. Reload AA
7. Enter world and cactuses are gone.

### Expected behavior 
Cactus shouldn't be destroyed by unloaded tiles

### Actual behavior
Cactuses are uprooted by unloaded tiles, and thus destroyed between loads.

### Reproduction frequency
100%

### Additional Information
May be considered in #1266

**Comment by Hotmud9** [comment]
The cacti themselves seem to be modded as well.
