### ISSUE TITLE
Launching TML drops at "Setting Up"

### ISSUE THREAD

**Issue by Cakeplane** [tModLoader/tModLoader#1350]
Hey, is someone Else having trouble launching tmod loader? After loading all the mods while launching, it somehow stops at "Setting Up". The Only way for me to launch the game is to remove all files and launch a fresh installed tmod loader, with no mods, no worlds and characters. 
This forces me to start all over again, which kinda sucks. I am still trying to figure out if some of the installed mods are to blame.

**Comment by Mirsario** [comment]
Reproduce the issue, and then
> Post your `.log` files from the following OS-dependent directory:
> 
> **On Windows:** `%userprofile%/Documents/My games/Terraria/ModLoader/Logs`
*> *On Linux:** `~/.local/share/Terraria/ModLoader/Logs`
> **On Mac:** `~/Library/Application support/Terraria/ModLoader/Logs`

**Comment by JavidPack** [comment]
Stale issue, probably fixed, closing.
