### ISSUE TITLE
TmodLoader error "terraria.exe is not the unmodified terraria executable"

### ISSUE THREAD

**Issue by ErasedU** [tModLoader/tModLoader#1361]
Log file:
GOG installs must have the unmodified Terraria executable to function. This version of tModLoader expects the Terraria_1.4.1.2.exe version of Terraria, you may need to downgrade or upgrade Terraria via GOG Galaxy, or wait for tModLoader to update.

> I already tried to downgrade and upgrade, same thing.

> Reinstalled, same thing.

> I tried to install the x64, doesn't work.

> Reinstall TmodLoader, same thing.

What do i do? I have GOG version.

**Comment by tilktilk5** [comment]
Installed using the "nested" option listed on the wiki. running 5.11.10-arch - same error.

**Comment by JavidPack** [comment]
0.11.8.2 supports gog installs coexisting with Terraria 1.4.2, I'd suggest trying that version.

**Comment by tilktilk5** [comment]
I can open a new issue, but this still persists for me. Installed native Linux version.

**Comment by kira78** [comment]
Neither 0.11.8.2 nor 0.11.8.3 work with the latest version of Terraria available for download from GOG for Linux. The Linux GOG version of Terraria is 1.4.1.2g, and the Linux version of tModLoader also won't recognize either that installation or the Terraria.exe from the Windows version as being a valid unmodified Terraria.exe.

**Comment by JavidPack** [comment]
The latest gog version for linux should be 1.4.2.1, released yesterday, if it's not, that is something relogic would need to double check, but my guess it your gog galaxy client is just behind on updates. If anyone has further issues related to this, chatting on discord is the most productive way to find a solution.

**Comment by devraza** [comment]
tModLoader v0.11.8.3 - or any previous versions - don't work with Terraria v1.4.2.2 on Linux (this is what I find after a lot of file name changes).
My guess is that version v0.11.8.3 doesn't support the latest version of Terraria, being released before it.
If this is true, the devs will need to update tModLoader to support the latest version of Terraria.

**Comment by Temiy21** [comment]
[REDACTED]

**Comment by devraza** [comment]
Thanks!

**Comment by Lucas559-noob** [comment]
> 

lol

**Comment by devraza** [comment]
Is that an SCP reference?!?!
