### ISSUE TITLE
[1.4] Hook proposal: Mod/GlobalTile.IsTileDangerous & IsTileSpelunkable

### ISSUE THREAD

**Issue by direwolf420** [tModLoader/tModLoader#1363]
### Description
Add hooks to or around the calls of:
`TileDrawing.IsTileDangerous(Player localPlayer, Tile tileCache, ushort typeCache)` and
`Main.IsTileSpelunkable(ushort typeCache, short tileFrameX, short tileFrameY)`

### What does this proposal attempt to solve or improve?
Finer control over when and which tiles are allowed to be highlighted by the dangersense and spelunker effects. Examples:
* Herb only glowing on certain growth stages
* Particular style of a tile is a trap or a treasure
* Overriding highlighting behavior selectively for vanilla tiles (game modes)

### Which (other) solutions should be considered?
If the hook is placed inside the aforementioned methods, it loses the position of the tile. It can be instead added to places where these are called and where the position context actually exists.

### Motivation
Currently, how ExampleMod showcases herbs is by using a single tile with separate growth stages differentiating via frameX/Y. Vanilla however has all herbs for one stage as a single tile, the herb "types" differentiating via frameX/Y. Main.tileAlch[] is responsible for dealing with anything related to them, such as placing/replacing when planted, spawning dust/items when killed, growing taking place, etc. Mods would have to follow this vanilla approach strictly, including the tile dimensions, amount of tiles/stages, YET there are many hardcoded checks for each stages' type (tile type), so it won't work. 
Instead, a herb is more or less reproducible using the existing tml hooks, but there are still gaps, such as this one. Rather than making Main.tileAlch[] work with modded tiles properly (which requires many patches), tml could add more general hooks that would make herbs easier to make while also opening opportunities for other things.

**Comment by Mirsario** [comment]
Sounds fine to implement.
