### ISSUE TITLE
Add automatic array tag serialization based off list serialization.

### ISSUE THREAD

**Issue by Chicken-Bones** [tModLoader/tModLoader#1364]
### Description
sample usage
```cs
var arr = tag.Get<T[]>(key);
tag[key] = arr;
```

### What does this proposal attempt to solve or improve?
Currently saving arrays requires `.ToList()` and `Get<IList<T>>.ToArray()` as a workaround.

**Comment by JavidPack** [comment]
Implemented in daa239205ab69743d44f7bb64c9cd3e080024a51
