### ISSUE TITLE
More flexible informational accessory system

### ISSUE THREAD

**Issue by ThomasSpeedrunner** [tModLoader/tModLoader#1367]
### Description
Add some way --- a couple of hooks in `ModItem`/`GlobalItem` may be best --- to register and display information from informational accessories (i.e. the things that build into Cell Phone, sans the Magic/Ice Mirror) which modders may want to add into the game, as well as allowing them to edit existing informational accessories' displays. This could theoretically be expanded into an improved informational accessory system overall which has the potential to be much more flexible than the current one.

### What does this proposal attempt to solve or improve?
Informational accessories internally function in a manner that, while practical, is extremely rigid in how it functions and prevents adding any new informational accessories without custom UI or extensive IL/On shenanigans. Given the amount of potential within being able to add custom informational accessories into the game, I believe this will greatly expand the number of options people have for conveying information quickly and effectively to the player without needing to create custom UI or long-winded tooltips.

### Which (other) solutions should be considered?
Hooks within `ModItem`/`GlobalItem` are almost certainly not the only method of doing this, but aside from *maybe* making a new class or similar for them (which seems excessive) I can't really see this being easily done another way at the time of writing this issue.

**Comment by DarioDaF** [comment]
Hi, I'm new in the tModLoader comunity and this seems doable I usually have weekends as free time to work on projects, I'm gonna give this a try this week end (the issue seems to imply only item based informational accessories, while a general hook to part of DrawInfoAccs registering a "information slot" might be more flexible to allow permanent info upon consumption of an item)

**Comment by JavidPack** [comment]
Looks like this issue was never closed, this issue was already resolved in #1370 for use on the 1.4 branch. Sorry about that. If you come to the discord server, we might be able to find you something within your skillset that you can attempt to implement.
