### ISSUE TITLE
Add proper support for "library" mods.

### ISSUE THREAD

**Issue by OliHeamon** [tModLoader/tModLoader#1369]
### Description
Firstly, mods should be able to distinguish to the loader that they are libraries, probably through something in build.txt. In addition to this, library mods should be kept in a location separate to actual mods, most likely a new tab in the mods section of the main menu, and perhaps only accessible in developer mode? (To prevent people from whinging about why a mod they supposedly did not download is there).

Most importantly, downloading a mod must automatically download dependencies, and when the mod in question is enabled, it must enable them as well. The biggest cause of grief seems to be user confusion between the different download buttons; this is easily fixable by doing this.

The opposite is also true - disabling a mod should also disable the dependencies (if nothing else is using them, of course).

Extra suggestion: mandate that libraries be open source. Though this seems extreme, it might reinstate the trust of the modders if they know how the thing they're using actually works.

### What does this proposal attempt to solve or improve?
This attempts to solve a long-standing issue within the community surrounding the use of dependencies. Many modders inexplicably do not want to use them, be it because of users complaining or because they prefer, for whatever reason, to remain "standalone". We could at least fix the former.

### Which (other) solutions should be considered?
Keep things the same, which is not ideal.

**Comment by Solxanich** [comment]
[Link](https://github.com/tModLoader/tModLoader/issues/1276#issuecomment-770079559) to steam workshop issue, that mentions this as thing to fix for it ahead of SW;
Mostly just linking so that can know we have an issue dedicated to do it and not just a random comment.

**Comment by imkSushi** [comment]
> Extra suggestion: mandate that libraries be open source. Though this seems extreme, it might reinstate the trust of the modders if they know how the thing they're using actually works.

People who don't want their lib to be open source will just not mark them as libraries, which would lead to the whinging continuing

**Comment by Chicken-Bones** [comment]
This seems reasonable. The libraries tab should show to all users, and each library should list "Required By: mod1, mod2"

**Comment by JavidPack** [comment]
Aside from separating library mods in the UI, this feature is implemented. I don't think we need to separate library mods at this time.
