### ISSUE TITLE
Requested vanilla code to watch out for in 1.4.2 BUT isn't guaranteed. 

### ISSUE THREAD

**Issue by Solxanich** [tModLoader/tModLoader#1372]
### Description
There are a fair few number of code changes in 1.4.2 that we asked about happening.
This issue summarizes them all from September 2020 onwards, and things we will need to check/update with regards to the ones that are known:

- [x] "Fix player biome being wrong for one frame when using teleportation" #1359 
  - [x] TODO: Add our hook to ForceUpdatePlayerBiomes
- [x] "basically with the NotScalingWithLuck itemdroprule, it leads to normal CommonDrop instead of CommonDropNotScalingWithLuck"
- [ ] "we would really appreciate having any sort of vanilla system which A. Puts all the vanilla items and probabilities into a data structure and B, gives us a common hook point for all chest gen contents."
- [ ] "swords  being 1 tick faster than any other weapon with same speed" #1138 
- [ ] WeGame bizarreness. Currently 'safely' de-prioritized, possibly we won't need to ever consider.
- [x] Mass conversion of private to public 
  - [x] in ItemDropRules
  - [x] on DoBootsEffect
  - [x] TryGetBuffTime
  - [x] BuffHandle_SpawnPet
  - [ ] Whip related methods
  - [ ] Methods related to reading .wld files
  - [ ] LegacySoundPlayer: Sound instance arrays and related
  - [ ] LegacyAudioSystem: Similar to SoundPlayer
  - [ ] All the buff related static methods in Main public
- [ ] Conversion of some liquid classes to liquid structs for memory saving
- [ ] Server's storing minimaps in instanced readonly fields bizarrely. Quote a dev: "(╯°□°）╯︵ ┻━┻"
- [x] Refactor ItemDropRule - dropsOutOfX, dropsXOutOfY, etc to be accurate naming (denom, numerator); IITemDropRule
- [ ] "every time that settings are saved due to the config's latest launched version number being out of date, the config.json will be missing various values that come from subscribers to Main.Preferences.OnSave. Like UseSteelSeriesRGB."
- [ ] "Rope usability check" bug
- [ ] Rewrite chest code and boss bag code (in particular bags with drop rulestuff)
- [ ] Something about resource packs supporting wav files? Needs context
- [x] Harpy feather attack not affected by harpy banner "https://forums.terraria.org/index.php?threads/harpy-feather-attack-not-affected-by-harpy-banner.90188/" ???
- [x] whoSpawnsThisProjectile (projectile owner tracking feature)
- [x] Exposing dungeon side and other local worldgen parameters as a public field
- [ ] (UNCONFIRMED, suspected as tML side) Remove debugging artifact code: Looks to be a vanilla debug artifact, code in ReLogic -> GameSenseConnection has it as every time it attempts to send it logs what its trying to send leading to log flooding. Suspect tML logs all net requests?
- [ ] in Player.HasEnoughPickPowerToHurtTile method, the GetPickaxeDamage call there uses tileTargetX and tileTargetY, instead of the x and y passed to the method.
- [ ] call to GetPickaxeDamage, as well as another one in PlaceThing_TryReplacingTiles pass the tile type to the tileID parameter, which should instead be the value returned by hitTile.HitObject(x, y, 1), as seen in PickTile
- [x] there's a small tidbit in Main.UpdateTime() where a value is divided by Main.dayRate directly, specifically for SlimeRain and journet mode time freeze

**Comment by cozykoko** [comment]
is this useful for the upcoming new terraria patch ? @Solxanich

**Comment by Solxanich** [comment]
> is this useful for the upcoming new terraria patch ? @Solxanich

Thanks for reminding me of this!
Unfortunately, this is stuff we've already requested, so not exactly what I was looking for, was looking for net-new stuff that has come up since. 
I'll have to review stuff here and see how much is outstanding at some point

**Comment by JavidPack** [comment]
Can we close this?

**Comment by Solxanich** [comment]
I think we can reasonably close this - vast majority has-been taken care of or has an issue for itself
