### ISSUE TITLE
[1.4] Moving the Patreon Link due to UI Conflicts

### ISSUE THREAD

**Issue by Solxanich** [tModLoader/tModLoader#1380]
### Description
The Patreon Link for tML is placed in the bottom left hand corner, and frequently overlaps with the back button in modded menus and the change mod theme introduced in 1.4 at lower resolutions.

### Log file
![image](https://user-images.githubusercontent.com/59670736/112206229-4e23cd80-8bdb-11eb-80c6-3d8002d64038.png)

![image](https://user-images.githubusercontent.com/59670736/112206302-63006100-8bdb-11eb-81a8-f03814f4c31a.png)

### Steps to reproduce
Any resolution below 1020 x 720 will have this problem while Patreon Link is displayed.

### Expected behavior 
We should look at opportunities to move the patreon link to not be overlapping UI, such as within the context of #687 .

**Comment by Hotmud9** [comment]
~Just use a higher resolution lmao~
Joking aside, moving the Patreon link to the credits does make sense.

**Comment by JavidPack** [comment]
New icon link fixes this.
