### ISSUE TITLE
[1.3] OnPickup running at the wrong time.

### ISSUE THREAD

**Issue by RighteousRyan1** [tModLoader/tModLoader#1382]
## Description
`OnPickup` seems to be a bit weird and messy when it comes to calling it. Even when a player doesn't have permission / the ability to pickup any said item, it still runs the hook regardless of conditions when the player and item hitboxes intersect.

### Log File
No log file, this is a simple mistake with hook calling.

### Steps to Reproduce
[1.] Return `ModItem`/`GlobalItem.CanPickup` as false or fill up inventory completely. 
[2.] Override `OnPickup` respectively. 
[3.] Put any code in `OnPickup` and it will run as long as `Player.Hitbox` intersects the `Item.Hitbox`.

### Expected Behavior 
Nothing in `OnPickup` should not be running as long as the player has no inventory space left or `CanPickup` is false.
Code is constantly run every frame during the things mentioned in the Description of this issue.

### Actual Behavior
Seems like `Player.Hitbox.Intersects(Item.Hitbox)` is being checked or something of the sort.
This causes the issue with the hook.

### Reproduction Frequency
100% of the time, easily. Just do the things mentioned in **Steps to Reproduce**

### Additional Information
Nothing extra is really worth noting.

**Comment by Agrair** [comment]
Are you aware of the condition of this problem in 1.4? I think you said OnPickup isn't implemented, yes?

**Comment by RighteousRyan1** [comment]
This works fine in `1.4`, but not in `1.3`.
`GlobalItem/ModItem.OnPickup` is implemented, I was talking about `GlobalItem.OnCraft`. It was removed.

**Comment by JavidPack** [comment]
Since it is mentioned that it works on 1.4, we will close this for now since 1.3 is legacy at this point.
