### ISSUE TITLE
Buying an Item has different functionality depending on if you Right Click or Left Click

### ISSUE THREAD

**Issue by doombubbles** [tModLoader/tModLoader#1400]
I'm not sure if this is something that was part of Terraria 1.3.5.3 originally or if this is because of tModLoader, but this really doesn't seem like intended behavior.

(screenshots from using dnSpy on tModLoader.exe below)

If you left click, it will attempt to automatically reforge the bought item.
![image](https://user-images.githubusercontent.com/7967384/112787196-e0c5d180-900c-11eb-8ab5-00911681346e.png)

However if you right click, it won't.
![image](https://user-images.githubusercontent.com/7967384/112787519-8da04e80-900d-11eb-84ec-162e8a0486a5.png)

This behavior can be confirmed in-game very clearly.

**Comment by Agrair** [comment]
If I had to guess, this is probably vanilla behavior. Typically, right click is used for stacking items like rope, whereas left click is for non-stacking items, so it stands to reason that reforging for right clicks are just excluded.

**Comment by DarkLight66** [comment]
This is actually vanilla 1.3 behavior. As for vanilla 1.4, items from shops cannot get modifiers at all, which i'm assuming is due to shops now allowing returning the item for the full price, which would mean a gain/loss if the bought item happened to get a prefix.

**Comment by Hotmud9** [comment]
> This is actually vanilla 1.3 behavior. As for vanilla 1.4, items from shops cannot get modifiers at all, which i'm assuming is due to shops now allowing returning the item for the full price, which would mean a gain/loss if the bought item happened to get a prefix.

Ohhhhhh, that explains why I wasn't getting any modifiers from shop items lol

**Comment by JavidPack** [comment]
Can someone definitively confirm that this issue is no longer present on 1.4 tmodloader and matches 1.4 terraria?

**Comment by JavidPack** [comment]
Ok, well, I got around to checking and behavior is consistent between current tmod and terraria so it's all working correctly.
