### ISSUE TITLE
tModLoaderserver.exe not working

### ISSUE THREAD

**Issue by Darkerstar120** [tModLoader/tModLoader#1414]
### Description

I'm trying to host a tModLoader server, but everytime I try to launch one I get an error message. Once I click ok it takes me to github to see if my issue is one of the most common ones. I can't find the issue on the list provided. 
![image](https://user-images.githubusercontent.com/81723030/113229748-94c19980-9265-11eb-8b67-0c8ba8ce888e.png)

### Log file

[client.log](https://github.com/tModLoader/tModLoader/files/6240289/client.log)

### Steps to reproduce

1. Load into tModLoader
2. Go to Host and Play
3. Choose any character (or create new, doesn't matter)
4. Choose any world (or create new, doesn't matter)
5. Attempt to start the server
6. Game crashes and gives the error previously mentioned

### Expected behavior 

You should be able to just host the server
### Actual behavior

The game crashes giving the error mentioned above
### Reproduction frequency

The issue is reproduced every single time I try to Host and Play with any character on any world. I've tried uninstalling and re-installing. I've tried verifying integrity of game files. I've tried many different things to no avail.
### Additional Information

Once again I'll leave the crash log information here

![image](https://user-images.githubusercontent.com/81723030/113230126-64c6c600-9266-11eb-90cc-04565a2b0e69.png)

I apologize if this issue has been resolved in the past, I couldn't find a thread about it.

**Comment by JavidPack** [comment]
This seems to be a case of file permissions being messed up, I would check tModLoader.exe and tModLoaderServer.exe and check that all users can execute them both. I don't know much about this, but that's what I gathered by some googling of the issue. I've heard of similar issues where Steam installs the files under the wrong user account.

Another thing to try is deleting the tModLoader folder itself, just incase uninstall isn't deleting it and resetting the permissions. It could also be a permissions issue with  the \Documents\ folder, sometimes windows is overprotective. You can try telling tModLoader to instead save to the install folder by making a text file named savehere.txt in the install folder, if that works, you can copy over your ModLoader folder contents into the newly created ModLoader folder. 

If everything fails, come to discord for live help, other people have other suggestions that are worth trying.
