### ISSUE TITLE
Add indicator of changed mods for Worlds similar to characters

### ISSUE THREAD

**Issue by Monkeyatgunpoint** [tModLoader/tModLoader#1416]
### Description
there is an icon that says what mods are new and/or missing when selecting a character, why doesn't this apply to worlds too? I also think it should prompt you when you try to load up a world with mods missing and ask if you wish to continue, furthermore, it should be more obvious when there are new mods or missing mods than a tiny box with an exclamation mark, maybe make the entire row orange or red.

### What does this proposal attempt to solve or improve?
this helps prevent players from clicking the play button on their favourite world, only to find everything irreversibly broken (this happened to me twice in case you haven't guessed, took me hours to replace everything)

**Comment by Solxanich** [comment]
A couple of items:
A) have you tried using Mod Helpers lock mods for world feature?  It may be helpful for you in interim that is 1.3
B) in terms of 'irreversibly broken' could you please be more specific? Our current plans for 1.4 include preserving walls and chests in addition to 1.3s tiles, so if something else is breaking, it would be great to know
C) I do like the idea of worlds showing if mods added/removed, so good suggestion independent

**Comment by Hotmud9** [comment]
Why do you think world backups are a thing?
