### ISSUE TITLE
TModLoader doesn't save

### ISSUE THREAD

**Issue by BetaCarotina** [tModLoader/tModLoader#1418]
### Description
When I try to exit any world with any character with any mods loaded, the game either crashes or shows a character, identical to another one, though it's only visual, as reloading the game properly shows the characters again, though without any progress saved.

### Log file
This one was created after a crash rather than character anomalies.
[client.log](https://github.com/tModLoader/tModLoader/files/6249353/client.log)

### Steps to reproduce
1. Enter the world
2. Do something
3. Exit the world through the appropriate menu

### Expected behavior 
The game should've been saved

### Actual behavior
It isn't saving, and sometimes crashes

### Reproduction frequency
Always

### Additional Information
All I currently know is that it's not connected to Terraria's resolution (I know, this sounds stupid, but that's all info I have)

**Comment by direwolf420** [comment]
> [14:40:49] [1/INFO] [Terraria]: Steam Cloud Quota: 0.0 bytes available

You need to free up space on the cloud. Just to note: Terraria and tModLoader share the same cloud space, so clearing out Terrarias cloud saved files should also open it up for tModLoader.

**Comment by BetaCarotina** [comment]
I moved half of the worlds I never used and forgot to remove, but the problem still persists. Might I also note that the Steam says that Terraria has 800.09 MB of free space, while TModLoader has "0 bytes"

**Comment by direwolf420** [comment]
tModLoader can only use the first 150 MB of space Terraria occupies
so get Terrarias usage below that, and you have more space for tModLoader
