### ISSUE TITLE
Color settings in mod's config doesn't work properly on Linux.

### ISSUE THREAD

**Issue by MoonLifer** [tModLoader/tModLoader#1419]
### Description
Color slider options ("Alpha", "Red", "Green", "Blue") doesn't work properly. When I try to adjust to a number, other than zero and then press "Save Config" button, it changes the number to 255 and changes the color as well.

### Log file
[client.log](https://github.com/tModLoader/tModLoader/files/6252453/client.log)

### Steps to reproduce

1. Open the game (While on Linux);
2. Enable any mod, that have color settings in it's config;
3. Try to change "Red" (for example) to 0;
4. Press "Save Config";
5. Try to change "Red" to any number from 1 to 254;
6. Press "Save Config" again.

### Expected behavior 
The color setting should be changed to 0 (after first four steps), and to a number between 1 and 255, that you have selected.

### Actual behavior
Slider moves to 255 and color changes as well.

### Reproduction frequency
Always.

### Additional Information
Probably, you will find no logs about color changing in mod config's. Maybe because tModloader doesn't record anything about config's changes in log.

**Comment by Solxanich** [comment]
Thanks for the report!
Before we look further into this on our end, could you please reach out to the affected mod(s) developers to confirm this isn't an issue coming from their implementation?

**Comment by MoonLifer** [comment]
So I asked Jopojelly to look for any issues in Boss checklist's config first. He gave me ColorSliderTest.tmod and asked me to experiment with color sliders. And I have got the same problem I had with Boss Checklist and OriMod.

**Comment by Mirsario** [comment]
Needs to be tested on 1.4. Could likely be fixed by the NET5 FNA port.

**Comment by JavidPack** [comment]
I'm fairly certain this is fixed as a result of updating FNA. If anyone on linux thinks they are having this issue still on 1.4 tModLoader, check SomeColor in ExampleMod's "Showcase D: Default Values" config, if it doesn't behave correctly, comment below and we will reopen this issue.
