### ISSUE TITLE
"Click to download just the targetting pack" not working

### ISSUE THREAD

**Issue by JohnSmith777779** [tModLoader/tModLoader#1421]
### Description
(I can't download Visual Studio) I can't enable developer mode because the reference assemblies aren't found, but when I click the button labeled "Click to download just the targetting pack", a download bar pops up and disappears immediately

### Log file
[client.log](https://github.com/tModLoader/tModLoader/files/6253008/client.log)

### Steps to reproduce
1. Enter the Mod Sources menu without Visual Studio installed
2. Click on the "!" button under ".NET 4.5 Reference Assemblies not found. Please install Visual Studio with the .NET 4.5 Targetting pack"
![download button that is feeling sick right now](https://user-images.githubusercontent.com/68935009/113485365-163e4500-947b-11eb-9b7b-9b986f71e056.png)

### Expected behavior 
The download bar under "Downloading: v4.5 Reference Assemblies" progresses and the assemblies are downloaded.

### Actual behavior
The download bar appears for about a third of a second and doesn't progress. The previous menu returns and nothing is downloaded.
![Fleeting Progress Bar](https://user-images.githubusercontent.com/68935009/113485352-06befc00-947b-11eb-959d-b2c2b8acbce1.png)

### Reproduction frequency
100% of the time even after restarting tModLoader

### Additional Information
Terraria version 1.3.5.3
TML version 0.11.7.2

[One person had this issue, but didn't include information and closed it on the same day.](https://github.com/tModLoader/tModLoader/issues/1264)

**Comment by JohnSmith777779** [comment]
There's information on the Discord

> **Tag: referenceassemblies (Owner: jopojelly#2739)**  
> The in-game download of the reference assemblies doesn't work at the moment, the workaround is to download this: https://tmodloader.net/dl/ext/v45ReferenceAssemblies.zip  
> Then, extract the contents of the `v4.5` folder from within the zip into: `C:\Program Files (x86)\Steam\steamapps\common\tModLoader\ModCompile\v4.5 Reference Assemblies` (make the folder if it doesn't exist).  
> Finally, leave and come back to the enable developer mode menu.

**Comment by nightblade9** [comment]
There's a work-around mentioned [here](https://github.com/tModLoader/tModLoader/issues/1887#issuecomment-933295752) that works for me (TL;DR download .NET 4.5.2 and copy/paste the folder to v4.5).
