### ISSUE TITLE
I cant update TML

### ISSUE THREAD

**Issue by MiReNooo** [tModLoader/tModLoader#1423]
I started TML and there a lot of mods needed new version of TML so i wanted to update it but in Steam but there was no update! I reload the steam but no but it wasn't there anyway.
Help please!
![screenshot](https://user-images.githubusercontent.com/81896101/113499923-c2476500-953b-11eb-92ff-7c4193b18b57.png)

**Comment by JavidPack** [comment]
I can confirm that 0.11.8.3 is live on Steam. Come to discord for support, it is better suited for helping you solve this issue.
