### ISSUE TITLE
Game freezes when near an evil biome and tundra

### ISSUE THREAD

**Issue by HaxchiDev** [tModLoader/tModLoader#1427]
### Description
When I go near an evil biome, the player character just suddenly freezes.

### Log file
[client.log](https://github.com/tModLoader/tModLoader/files/6255797/client.log)

### Steps to reproduce

1. Load a world
2. Walk to an evil biome

### Expected behavior 
The game should continue on.

### Actual behavior
The player freezes and cant use any ui elements.

### Reproduction frequency
80% of the time

### Additional Information
Mod list:
Calamity Mod 1.4.5.7
Yet Another Boss Health Bar 1.3.2
Recipe Browser 0.8.8.1
VeinMiner 1.3.1
Boss Checklist 1.1.5.4
Mod of Redemption 0.7.9.62
Start with base 0.2.2.5

**Comment by direwolf420** [comment]
First of all, I would like to point out that this is not the usual install direction: `Desktop\mah stuff\games\tModLoader.Windows.v0.11.8.3\tModLoader.exe`, the normal one is besides Terraria, usually in `steamapps/common` or `GOG Games`.

The issue is most likely related to music in those biomes, and your audio device not registering. Plug in a suitable audio device (headset, speakers).

**Comment by HaxchiDev** [comment]
Hmm... The music when i play does not work, so this might make sense, but even with headphones, the music does not work at all. anyone know how to fix the music not working?

**Comment by Hotmud9** [comment]
Could it be a mod conflict with Calamity and MoR?

**Comment by HaxchiDev** [comment]
disabled MoR, issue still persists.

**Comment by HaxchiDev** [comment]
update: player freezes when blizzard occurs as well

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
