### ISSUE TITLE
Document FAudio changes and build instructions

### ISSUE THREAD

**Issue by Chicken-Bones** [tModLoader/tModLoader#1429]
The latest version of FNA we can use on windows is 20.08 because it's the last version of FAudio with the FFmpeg backed for xWMA decoding.

I've managed to get G-Streamer working before and there are some instructions left in `GStreamerAudioSupport.cs` but the G-Streamer plugin backend is slow, large and just delegates to FFmpeg anyway. Additionally, it doesn't work with a minimal FFmpeg build only including xWMA decoding.

Ideally, we should be able to build a native, windows dll which pretends to be G-Streamer to FAudio, but just talks directly to FFmpeg/libavcodec like the old FAudio used to, acting as a lightweight shim.

Other options are to maintain a custom FAudio build on windows which runs the old FFmpeg backend, or to develop a slimmer G-Streamer plugin, dedicated to xWMA only.

**Comment by Chicken-Bones** [comment]
@Mirsario can you update our FNA fork to include the FAudio changes we're currently running with, along with build instructions?

**Comment by Mirsario** [comment]
Since a somewhat recent pr we no longer use anything special in case of FAudio, because it killed off THE DEMON that is gstreamer in favor of WINAPI calls that just.. Work like they used to on xna.

**Comment by Chicken-Bones** [comment]
So our FAudio identical to the one in mainstream FNA? No small tweaks to enable support?

**Comment by Mirsario** [comment]
I am not sure if fnalibs distributions compile the windows version with the win32 directive (`PLATFORM_WIN32=ON`, all that is required), but the code on github is the same. Our `ffmpeg` branch is no longer used and the main branch is now `master` again, which has no commits from us.
