### ISSUE TITLE
[1.4] Turn Tile into a struct

### ISSUE THREAD

**Issue by Mirsario** [tModLoader/tModLoader#1430]
Tile being a class can potentially steal around 160MB of memory on large worlds in 64-bit mode. That misuse of 'class' also costs the game some cpu/memory lookup performance. We should try turning it into a struct.

This will require making a roslyn analyzer patch step for the sake of turning normal Tile locals into ref locals, like:
`var tile = Main.tile[x, y];` -> `ref var tile = ref Main.tile[x, y];`.

**Comment by sgkoishi** [comment]
TShock (or, OTAPI under MIT license) use [`ITileCollection`](https://github.com/DeathCradle/Open-Terraria-API/tree/master/OTAPI.Modifications/OTAPI.Modifications.Tile) interface with `ITile this[int x, int y] { get; set; }`, make this replacement compatible without modifying the source of other usages.
However, a re-compile/patch is still required for those already compiled assemblies.

**Comment by Chicken-Bones** [comment]
it would be possible to be compatible with that, but anyone using the TShock api would have significantly degraded performance.

**Comment by sgkoishi** [comment]
The default TShock TSAPI uses a [`TileProvider`](https://github.com/Pryaxis/TSAPI/blob/e0302513009220a8d92ba12c867a401e7731d28a/TerrariaServerAPI/TerrariaApi.Server/TileProvider.cs) and HeapTile, which stores data in a raw `byte[]`.
A plugin called [Tiled, GPLv3](https://github.com/thanatos-tshock/Tiled) provides 1d and 2d struct array implementation without performance and memory usage degrades.


From [TiledPlugin.cs](https://github.com/thanatos-tshock/Tiled/blob/43174c827f062a68d5b8415cf470a69805c084c4/Tiled/TiledPlugin.cs#L11-L40)
> The tiled plugin which will be loaded into a TSAPI server.
> It serves to bootstrap one tile provider.
> </summary>
> <remarks>
> Here's the short on the major differences between my versions and TSAPI's HeapTile.
> ** based on the release version
> ** excludes internal array initialisation
> 
> 1dTile:
> 6 instructions used to get a tile from the provider
> 8 instructions used to set a tile into the provider
> 1d stores tiles in one flat array, using one int32 index.
> 
> 2dTile:
> 6 instructions used to get a tile from the provider
> 8 instructions used to set a tile into the provider
> 2d stores tiles using two dimensions, using two int32 indexes
> Using int32 instead of int16 because array indexers require int32, which also saves 2 instructions per access
> 
> Structured:
> 7 instructions used to get a tile from the provider
> 10 instructions used to set a tile into the provider
> Structured stores tiles in one flat array, using one int32 index - similar to 1d
> 
> TSAPI's HeapTile provider:
> 40+ instructions used to get a tile the provider (i lost count, twice - but you get the point)
> 14 instructions to set a tile into the provider
> HeapTiles are stored in a flat one dimensional array, using one int32 offset + constants to calculate data offsets

**Comment by Chicken-Bones** [comment]
Right, so our implementation would be most similar to struct tile approach from TiledPlugin. Anyone from tShock could still use `StructuredTileReference : ITile` but tML would be using the tile struct directly (often via `ref Tile`).

The most significant thing to take into account is boxing. Whenever someone writes `ITile` in their code, the `StructuredTileReference` has to be wrapped in a new object allocated on the heap with the same data, because interfaces all operate by reference. There's no way to get the cpu performance of a struct without using that struct type directly.

**Comment by sgkoishi** [comment]
Yes, a reference wrapper seems to be slower than a direct accessing array (either class or struct).

An interesting finding is that the assembly instruction count of those different implementations:
| | 2d array of class | 2d struct | 1d struct | 1d struct with 2d wrapper |
|:--:|:--:|:--:|:--:|:--:|
| Read Field | 25 | 26 | 19 | 26 |
| Write Field | 26 | 27 | 20 | 27 |
| Assign with a given item | 16 | 21 | 26 | 33 |
| Create new item and assign | 22 | 31 | 36 | 43 |
| Do something more | 36 | 39 | 31 | 60 |

By "do something more" it's
```csharp
public void Test(int width, int height)
{
    var item = tiles[width, height];
    Console.WriteLine(item.type + item.wall);
    item.type = (ushort)width;
    item.wall = (ushort)height;
    item.liquid++;
    item.sTileHeader--;
}
```

While 2d struct array always has more instructions than 2d class array, 1d struct array is performing well except assigning. No idea why :)

**Comment by Chicken-Bones** [comment]
I doubt you're disassembling x86 here, so I want to say that IL instruction count is a poor proxy for performance. Only profiling will get you moderately close to the insitu result

**Comment by sgkoishi** [comment]
Count jitted assembly code under release mode, core clr 5.0, x86.
The difference between 2d class and 2d array field r/w is `mov eax, [eax+edx*4+0x18]` -> `lea eax, [eax+edx+0x18]` + `movzx eax, word ptr [eax+6]` 
~~I guess the 1d version is much shorter for less index boundary check but I actually have no idea about assembly~~

The IL count is quite different, I'm not expecting it:
| IL Count for x86 release core 5 | 2d array of class | 2d struct | 1d struct | 1d struct with 2d wrapper |
|:--:|:--:|:--:|:--:|:--:|
| Read Field | 6 | 6 | 9 | 6 |
| Write Field | 7 | 7 | 10 | 7 |
| Assign with a given item | 6 | 6 | 9 | 7 |
| Create new item and assign | 9 | 11 | 14 | 12 |
| Do something more | 34 | 36 | 39 (even more than jitted) | 38 |

**Comment by Chicken-Bones** [comment]
See #2047 instead
