### ISSUE TITLE
[1.4] Optimize or redesign IsVanitySet

### ISSUE THREAD

**Issue by Mirsario** [tModLoader/tModLoader#1431]
### Description
ItemLoader.IsVanitySet and a similar method have always been infamous for sometimes ruining performance of the game, due to them creating new Item instances, together with SetDefaults calls. We can either solve this by using ContentSamples, or by redesigning vanity sets to be declarative.

**Comment by AnyhowStep** [comment]
Can we close this ticket?
https://github.com/tModLoader/tModLoader/pull/1946 seems to have solved this
