### ISSUE TITLE
[1.4] Game crashes for UIResourcePackSelectionMenu HandleBackButtonUsage

### ISSUE THREAD

**Issue by Solxanich** [tModLoader/tModLoader#1436]
### Description
Clicking the back button on ResourcePack menu in 1.4.2.1 of tModLoader dev version causes the client to hang.

### Log file
As it hangs, and isn't a crash, don't get a useful log.
Tracing it, I did find that the first null exception causing the hang is tossed at line 251 in LegacySoundPlayer: CreateInstance(SoundItem[num2]) as the last 'item' in the array is null.

### Steps to reproduce

1. Open Resource Pack selection menu
2. Click back button
3. Application hangs

### Expected behavior 
Application should return to main menu

### Actual behavior
Application hangs on a null exception

### Reproduction frequency
100%

**Comment by Mirsario** [comment]
I've used plenty of resource packs properly yesterday on mergedtesting, and this hasn't happened for me.

**Comment by Solxanich** [comment]
Fixed per #1444
