### ISSUE TITLE
Old Bug, Still Persist: Mobs Disappearing

### ISSUE THREAD

**Issue by gaestraidr** [tModLoader/tModLoader#1438]
### This bug is on Multiplayer only
This has been happening since the old update, but mobs disappearing on taking damage or on hit. So what I did was I develop a mod that modifies enemy status (Health, Max Health, Defense & Damage), and yes this the only mod thats loaded into the game. Nothing else. So then, I tried to implement some network module to sync the mob status between clients and the main server. Obviously because I want Vanilla mob to be included, I use GlobalNPC. I first hook my implementation to PostAI() to modified the stat, put it some netcode to sync to player if netmode is >0. NetMode 2 as sender, NetMode 1 as receiver. So far not going great, NPCs on every hit keep disappearing. I try to hook to:

- SetDefaults(): Nothing changes, result are the same.
- PreAI(): Same
- AI(): Same
- SpawnNPC(): Desperate attempt, even though if the npc type is found on vanilla module, it wont be called. So yeah, nothing changes.
- ScaleExpertStats(): Yes my world is in expert mode (even trying in hardmode), and no it still the same result.

Other than the hook, I tried different route to send update to client, and would I told you.. it changes nothing. Here:

- NetMessage.SendData with code 23: Does nothing, and apparently this only sync pos, life and ai, not sending defense, damage or lifemax attribute.
- npc.netUpdate: Same as above, does nothing. Well using this is just a proxy to above after all.
- Sending All Involved Stats with GetPacket() stream: It sync the stats, and yes, the problem of mob disappearing.
- Serialize and sending the GlobalNPC object as a whole: Data become a lil bigger, and it still didn't fix the problem of mob disappearing. Totally a desperate measure.

I don't get how tModLoader (or Terraria?) do it syncing, this is so confusing. Is there at some point a function that keep reseting life / lifeMax on every frame? or different things that I didnt know about? Even if that was the case, it shouldn't be a problem if it hook to Pre, Post, or AI() itself.

### Log file
Logs: https://www.dropbox.com/s/7ys1g3tq2lujc74/client.log?dl=0

### Steps to reproduce

1. Run Dedicated Server with only my mod
2. Connect with only my mod 
3. Hit any mob
4. Mob Disappear, Gone, Vanish, to ashes, to rubble, cease and decist.

### Expected behavior 
Getting hit, damage entering, life decreasing, still moving, still attacking. If dead well, died.

### Actual behavior
Yes, its mob disappearing.

### Reproduction frequency
Every Mob with this mod loaded.

### Additional Information
Theres definitely something wrong with how server and (or) client synchronize their mob status, even if the status not mismatch. I keep looking inside VanillaAI() function but didnt see anything wrong. Maybe Im just not so familiar with the implementation, so It can be me.

So all I could say is one of these factor that always make mob dissapear (on every Mod I know that do modified this) if changed:

- life
- lifeMax

I'm not sure about defense / damage. but those two above is always the case whenever I involved them.

**Comment by direwolf420** [comment]
try not changing lifeMax, Terraria has special netcode regarding this (InitLifeBytes method). Also, this sounds more like a problem with your mod and not tml, you can try asking on the discord for help, including sharing your mods code.

**Comment by gaestraidr** [comment]
I did look about at that function before, but I just realize it now after you mentioning it. Can I know the reason why is there a byte optimization? Is it for frame synchronizing? I mean 4 bytes isn't that big to send through network, I've never heard bottlenecked system because of just 3 bytes more, it looked somewhat unnecessary to optimize those.

**Comment by gaestraidr** [comment]
And it kinda limit the extends of what modding can do. Especially when the mod is trying to utilize RPG Advancement mechanic throughout the game. One of the case is where Calamity Mod advancing mob status (life included) after defeating Devourer of Gods and it bugged the mob like dissapearing things, and that mod isn't even using any RPG style mechanic. 

As far as I know, any RPG Game I know that exist never hit that 4 bytes ceiling. I mean I just need 1/2 bytes more to escalate the game difficulty on each leveling. And surely, 1 byte won't be enough to utilize those genre. It just restricting too much scenario what mod can do. Like mobs around the area get buffed when fighting a modded boss, or after defeating them making a narration that something unsealed / unleased. This is just won't happen.

**Comment by gaestraidr** [comment]
Aside from that thank you though, I fix it with forcing the byte to 4 in PreAI() by accessing Main.npcLifeBytes[npc.netID] and it sync now, you really help my frustation from overflowing. I did not see bottleneck in frame, my device is from 2015, and its an old laptop.
Although my point still stand, but if this not the right place to discuss it, you can close the issues.

**Comment by direwolf420** [comment]
In 1.4, all this headache will not exist, as life/lifeMax syncing is done on-send and not through Main.npcLifeBytes anymore

**Comment by gaestraidr** [comment]
Thats good to know, thank you. Let me close this issue now!
