### ISSUE TITLE
Prefix category override for items

### ISSUE THREAD

**Issue by DarkLight66** [tModLoader/tModLoader#1446]
### Description
I propose a way to override from which category of prefixes a modded weapon can get, something along the lines of:
```cs
public override PrefixCategory? PrefixCategoryOverride => null;
```
Where returning null would default to the current behavior.

### What does this proposal attempt to solve or improve?
Right now, tModLoader assumes that weapons added by mods should receive prefixes based on their damage type, which is fine in the great majority of cases. However, for melee prefixes specifically it also arbitrarily checks for `Item.noUseGraphic` being false, which doesn't apply for all vanilla melee weapons, notable examples being the shortswords, after their changes in 1.4, as well as the Zenith. 
Note that I am aware of an existing way to circumvent this issue in tModLoader, but it would entail overriding `ChoosePrefix` and recreating the vanilla code + tMod hooks for choosing the prefix.

**Comment by JavidPack** [comment]
Addressed in #2773
