### ISSUE TITLE
[1.4] Visual bug in Player centred Dust and Gore

### ISSUE THREAD

**Issue by Ishigh1** [tModLoader/tModLoader#1449]
### Description
I noticed that some of the dust and gore effects are duplicated to the top left corner of the screen and only when the minimap is shown (it's a bit hidden as it's under the 1 in the hotbar, but it doesn't seems to move with the player once generated.

### Steps to reproduce
The easiest one to trigger is Leinfors' Luxury Shampoo, but it works with at least few others. When equipped and visible, sparkles should appear on the top left.

### Additional Information
I looked at the code, and only saw Dust and Gore stored in Terraria.DataStructures.PlayerDrawSet.DustCache/GoreCache triggering the bug for now, and every effect I tried was duplicated (Leinfors' Luxury Shampoo, On Fire!, FrostBurn, Palladium buff, Lovestruck and Stinky). I also tried Lovestruck on NPCs, it doesn't trigger the effect (but I didn't test on other players).
I also noticed that the effet on the top left and on the player don't seem to share a pattern  and going to the world edge doesn't change where the additional effect spawn on the top left

**Comment by JavidPack** [comment]
Can you get a screenshot and confirm that this does not happen on vanilla Terraria?

**Comment by Ishigh1** [comment]
Well, it's hard to say something doesn't exist, but here's a screenshot of vanilla and tmod with lovestruck active because it's one of the most visible while standing
Vanilla : 
![vanilla](https://user-images.githubusercontent.com/45936615/115106023-a2b03380-9f62-11eb-9e7c-cb1dac083ed7.png)
Tmod : 
![tmod](https://user-images.githubusercontent.com/45936615/115106029-a9d74180-9f62-11eb-9299-869c50f2b714.png)

**Comment by JavidPack** [comment]
I can't replicate. Are you sure you have 0 mods enabled?

**Comment by Ishigh1** [comment]
It also happens when no mods are loaded
