### ISSUE TITLE
Clenteminator memory leak

### ISSUE THREAD

**Issue by DidgetMidget** [tModLoader/tModLoader#1450]
### Description
If i use the Clenteminator for a certain amount of time like 2-5 minutes i get an out of memory error. I guess that revealed area is causing this issue  

### Steps to reproduce

1. Open taskmanager to see the memory increase
2. Using the clenteminator to reveal unrevealed area on the map

### Expected behavior 
That revealed area should be cleaned by the garbage collector because you cant see it anymore after some time

### Actual behavior
Memory does not get cleared. 

### Reproduction frequency
100%

**Comment by direwolf420** [comment]
1.3 or 1.4?

**Comment by DidgetMidget** [comment]
Its 1.3 and its the same behavior on this 32bit tmodloader version and the 64bit version
And i ran some further testing myself only happens on a dedicated server single player is fine (tested this only in the 64bit version) idk about singleplayer and 32bit 
Here is my mod list
  "AlchemistNPC",
  "MagicStorage",
  "CalamityMod",
  "BossCursor",
  "VeinMiner",
  "ElementalHearts",
  "RecipeBrowser",
  "TerrariaAmbience",
  "WMITF",
  "SmartDoors",
  "CalValEX",
  "FargowiltasMusic",
  "Luiafk",
  "ReducedGrinding",
  "FargowiltasSouls",
  "BossChecklist",
  "chadsfurni",
  "FKBossHealthBar",
  "StarterClasses",
  "NoMoreTombs",
  "Fargowiltas",
  "CalamityModMusic",
  "FargowiltasSoulsDLC"
  
 Tho these logs are from the 64bit version its nearly the same problem i just got more memory to play around with and instead of a out of memory exception my client freezes and before that i stop getting new world information from the server so its an empty world after using the clenteminator for a short while 
[client.log](https://github.com/tModLoader/tModLoader/files/6331143/client.log)
[server.log](https://github.com/tModLoader/tModLoader/files/6331144/server.log)

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
