### ISSUE TITLE
wall mounted items sometimes bug out

### ISSUE THREAD

**Issue by Gsoverheaven** [tModLoader/tModLoader#1458]
sometimes when i want to hang a weapon on a weapon rack or place a decorational background item like the spear rack or painting, the thing will bug out and drop random items, the items include:
-paintings
-trophies
-weapons
-blocks
-unobtainable items
-money and many more
so far, this bug happens randomly and i can't find a way to reproduce it, i asked around and some say it's something to do with internal ids conflicting.

**Comment by kittenchilly** [comment]
If this is 1.3, it's known and will be fixed in 1.4 tModLoader.

If it's a 1.4 version of tModLoader, this could actually be an issue, but first, we should clear the version you're using up.

**Comment by Gsoverheaven** [comment]
0.11.8.3(latest)
again it happends randomly when i enable/disable some mods

**Comment by Gsoverheaven** [comment]
it's 1.3

**Comment by Gsoverheaven** [comment]
if it's knowsn and may be fixed then you can close the thread

**Comment by Mirsario** [comment]
The 1.3 TML version has nearly no support for item and weapon racks. This is fixed on the 1.4 development branch.
