### ISSUE TITLE
[1.4] Use HJson for localizations

### ISSUE THREAD

**Issue by Mirsario** [tModLoader/tModLoader#1471]
This has been discussed in discord. The current .ini syntax that lang files use is too limiting, and requires a lot of key repetition. Json would be too annoying to write. Toml - too confusing/weird. HJson, however, seems perfect - https://hjson.github.io/

**Comment by Mirsario** [comment]
Related to #1365

**Comment by jackbondpreston** [comment]
Happy to give this a shot, but what is the process for adding dependencies (https://github.com/hjson/hjson-cs for parsing HJson)?

**Comment by Mirsario** [comment]
Nuget should work.

**Comment by jackbondpreston** [comment]
@Mirsario closable I should imagine
