### ISSUE TITLE
Tmodloader lag bug

### ISSUE THREAD

**Issue by Samuell2000** [tModLoader/tModLoader#1474]
I don't really know how to explain the bug so here is a video. 

https://youtu.be/OkFvE_uhOIU

**Comment by cozykoko** [comment]
what is the mod?

**Comment by Samuell2000** [comment]
The mod was deleted by the owner i cant find it

**Comment by direwolf420** [comment]
This is a known bug with that particular mod (and another mod aswell). Not a tML issue
