### ISSUE TITLE
[1.4] Duplication Menu doesn't respond to mouse scroll

### ISSUE THREAD

**Issue by YoruToboe** [tModLoader/tModLoader#1475]
### Description
Research Duplication Menu middle mouse scroll won't scroll up or down.

### Expected behavior 
The middle mouse scroll should go up or down depending on the direction of the scroll

### Actual behavior
Doesn't work. Still able to manually scroll the window using the right scroll bar

### Reproduction frequency
Always

### Additional Information
Using tModLoader 0.12 mergetesting branch

**Comment by Mirsario** [comment]
Fixed with #1528
