### ISSUE TITLE
Auto Selector resets

### ISSUE THREAD

**Issue by PrimeNL** [tModLoader/tModLoader#1478]
Auto Selector resets after releasing the button for it, even when still holding the "Use item" button.
Happening on "1.4" and "1.4_mergedtesting" branches

Have a pickaxe and torch in inventory > put copper sword as active > hold auto select button > hover a minable tile > start mining, you now remove the block and then place a torch > mine the torch on infinite repeat.

What should happen is that you keep swinging the pickaxe until you release the use item button (left mouse) even if you released the auto select button

**Comment by DarkLight66** [comment]
This feels like it has to do with the tModLoader changes to `itemAnimation` in the `Player.ItemCheck` method, which now make it so there's one frame between each use where `itemAnimation` is 0 (aka no item is in use) on `autoReuse` items.

**Comment by andrewlord607** [comment]
> This feels like it has to do with the tModLoader changes to `itemAnimation` in the `Player.ItemCheck` method, which now make it so there's one frame between each use where `itemAnimation` is 0 (aka no item is in use) on `autoReuse` items.

I could not find an issue describing this, but apparently it causes blinking sprites on auto reusing items. 
Now this prevents me from understanding when to reset the animation.
Is there a solution already?

**Comment by Solxanich** [comment]
@PrimeNL - This bug should have gone a way with the recent merge of UseItemFix to 1.4 and 1.4 MergedTesting.
If it indeed has gone away, do you mind closing this?
