### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Avoreas** [tModLoader/tModLoader#1486]
Hello, after loading tModLoader it does not respond to mouse and keyboard presses, I have Windows 7 Pro 64x, there is no log file for some unknown reason, please help

**Comment by Chik3r** [comment]
>  there is no log file

This might be caused by your antivirus, so try disabling it: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#systemunauthorizedaccessexception-access-to-the-path-is-denied
