### ISSUE TITLE
[1.4] Release build has several graphical glitches

### ISSUE THREAD

**Issue by direwolf420** [tModLoader/tModLoader#1487]
### Solution
Apparently updating to `NETCore 5.0.5` ([latest as of 29th april 2021](https://dotnet.microsoft.com/download/dotnet/5.0)) fixes this.

### Description
Either get a pre-[nightly-fix](https://github.com/tModLoader/tModLoader/commit/58cc5ec1d2678585d99460821ec8c7299ac36849) build, or build the release directly, enter a world, and after a second, items turn opaque in a seemingly random color each time (reports of green, grey, purple, blue), NPCs disappear, dusts are barely visible. The issue happens on all graphic platforms (dx, vulkan and opengl).

No logs, no errors.

Examples:
[1](https://cdn.discordapp.com/attachments/445276626352209920/835184238068236308/Screenshot_23.png)
[2 (notice the held torch)](https://cdn.discordapp.com/attachments/445276626352209920/835183063339630642/Screenshot_21.png)
[3](https://cdn.discordapp.com/attachments/445276626352209920/835182905332203570/Screenshot_20.png)
[4](https://cdn.discordapp.com/attachments/445276626352209920/835180356319576125/Screenshot_15.png)

Specs that triggered this:
1. RX 580, driver version 18.50.03.05-181217a-337289E
Windows 7
Running on Windows NetCore 5.0.1

2. GTX 1080, driver version 466.11
Windows 10

**Comment by nevzat666** [comment]
having this issue too

**Comment by cozykoko** [comment]
Windows 10, 2070 Super, 461.92 same issues

**Comment by direwolf420** [comment]
> 
> 
> Windows 10, 2070 Super, 461.92 same issues
@cozykoko 

Can you open cmd.exe and type `dotnet --list-runtimes`, and check which version your highest Microsoft.NETCore.App version is? Something 5.0.x.

**Comment by cozykoko** [comment]
sorry, should have clarified that im aki in the discord and have already fixed it with solxan.
