### ISSUE TITLE
Vanilla item research doesn't work

### ISSUE THREAD

**Issue by Crapsky233** [tModLoader/tModLoader#1493]
### Description
When I drag a item to Journey Mode research item slot, the message bar shows "X" and I can not research it. 
![82C {D_@AW3RAPNP L{}MN5](https://user-images.githubusercontent.com/35227653/116773824-aa0b2d00-aa8a-11eb-8b9b-2b69e78867bb.png)
The research menu is empty.
![K6`J%M510 %CK4REJ5)B5LX](https://user-images.githubusercontent.com/35227653/116773918-49c8bb00-aa8b-11eb-82a6-06a18bfb132c.png)

### Steps to reproduce

1. Create a new character in Journey Mode.
2. Enter any world.
3. Drag any vanilla item into research slot.

### Expected behavior 
The research of the item should be available.

**Comment by Steviegt6** [comment]
Does it show the pink text indicating how many items are required to completely research an item? Last time I checked, it should work fine.

**Comment by Steviegt6** [comment]
Furthermore...
- Are you on `1.4`? `1.4_mergedtesting`? Any other `1.4_x` branch?
- Could you send us your logs?
- What mods are you using (should be provided in logs, regardless)?

**Comment by Steviegt6** [comment]
Research should work fine with modded items? Only issue I remember in recent time was _saving_, which I believe was fixed. Most mods just haven't bothered to give their modded items research values.
