### ISSUE TITLE
tModLoader no sounds

### ISSUE THREAD

**Issue by jianzen** [tModLoader/tModLoader#1496]
I did created another duplicate of this issue, because of a mistake (I accidentally deleted the whole text without knowing and submitting stupidly)

I'm very new to the world of modding in Terraria and basically I'm having troubles in terms of audio and music in the game. There is no slider to be found in the volume mixer, I have tried numerous ways to fix the sounds but to no avail, failed miserably from updating audio drivers, uninstalling and re-installing to using Quick Wave Banks of some sort. I'm so uncomfortable with the sheer silence while playing the game and I want to have full experience when playing with mods on Terraria. I'm currently using the latest version, v0.11.8.3.

But I did something find odd, when I'm trying to fix the audio for the god-forsaken amount of tries, I have found that in the Content folder, it doesn't have Sound folder nor the `Sound Bank.xsb`, `Wave bank.wxb` and `TerrariaMusic.xgs` and so I did find some old stuffs in the game to add those missing files from the Content folder. but the thing is, when I launch the tMod, it will just stay in the background and will not appear. I closed it again and move the `TerrariaMusic.xgs` anywhere outside of the Content folder. And when I launch the application, it will work as fine but still, no sounds. So I'm thinking maybe because of this `TerrariaMusic.xgs` file? 

Any replies that will fix this is a big help and I will appreciate it a lot. (_and sorry for the wrong grammar, English is not my first language._)

Edit: Vanilla is working fine.

**Comment by Mirsario** [comment]
The TML content directory only contains files that were changed in 1.4, to make the game use 1.3 content.

Post a log file after reproducing the issue:
> Post your `.log` files from the following OS-dependent directory:
> 
> **On Windows:** `%userprofile%/Documents/My games/Terraria/ModLoader/Logs`
> **On Linux:** `~/.local/share/Terraria/ModLoader/Logs`
> **On Mac:** `~/Library/Application support/Terraria/ModLoader/Logs`

**Comment by Chicken-Bones** [comment]
Closing due to no response
