### ISSUE TITLE
Server-side mods shouldn't be sent to clients

### ISSUE THREAD

**Issue by Ry0taK** [tModLoader/tModLoader#1497]
### Description
In `MessageBuffer.cs.patch`, there is a message type named `ModFile`: https://github.com/tModLoader/tModLoader/blob/dfe30aae2a3ecc8f5f7bc45db2132e386ddb90f5/patches/tModLoader/Terraria/MessageBuffer.cs.patch#L461-L466
When the server receives this message, the server sends back the mod contents with the name passed by the client.
https://github.com/tModLoader/tModLoader/blob/dfe30aae2a3ecc8f5f7bc45db2132e386ddb90f5/patches/tModLoader/Terraria.ModLoader/ModNet.cs#L239-L260
However, since it doesn't verify that the mod specified here is a client-side mod, it allows the client to read server-side mods.
https://github.com/tModLoader/tModLoader/blob/dfe30aae2a3ecc8f5f7bc45db2132e386ddb90f5/patches/tModLoader/Terraria.ModLoader/ModLoader.cs#L90-L94

### Expected behavior 
The server should only send back mods that are configured as a client-side mod.

### Actual behavior
The server sends back mods that are configured as a server-side mod.

### Additional Information
As it may reveal some sensitive information hard-coded in the server-side mod, I talked it with someone on the TML team.
After discussing it, it seems it should be treated as a bug rather than a security issue. So I'm opening this issue.

**Comment by Chicken-Bones** [comment]
The client would need some way to know the mod name of the server mod, since this is not exposed anywhere to my knowledge. It's an easy patch regardless.

**Comment by PragmaticBeaver** [comment]
Hi everyone! I wanted to contribute and thought this issue would be a great starting point but I can't figure out how I manually test my fix because I can't find any Terraria Mods for tModLoader Version 0.12 (because it is still in development ;D).

So I guess my only option to evaluate my fix is to create my own micro mod? Could you kindly point me in the right direction?

**Comment by cozykoko** [comment]
https://discord.com/channels/103110554649894912/445276626352209920/791631101814767626 mods for 1.4

**Comment by PragmaticBeaver** [comment]
Thank you kindly, I will look into it!

**Comment by PragmaticBeaver** [comment]
I think, I still need some help.
I can't find a way to call the aforementioned "ModNet.SendMod(reader.ReadString(), whoAmI); " method.
From the code I thought, it would be called as soon as a client connects to the server but it doesn't look like it.
The MessageBuffer class is called in a few places but it still isn't making sense to me.
Could you kindly point me in the right direction again?

**Comment by Chicken-Bones** [comment]
Please come find us on Discord! Ping me or another dev and we'll give you access to #collaborators and help you out.

**Comment by ghost** [comment]
Hi, is this do the thing? 
in MessageBuffer.cs at line 3536
```
				case MessageID.ModFile:
					if (Main.netMode == 1)
					{
						ModNet.ReceiveMod(reader);
					}
					else
					{
						string modName = reader.ReadString();
						Mod mod = ModLoader.GetMod(modName);
						if (mod.Side == ModSide.Client)
							return;
						ModNet.SendMod(modName, whoAmI);
					}
					return;
```
I can also doing that but i dont know sendmod using in other functions or not.
in ModNet.cs at line 241
```
		internal static void SendMod(string modName, int toClient) {
			Mod mod = ModLoader.GetMod(modName);
			if (mod.Side == ModSide.Client)
					return;
			string path = mod.File.path;
			FileStream fs = File.OpenRead(path);

			{
				//send file length
				var p = new ModPacket(MessageID.ModFile);
				p.Write(mod.DisplayName);
				p.Write(fs.Length);
				p.Send(toClient);
			}

			byte[] buf = new byte[CHUNK_SIZE];
			int count;

			while ((count = fs.Read(buf, 0, buf.Length)) > 0) {
				var p = new ModPacket(MessageID.ModFile, CHUNK_SIZE + 3);
				p.Write(buf, 0, count);
				p.Send(toClient);
			}

			fs.Close();
		}
```
