### ISSUE TITLE
NPC Head error

### ISSUE THREAD

**Issue by MestreSol** [tModLoader/tModLoader#1504]
The NPC head not found from the Autoload;
![image](https://user-images.githubusercontent.com/42494721/117323346-2fb12300-ae65-11eb-8f24-b447e7679149.png)
Only ExamplePerson.cs found the Head

**Comment by direwolf420** [comment]
For mod development related errors, visit the discord at `tmodloader.net/discord`

**Comment by Steviegt6** [comment]
(You should close this issue, by the way. The tML issue tracker is for *tML* bugs, enhancement suggestions, etc.)
