### ISSUE TITLE
[1.4] D3D11 related crash on asset loading? 

### ISSUE THREAD

**Issue by MrSlimeDude** [tModLoader/tModLoader#1508]
### Description
When loading a mod that overrides `AddRecipeGroups` (Needs checking) TML crashes on adding recipes but also sometimes crashes on general loading. 

### Log file

Usually the log reports no error like this:
[clientnoerror.log](https://github.com/tModLoader/tModLoader/files/6443710/clientnoerror.log)
Building FNA and FNA3D myself with debugging symbols I am able to get something out of the report:
[clientwitherror.log](https://github.com/tModLoader/tModLoader/files/6443717/clientwitherror.log)

### Steps to reproduce

1. Install the latest CheatSheet for 1.4
2. Start TML with D3D11

### Expected behavior 

TML does not crash

### Actual behavior

TML does crash

### Reproduction frequency

80-95%

### Additional Information

After building FNA and FNA3D and enabling native code debugging I was able to get VS to catch something which most notably logs something that looks like the following to the VS debug output:
`D3D11 CORRUPTION: ID3D11DeviceContext::PSSetShaderResources: Two threads were found to be executing functions associated with the same Device[Context] at the same time. This will cause corruption of memory. Appropriate thread synchronization needs to occur external to the Direct3D API (or through the ID3D10Multithread interface). 18320 and 30284 are the implicated thread ids. [ MISCELLANEOUS CORRUPTION #28: CORRUPTED_MULTITHREADING]` or 
`D3D11 CORRUPTION: ID3D11DeviceContext::UpdateSubresource: Two threads were found to be executing functions associated with the same Device[Context] at the same time. This will cause corruption of memory. Appropriate thread synchronization needs to occur external to the Direct3D API (or through the ID3D10Multithread interface). 27808 and 17636 are the implicated thread ids. [ MISCELLANEOUS CORRUPTION #28: CORRUPTED_MULTITHREADING]`.
Something of note is that one of the implicated thread ids always seems to be the main thread id and `PSSetShaderResources` or `UpdateSubresource` sometimes change to other functions although `UpdateSubresource` has been the most common for me. I have it crash most consistently with CheatSheet but direwolf420 has had it happen with ExampleMod during the loading phase, not recipes, and kitenchilly had it happen with Magic Storage which also overrides `AddRecipeGroups` although ExampleMod does not.

An example of the non-main thead call stack:
![image](https://user-images.githubusercontent.com/45675291/117496656-5b0b3f00-af45-11eb-96d5-623ea7c2c6a2.png)
Main thread call stack:
![image](https://user-images.githubusercontent.com/45675291/117496697-678f9780-af45-11eb-9fb6-f49f68b1f6a2.png)

Of potential note in the call stack is how `ReLogic.Content.AssetRepository.Request` is called on the worker thread.

**Comment by Solxanich** [comment]
I can't reproduce it crashing to even begin looking at fixing.
In 50 reloads, I've had zero crashes. My hunch is its related to how long its taking to run commands between swap_buffer calls - the former is exceeding the latter. ~~Just buy an i9 or better single-core performance to fix it~~
Elaborating my hunch:
FNA's Texture2D.SetData in PngReader must be holding on to the graphics device too long such that collision with FNA's buffer_swap is possible, if I'm reading this right. The reason it triggers on AddRecipeGroup for Cheat Sheet more oft is likely related than to that it continually loads the texture for every item in a loop with "instance.LoadItem", which has more collision opportunities.

One option would be to add an overload to the Main.LoadX(type) that allows specifying load asynchronously.
Another option would be to try re-implementing the AssetRepository.Request<T> lock again. 

I'd lean towards the latter if trying to fix.
