### ISSUE TITLE
Ammo damage discrepancy between vanilla and tModLoader

### ISSUE THREAD

**Issue by DarkLight66** [tModLoader/tModLoader#1521]
### Description
The way tModLoader applies damage modifiers to ammo differs from vanilla, as it calculates the damage modifier to apply to the ammo by roughly estimating the damage bonus the weapon received and then applying it to the ammo. This has the problem that:
 * The result of applying the damage modifier to the weapon was rounded down when the damage code had to cast the resulting value to an integer. Say a ranged weapon has a damage of 5 and the player has a ranged damage bonus of 50%, the weapon will end up dealing 7 damage instead of 7.5 due to casting, which would translate to 40% damage bonus instead, and that is the bonus that will be applied to the ammo it uses.
 * If the weapon happens to have a different damage class from the ammo, or deals no damage to begin with but the ammo does, the ammo will end up not being affected by modifiers that should apply to it. In vanilla, some weapons that would be affected by this are the flare gun, which has no damage type, but the flares it uses as ammo deal ranged damage; and the coin gun, which deals no damage by itself, but uses ammo that deals considerable amounts.
 * In vanilla, certain damage modifiers that apply to ranged weapons don't actually apply to ranged ammo of the corresponding type, but they do in tModLoader, namely the `arrowDamage`, `bulletDamage` and `rocketDamage` ones.
 * Archery potions, which increase both the damage of weapons that use arrows as ammo, and the damage of arrow ammo items themselves, apply their damage modifier in `PickAmmo` in vanilla. In tModLoader, this is applied as a multiplier to `arrowDamage`, which has the issue i mentioned above.
   * [Edit] Additionally, the move to `arrowDamage` doesn't account for the molten quiver's 2 damage bonus to normal arrows.
   * [Edit2] Also, the multiplier is applied to the sum of weapon and ammo damage in vanilla, while in tModLoader it's only applied to each one individually. In a lot of cases, this will result in 1 less total damage for the projectile. This suggests the archery potion bonus is a very special case, and modders trying to imitate such a bonus should apply it somewhere more appropriate, like in the `PickAmmo` hook.
 * As an aside, there's no way for modders to apply custom damage modifiers to ammo specifically.
 
Additionally, there's a another issue that applies to ranged weapons: vanilla applies ranged damage modifiers sequentially, by multiplying by the damage then casting to int for each of them, while tModLoader combines all of them first, by adding additive multipliers and multiplying multiplicative ones, then applies them to the damage before casting to int. Having 50% bonus ranged damage and 45% bonus arrow damage (yes, possible in vanilla) would mean a 19 damage bow will end up with 40 `(int)((int)(damage * 1.5f) * 1.45f)` in vanilla, while in tmodLoader it will end up with 37 `(int)(damage * (1f + 0.5f + 0.45f))`. 
[Edit2] In vanilla the tooltip actually multiplies the modifiers before applying them to the weapon, same as tModLoader as the tooltips just call `GetWeaponDamage`, so it's possible this was how the damage modifiers were supposed to be applied.
 
[Edit] And finally, something that applies to some weapons: due to floating point inaccuracies, depending on which damage bonuses the player has and their amounts, a resulting damage bonus may end up being 1.49999... instead of 1.5. These inaccuracies stack as more damage bonuses are added. I'm assuming this is why vanilla adds 0.000005f (5E-6f in code) to damage modifiers before applying them (except for summon damage for some reason), but tModLoader doesn't. This mostly results in damage differing by 1 on low damage weapons under certain conditions.
 
***Note: All of the issues i mentioned were inferred from the code, and need proper in-game verification. Also, the damage value on the tooltip isn't always a good way to check these values, as some modifiers (like the one from archery potions) aren't properly reflected on the tooltip.***

**Comment by Chicken-Bones** [comment]
I believe all of these have been resolved in the many damage class reworks and followups
