### ISSUE TITLE
Crash when alt-tab with Vulkan

### ISSUE THREAD

**Issue by Truhard** [tModLoader/tModLoader#1522]
### Description

https://pastebin.com/3Ztu1mbv

### Steps to reproduce
Fresh install of Tmodloader, Tmodloader64, and Tmodloader Vulkan. Launch game, alt-tab causes crash.

**Comment by JavidPack** [comment]
This is not the tModLoader64 Github, that is here: https://github.com/Dradonhunter11/tModLoader64bit/pulls

**Comment by Truhard** [comment]
Whoops, no wonder it had so many more issues. Thanks
