### ISSUE TITLE
[1.4] Rename Tooltip in Select Player menu flickers.

### ISSUE THREAD

**Issue by Solxanich** [tModLoader/tModLoader#1531]
### Description
Rename Tooltip in Select Player menu flickers.
The same tooltip in Select World does not.

### Log file
[client.log](https://github.com/tModLoader/tModLoader/files/6505538/client.log)

### Steps to reproduce
Rename Tooltip in Select Player menu flickers. Hover over it.

### Expected behavior 
It does not flicker.

### Actual behavior
It does flicker. Appears to be misaligned; hovering the outline on the left is not flickering, any further right flickers.

### Reproduction frequency
100%

**Comment by cozykoko** [comment]
duplicate of #1489

**Comment by Solxanich** [comment]
Closing as duplicate. Missed the other report
