### ISSUE TITLE
[1.4] Mod Config Saving/Revert Changes buttons don't properly disappear

### ISSUE THREAD

**Issue by direwolf420** [tModLoader/tModLoader#1532]
### Description
On 1.4, doing changes to a ModConfig ingame causes the Saving/Revert Changes buttons to show up (normal behavior), but clicking them does not cause any feedback: the buttons don't disappear, making the user think that nothing happened, yet it does save the config properly into the json file.

### Log file
No logs

### Steps to reproduce
Get a mod with a ModConfig and atleast one field in it. Open the game, open the mods config, change a value, press save.

### Expected behavior 
Buttons disappear.

### Actual behavior
Buttons don't disappear.

### Reproduction frequency
100%.

### Additional Information
Closing and then reopening the ModConfig afterwards makes the buttons disappear. EXCEPT if when you click "Revert to default", then save, open and close, the buttons don't go away, until you manually change something again.

**Comment by JavidPack** [comment]
Should be fixed with the recent commits
