### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by TheOldManWithAStick** [tModLoader/tModLoader#1534]
Sorry if this story is long, but I need help.

It all started when I was downloading a mod called 'Limited life'. I went to the config files and for fun, I set the max health to 50,000. Then, when I hit 'Single Player', I froze. Literally my game froze for 1-3 minutes, and then when it unfroze, it was all extremely laggy at 6 fps. I then saw I had about 200 copies of a character named 'foot' ( I named it myself). I went to the files and tried to delete it, but it kept replicating! I had tried everything from removing the mod to uninstalling the game COMPLETELY

Conclusion: I really need help. I cant play the game w/o it.

Also, when I loaded into a world, my Calamity starter bag didnt spawn!

**Comment by direwolf420** [comment]
This is a known issue with this mod, nothing related to tml. Disable the mod, delete the duplicate players it created, and continue playing with it disabled.

**Comment by Gsoverheaven** [comment]
just installn't the mod.
and why don't you just use creative tools for extra hp?

**Comment by TheOldManWithAStick** [comment]
I've tried, direwolf420. It still doesnt work!

**Comment by Gsoverheaven** [comment]
> I've tried, direwolf420. It still doesnt work!

reinstall tmodloader and delete that mod and the corrupted characters

**Comment by Gsoverheaven** [comment]
and delete the mod,oader folder in documents

**Comment by TheOldManWithAStick** [comment]
I've done all 3. Ok maybe this will help you riddle this out. Every time i delete the player files, it duplicates!

**Comment by Gsoverheaven** [comment]
that's weird, does it duplicate even if tml is uninstalled?

**Comment by Mirsario** [comment]
@TheOldManWithAStick 
The TML discord's support channel may be of better help you with troubleshooting this - https://discord.gg/RMZCqq6

Perhaps we'll need to log every time when a file is created.
