### ISSUE TITLE
i cant download TML from steam idk is it a steam problem help please

### ISSUE THREAD

**Issue by RanPix** [tModLoader/tModLoader#1536]
![IgvHk6MrEM](https://user-images.githubusercontent.com/68966087/119182590-c68ff900-ba7b-11eb-9e79-bebfb7b43465.gif)
it just cant start a downloading it closes immidietly

**Comment by sakuriki** [comment]
Do you owned the game or is this a family share? I think you can't download TML from steam on a family share account

**Comment by RanPix** [comment]
> Do you owned the game or is this a family share? I think you can't download TML from steam on a family share account

i own the game

**Comment by Gsoverheaven** [comment]
try installing tmodloader directly from github, famiky share doesn't work mostly

**Comment by RanPix** [comment]
im dumb sorry i have the game by family share

**Comment by RanPix** [comment]
i forgot sorry

**Comment by Gsoverheaven** [comment]
bruh
