### ISSUE TITLE
Clients' ModWorld is not server sync'd in ModPlayer.OnEnterWorld

### ISSUE THREAD

**Issue by hamstar0** [tModLoader/tModLoader#154]
_Edit: Described wrong problem.  Better information included:_

**Description**
ModWorld.Initialize runs at least once (chronologically) after ModPlayer.OnEnterWorld.

A GUID field is set for the ModWorld instance in ModWorld.Initialize.  Client and server must have the same one, so ModWorld.NetSend (server) and ModWorld.NetReceive (client) is used to sync.  GUID field is called for in ModPlayer.OnEnterWorld.

**Expected Behavior**
Expected correct GUID on client (OnEnterWorld).

**Actual behavior**
> ModWorld.Initialize (netMode:2) Current GUID: acaedd91-db55-4de6-b855-014d2e8ef674
> ModWorld.Initialize (netMode:2) Current GUID: 925c7e5e-c9cd-4df6-ba62-e19f127066c5
> ModWorld.Load (netMode:2) Current GUID: 90769f02-4217-44c0-be17-0fbf86af2343
> ModWorld.NetReceive (netMode:1) Current GUID: 90769f02-4217-44c0-be17-0fbf86af2343
> ModWorld.Initialize (netMode:1) Current GUID: 8bb62b8a-d845-4e23-bc19-5d9a3b304a35
> ModPlayer.OnEnterWorld (netMode:1) Current GUID: 8bb62b8a-d845-4e23-bc19-5d9a3b304a35
> ModWorld.NetReceive (netMode:1) Current GUID: 90769f02-4217-44c0-be17-0fbf86af2343

Line 4 indicates the correct GUID gets sent to the client, but line 5 undoes that right before OnEnterWorld runs.  The last line corrects it once and for all, but this renders the OnEnterWorld hook unusable for this purpose.

**Reproduction frequency**
Happens each time.

**Versions**
Using tML v0.9.2-v0.9.2.2

**Mods**
Wormholes, Cheat Sheet

**Comment by Jofairden** [comment]
Do you even template?

**Comment by Jofairden** [comment]
Wait, so how come your 2 MP clients have a different generated GUID compared to the end GUID? Like at ModWorld.Load you already have a different GUID there

**Comment by hamstar0** [comment]
There should only be 1 MP client.  ModWorld.Load simply pulls in the world's initially-generated GUID (it won't do this is nothing exists to load).  Regardless, AFTER _Load()_ (note _Load()_ runs only on the server), the correct GUID exists on the _server_.

**Comment by Jofairden** [comment]
The _Initialize()_ for the ModWorld is called when the world is loaded, which is before the client actually enters. `Main.LoadWorlds();` is called before `Player.Hooks.EnterWorld(Main.myPlayer);` then the _NetReceive()_ happens somewhere later in the ServerLoop I think. I'll let some smarter people bend their heads over this.

**Comment by Solxanich** [comment]
Fixed in #2065
