### ISSUE TITLE
tModLoader is not installed on gog version of terraria

### ISSUE THREAD

**Issue by makarhuyaker** [tModLoader/tModLoader#1542]
![Снимок](https://user-images.githubusercontent.com/63492966/119531559-b84c2080-bd8c-11eb-98cf-c3cbe9cfe817.PNG)

**Comment by Steviegt6** [comment]
This is pretty meaningless without any accompanying context.

**Comment by JavidPack** [comment]
It seems you are trying to generate the tml source code, that is not what you should do if you want to install tml. The patcher is for people working on developing tml itself, not users. Here are the install instructions: https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players
