### ISSUE TITLE
tModLoader Starts v1.3.5.3 But Game Is v1.4.2.3

### ISSUE THREAD

**Issue by Epicskunk** [tModLoader/tModLoader#1557]
### Description
Even though I only and ONLY have Terraria 1.4.2.3, tModLoader starts with Terraria 1.3.5.3, which doesn't exist in my computer.

### Log file
There is no Log file.

### Steps to reproduce
1. Installed Terraria 1.4.2.3 from GOG
2. Extracted tModLoader's latest version into a folder named tModLoader that is in Terraria's installed path
3. Started tModLoader.exe

### Expected behavior 
It's supposed to start the game with tModLoader, but the game version should be 1.4.2.3

### Actual behavior
The game starts with tModLoader loaded, however the game version is 1.3.5.3

### Reproduction frequency
Always.

### Additional Information
None I can think of.

**Comment by MikhailMCraft** [comment]
This is not a tModLoader issue, it is still on 1.3.5.3 and has not been updated to 1.4.2.3 yet.

**Comment by TheStachelfisch** [comment]
Read the About me section of this Repository

**Comment by Epicskunk** [comment]
> This is not a tModLoader issue, it is still on 1.3.5.3 and has not been updated to 1.4.2.3 yet.

Thank you for your help, sir. I will be closing this issue.
