### ISSUE TITLE
[1.4] .NET Libraries are not found

### ISSUE THREAD

**Issue by BlackTeal** [tModLoader/tModLoader#1560]
### Description
Whenever I try to use a .NET Library (in my case ImGui.NET which is a .NET Standard 2.0 Library), my Mod just doesn't find it (it fails to Load the Library), the Library is referenced in build.txt with the dllReferences thing (dllReferences = ImGui.NET) and it is present in the lib Directory inside the Directory of my Mod

### Log file
[client.log](https://github.com/tModLoader/tModLoader/files/6608966/client.log)

### Steps to reproduce
1. Create your 1.4 Mod Project
2. Add any .NET Library (not sure if it happens with other Libraries than .NET Standard 2.0 Libraries, I tried with the ImGui.NET Library, which is a .NET Standard 2.0 Library) compatible with .NET 5 as a Project Reference, or download one from nuget
3. In the build.txt file, add the name of the DLL of the Library to the dllReferences
4. Add the .NET Library to the lib Directory inside the Directory of your Mod
5. Use it in any way so your Mod tries to Load the Library

### Expected behavior
The mod loads the library, without any exceptions or crashes

### Actual Behavior
The mod throws System.Reflection.ReflectionTypeLoadException exception when it tries to load the .NET Library

### Reproduction frequency
100% as far as I have tested, the Mod never is able to find the .NET Library DLL, not even if I put it in the tModLoader Directory or in the Mod DLL Directory

**Comment by Chicken-Bones** [comment]
Please send a zip of your mod from the mod sources directory.

**Comment by BlackTeal** [comment]
[BlackTeal.zip](https://github.com/tModLoader/tModLoader/files/6613564/BlackTeal.zip)

**Comment by Solxanich** [comment]
@BlackTeal - 
A problem I note with the ImGui.net lib you're using in that mod is that its missing several other parts to it.
IE, all the cimgui.dll and its variations for each of the platforms.
Further, I see its supposed to be a NuGet package, but with what you have, it doesn't match the contents of the package either.

Although a fix may be done to eliminate the error resulting from not finding ImGui.Net, I won't anticipate that it will start working fully for you until said problem is addressed on your end.

**Comment by BlackTeal** [comment]
Yes, I'm aware that it's missing the native libraries, but as the managed library wasn't being loaded at all, I reported that as a bug, I don't know why it doesn't match the package (because I have took it somewhere in the .nuget folder from my user directory) but thanks for telling me those stuff though.

**Comment by Chicken-Bones** [comment]
Has been fixed. New error for your test mod is below. You can see the managed library is being loaded correctly.
```
System.DllNotFoundException: Unable to load DLL 'cimgui' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at ImGuiNET.ImGuiNative.igGetCurrentContext()
   at ImGuiNET.ImGuiNative.igGetCurrentContext()
   at BlackTeal.BlackTeal.Load() in BlackTeal.cs:line 22
   at Terraria.ModLoader.ModContent.<>c.<Load>b__43_0(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 331
```
