### ISSUE TITLE
Tool for Exporting pre-formatted Translation Skeletons by Content Type

### ISSUE THREAD

**Issue by Solxanich** [tModLoader/tModLoader#1575]
### Description

A tool should exist to auto-output a pre-formatted skeleton based on all ModTypes registered and standard properties for each of them, where missing.

Previously, someone had begun work towards this with ModTranslation fields, but there would need to be further work done to actually fully implement this throughout tML.
For example, one could consider adding ModTranslation.DisplayName to ModType itself.

A sample implementation idea provided by Direwolf420 is "by using reflection and looking for any public ModTranslation fields/properties, so that for example items get MyItem.DisplayName and MyItem.Tooltip"

Further this should build on top of the work done under #1527 to deliver a smooth transition.

### What does this proposal attempt to solve or improve?
Addressing Point 6 in #1365 
For mods with large amounts of standard translatable ModTypes, this is a clear gap in translations that should be addressed to simplify Modder & translator experiences 

### Which (other) solutions should be considered?
Details of implementation TBD.

**Comment by sgkoishi** [comment]
Some mod translation fields are named differently - MapEntry has internal `LocalizedText name` and `ModTranslation translation`. 
Also, this kind of export does not work so well facing dynamic generated text - like most cross-mod contents do. Modders are required to replace their string with `Language.GetTextValue` and initialize ModTranslation somewhere else.

~~Simple implementation using reflection: [Localizer](https://github.com/chi-rei-den/Localizer/blob/eddcaa798702a177c0cb03bb6ebc62042c39e2e9/Localizer/Package/Export/BasicFileExport.cs)~~

**Comment by Chicken-Bones** [comment]
Solved by #3101
