### ISSUE TITLE
tML 0.11.8.4 (current Steam version) has bad libMonoPosixHelper.so bundled

### ISSUE THREAD

**Issue by TNTftw21** [tModLoader/tModLoader#1577]
To preface, I have made note of this problem on the Magic Storage repo as well. However, seeing as this appears to be a bug in libMonoPosixHelper (or at least the version provided by tML) I have chosen to post an issue here as well.

### Description
Certain mods (such as the infamous Magic Storage) use methods provided in libMonoPosixHelper.so on Mac/Linux. This version of tML packages a version of libMonoPosixHelper.so which silently errors when these methods are called, typically resulting in client-side world loading problems.

### Log file
I've confirmed the source of this issue as being libMonoPosixHelper.so (via a method call from Magic Storage). The client log shows the error as being something to do with Calamity (misleading), and the server log shows no issues. Still, they are attached for completeness's sake. Forgive the player/world names, I was... tired.
[client.log](https://github.com/tModLoader/tModLoader/files/6643129/client.log)
[server.log](https://github.com/tModLoader/tModLoader/files/6643130/server.log)

### Steps to reproduce
Error can occur with only Magic Storage enabled, I haven't tested to see if other mods rely on the faulty libMonoPosixHelper.
1) Start a server (can be on any OS)
2) Create any sized world
3) Log into server from Mac/Linux client
4) Place a Magic Storage Storage Heart and hook up some Storage Units to it
5) The bug seems to be based on how much data MS has to send to the client. Either dump several thousand items into the storage, or use a mod such as Calamity that adds a bunch of data to the items and dump a couple hundred in.

### Expected behavior 
Magic Storage _should_ handle the items, and relogging/reloading will leave everything as it was left.

### Actual behavior
Parts of the world will not load in on the client and, in extreme cases, the lighting system will break, eventually leading to a crash.

### Reproduction frequency
100% with the world.

### Additional Information
Attached is a zip (since GitHub apparently limits the possible file types) containing my world data (.wld and .twld).
[Worlds.zip](https://github.com/tModLoader/tModLoader/files/6643144/Worlds.zip)

**Comment by MarkusG** [comment]
I remembered having to deal with this issue a while back. Today, I'm unable to reproduce with a couple inventory fulls of item stacks. Has this been fixed?

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
