### ISSUE TITLE
Line endings in `sh` are CRLF

### ISSUE THREAD

**Issue by drunderscore** [tModLoader/tModLoader#1581]
### Expected behavior 
As these are shell scripts intended for a unix environment, they should have LF line endings.

### Actual behavior
Shell scripts have CRLF line endings. This causes the shebang (and all other lines) to be completely useless and fails with the following:
`./start-tModLoader.sh: bad interpreter: /bin/sh^M: no such file or directory`

**Comment by Solxanich** [comment]
Is this 1.4 or 1.3 observed?

If this is 1.4, I've heard the files work on Unix, however if you believe a fix is needed and know clearly what it is that is to do, than feel free to create a pull request updating the 1.4 branch Solutions/Release Extras with

**Comment by Chicken-Bones** [comment]
I've fixed this a couple times, I think someone has their git autocrlf settings wrong. 
With that in mind, we should definitely setup a .gitattributes for .sh files https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings
