### ISSUE TITLE
Jumping and dashing broken on linux 

### ISSUE THREAD

**Issue by kaanyalova** [tModLoader/tModLoader#1583]
### Description

shield and double jump repeatedly activating while I am holding space key or a/d keys 
### Log file

[client.log](https://github.com/tModLoader/tModLoader/files/6679076/client.log)

### Steps to reproduce

1. Get an item that gives double jump or dash
2. try to use them 

### Expected behavior 

items working normally 
### Actual behavior

dash or double jump activating  repeatedly like I am spamming space or a/d keys 
### Reproduction frequency

always 
### Additional Information

it gets fixed by setting repeated key presses off by running `xset r off` or replacing `tModLoader/lib/libSDL2-2.0.so.0` with `Terraria/lib/libSDL2-2.0.so.0` and `tModLoader/lib64/libSDL2-2.0.so.0` with `Terraria/lib64/libSDL2-2.0.so.0`

**Comment by direwolf420** [comment]
Similar to this? https://github.com/tModLoader/tModLoader/issues/632
Here is how someone solved it:
> Thanks! I fixed it using the command shown here -http://xahlee.info/linux/linux_set_key_repeat_rate.html.
Changing the delay to a high value (2000) is what did it.

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy. Try 1.4 tModLoader, if you have similar issues with 1.4 tModLoader feel free to open a new issue and fill out the issue template.
