### ISSUE TITLE
Cant Open In terraria 1.4.2.3

### ISSUE THREAD

**Issue by tmodersus** [tModLoader/tModLoader#1585]
when i open it it says that 'tmodloader excepts terraria 1.4.2.3 you may need to upgrade or downgrade your terraria' but in the tmodloader releases it says that you have to upgrade your terraria 1.4.2.3

**Comment by JavidPack** [comment]
Support questions such as this are more suited for the discord chat: https://tmodloader.net/discord . We can confirm that tmodloader works with the latest terraria, so double check the install instructions or as for help on discord. https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players
