### ISSUE TITLE
Question about modding in TML

### ISSUE THREAD

**Issue by MasterBroNetwork** [tModLoader/tModLoader#1586]
I'm wondering whether or not to wait for tModLoader 1.4 to release to begin developing my mod or whether to begin it now since 1.4 brings a lot of balance changes to items.

**Note: I wasn't sure where else to ask this, if this isn't right then please feel free to close it or tell me to close it. :)**

**Comment by JavidPack** [comment]
You should mod now for current tmodloader, as you are currently interested in it. Re-balancing your mod and tweaking the code for a future 1.4 release won't be an issue.
