### ISSUE TITLE
macOS crash bug

### ISSUE THREAD

**Issue by Terrariaperson** [tModLoader/tModLoader#1593]
Tried launching from steam and it crashed instantly. No logs in log folder.
Got this error in terminal when launching with mono:
[message.txt](https://github.com/tModLoader/tModLoader/files/6721077/message.txt)

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy. Try 1.4 tModLoader, if you have similar issues with 1.4 tModLoader feel free to open a new issue and fill out the issue template.
