### ISSUE TITLE
.NET 4.5 reference assemblies not found please install visual studio with the .NET 4.5 targeting pack I already have it installed

### ISSUE THREAD

**Issue by SolariusEclipse** [tModLoader/tModLoader#1597]
### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [And so on...]

### Actual behavior
.NET 4.5 reference assemblies not found please install visual studio with the .NET 4.5 targeting pack it won't let me download the targeting pack again
### Additional Information
<!-- I haven't done anything but in mod sources it is saying .NET 4.5 reference assemblies not found please install visual studio with the .NET 4.5 targeting pack I already have it installed.

**Comment by Chik3r** [comment]
You could either try installing the `.NET desktop development` workload in the vs installer, or try this:
> The in-game download of the reference assemblies doesn't work at the moment, the workaround is to download this: https://tmodloader.net/dl/ext/v45ReferenceAssemblies.zip
Then, extract the contents of the `v4.5` folder from within the zip into: `C:\Program Files (x86)\Steam\steamapps\common\tModLoader\ModCompile\v4.5 Reference Assemblies` (make the folder if it doesn't exist). Finally, leave and come back to the enable developer mode menu.

**Comment by nightblade9** [comment]
I have the same problem. Extracting the zip to the specified directory doesn't work. There's a work-around mentioned [here](https://github.com/tModLoader/tModLoader/issues/1887#issuecomment-933295752) that works for me (TL;DR download .NET 4.5.2 and copy/paste the folder to v4.5).

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
