### ISSUE TITLE
Server doesn't load

### ISSUE THREAD

**Issue by Flaymy123** [tModLoader/tModLoader#1598]
Hello Terraria friends,
I wanted to play tmodloader with my friends. We tried anything but the server tells me that it is running on 0.11.8 and we play on 0.11.8.4 to play with mods. Do you know how to fix this problem already or is it new

I would be happy if I got an answer
Your Flaymy123

**Comment by JavidPack** [comment]
Sounds like you didn't install the update correctly, in any case, download the 0.11.8.4 zip again, take the tModLoaderServer.exe file from it and place it in your install folder. If you are on steam, this should happen automatically, but if you installed tmodloader manually, you'll have to find your install folder by finding where tModLoader.exe is located. For me it is in C:\Program Files (x86)\Steam\steamapps\common\tModLoader, but it sounds like you aren't using steam
