### ISSUE TITLE
Tmodloader takes around a hour to open.

### ISSUE THREAD

**Issue by oofyboy** [tModLoader/tModLoader#1599]
### Steps to reproduce

1. [First Step]
Try to open it

### Expected behavior 

The game opening within a minute or so
### Actual behavior

Taking an hour
### Reproduction frequency

Everytime i try to open the game
### Additional Information

Im on windows

**Comment by JavidPack** [comment]
You didn't provide client.log, so we can't really help. Please provide client.log of a session where you get to the main menu.
