### ISSUE TITLE
I cannot run tmod through steam

### ISSUE THREAD

**Issue by void-reboot** [tModLoader/tModLoader#1604]
I have had tmod in the past through the website but now I wanted to get it through steam. I haven't been able to even after deleted tmod and making sure I had no further tmod files. Whenever I try and install tmod on steam it prepares for the installation for a split second and then closes the prep window

**Comment by JavidPack** [comment]
If you are using terraria through family share, you'll have to do the manual install. If you haven't updated terraria to the latest version either, it won't work. See https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players

For any further help, please visit the discord, tModLoader.net/discord .
