### ISSUE TITLE
Some modules cannot be started normally, such as thorium mod

### ISSUE THREAD

**Issue by yhxaxy** [tModLoader/tModLoader#1606]
Use the server opener built in the latest version of tml64 (0.11.8.4) to open webmilio's commons library, thorium mod, and leveled mod. It always reports an error and can't start these three modules normally. Use the server opener in 32-bit tmodloader to start normally. I don't know how to reply. Please help me, thank you
![image](https://user-images.githubusercontent.com/56006944/124803521-d01de380-df8b-11eb-82a0-37589416b5dd.png)

**Comment by yhxaxy** [comment]
使用最新版Tml64（0.11.8.4）内置的开服器 开启Webmilio's Commons Library，，Thorium Mod，， Leveled Mod总是报错无法正常启动这三个模组，而用tModLoader32位里自带的开服器就可以正常启动，不知道是怎么回事，恳请大佬们帮帮我，谢谢

**Comment by Solxanich** [comment]
Unfortunately, it sounds like this is an issue exclusive to tml64. We don't officially support it.
Thats a separate dev team and github, its unofficial and use at own risk of issues.

You can access their discord here: https://discord.gg/DY8cx5T
And github here: 
https://github.com/Dradonhunter11/tModLoader64bit/releases

**Comment by sgkoishi** [comment]
Also you may try to disable the Localizer (it should work on the client side).
你也可以试下关闭汉化者（比较建议只在客户端开启，服务器不开）

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
