### ISSUE TITLE
TModLoader Compiler does not recognize mod reference namespace

### ISSUE THREAD

**Issue by JPPlaysGamer** [tModLoader/tModLoader#1607]
I'm having a problem referencing a mod with strong references. I read several times on the wiki about the strong reference, I put in `build.txt` the reference of my core mod.

`
modReferences = myMod
`

`
using ModNamespace;
using ModNamespace.Something;
...
ClassOfModCore.Func();
`
Extract the core mod .dll located in `references\mods`, use the methods contained in the mod and Visual Studio doesn't show syntax and assembly error, but when it starts to compile the TML compiler it doesn't recognize the namespace of mod and methods. What am I doing wrong? Do I need something else?

I'm using recent TML, recent Visual Studio, developing with .NET 4.5.

**Comment by JavidPack** [comment]
Everything you wrote looks fine, you should come to the discord for this type of help. tmodloader.net/discord
