### ISSUE TITLE
[1.4] ModDust.Draw() crashes game

### ISSUE THREAD

**Issue by Solxanich** [tModLoader/tModLoader#1614]
### Description
After AssetLoading was merged, discovered that ModDust.Draw() is crashing the game.

Context links:
https://discord.com/channels/103110554649894912/445276626352209920/865045700499472404 &
https://discord.com/channels/103110554649894912/445276626352209920/864227526397263872

Suspect any other similarly designed methods may have similar risk, but no other objects have been identified as such.

### Log file
[client.log](https://github.com/tModLoader/tModLoader/files/6820232/client.log)

### Steps to reproduce
Jumping in water while in ExampleBiome crashes the game.

Possibly also any other form of ModDust, such as tile breaking?

### Expected behavior 
Dust appears

### Actual behavior
Game Crashes

### Reproduction frequency
100% for specified cause

### Additional Information
@Chicken-Bones 
Likely just need to update the ModDust.Draw() method, but also seems like it may be deeper rooted.

**Comment by Mirsario** [comment]
(Fixed in https://github.com/tModLoader/tModLoader/commit/70decddca14fa2782329dfa5f26af57596aa9cbf)
