### ISSUE TITLE
[1.4] Unintended behavior regarding CombinedHooks.CanPlayerHitNPCWithItem

### ISSUE THREAD

**Issue by direwolf420** [tModLoader/tModLoader#1616]
### Description
Hooks called through `CombinedHooks.CanPlayerHitNPCWithItem` do not share the same logic as the 1.3 versions. Returning true ignores the melee hitbox collision, meaning a swung item will hit the NPC regardless of being in contact or not.
This is contrary to the projectile->NPC hooks where hitboxes are checked accordingly.

### Possible solutions
1. Pass `itemRectangle` into the hooks, modders would have to check `itemRectangle.Intersects(npc.getRect()) && (npc.noTileCollide || player.CanHit(npc))` if they want to return anything other than null
2. Change the order of operations to insert the hook in a similar place to mirror projectile->NPC hook logic to avoid modders having to check the above manually
3. Create an additional hook to allow more finetuning, quoting Mirsario: "some canhit hooks should likely be split into canhit and cancollidewith"

**Comment by JavidPack** [comment]
Fixed in [d9eceb3](https://github.com/tModLoader/tModLoader/commit/d9eceb3249a19a4c5d03c62ebbfbe3ebd33882d2)
