### ISSUE TITLE
Crash upon mod reloading

### ISSUE THREAD

**Issue by Zemogiter** [tModLoader/tModLoader#1633]
### Description
I was updating mods in Mod Browser and upon clicking back the mods reloaded and the game crashed.

### Log file
[client.log](https://github.com/tModLoader/tModLoader/files/6874414/client.log)

### Steps to reproduce

1. Go into Mod Browser.
2. Update any mods
3. Click back to go to main menu/reload mods

### Expected behavior 
The mods should reload. After that the main menu should appear.

### Actual behavior
The game crashed somewhere during the mod reload process

### Reproduction frequency
Almost every time when mod reload happens and more than one mod is being enabled/disabled.

### Additional Information
After the crash, Steam displays TML as active despite it being absent from task manager/tasklist cmd command. A restart of Steam is needed.
```
Host Name:                 DESKTOP-JFMFNS3
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19043 N/A Build 19043
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Jonasz
Registered Organization:
Product ID:                00331-20300-00000-AA820
Original Install Date:     01.09.2020, 21:19:29
System Boot Time:          25.07.2021, 20:19:16
System Manufacturer:       Gigabyte Technology Co., Ltd.
System Model:              Z270-Gaming K3
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 9 GenuineIntel ~4201 Mhz
BIOS Version:              American Megatrends Inc. F9d, 09.03.2018
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume3
System Locale:             pl;Polski
Input Locale:              pl;Polski
Time Zone:                 (UTC+01:00) Sarajewo, Skopie, Warszawa, Zagrzeb
Total Physical Memory:     32 649 MB
Available Physical Memory: 25 474 MB
Virtual Memory: Max Size:  36 745 MB
Virtual Memory: Available: 29 446 MB
Virtual Memory: In Use:    7 299 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-JFMFNS3
Hotfix(s):                 13 Hotfix(s) Installed.
                           [01]: KB5003537
                           [02]: KB4561600
                           [03]: KB4562830
                           [04]: KB4570334
                           [05]: KB4577266
                           [06]: KB4577586
                           [07]: KB4580325
                           [08]: KB4586864
                           [09]: KB4593175
                           [10]: KB4598481
                           [11]: KB5000736
                           [12]: KB5004237
                           [13]: KB5003742
Network Card(s):           2 NIC(s) Installed.
                           [01]: Wintun Userspace Tunnel
                                 Connection Name: VPNUWireguard
                                 Status:          Media disconnected
                           [02]: Killer E2500 Gigabit Ethernet Controller
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.104
                                 [02]: fe80::f853:4464:7f32:6f47
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
```

**Comment by Mirsario** [comment]
The log has had quite a few failures in mod unloading before encountering the final exception. You should disable `giantsummon`, as it was one of the causes of these failures. When reporting such loading errors, it's better to restart the session clean.

> System.NullReferenceException: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
> w BetterTaxes.BetterTaxes.Call(Object[] args) w BetterTaxes.cs:wiersz 102
> w giantsummon.MainMod.LoadCustomGuardians()
> w giantsummon.GuardianBase.GetGuardianBase(Int32 ID, String modid)
> w giantsummon.GuardianData.get_Base()
> w giantsummon.GuardianData..ctor(Int32 ID, String ModID)
> w giantsummon.TerraGuardian..ctor(Int32 CreateByType, String ModID)
> w giantsummon.GuardianNPC.GuardianNPCPrefab..ctor(Int32 ID, String ModID)
> w giantsummon.GuardianNPC.List.ArmorWraith..ctor()

Also:
> Support issues such as this are more suited for our discord chat, found at <https://tmodloader.net/discord>. Please direct this 
> question there, as it will be much easier to solve this issue through back and forth chatting. The github issues tracker is solely 
> for actual bugs and feature requests, not troubleshooting discussions.
