### ISSUE TITLE
worlds not loading

### ISSUE THREAD

**Issue by MightyLobster1** [tModLoader/tModLoader#1638]
-->

### Description
<!-as for the issue, whenever i make a world or join a previously created one, (though ive tried disabeling all the mods, then it works fine, and ive even tried enabeling 1 mod or just a random one from the mod browsing page, but then it does crashj) it crashes the game as soon as it gets to "setteling liquids 99%"  -->

**Comment by Mirsario** [comment]
I've heard suspicions that this is either related to Terraria Overhaul, or Yet Another Boss Health Bar. As the creator of the former, I was never able to reproduce this, at least with a debugger on hand, so I don't know how to help you. Usually, people said that the issue went away after a few retries/restarts, though. Or by making a new world.

Post your mod list.
