### ISSUE TITLE
Some wings non-functional with lots of mods

### ISSUE THREAD

**Issue by tlitookilakin** [tModLoader/tModLoader#1639]
### Description
When there are greater than 127 (appx.) wing/flight accessories registered to the game (vanilla + modded), any wings > 127 do not function when equipped.

### Log file
[log file](https://pastebin.com/H0MYDVJb)

### Steps to reproduce

1. Install multiple mods adding wings, until you have more than 127 wings
2. equip modded wings until you find one that does not grant flight

### Expected behavior 
All items designated for flight should grant flight.

### Actual behavior
Some modded items designated for flight have no effect.

### Reproduction frequency
Very consistently with a sufficient number of mods installed, and with various items. Consistent across restarts.

### Additional Information
Some mods that add lots of wings and can be used to demonstrate the bug include Ancients Awakened, Shadows of Abaddon, Calamity, and Thorium. 

If Recipe Browser is installed, item filtering can be used to pinpoint which wings do and do not function; non-functional wings will not appear when the item browser is filtered to wings. Any flight items with an ID higher than the last item on the wings page will not function.

Not tested on the 1,4 version

**Comment by JavidPack** [comment]
Looking at the code, since wingSlot and many others are all sBytes, I assume the limit might be an issue with many other equip slots as well.

**Comment by direwolf420** [comment]
Bumping this. If you stack multiple large mods which naturally have a good bit of wings, and a few mods that add lots of wings in general, it causes exceptions when used with `ArmorIDs.Wing.Sets.Stats` as Item.wingSlot is assigned to an invalid index. This has become more apparent as many people have been adding the newly released Thorium Mod to their mod packs, tipping the wing count above the threshold of 127 slots

**Comment by P3rf3ctXZer0** [comment]
I am eagerly waiting for this to get fixed. In the meantime I will just play something else.

**Comment by ChapperNi** [comment]
> I am eagerly waiting for this to get fixed. In the meantime I will just play something else.

Same here.

**Comment by JavidPack** [comment]
Just so people know, it will be impossible to fix this on 1.4, since doing so would break many mods. We'll try to get this in 1.4.4, but that won't be "stable" for quite a while

**Comment by P3rf3ctXZer0** [comment]
See you on 1.4.4 then.

**Comment by JavidPack** [comment]
Should now be fixed on 1.4.4.

**Comment by Natedogwoooof** [comment]
your lucky my game just crashes lol on 1.4.3 cuz AFK PETS Haven't Updated
