### ISSUE TITLE
[Feature proposal] Show loading progression

### ISSUE THREAD

**Issue by Ishigh1** [tModLoader/tModLoader#1643]
### Description
Some mod loads are quite long and progress bar only depends on which mod finished its load, not progress inside the mod load

### What does this proposal attempt to solve or improve?
To allow mods to impact the progress bar, I can think of few ways : 

- Giving an argument in every loading method, like the worldgen methods
- Have a ModLoader static method or a Mod method to affect the progress
- Make Terraria.ModLoader.UI.Interface public and trust the users to set the progress by themselves when they need to

**Comment by NotLe0n** [comment]
Possibly a duplicate of #1524

**Comment by Ishigh1** [comment]
Indeed
