### ISSUE TITLE
tModLoader not working on mac for gog

### ISSUE THREAD

**Issue by SanGakuBoi** [tModLoader/tModLoader#1645]
I tried to run tmod using the manual install info and it didnt run, i checked and it was archive utility, who broke the app when i unzziped it, i used the unarchiverto unzip it and it ran but it imediately closed, when i searched for the tmodloader file on my finder i found this little thing
[client.log](https://github.com/tModLoader/tModLoader/files/6904853/client.log)
that specifically said this thing

> GOG installs must have the unmodified Terraria executable to function. This version of tModLoader expects the Terraria_1.4.2.3.exe version of Terraria, you may need to downgrade or upgrade Terraria via GOG Galaxy, or wait for tModLoader to update.

i was alredy using the latest install of tmod and terraria
i tried using this method: https://github.com/tModLoader/tModLoader/issues/1183 but it didnt work again, and when i ran tmodloader after doing so it said this:

> Terraria: Error (tModLoader v0.11.7.4)

../Terraria_1.4.0.4.exe could not be found.

GOG installs must have the unmodified Terraria executable to function.

the only werid thing i noticed here is that instead of the latest version of terraria (1.4.2.3) it said 1.4.0.4, but i was using the latest install of terraria and of tmodloader.

can someone help me?

**Comment by Chik3r** [comment]
> tModLoader v0.11.7.4

You didn't download the latest version of tModLoader, make sure to download it from https://github.com/tModLoader/tModLoader/releases/latest (Note: the releases on the forum page are old)
Also, I recommend following this guide in order to manually install tModLoader: https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#manual-installation

**Comment by SanGakuBoi** [comment]
it was just me who was installing wrong hehe sorry
