### ISSUE TITLE
[1.4] Game crashes on Windows due to in-game copy or paste

### ISSUE THREAD

**Issue by Ishigh1** [tModLoader/tModLoader#1649]
### Description
When the clipboard is set then the clipboard is opened again with the same instance of Terraria, the game crashes due to a heap corruption. (This doesn't happen is the clipboard set is done on a null pointer.)

### Steps to reproduce
1. Go on the new character style UI
2. Click on the "copy" button
3. Click on the "copy" or "paste" button

### Reproduction frequency
It seems to always happen on Windows, even though I managed to make it work once with the debugger but I couldn't reproduce it

**Comment by Chicken-Bones** [comment]
Fixed in #1757
