### ISSUE TITLE
[1.4] Text Replacement doesn't work in Resource Packs

### ISSUE THREAD

**Issue by Mayonnaisinator** [tModLoader/tModLoader#1655]
Vanilla Resource Packs look to be almost entirely compatible with the current 1.4 tML Alpha, except for text replacement. From what I have tested, texture, sound, and music replacements all work as expected, but text is not replaced.

### Steps to reproduce

1. Enable resource pack that modifies text
2. See no change in game
3. Profit

### Additional Information
I used my own personal resource pack to test this, as well as ones downloaded from the vanilla Steam Workshop, such as "Axolotl replaces Baby Shark pet", which should change the Shark Bait item.

**Comment by pixelizedgaming** [comment]
Happened to me too, was using a minecraft texture pack and noticed that some of the item and npc names were reset to their vanilla names.

**Comment by Chicken-Bones** [comment]
Please link a resource pack here

**Comment by Mayonnaisinator** [comment]
Here's a fairly easy one to test. https://steamcommunity.com/sharedfiles/filedetails/?id=2468248842

It changes the "Shark Bait" pet summon, both visually and text-wise, and while the texture change works, the renaming of the item and tooltip doesn't. You can compare the item in game to the third screenshot on the Steam page.

**Comment by ttoastt** [comment]
I'm having this exact problem! i tried even making a new resource pack to fix it but it didn't work. Any developments for this?

**Comment by JavidPack** [comment]
This has been fixed since b177f77ffc62ed6d9a6b1fd9dc1b361804e2c903
