### ISSUE TITLE
Fluids have odd graphics when flowing EDIT: base Terraria has the bug too

### ISSUE THREAD

**Issue by RylicTWG** [tModLoader/tModLoader#1667]
### Description
Flowing liquids have odd graphical errors

### Log file
[client.log](https://github.com/tModLoader/tModLoader/files/6913971/client.log)

### Steps to reproduce
Just zoom in and out while flowing liquids are on screen and you should see the graphical errors pop up

### Expected behavior 
Should flow without graphical issues like base Terraria

### Actual behavior
Graphics aren't rendering properly I guess

### Reproduction frequency
Every time I zoom in and out with flowing liquid on screen I can see the graphic errors

### Additional Information
Issue on tmodloader:
![stairsteps](https://user-images.githubusercontent.com/45835439/127795777-7e5e0fb8-619e-4926-8431-8f38dbff4730.PNG)
![graphic](https://user-images.githubusercontent.com/45835439/127795785-7f8ea85c-7392-46c8-b2d1-6e49ec9b9d13.PNG)

Issue on base Terraria:
![same](https://user-images.githubusercontent.com/45835439/127795801-3a2bc535-04fe-4068-808a-bbfaad98f850.PNG)

Disclaimer: Resource packs are being used in the screenshots but I tested the issue with and without them and issue still popped up. Issue was however never present on base Terraria regardless of resource packs used (or lack thereof).

**Comment by RylicTWG** [comment]
IMPORTANT: Bug is also present on normal Terraria, I just didn't zoom in and out to notice it but it is still a bug nonetheless I guess. Also tested without any resource packs on and issue is still present

**Comment by JavidPack** [comment]
Since this bug is also present in Terraria, we probably won't be able to fix this without a lot of code to maintain, sorry. Maybe the next Terraria update will fix this.
