### ISSUE TITLE
Index and chat manager issues for v0.11.8.4 64bit.

### ISSUE THREAD

**Issue by CSwapJack8** [tModLoader/tModLoader#1668]
### Description
There is a System.IndexOutOfRangeException issue for mod content, and a System.NullReferenceException issue for the chat manager.

### Log file
[client.log](https://github.com/tModLoader/tModLoader/files/6914134/client.log)

### Steps to reproduce

To see the effects of the index exception:
1. Enable a lot of mods
2. Reload them in
3. Wait till it fully loads
4. Then the Index message will appear

To see the effects of the null exception:
1. Repeat all the steps to get the Index message
2. click 'Retry'
3. now once you click on Mods or Mod Browser, they will not load in.

### Expected behavior 
I think it's pretty self explanatory, but run the system index in range, and the chat manager correctly. 

### Actual behavior
I am unaware of what I am supposed to put here, so: tModLoader itself is having internal issues with correctly running (might only be in bulk) mods. 

### Reproduction frequency
Every single time, I have not been able to not reproduce the index exception, and for the null exception, if you do the steps listed it also always happens.  

### Additional Information
The mods load in, but the index exception still happens. I spent a few hours mixing around mods and taking certain ones off based on the client log's warnings and errors, to no avail. Doing only calamity it went through, but I did not do 2 mods only and onwards until the error happened again. I sincerely apologize if this issue report is bad, this is my first time ever writing one.

**Comment by cozykoko** [comment]
This is the 32bit tmodloader. The 64bit tmodloader is unofficial and not supported.

**Comment by Mirsario** [comment]
That's also quite a lot of mods, some could be messing with localizations. Try asking around 64-bit TML's support channels on Discord: https://discord.gg/DY8cx5T
Troubleshooting is always better in a chat than on a forum.
