### ISSUE TITLE
[1.4] Researching Modded Items and disabling the Mod makes players not save correctly

### ISSUE THREAD

**Issue by Mayonnaisinator** [tModLoader/tModLoader#1672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

There are two branches to this issue depending on steps taken:

1. If a modded item is researched in Journey mode, and then the mod is disabled, the player file doesn't save correctly and reverts back to before the item was researched.
2. Alternatively, if you research, close the world, re-open the world with the player, and _then_ leave and disable the mod, the player becomes unplayable. Clicking on the player on the menu does nothing, and the player appearance reverts to default, and it says "Classic", even if the player is a Journey mode character. Re-enabling the mod does then restore the ability to play as that player.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/6916000/client.log)

### Steps to reproduce

1. Research a modded item in Journey mode, and make changes to your inventory so that it is noticeable
2. Exit the world and disable the mod
3. Re-open a world using that player, and the player will have reverted back to before the item was researched, so the inventory will be back how it was before

Alternatively:
1. Research a modded item in Journey mode, and make changes to your inventory so that it is noticeable
2. Exit the world, and then re-open a world using that player
3. Exit again, and now disable the mod
4. Try selecting the player on the menu, but you won't be able to as clicking it does nothing. The player's apperance will have lost their armour/vanity, and it will say that the player is a classic player, despite being a Journey player
5. Re-enable the mod and the player can be selected again

### Expected Behavior

If a modded item is researched and the mod is disabled, the modded item should disappear from the research menu. Upon re-enabling the mod, that item should re-appear in the research menu. If an item is only partially researched, its progress should also be preserved. Obviously, the player's inventory should save correctly throughout all of this.

### Actual Behavior

Player's inventory/state isn't saving when modded items are researched. Note that this actually also happens if a modded item is only partially researched (e.g. 10/100), so it doesn't even have to be fully researched and appear in the menu for the issue to happen.

### Reproduction frequency

I can get this to happen with 100% frequency following the steps above. I used ExampleMod to test this extensively, but I did have this happen with Magic Storage yesterday.

**Comment by Erisfiregamer1** [comment]
Hmm, try importing the character to Terrasavr and removing all research. Does that fix it?

**Comment by Mayonnaisinator** [comment]
> 
> 
> Hmm, try importing the character to Terrasavr and removing all research. Does that fix it?

I tried that, but I don't think Terrasavr would help since modded research is stored in the .tplr file, which I don't think Terrasavr accepts. I instead tried just straight up deleting the .tplr file, and that did correct the issues, albeit at the loss of modded player data.

So that confirms that the issue is definitely with the modded research.

**Comment by Mirsario** [comment]
Should now be fixed with #1740 merged.

**Comment by PedroFodas** [comment]
how do you fav researched items?
