### ISSUE TITLE
[1.4] Extracting dlls out of mods doesn't work

### ISSUE THREAD

**Issue by saschahi** [tModLoader/tModLoader#1677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

Extracting dlls out of mods doesn't work

### Log File

Found nothing about the extraction in there anyway.

https://pastebin.com/CReThPr8

### Steps to reproduce

1. Extract a mod
2. look for extracted dlls in "ModLoader\Beta\references\mods" or "ModLoader\references\mods"
3. Don't find them

### Expected Behavior

It should put extracted dlls in
"ModLoader\Beta\references\mods"
(was confirmed this is expected behaviour on discord)

### Actual Behavior

It doesn't put extracted dlls in
"ModLoader\Beta\references\mods"
and the entire "references\mods" path doesn't exist

### Reproduction frequency

tested it with one of my mods I updated from the old tModLoader version and 2 random mods I downloaded from the workshop

### Additional Information

The folders "references\mods" also weren't created.

I also tried to manually create this path but it still doesn't work.

**Comment by Chik3r** [comment]
Have you tried going to the extracted mod's folder and seeing if the dll is there? If it isn't there, it might be that the developers of that mod aren't allowing people to extract the dlls. (Done by setting `hideCode` to `true` in `build.txt`)
If the dll is being extracted, but not copied, someone would have to fix that.

(Extracted mod folder is `Terraria\ModLoader\Beta\Mod Reader\ModName` I think)

**Comment by saschahi** [comment]
> 
> 
> Have you tried going to the extracted mod's folder and seeing if the dll is there? If it isn't there, it might be that the developers of that mod aren't allowing people to extract the dlls. (Done by setting `hideCode` to `true` in `build.txt`)
> If the dll is being extracted, but not copied, someone would have to fix that.
> 
> (Extracted mod folder is `Terraria\ModLoader\Beta\Mod Reader\ModName` I think)

yep. i tried that. and no i don't have hidecode on (like I said, one of the mods I tried it on was my own mod)

and yep, I also looked there. there IS a dll that generated, but it's not the correct one.

**Comment by JavidPack** [comment]
K, They will now end up in Mod Sources/Beta/Mod Libraries
