### ISSUE TITLE
[Compiling Mods] FNA/XNA Types Confliction

### ISSUE THREAD

**Issue by NaitLee** [tModLoader/tModLoader#1678]
I'm developing mods with tml 0.11.8.4. But whenever there's something like `Color` or `Vector2` i.e. XNA types in code, the build fails with something like this:

```
error CS0433: The type 'Vector2' exists in both 'FNA, Version=17.4.0.0, Culture=neutral, PublicKeyToken=null' and 'Microsoft.Xna.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=842cf8be1de50553'
```

I've dived into this for hours and cannot find a solution on Internet or Wiki.

Both Visual Studio and in-game compile have this problem. Means even ExampleMod will fail the compile.

Seems only me have this issue... Any helps?

P.S. I'm new to C# & VS (big project) development, please forgive me if this is really easy to resolve...

**Comment by Chik3r** [comment]
You could try going to the tModLoader install folder (generally `C:\Program Files (x86)\Steam\steamapps\common\tModLoader`), deleting the `ModCompile` folder, and opening tModLoader, going to the Mod Sources menu and redownloading ModCompile, then building your mod.
Generally, that solves the issue, but if it doesn't work, you could try deleting the tModLoader folder and reinstalling tModLoader

**Comment by NaitLee** [comment]
Oh, it works, thanks!

So the problem is that I've mixed `tModLoader.FNA.exe` and `tModLoader.XNA.exe` along with their files together.

But, they are not documented in the wiki. Consider updating it?
