### ISSUE TITLE
[1.4] Minion shots deal critical hits

### ISSUE THREAD

**Issue by Falcon-05** [tModLoader/tModLoader#1688]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

Minion shots (projectiles that are shot by minions) are dealing critical hits even though minions should not have critical strike chances, excluding whip tags.

### Steps to reproduce

1. Summon a minion that shoots projectiles
2. The minion will attack enemies and occasionally crit

### Expected Behavior

The minions don't crit.

### Actual Behavior

The minions are dealing critical hits.

### Reproduction frequency

All of the time, though the crit chance is quite low (likely 4%)

### Additional Information

Here are two examples of minion shots dealing critical hits:
https://gyazo.com/9c1b1dbf174d7f29a76c379332c7897d
https://gyazo.com/943c4ace6e5c5e96e27e0d0047ac7338

**Comment by Falcon-05** [comment]
After some more testing, it seems that whips (and projectiles spawned by whips, such as cool whip's snowflake projectile) are also affected by this issue.

**Comment by Blookiwi** [comment]
I tried reproducing this oddity with the Tempest Staff, but it doesn't seem to happen on my side, even with my regular hyrbid set...
Even with Xeno and Hornet Staves :/
However, I can confirm that whips can indeed have some critical strikes.

**Comment by Mirsario** [comment]
A temporary fix has been merged a few days ago - ede936c . But I'll keep this issue open until it's replaced/finalized.

**Comment by Falcon-05** [comment]
I haven't tested it, but you should probably make sure stuff like the chlorophyte leaf crystal can't crit either

**Comment by Falcon-05** [comment]
Yep, leaf crystal is dealing critical hits

**Comment by Chicken-Bones** [comment]
Fixed in #2196
