### ISSUE TITLE
The 4k Screen resolution would cause the carsh when you join the world

### ISSUE THREAD

**Issue by IreneClift** [tModLoader/tModLoader#1690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest Official

### OS

Windows

### Platform

Steam

**Comment by IreneClift** [comment]
I can't join the world when my Screen resolution>2k

**Comment by Mirsario** [comment]
Duplicate of #1661

**Comment by IreneClift** [comment]
Sorry I don't Find it because I use wrong keyword to search
