### ISSUE TITLE
[1.4] [Windows] Vanilla Asset loading crashes due to lowercase files

### ISSUE THREAD

**Issue by direwolf420** [tModLoader/tModLoader#1691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

The following files in `Terraria\Content\Images` (not tmodloader!) can cause exceptions during gameplay if the associated content appears on screen:
```
npc_517.xnb
gore_240.xnb
projectile_179.xnb
projectile_618.xnb
```
It can be fixed by deleting the files and letting steam update them, or by manually renaming them. What will not fix it is simply reinstalling the game. Windows ignores casing on files and will not replace them.

### Log File

The usual "asset not found" exception pointing to one of those four things

### Steps to reproduce

1. Make sure the file `Terraria\Content\Images\projectile_179.xnb` exists with that exact casing
2. Place some [slush](https://terraria.fandom.com/wiki/Slush_Block)
3. Break blocks beneath it
4. Get exception regarding `projectile_179`

### Expected Behavior

No exception

### Actual Behavior

Exception

### Reproduction frequency

100% 

### Additional Information

It was suggested to auto-rename those files in the Terraria install folder on tml launch.

**Comment by Mirsario** [comment]
Handled with #1768
