### ISSUE TITLE
[1.4] Walls can't be destroyed in assisted mode

### ISSUE THREAD

**Issue by htd-tstepien** [tModLoader/tModLoader#1694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

When trying to destroy a wall with assisted mode (default: ctrl) the wall doesn't get destroyed.
It only happenes when in front of the wall we have something (like torch, door, or wall is "between" the block)

### Steps to reproduce

I've created short video about how to reproduce it, it's in non-public [youtube video](https://youtu.be/4FFl9WM2uB4).

### Expected Behavior

Walls in assisted mode should breaks without issue when in front of the wall we have other block.

### Actual Behavior

Wall doesn't break.

### Reproduction frequency

Every time

**Comment by htd-tstepien** [comment]
Probably can be closed - after #1695 I can remove in assisted mode wall

**Comment by JavidPack** [comment]
Ok, thanks for checking, I wasn't sure if this was fixed by coincidence.
