### ISSUE TITLE
[1.4] Hammer change from walls mode to blocks mode.

### ISSUE THREAD

**Issue by htd-tstepien** [tModLoader/tModLoader#1695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

Maybe not everyone knows this, but in Vanilla Terraria when you start hitting a wall with the hammer and move the mouse on the screen, nothing will be destroyed except the walls. Only when you stop holding the mouse button and "attack" a block then the block will be modified (and you'll be not able to destroy walls).

### Steps to reproduce

1. Put a wall by the door
2. Move the hammer with the mouse during the destruction (without clicking) outside the wall (e.g. under the door)
3. The door will be destroyed because the hammer suddenly gains the ability to edit the block, besides destroying the walls

### Expected Behavior

A hammer shouldn't be able to destroy walls and edit blocks at the same time.

### Actual Behavior

A hammer is be able to destroy walls and edit blocks at the same time.

### Reproduction frequency

always

**Comment by Mirsario** [comment]
Should now be fixed via #1698
