### ISSUE TITLE
[feature proposal] Header for twld data

### ISSUE THREAD

**Issue by Ishigh1** [tModLoader/tModLoader#1704]
### Is there an existing suggestion for this?

- [X] I have searched the existing issues

### Do you intend to personally contribute/program this feature?

No

### Description

Some mods need to get info from a world before it is even loaded, to change the world selection UI
My proposal is to provide ways to save info outside of the main twld save to provide quick way to access info

### What does this proposal attempt to solve or improve?

For now the only way to have such info is to load the whole twld of each world, this can easily take few seconds even with few low modded worlds

### Which (other) solutions should be considered?

I'd say either a separate file or a special part of the twld file that can be fetched separately without having to load everything, or few methods to directly use it so every mod doesn't have to load it

**Comment by Chicken-Bones** [comment]
If you provide me some `.twld` files which take the said 2s to load, and a list of the tags you'd like to get, I'll look at both profiling the current deserializer, and making a 'quick access' one which can search for a specific tag path in a file and only deserialize that portion.

**Comment by Ishigh1** [comment]
With 5 worlds with this data, it requires the 2 seconds to load the .twlds
The data I need is at `modData.[mod = AdvancedWorldGen].data.Options` (and even by commenting out this search the load is still slow)
[Fragile_Mesa_of_Care.zip](https://github.com/tModLoader/tModLoader/files/6949248/Fragile_Mesa_of_Care.zip)

**Comment by Ishigh1** [comment]
Well it seems it went faster somehow, only 1/10th of a second for every twld

**Comment by JavidPack** [comment]
This would facilitate #1416

**Comment by Chicken-Bones** [comment]
Annoyingly this would require another file alongside `.twld`, maybe `.twldheader`? The NBT format provides no way to 'skip' entries you don't care about

**Comment by absoluteAquarian** [comment]
A `.twldheader` file would be useful.  The bottleneck in loading the `.twld` file is having to load the `tiles.tileData` and `tiles.wallData` entries, which are easily in the millions of bytes.

If you only wanted to check the `modData` in the world, having to load `tiles.tileData` and `tiles.wallData` would be unnecessary.

**Comment by Chicken-Bones** [comment]
I'm reluctant to add an extra file.

It occurs to me, that `TagCompound` entries are saved in the dictionary iteration order. In our current version of .NET, `TagCompound` is backed by `Dictionary` which preserves insertion order (provided no entries are removed). Thus, when saving the world, it would be possible to write the first entry as `"header"` and to make a custom reader which only reads one entry from a `TagCompound` and skips the rest.

Other options include using a `List` as the root element, or using an `OrderedDictionary`, perhaps optionally when constructing the `TagCompound`
