### ISSUE TITLE
[1.4] On Click button inner exception Fatal Freeze

### ISSUE THREAD

**Issue by Solxanich** [tModLoader/tModLoader#1706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

Button Click events with inner exceptions trigger an infinite loop of reattempting the same code from the click onwards. 
Basically ends up as a fatal crash.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/6948046/client.log)

Was produced by forcefully throwing a generic exception in WorkshopHelper.PublisherInstance.UpdateItem() while trying to fix some vanilla code gaps.

Was also a problem in #unloading

### Expected Behavior

Graceful Exception thrown, the game processes exception instead of freezing.

### Actual Behavior

Game freezes in an inner exception loop within on click.

### Reproduction frequency

100%

### Additional Information

 Initial thought is that the inner exception within the event means that the release of click event is never reached on the main thread

**Comment by JavidPack** [comment]
I think someone could easily fix this with a check
