### ISSUE TITLE
Optional Mod class feature not working (Cannot create an abstract class)

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#1713]
If you are a modder experiencing this issue, you mistakenly changed your Mod class to some other class, like ModSystem. The Mod class is typically named ModName.cs and is located directly in the ModName folder.

In 1.4 we seem to support a mod not having a Mod class, but that leads to an error since it attempts to instantiate the abstract Mod class directly.

I'm not sure if we want to support this feature, as it seems a recipe for issues, especially if some other mod uses reflection on a Mod class in an attempt to get the modded assembly, or some other issue I can't imagine right now.

![](https://i.imgur.com/66z7XdE.png)    

https://github.com/tModLoader/tModLoader/blob/ec75d51fef89889954c82fb0cfda3c32bfd7d0da/patches/tModLoader/Terraria/ModLoader/Core/AssemblyManager.cs#L152-L166

**Comment by Chicken-Bones** [comment]
`Mod.Code` exists for getting the assembly.
