### ISSUE TITLE
Mod browser not downloading mods.

### ISSUE THREAD

**Issue by ThatRandomCoder** [tModLoader/tModLoader#1717]
It seems that i can't download any mod from the mod browser, it just kinda tries to load, then just kicks me back to the browser without downloading said mod.

Has anybody else encountered this problem?

**Comment by Solxanich** [comment]
@ThatRandomCoder - I recommend getting support in our discord, in the #Alpha-Support channel for 1.4, #support for 1.3. 

This issue description doesn't provide enough information to work off of. Please use the template. Primarily, first obvious question - is this 1.4 or 1.3 you are encountering this on?

Do you have any logs from this issue?
And can you clarify what Operating System you're running on?

**Comment by ThatRandomCoder** [comment]
Sorry this is my first time using Github.

I’m using it on a MacBook Air with macOS Catalina, I don’t think it’s generating any logs because it’s not crashing, but if it was where should I find those? This is in the 1.3, I actually didn’t know there was a 1.4, Is the 1.3 a 32 bit app? Cause I can see how that might cause problems with Catalina.

Thank you for responding, sorry about the template, I didn’t know and I’ll make sure to format my questions better in the future if I have any.

**Comment by Solxanich** [comment]
Mac Logs: ~/Library/Application support/Terraria/ModLoader/Logs/

Is this an M1 based processor or an older Mac? (It will likely be an M1 if purchased this year). If its an M1, note that they aren't really supported at this point in time: (https://github.com/tModLoader/tModLoader/issues/1582)

tmodloader 1.3 is supposed to be 64 bit on Mac (although people have reported it isn't clear as such).
Likely launch issues for Mac can range in possibilities, with M1 being a leading cause afaik. 
For 1.3 support, I may have to defer to another to respond. Again, I'd recommend getting help in #support here for faster and more detailed help: https://discord.gg/tmodloader

**Comment by ThatRandomCoder** [comment]
Thanks! I went over and my problem was solved almost immediately.
