### ISSUE TITLE
[1.4 alpha] Mod browser, large images

### ISSUE THREAD

**Issue by zackadiax24** [tModLoader/tModLoader#1720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

Some images become very large within the mod browser and sometimes will cover buttons. I have noticed this several times during use.

### Log File

![Tmodloader bug 1Z-2](https://user-images.githubusercontent.com/47438594/128799878-e84912ab-ecaa-40db-85b9-a3123ba86a6e.PNG)
![Tmodloader bug 1Z-3](https://user-images.githubusercontent.com/47438594/128799882-1959b2f3-5722-416f-a528-e47a30b49f03.PNG)
![Tmodloader bug 1Z-1](https://user-images.githubusercontent.com/47438594/128799884-22420846-0ef7-45b1-a46e-a7336868e94e.PNG)

### Steps to reproduce

1. Launch TModloader
2. Open mod browser
3. profit?

### Expected Behavior

images should be consistently sized and not cover buttons.

### Actual Behavior

images are not consistently sized and cover buttons.

### Reproduction frequency

any time i open the mod browser

**Comment by Solxanich** [comment]
Do you have any mods enabled while experiencing this issue?
I believe Eternal Resolve has already been flagged to be causing issues like this, wouldn't surprise me if other mods were causing similar problems.

Please replicate without any mods, or if it is caused by a mod, contact them appropriately, via the Workshop discussions or otherwise.

**Comment by Steviegt6** [comment]
> wouldn't surprise me if other mods were causing similar problems.

I would actually be pretty surprised. The only other mod I know of that makes any modifications to the mod menu is one of my own, but that's only on the Mod List anyway, and not the workshop page. EternalResolve makes some Mono.Cecil-based modifications using MonoMod for display their animated logo. It's a very niche thing, especially right now.

And, @zackadiax24, please ensure you aren't running any mods when having these kinds of issues. If you aren't, then this is pretty concerning considering we utilize vanilla UI features to resize images, and those shouldn't break.

**Comment by Steviegt6** [comment]
Also, Ishigh and I have already communicated the problems to the EternalResolve developers, so please don't go out of your way to report the issue if it ends up being a result of their mod.

**Comment by Chicken-Bones** [comment]
Feel free to re-open and comment if you can confirm it's a tML issue and not a specific mod
