### ISSUE TITLE
[1.4] Visit Workshop Button in the Mod Info Section

### ISSUE THREAD

**Issue by Rijam** [tModLoader/tModLoader#1727]
### Is there an existing suggestion for this?

- [X] I have searched the existing issues

### Do you intend to personally contribute/program this feature?

No

### Description

Add a button to visit the mod's Steam Workshop page in the mod info section in addition to the normal "visit the mod's homepage" button.

Here is a mock-up image that I made.
![tMLFeatureRequest](https://user-images.githubusercontent.com/11262234/129108722-ee3f7b6b-db59-4e8f-aa9a-704346fa7fc9.png)

### What does this proposal attempt to solve or improve?

It would allow users to easily visit any mod's Steam Workshop page while in game without having to manually search for the mod on the Workshop themselves. This would be beneficial if the user wanted to see the comments on the mod's Workshop page, see how many subscribers it has, or look at the version history.

**Comment by JavidPack** [comment]
Would people want this to open in their browser? or in the steam overlay browser?

**Comment by Rijam** [comment]
> Would people want this to open in their browser? or in the steam overlay browser?

Personally I would prefer the Steam Overlay, but for GOG users it would have to be the browser. If it is easier just to make it the browser for everyone, then that would work too.

**Comment by Ishigh1** [comment]
Steam browser isn't exactly the best, I'd prefer the favorite browser, but it could be something asked when opening workshop for the first time, with an option to remember

**Comment by Steviegt6** [comment]
> Would people want this to open in their browser? or in the steam overlay browser?

Configurable? Default to overlay.

**Comment by Rijam** [comment]
Thanks Solxan and everyone else!
