### ISSUE TITLE
Linux - Crashes before Launch 

### ISSUE THREAD

**Issue by Onering20** [tModLoader/tModLoader#1730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest Official

### OS

Linux

### Platform

Steam

### Description

The app fails to bring up a window when launched via steam or Lutris (via steam) 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/6975723/client.log)

### Steps to reproduce

1. open steam
2. select tModLoader from Library (steam or Litrus)
3. select play
4. wait (some times the crash kills Main on its own)
5. Open System Monitor (Linux Task Manager)
6. Find and Kill Process name "Main" with Command Line "./tModLoader.bin.x86_64"
7. repeat from step 3 until it successfully Loads

1. open steam via terminal
2. select tModLoader from Library (steam or Litrus)
3. select play
4. wait (some times the crash kills Main on its own) (watching for text like Stacktrace (crash) or Loaded n vanilla assets (launched)
5. Open System Monitor (Linux Task Manager)
6. Find and Kill Process name "Main" with Command Line "./tModLoader.bin.x86_64"
7. repeat from step 3 until it successfully Loads

### Expected Behavior

the TModLoader Launchs
[SteamTerminal(launches).log](https://github.com/tModLoader/tModLoader/files/6975768/SteamTerminal.launches.log)

### Actual Behavior

The app never shows up and the Main process (./tModLoader.bin.x86_64) persists until Killed (stop or end doesn't stop it)

[SteamTerminal(fails).log](https://github.com/tModLoader/tModLoader/files/6975756/SteamTerminal.fails.log)

### Reproduction frequency

4 of 5 launches, eventually I can get in to the game just fine
it feels more stable with steam launched via terminal but it could just be waiting for vanilla assets to load and no feed back otherwise

### Additional Information

Ubuntu 21.04
Lutris  0.5.8.4
Steam: API: v020 Package:1626824053  build:7/20/2021
tModLoader v0.11.8.4 (steam install)
Ram 8 gb

**Comment by ExistingDude** [comment]
Try to launch using the tmodloader-mono script. You can find it by click "Browse Local Files" in steam. I got it to launch by installing mono and using aforementioned script.

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
