### ISSUE TITLE
Mod Sources Not Working/Already tried installing .net 4.5 reference assemblies from the link multiple times

### ISSUE THREAD

**Issue by Arcinoux** [tModLoader/tModLoader#1737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest Official

### OS

Windows

### Platform

Steam

### Description

I wanted to start getting to work on modding, but I'm unable to activate developer mode. The button is nowhere to be found and this screen pops up every time despite me following multiple guides on the .net 4.5 reference assemblies
![image](https://user-images.githubusercontent.com/88911892/129426576-d61732fd-dcf0-4897-bd3d-c307ac73e58e.png)
I created a github account for this as nobody on the discord was able to resolve the issue

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/6985551/client.log)

### Steps to reproduce

I honestly have no idea (this is my first time troubleshooting here) but I'm pretty sure it goes something like this
Open devmode on a previous version.
Exit out.
Switch to most recent version on a new pc or drive.

### Expected Behavior

Idk how much this changed since I last tried modding but there should be a screen with the build + reload button, etc instead of this
![image](https://user-images.githubusercontent.com/88911892/129426779-bbca36f0-9d77-495c-9bf7-34017ef65a70.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/88911892/129426783-9225bf3e-2fe9-4f50-b734-d6e266f1b65d.png)

### Reproduction frequency

100% of the time

### Additional Information

I've already tried the link (https://tmodloader.net/dl/ext/v45ReferenceAssemblies.zip) multiple times to no avail

**Comment by Spoldozer** [comment]
I can say that I was able to get Devmode to work on my own end. (granted this was before the 1.4 alpha version came out, and I still use 1.3.5) From what I can tell from the pictures you have provided, it seems like you are missing Visual Studio, or an extension for it. I originally went to the Contributor's guide for TModLoader, and followed the instructions there, and used the Developer's guide to finish off what the Contributor's guide could not provide information-wise. I recommend you do the same, as it worked and works for me just fine.

**Comment by Chicken-Bones** [comment]
Specifically https://github.com/tModLoader/tModLoader/wiki/Developing-with-Visual-Studio

**Comment by Arcinoux** [comment]
thank you!
