### ISSUE TITLE
[1.4] A pixel on leather whip's projectile tip sprite is missing

### ISSUE THREAD

**Issue by Falcon-05** [tModLoader/tModLoader#1739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

When a leather whip is used, the sprite of the projectile's tip has a missing pixel.

### Steps to reproduce

1. Use a leather whip 

### Expected Behavior

Sprite doesn't have a missing pixel

### Actual Behavior

Sprite has a missing pixel

### Reproduction frequency

100% of the time

### Additional Information

Screenshot of a leather whip being used:
https://gyazo.com/0d608fc04811113ca773e3e9f902261f

**Comment by jjohnsnaill** [comment]
This is a vanilla issue, and one so miniscule I don't think tML should bother fixing honestly.

**Comment by JavidPack** [comment]
Just checked, looks correct now, maybe this was fixed in a vanilla update.
