### ISSUE TITLE
[1.4] Multiplayer characters both "mine" when only one clicks 

### ISSUE THREAD

**Issue by MunchyG** [tModLoader/tModLoader#1745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

so basically if two (or more idk) people in multiplayer are near each other and one [player 1] of them attempts to mine (or any action, placing included) if the other player's [player 2] cursor is in the range of "player 1" then it will double peform the action, so say "player 1" is trying to mine with a pickaxe, if "player 2"'s cursor is in range it will mine that block too, even if "player 2" doesn't have a pickaxe at all. 

### Log File

[client2.log](https://github.com/tModLoader/tModLoader/files/6988175/client2.log)
[server.log](https://github.com/tModLoader/tModLoader/files/6988177/server.log)
[client.log](https://github.com/tModLoader/tModLoader/files/6988179/client.log)

### Steps to reproduce

have 2 or more players.
have the players close and all looking at different blocks
have one player attempt to mine a block

### Expected Behavior

think it is pretty clear

"player 1" shoudn't also "mine" the blocks under "player 2"'s cursor 

### Actual Behavior

"player 1" also "mines" the blocks under "player 2"'s cursor, as well as the one under his cursor

### Reproduction frequency

so far 100%. every time we have left clicked and the cursors overlapped in "build/mine" range it has double performed the action

### Additional Information

this was originally noticed in journey mode (cos long reach) with mods, and i just thought it was a mod causing the issue but decided to test it without any mods loaded and the same issue arose. This may just be a journey mode thing though cos all my testing was also in journey mode. (have attached both of my clients and the server log hosting while i was testing)

**Comment by DBotThePony** [comment]
[Video demonstrating the issue](https://icf.dbotthepony.ru/Videos2/2021-10-02_14-32-54.mp4)

also on video you can hear soundtrack is distorted

**Comment by MunchyG** [comment]
any updates on how patching this bug is going

**Comment by Solxanich** [comment]
@MunchyG  the issue should now be suitably patched.

If you can confirm, then please close this.
If we don't hear anything, we will assume it is resolved and this can be closed

**Comment by MunchyG** [comment]
Should get around to testing it later today, I will let you know how it goes.

**Comment by MunchyG** [comment]
From some very quick testing I would say it is good (however it is local host testing, but given the code changes I don't think it should make a difference)
