### ISSUE TITLE
ItemLoader.DrawHands, DrawHair, DrawHead, DrawBody, DrawLegs, DrawArmorColor, ArmorArmGlowMask, HoldoutOrigin, PostDrawTooltip all not called

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#1761]
The following `ItemLoader` methods are never called. As such, several things possible previously in 1.3 no longer are possible.

- [x] ~~DrawHands~~
- [x] ~~DrawHair~~
- [x] ~~DrawHead~~
- [x] ~~DrawBody~~
- [x] ~~DrawLegs~~
- [x] DrawArmorColor
- [x] ArmorArmGlowMask
- [x] HoldoutOrigin
- [x] PostDrawTooltip

**Comment by Mirsario** [comment]
Fixed with the above PR. DrawX methods were removed in favor of Sets entries and booleans in PlayerDrawSet.
