### ISSUE TITLE
Can't bind Mouse4 and Mouse5 buttons

### ISSUE THREAD

**Issue by ExistingProgrammer** [tModLoader/tModLoader#1766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest Official

### OS

Linux

### Platform

Steam

### Description

Can't bind Mouse4 and Mouse5 buttons on Linux, i tried to search for it and i found a merged PR from 2017. I can bind Mouse1, Mouse2 and Mouse3 but not the extra mouse buttons.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7025205/client.log)

### Steps to reproduce

1. Go to Controls
2. Try Binding extra mouse buttons

### Expected Behavior

I can bind the mouse buttons

### Actual Behavior

I think terraria doesn't recognise the extra buttons

### Reproduction frequency

All the time.

### Additional Information

Garuda Linux Barebones, and Arch Linux based distro. I launched using the tmodloader-mono script because tmodloader didn't launch normally. I am using Feral Gamemode for extra performance but the shouldn't be an issue. The only major content mod I have enabled is calamity. Using some QoL mods as well.

**Comment by Mr-Crabman** [comment]
I'm having the same issue, so this either didn't get fully fixed or has been broken again; I can't bind anything to Mouse4 or Mouse5, and if I manually bind something to them in the `input profiles.json` file, I can see the action has Mouse4 bound to it in the settings menu, but the button/action doesn't actually work ingame: [client.log](https://github.com/tModLoader/tModLoader/files/7831502/client.log)

I am using Xubuntu 20.04.3, an Ubuntu Linux distro. I just installed and launched tModLoader normally from Steam, and have not installed any mods yet. I'm in the 1.4 beta.

It may be worth noting that the same problem seems to apply vanilla Terraria, but only the native Linux version (running the windows Terraria through Proton fixes this issue).
