### ISSUE TITLE
Coin Gun does something... weird

### ISSUE THREAD

**Issue by BigPlagueBee** [tModLoader/tModLoader#1769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

When i hold the coin gun, it freezes my animation, and removes vanity/accs
oh, and i cant use it

### Log File

[https://steamcommunity.com/sharedfiles/filedetails/?id=2581540929](https://steamcommunity.com/sharedfiles/filedetails/?id=2581540929)

### Steps to reproduce

The only step: HOLD THE COIN GUN

### Expected Behavior

it should act how the Coin Gun normally acts, shooting coins without doing anything visual

### Actual Behavior

it is freezing my animations and getting rid of accs/vanity

### Reproduction frequency

every time i hold it

**Comment by Steviegt6** [comment]
That isn't a log file.

**Comment by Mirsario** [comment]
Unable to reproduce

**Comment by BigPlagueBee** [comment]
> Unable to reproduce

so then it must be a mod i have
Thanks!
