### ISSUE TITLE
[1.4] Feral Claws autoswing locks player facing direction

### ISSUE THREAD

**Issue by DarioDaF** [tModLoader/tModLoader#1770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

*Feral Claw* only autoswing keeps the player and weapon facing the direction of the first use

### Log File

Not applicable

### Steps to reproduce

Get a *Lead Broadsword* and equip *Feral Claws*.
Start to autoswing and try to move around

### Expected Behavior

Player switch face direction to the direction of motion **on use frame** (not at any moment)

### Actual Behavior

Player and weapon don't change facing direction even when moving

### Reproduction frequency

100%

### Additional Information

Player facing behaviour:
- Vanilla
  - *Terra Blade*: Facing the mouse cursor
  - *Lead Broadsword* with *Feral Claws*: Player motion direction
  - *Lead Broadsword*: Player motion direction

- tModLoader
  - *Terra Blade*: Facing the mouse cursor
  - *Lead Broadsword* with *Feral Claws*: Player motion direction **on first swing (no changing when moving around or moving cursor)**
  - *Lead Broadsword*: Player motion direction

**Comment by JavidPack** [comment]
I can confirm this still happens.
