### ISSUE TITLE
Request Unban from Tmodloader Discord Server

### ISSUE THREAD

**Issue by NameLord** [tModLoader/tModLoader#1775]
My name on discord is NGeorge#0733 and i was banned because i was having terraria pirated and i im so sorry but now i need a help but noone wants to help me
now i bought terraria legally from steam.
don't delete this and please take serious attention who is admin or owner of tmodloader.

**Comment by drunderscore** [comment]
:man_dancing:

**Comment by NameLord** [comment]
> 🕺

I was banned. :(

**Comment by Steviegt6** [comment]
🕺

**Comment by Mirsario** [comment]
PM any of these people via being in the official terraria discord:
> Moderators:
> - Jenosis
> - Rartrin 
> - Itorius 
> - Shockah
> - orian34 
> - Frous 
> - Trivaxy
