### ISSUE TITLE
InstallNetFramework.sh on Debian Stretch issue

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#1778]
It seems the `[[` and `]]` are not standard syntax for .sh files. This user reported changing `#!/bin/sh` to `#!/bin/bash` worked, but maybe we can just get rid of this syntax? I think `[` and `]` should work fine?

Edit: this was actually someone running a really old build. Might not be a current issue.

![unknown](https://user-images.githubusercontent.com/4522492/130422679-57e8c224-7f64-4fd1-a5a5-69c220121390.png)

**Comment by RuneZhevitz** [comment]
After it testing via the dash shell myself, I can confirm that [[ isn't a posix shell feature.

**Comment by RuneZhevitz** [comment]
Added fixes in my latest pull request: #1782
