### ISSUE TITLE
[1.4 MergedTesting] RGB Lighting Integration doesn't work 

### ISSUE THREAD

**Issue by Soulfurious** [tModLoader/tModLoader#1785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Other (please specify elsewhere)

### OS

Windows

### Platform

Steam

### Description

Terraria seems unable to take control of various “RGB” enabled devices when TML is used for version 1.4 of the game. 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7039340/client.log)

### Steps to reproduce

1. Launch the game using the batch file located in the installations root directory.
2. Observe the multicolored LEDs on your mouse, keyboard, or any other supported peripheral. Observe your gaming software to see if profiles are switched.

### Expected Behavior

Upon launching the game, the peripherals profile should immediately switch to the profile created for the game. This should result in the multicolored LEDs on your peripherals dimming, starting the 'breathing' effect where the lights turn green and reach peak brightness as the sun reaches its zenith over the horizon in the main menu screen.

This behavior being present would obviously indicate that the feature of lighting integration is working as intended, which is not what's happening.

### Actual Behavior

The lighting integration does not work at all, and the gaming software does not switch to the Terraria profile which contains the integration for the original Terraria executable.  

### Reproduction frequency

This problem occurs every time the game is launched with TML 1.4's batch file on the MergedTesting branch.

### Additional Information

This feature appears to work normally in the vanilla game on my end. The option to use RGB is enabled in the JSON files in both installations.

I am using the MergedTesting branch (though results should be the same in the public alpha build, and .NET version 5.0.8 is installed. The vanilla game and the steam version of TML are installed in separate directories. The peripherals in use are the Logitech G213 and G502. G-Hub has been installed, migrating from LGS. I attached the screenshot of what my profile settings and paths look like within G-Hub.

![terraria lgs profile](https://user-images.githubusercontent.com/11460328/130621827-0764bbcd-0ad5-4dfc-a7cc-4e41c2ce1d11.png)

I have some speculation to bring to the table as well. Whilst troubleshooting this issue with Solxan and others, he surmised that something wrong within the startup code that is supposed to create RGB handlers. And that someone potentially disabled the error tossing for the scenario where RGB is unsuccessfully loaded, and that they also disabled it entirely by accident. I do not know whether or not this could be the case.

**Comment by Armipotent** [comment]
**Temporary fix - Tested on `tModLoader v0.12 1.4 Alpha 02024925`**

After looking at task manager, it would seem the tModLoader 1.4 executable is called `.NET Host`. Looking at the properties of the executable, it can be found under `C:\Program Files (x86)\Steam\steamapps\common\tModLoader\dotnet\6.0.0`.

This means that, temporarily, you can add the custom path `C:\Program Files (x86)\Steam\steamapps\common\tModLoader\dotnet\6.0.0\dotnet.exe` to G-Hub's Terraria path. This fix works for me, but I'm unsure if this will work for others.

**Comment by YSpoof** [comment]
Didn't worked for me :(

**Comment by MsVoxxie** [comment]
Would love to see this feature fixed / readded. It was neat!

**Comment by sp00pster** [comment]
I'm still having this issue. The lighting is not working for me (using Razer) or my friend (using Corsair), but is working properly for my other friend (using SteelSeries). It doesn't look like Razer Synapse has a workaround option similar to the above G-Hub fix. Vanilla Terraria displays the lighting properly for both me and my Corsair friend, but TML does not.

**Comment by kazyofloof** [comment]
Can confirm temp. fix doesn't work, at least not currently. Adding that ....\6.0.0\dotnet.exe path as a custom path *does* make it swap to the profile when the window is selected, but it does not activate the integration, meaning it is just a blank color/default animation when accessed in this way.

**Comment by Fyrescent** [comment]
There is still an issue with the 1.4.3 tModLoader not recognizing any keyboards in G-Hub and just showing the default rainbow animation when the path is set to `C:\Program Files (x86)\Steam\steamapps\common\tModLoader\dotnet\6.0.0\dotnet.exe`.

**Comment by SomaTGW** [comment]
I can second it doesn't work on current tModLoader, mine just switches back to default desktop background when I switch to tmodloader

**Comment by zLennii** [comment]
i can third this as it works fine with vanilla terraria but does not work with tmod (logitech G815 keyboard + logitech G502 mouse)
