### ISSUE TITLE
[1.4 Alpha] Request Improved Rendering performance

### ISSUE THREAD

**Issue by Solxanich** [tModLoader/tModLoader#1788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

There is still a severe performance issue with the current rendering system, that leads to severe fps drops.

It is currently unrealistic to play tmod in areas with large amounts of tile lighting due to the frame rate drop involved. 
It is important we address this, and try to bring rendering performance within close proximity of vanilla.

### Log File

Nothing useful shows in the logs; this is just lighting code in and of itself.

### Steps to reproduce

In particular, testing the following yields significant concerns for FPS performance:
1) Cheat Sheet's Light hack
2) The Builder's Workshop map from Terraria, in particular the underground tiles room.

In both cases, I see fps drops. This issue was reported originally in Alpha Support, with the following summary screenshot:
![image](https://user-images.githubusercontent.com/59670736/130662539-5e6a59e6-37a7-43ef-8b4c-ee5bd665cf7d.png)

Each of the values provided correlate to Main.cs RenderTiles, RenderTiles2, RenderWalls, RenderBackground, and RenderWater.  They all run on a 4 frame cycle.
Tiles, Tiles2, and Walls runs on the 4/4 frame. Background runs on 3/4. Water on 2/4. Nothing runs on frame 1/4. 

The exact performance drop varies by system; on my i9, I get 60fps at 1080p in both vanilla and tmod on the Builder's Workshop map. I see 40 fps when zoom is at 100% and at 1440p. However, on the ryzen 3700 of original reporter, they get as low as 25 fps on Builder's workshop on tmod at 1080p. 

Further testing also yielded that Retro and Trippy lighting saw a further decrease in performance, being worse than color lighting in terms of fps.

Clearly something ought to be done to improve rendering performance so that its not dragging down fps so drastically in and of itself. Rendering performance seems to be ~3 times worse than vanilla, per the original reporter (CrabBar), and testing myself I see similar tModLoader values.

### Expected Behavior

60 fps holds in well lit scenarios, in addition to low lit scenarios.

### Actual Behavior

fps tanks in well lit scenarios, as opposed to low lit scenarios.

### Reproduction frequency

100%

**Comment by Xetheon** [comment]
This issue does make the game unplayable in areas of lots of lighting. Even in vanilla this is a bit of an issue but it's overly pronounced with the current Alpha. The overall rendering engine just doesn't seem to be able to handle what the game is trying to push out with recent updates, which is pretty expected given how early access tmod 1.4 is. I wouldn't know if it's possible considering all the fundamental limitations there are, but having the rendering side of the game reworked to a point where it's on par with vanilla or even better in some cases would be phenomenal.

**Comment by Solxanich** [comment]
Mitigated with the merging of #1802 . Colour lighting now provides the best performance in general.

Will be fully solved when switch to release builds instead of debug builds (debug builds roughly double rendering times), but since that's out of control of a bug fix per se, I believe that #1802 is sufficient as an improvement for well lit areas at this time.
