### ISSUE TITLE
Steam Workshop Features & Integrations

### ISSUE THREAD

**Issue by Solxanich** [tModLoader/tModLoader#1795]
### Is there an existing suggestion for this?

- [X] I have searched the existing issues

### Do you intend to personally contribute/program this feature?

Yes

### Description

The feature request will list various features that could be added to improve integration with Steam Workshop and Mod development/deployment process, but may not necessarily be done

- [x] Ability to set change notes with a custom string on updates
- [ ] Ability to publish mods from Github Actions or similar
- [x] Ability to set tags on an Item
- [ ] Ability to filter by tags in Mod Browser, similar to Hamstar Helpers in 1.3
- [ ] Integration of ModPacks with Workshop Collections
- [ ] Showing the load progress on Mod Browser after each query completes
- [ ] #1728 
- [ ] Ability to delegate a separate location for where Steam installs mods on GoG, instead of the steam's brokenly forced InstallFolder/SteamApps directory
- [ ] Ability to Download any missing mods from an enabled.json like file, a good step towards modpack distro
- [ ] option to run SteamAPI init/Get Client huser on GoG so can manually force download all subscribed workshop items
- [x] other Steam Workshop integrations from Wallpaper zengine?
- [x] Categories/Tags: #245

**Comment by Solxanich** [comment]
@zzp198 - this is not an issue for support questions. This is intended for Feature Addition suggestions. 
Please use a New issue, or seek help in the Discord's Alpha Support channel https://discord.gg/tmodloader

**Comment by direwolf420** [comment]
* [x]  By default, after downloading a mod, keep the list position. Add a button to "go back to top" (although not really necessary since it's a scroll bar)

**Comment by zzp198** [comment]
The title and description support I18N(e.g. multiple files?), and the corresponding language will be preferentially displayed on the steam according to the user

**Comment by Mayonnaisinator** [comment]
- [x] Add an “Open Workshop Folder” button to the Manage Mods menu that opens the Steam file directory to tModLoader’s workshop folder.
