### ISSUE TITLE
[1.3 and 1.4] Mod/GlobalItem.IsVanitySet poor performance

### ISSUE THREAD

**Issue by direwolf420** [tModLoader/tModLoader#1806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

`ModItem.IsVanitySet` calls `SetDefaults` up to three times per item (and it's called three times to cover all 3 parts, potentially calling 9 times), just so it can turn the equip IDs into `Item`s for `IsArmorSet`.
Same applies to `GlobalItem.IsVanitySet` for every GlobalItem.

In 1.4, this can be simplified to use the `ContentSamples.ItemsByType` instead of `SetDefaults`.

@Mirsario suggested reworking the hook(s) to remove this requirement for converting data, but I forgot at this point what his suggestions were, hope he can elaborate on this issue.

**Comment by Mirsario** [comment]
The hooks can be replaced with basic declarative programming. An "(id, id) -> bool" lookup table.. Somewhere in sets?

**Comment by direwolf420** [comment]
Duplicate of #1431, and fixed for 1.4 in #1946
