### ISSUE TITLE
Title turns from tModLoader to Terraria as soon as I click on the sun in the menu to move it.

### ISSUE THREAD

**Issue by malariogaming** [tModLoader/tModLoader#1808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

It's not a huge problem or anything. When I click on the sun in the main menu while I'm creating the world to drag it around the screen, the title changes from tModLoader to Terraria.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7093479/client.log)

### Steps to reproduce

1. Create a new world
2. While the world is being created, drag the sun around the screen and the title changes from tModLoader to Terraria.

### Expected Behavior

The title should remain tModLoader and not change.

### Actual Behavior

The title changes to Terraria.

### Reproduction frequency

I've only done it once, and it happened.

**Comment by Steviegt6** [comment]
That's... literally a feature.
Change it back by cycling mod menus at the bottom.
