### ISSUE TITLE
[1.4] ModTileEntity doesn't place in multiplayer

### ISSUE THREAD

**Issue by Liburia** [tModLoader/tModLoader#1813]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

`NetMessageID.TileEntityPlacement` received on the server calls `TileEntity.PlaceEntityNet` which calls `TileEntitiesManager.NetPlaceEntity` which checks `TileEntity._types[id].IsTileValidForEntity(x, y)` which is a virtual method that returns false by default and is not overriden by `ModTileEntity`.

This results in modded TEs not being placed on the server when a client places one.

**Comment by Mirsario** [comment]
Handled with the PR above.
