### ISSUE TITLE
Dust 182 DustID name is misspelt as "TheDestoryer" and Dust 50 is misspelt as "Adamantine"

### ISSUE THREAD

**Issue by Rijam** [tModLoader/tModLoader#1824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest Official

### OS

Windows

### Platform

Steam

### Description

The DustID name for Dust 182 is misspelt as "TheDestoryer" when it should be "TheDestroyer".

The DustID name for Dust 50 is misspelt as "Adamantine" when it should be "Adamantite".

### Log File

N/A

### Steps to reproduce

1. Create or modify a dust hook like Dust.NewDust or Dust.NewDustDirect.
2. Set the dust type as "182" or "50".
3. The ChangeMagicNumberToID will say the numbers should be changed to "TheDestoryer" or "Adamantine" respectively.

### Expected Behavior

Dust 182 should be "TheDestroyer" and Dust 50 should be "Adamantite".

### Actual Behavior

Dust 182 is incorrectly named "TheDestoryer" and Dust 50 is incorrectly named "Adamantine".

### Reproduction frequency

Always.

### Additional Information

The misspellings are present on both 1.3 tModLoader and the 1.4 Alpha.

**Comment by Rijam** [comment]
The spellings have been fixed, but the ChangeMagicNumberToID still says the incorrect spellings.

**Comment by JavidPack** [comment]
Yes, that is done by the CodeAssist analyzer, I just pushed the changes there, so it'll fix for you in VS if you update it to 0.1.3, but only for 1.4. If you are on 1.3, don't update, since the incorrect spellings are correct there.

![image](https://user-images.githubusercontent.com/4522492/133335317-7ea8c435-e63f-41ee-915f-0a2b8228d7fc.png)

**Comment by Rijam** [comment]
Alright, confirmed fixed for 1.4. Thank you, closing this issue.
