### ISSUE TITLE
[1.4] ItemRarityID.Count bleeds into the first entries of ModRarities.

### ISSUE THREAD

**Issue by RighteousRyan1** [tModLoader/tModLoader#1831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

Simply having something that is Rarity 10 that is reforged into Legendary (`rare += 2`), can turn the rarity into 12, which is the first index of any `ModRarity` in any context. Either the rarity increase could be hard capped to 1, but that could cripple `ModPrefix`, so maybe make `ModRarity`s start indexing at `13`.

### Log File

Log not applicable.

### Steps to reproduce

[1] Get an item with a `rare` of `10`
[2] reforge it to legendary.

### Expected Behavior

The rare should be purple, not a `ModRarity`

### Actual Behavior

The rare is turning into the first `ModRarity` loaded.

### Reproduction frequency

100%

**Comment by Steviegt6** [comment]
It already *is* capped at 11 for any items without a `ModRarity`. This is a bug in the code, not a lack of a lack of a feature. Your proposal also accomplishes nothing.
We had it in place where any items without a modded rarity just cap at 11, and `ModRarity`s determine what comes before and after them using hooks. Forwarding the index would accomplish practically nothing.
