### ISSUE TITLE
[1.4] [Multiplayer] Wings flight not properly synced among clients

### ISSUE THREAD

**Issue by MoebiusMeow** [tModLoader/tModLoader#1832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

It seems that the in flight state is not synced properly during wings flight (it turned into a simple jump in other clients). 

### Steps to reproduce

1. In 1.4 alpha with no mod loaded
2. launch local server and clients
3. Use wings to take flight in one client

### Expected Behavior

The flight should be smooth in other clients

### Actual Behavior

The player glitches between distanced positions in other clients
(The local behavior looks like one simple jump and the player glitches to the synced position and back)

### Reproduction frequency

100%

**Comment by zzp198** [comment]
More precise question.
**wingLogic** and **wingTime** can't synchronize between client and server.
**controlJump** and **TryingToHoverDown** can synchronize normally.

**Comment by SofiAstat** [comment]
I just encountered this bug for the first time after the most recent update. So whatever had kept it from occurring so far seems to have been thoroughly rattled by the new update for me at least.
