### ISSUE TITLE
Inventory menu cannot be bound a mouse button

### ISSUE THREAD

**Issue by Zoshi** [tModLoader/tModLoader#1851]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

I use mouse4 to open my inventory in Vanilla Terraria without issue. This muscle memory causes a serious problem for me in Tmodloader, as it is no longer possible.

### Steps to reproduce

Open keybindings menu
Attempt to bind "Inventory" to a mouse button

### Expected Behavior

"Inventory" binds to the selected mouse key, as it does in Vanilla

### Actual Behavior

Inventory defaults to Escape

### Reproduction frequency

100%

### Additional Information

This also happens when binding the key manually in the config file. The game simply does not accept the mouse as a valid key for this one entry.

**Comment by Solxanich** [comment]
I can change the mouse button for mouse 4 to mouse 2, if I first unbind mouse 2 as mouse 2, so if you change Mouse4 to something else, I you can than bind mouse 4 to inventory.

In terms of a fix for this exclusivity of key binds, will look in to later, but this workaround should be sufficient for anyone looking for such capabilities

**Comment by Zoshi** [comment]
...Wait, I never noticed that. Why are there even binds that are labeled "mouse 4 and 5"? What do they even do? Google has NOTHING on the subject.
