### ISSUE TITLE
[1.4] Add a hook to builderAccStatus

### ISSUE THREAD

**Issue by zzp198-old** [tModLoader/tModLoader#1854]
### Is there an existing suggestion for this?

- [X] I have searched the existing issues

### Do you intend to personally contribute/program this feature?

Yes

### Description

![`U`RWKKW_CGRR2 IJX(X91](https://user-images.githubusercontent.com/43930552/133914489-ffbc4d66-41e6-4563-96e7-6e12756617bb.png)

This hook allows players to customize icons and click events, etc

### What does this proposal attempt to solve or improve?

A fast local player configuration switch.
Yes, but it's not necessary. It's just a proposal.

### Which (other) solutions should be considered?

Add a ModBuilder class, which rewrites index, draw, texture, position, etc

**Comment by JavidPack** [comment]
Sounds reasonable. If someone is attempting this, something similar to the implementation of the info display system would be a good guide to emulate. https://github.com/tModLoader/tModLoader/pull/1370
