### ISSUE TITLE
ModBiome bestiary entries broken

### ISSUE THREAD

**Issue by EpicCrownKing** [tModLoader/tModLoader#1855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

ModBiome bestiary entries are broken, specifically setting a custom background for NPCs

### Log File

N/A

### Steps to reproduce

just add a bestiary entry

### Expected Behavior

the custom background should be drawing

### Actual Behavior

it's not drawing

### Reproduction frequency

every time

### Additional Information

nope

**Comment by Solxanich** [comment]
For somebody's future reference later when go to fix, I believe background bestiary code is contained in: https://github.com/tModLoader/tModLoader/blob/1.4/patches/tModLoader/Terraria/GameContent/Bestiary/ModBiomeBestiaryInfoElement.cs

**Comment by JavidPack** [comment]
I've updated PartyZombie to show how to prioritize a specific biome background. I think this might have been the issue, since modders assumed it wasn't working before.
