### ISSUE TITLE
Server can't start headless

### ISSUE THREAD

**Issue by FreshDoktor** [tModLoader/tModLoader#1856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Linux

### Platform

Steam

### Description

If i try to start an Headless Server it throws following exeption
![grafik](https://user-images.githubusercontent.com/39657947/133936973-a0e085a9-6f6e-4c08-966e-588a5142a2b7.png)

I already reportet the bug on the Discord and only creating this ticket to make sure this is not forgotten
Discord Message: https://discord.com/channels/103110554649894912/871289059396448337/887433509235458108

### Log File

[server.log](https://github.com/tModLoader/tModLoader/files/7192594/server.log)
[client-crashlog.txt](https://github.com/tModLoader/tModLoader/files/7192595/client-crashlog.txt)

### Steps to reproduce

Start server directly with "dotnet tModLoader.dll -server"

Read Exception

### Expected Behavior

Server should start

### Actual Behavior

Server is not starting

### Reproduction frequency

Anytime

**Comment by Mirsario** [comment]
Addressed in recent commits. Please check if it still occurs.

**Comment by FreshDoktor** [comment]
It seems to work thanks!
