### ISSUE TITLE
Cannot download the Pumpking mod

### ISSUE THREAD

**Issue by trantinvan21087** [tModLoader/tModLoader#1869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest Official

### OS

Windows

### Platform

Steam

### Description

Cannot download the pumpking mod either on the mod browser or manually download it.

### Steps to reproduce

1. Download the Pumpking Mod

### Expected Behavior

the Pumpking Mod should be downloaded

### Actual Behavior

the Pumpking Mod isn't being downloaded and exit the back to the mod browser

### Reproduction frequency

Always

**Comment by JavidPack** [comment]
Please keep simple things like this to the discord chat. In any case, I might have fixed it for you.
