### ISSUE TITLE
Dedicated Server Crash

### ISSUE THREAD

**Issue by Skyibis** [tModLoader/tModLoader#1871]
https://pastebin.com/4YT7WNsV - Server Log Pastebin
[server.log download](https://github.com/tModLoader/tModLoader/files/7229981/server.log)

[Vienna.zip](https://github.com/tModLoader/tModLoader/files/7229982/Vienna.zip) - World File

Experienced a hard crash on the dedicated server upon trying to load up the world. I've tried loading it without any mods enabled whatsoever and still get the same crash, crash happened across all my worlds, freshly created or not.

**Comment by direwolf420** [comment]
Important to mention is that this log is from the `1.4_mergedtesting` branch, which is not updated regularly.

**Comment by Skyibis** [comment]
As direwolf mentioned, was somehow using an old executable from 1.4_mergedtesting. Fixed with updating files.
