### ISSUE TITLE
ModCommand collocation problem

### ISSUE THREAD

**Issue by zzp198** [tModLoader/tModLoader#1873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

Cannot find command when CommandType is Server.

When the CommandType is Chat|Server, the command can be found, but the Server is overwritten by Chat and cannot execute the command on the server.

Cannot find command when CommandType is world.

When the commandtype is Chat|World, the command can be found, but the World is overwritten by Chat and the command cannot be executed on the server.

### Expected Behavior

When the CommandType is Server, the command is executed by the server.

### Actual Behavior

The command will not be executed by the server in any case.

**Comment by Steviegt6** [comment]
I don't quite understand; are you attempting to make a command work on both the server and client, or are you trying to make a command that's run by a client and causes the server execute something?

**Comment by Steviegt6** [comment]
From my understanding, nearly all of tModLoader's enums are not made to function like flags. If what you want is to make a command executable on both the server and client, this is definitely a case where they should. For now, the solution would just be to make two different classes. You could just make a non-autoloaded class and register content manually by passing the command type to the constructor.

**Comment by zzp198** [comment]
As described by the CommandType.Server, the client inputs commands and the server executes them.

You only need to use the CommandType.Server type alone.

**Comment by zzp198** [comment]
> I don't quite understand; are you attempting to make a command work on both the server and client, or are you trying to make a command that's run by a client and causes the server to execute something?

 run by a client and causes the server to execute something
