### ISSUE TITLE
Item Prefix ID limit

### ISSUE THREAD

**Issue by Artdigy** [tModLoader/tModLoader#1875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest Official

### OS

Windows

### Platform

Steam

### Description

So I don't have much to say. Not many mods enabled, no other errors. Lots of weapon class mods I love that add prefixes and there's a bogus limit on how many prefixes a user can have. Would prefer it be removed.

### Steps to reproduce

Have a lot of weapon class mods and the classic thorium / calamity combo.

**Comment by Mirsario** [comment]
The prefix and many other limits are removed in 1.4. You can find the alpha for it on our discord/steam.
