### ISSUE TITLE
[1.4] Windows 'fullscreen' resolution not compatible with the "Go Windowed" button

### ISSUE THREAD

**Issue by Solxanich** [tModLoader/tModLoader#1889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

Currently, when one goes to "fullscreen" via the button in settings, this leads to the window being resized as windowed borderless-  ie it matches screen size.

However, the reverse direction of "Go Windowed" doesn't resize the window resolution back down, so one ends up with a window with no controls, despite having 'gone windowed'.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7280547/client.log)

**Comment by LuaLighter** [comment]
I have the same issue! I'm going to try and fix this rn.
