### ISSUE TITLE
Server cannot load mods for older version

### ISSUE THREAD

**Issue by neko-para** [tModLoader/tModLoader#1902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest Official

### OS

Linux

### Platform

Steam

### Description

I'm going to set up a dedicated server, but I'm stuck in loading mods.
I've just copy all mods from my client to the server, and got these message
```
An error occurred while loading Luiafk
It has been detected that this mod was built for tModLoader v0.10.1.5
However, you are using tModLoader v0.11.8.5
The mod(s) have been automatically disabled.

Could not resolve type with token 01000001
Could not resolve type with token 01000026
... many rows
```
As it says, do I really need the mods built for the TML which has exact the same version? My client can correctly load all these mods, so why server cannot do it?
I've checked that my client is also `v0.11.8.5`.
Is there any way to solve this? I'm not familier with compiling mods.

### Log File

[server.log](https://github.com/tModLoader/tModLoader/files/7321717/server.log)

### Steps to reproduce

1. Uploads all mods and one modpack json
2. Excute program as `./tModLoader -config serverconfig.txt`, while config is
```
maxplayers=2
port=7777
password=123
modpath=/home/steam/.local/share/Terraria/ModLoader/Mods
modpack=nal
```

### Expected Behavior

All mods should be loaded correctly.

### Actual Behavior

Mods that has mismatch versions are disabled.

**Comment by Hotmud9** [comment]
> 1. Calamity mod music is client only
> 2. Recipe Browser is client only afaik
Neither of these mods are client-sided. If a server you're joining has them enabled, you'll need them to be enabled too.
I've tried joining servers that don't have either of these mods enabled. It either bugged out in some way (I believe it was an infinite loading loop that's Mac-related) or forced a reload with the mods enabled.

**Comment by JavidPack** [comment]
Stale issue, reopen if issue persists. Seems to be a combination of a large number of bugs in mods to me.
