### ISSUE TITLE
Blue's Textures (and possibly other resource packs) breaks the game

### ISSUE THREAD

**Issue by emihead** [tModLoader/tModLoader#1913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

Whenever I try to load Blue's Textures, a popular resource pack, the UI begins to change size every frame alongside with the menu "back" sound playing. This softlocks me in the resource packs menu and forces me to close the game. This issue doesn't occur with any other resource packs I have but it's possible that it isn't specific to Blue's Textures.### 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7374792/client.log)

Log file of me opening the game with no mods loaded, navigating to the Resource Packs menu, and attempting to load Blue's Textures before closing the game.

### Steps to reproduce

1. Subscribe to Blue's Textures on the Steam Workshop: https://steamcommunity.com/sharedfiles/filedetails/?id=2493507652
2. Open the alpha.
3. Navigate to the "Load Resource Packs" menu.
4. Select Blue's Textures and press Back.

### Expected Behavior

Upon pressing Back the texture pack should be loaded as normal.

### Actual Behavior

The UI begins to change size every frame alongside with the menu "back" sound playing. I'm softlocked in the resource pack menu.

### Reproduction frequency

100% of the time.

### Additional Information

I have a 4k monitor, if that makes any difference.

**Comment by Solxanich** [comment]
Linking to #1612

**Comment by Chicken-Bones** [comment]
Tracking in duplicate, #1913
