### ISSUE TITLE
[1.4] TEFoodPlatter

### ISSUE THREAD

**Issue by HiKoNe** [tModLoader/tModLoader#1928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

When FoodPlatter is destroyed, TileEntity does not die

### Log File

NONE

### Steps to reproduce

1. Place Item: Food Platter
2. Break created Tile Food Platter
3. Checking for existing TEFoodPlatter in TileEntity.ByID or TileEntity.ByPosition

### Expected Behavior

TEFoodPlatter must die

### Actual Behavior

TEFoodPlatter not die

### Reproduction frequency

Always (100%)

**Comment by ExterminatorX99** [comment]
Fixed in 1.4.3.2
Verification needed for modded 1x1 TEs

**Comment by JavidPack** [comment]
Seems fixed for me, tested SP and MP. If modded TEs are exempt from this fix for some reason, we can reopen and investigate.
