### ISSUE TITLE
Multiplying Buckets

### ISSUE THREAD

**Issue by Mionikoi** [tModLoader/tModLoader#1932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Other (please specify elsewhere)

### OS

Windows

### Platform

Steam

### Description

Version 1.4.2.1 tmodLoder v0.12.1.4 Alpha 3fb60956, built 10/30/4:25pm

condition tested
started with 3 empty buckets

Action: hold down mouse on a body of water 
Result: buckets of water will multiply to 99 in inventory with 1 bucket in hot bar.
retested results after closing, opening, saving and exiting, and creating new world. Results are consistent with water.

### Steps to reproduce

1. 3 empty buckets in inventory
2. click on a body of water
3. hold until a stack of 99 is achieved + 1 in hotbar.

### Expected Behavior

1. Fill 3 empty buckets with water
2. Empty 3 buckets of water.
3. 3 buckets are always in inventory if space allows.

### Actual Behavior

So long as there is more than a single bucket the buckets of water will multiply until 99 are in inventory and 1 bucket is in hotbar. After the 99 stack is achieved the multiplication stops until a stack of 3 are in hot bar again.

### Reproduction frequency

Every time so long as 2 or more empty buckets are in the hotbar. one bucket will empty and fill normally. 2 or more buckets were tested and always multiply buckets of water. 

### Additional Information

No attempts with honey or Lava have been tested yet. World seed is 3.3.1.1323050566, Master, large, corruption. Created September 5, 2021

**Comment by Ishigh1** [comment]
There is no info on the enabled mods, usually this is caused by Max Stack Plus

**Comment by Chicken-Bones** [comment]
You must give us a log file. Please come to the discord if you don't know how to do that.

**Comment by ExterminatorX99** [comment]
Tested with only Cheat Sheet enabled

https://user-images.githubusercontent.com/16169502/141526099-a88541f4-5e81-4f7c-b852-671033e782f1.mp4

https://user-images.githubusercontent.com/16169502/141526396-89f8e677-eef0-4eff-aedf-ed7cabb4e225.mp4

https://user-images.githubusercontent.com/16169502/141528843-dc12c9e1-622a-4030-b047-1041c868d4c9.mp4

**Comment by esotericist** [comment]
for what it's worth, i experienced this last week, but i'm no longer able to duplicate the problem since the 1.4.3.2 patch integration. it's possible this has been resolved?

edit: i stand corrected. it started happening again later in a session. weird.
