### ISSUE TITLE
[1.4]hidden by taskbar[windows11]

### ISSUE THREAD

**Issue by moe41** [tModLoader/tModLoader#1940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows11

### Platform

Steam

### Description

when display mode:1366×768 100%(from windows settings>system>display),bottom of window is hidden by taskbar.
(resolution:1366×720)i can't push maximize button.
![無題](https://user-images.githubusercontent.com/66813644/140630917-965a4f0a-6016-49d0-b472-b31bf504dec7.png)
comparison:from vanilla terraria,resolution:1366×696(the same display mode and miximized window)
![無題2](https://user-images.githubusercontent.com/66813644/140631022-c5c16f6a-f662-4f1e-b096-a33fe603e750.png)

**Comment by moe41** [comment]
when open inventory, "settings" is hidden by taskbar.
![無題](https://user-images.githubusercontent.com/66813644/140648475-2c493707-a957-440e-9b37-82301c545efe.png)

**Comment by moe41** [comment]
![無題](https://user-images.githubusercontent.com/66813644/142625985-e8cba1e8-be88-48f5-b254-8d56c1efbea9.png)
latest version, social media buttons are hidden by taskbar.

**Comment by inikishev** [comment]
temporarily you can edit game config to make UI scale smaller

**Comment by moe41** [comment]
in config.json(from "C:\Users\(username)\Documents\My Games\Terraria\ModLoader\Beta\"),i tried to edit
from "DisplayHeight": 720, to "DisplayHeight": 696
but returned "DisplayHeight": 720

**Comment by inikishev** [comment]
> in config.json(from "C:\Users(username)\Documents\My Games\Terraria\ModLoader\Beta"),i tried to edit from "DisplayHeight": 720, to "DisplayHeight": 696 but returned "DisplayHeight": 720

edit the UI scale setting instead, idk what the name is

**Comment by moe41** [comment]
UI scale? where?
manual window sizing?

**Comment by inikishev** [comment]
> UI scale? where? manual window sizing?

ni its called ui scale. Search for uiscale or something like that

**Comment by moe41** [comment]
![無題](https://user-images.githubusercontent.com/66813644/154858960-0774ed35-f0bf-4df4-aed3-183d7dbc7497.png)

**Comment by moe41** [comment]
[03:47:01] [Main Thread/DEBUG] [Terraria]: Device Reset, Adapter: LCD 1920x1080, DisplayMode: {{Width:1366 Height:768 Format:Color}}, Profile: Reach, Width: 1366, Height: 720 -> 697, Fullscreen: False, Display: \\.\DISPLAY1
[03:47:01] [Main Thread/DEBUG] [Terraria]: Device Reset, Adapter: LCD 1920x1080, DisplayMode: {{Width:1366 Height:768 Format:Color}}, Profile: Reach, Width: 1366, Height: 697 -> 720, Fullscreen: False, Display: \\.\DISPLAY1
