### ISSUE TITLE
Deleting a mod from the workshop twice causes a crash

### ISSUE THREAD

**Issue by Truhard** [tModLoader/tModLoader#1943]
### Is there an existing issue for this?

- I have searched the existing issues

### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

If you download a mod from the browser, then go back to the browser, reselect the mod, click delete on the downloaded mod from the browser, then select it again and click delete again, the game crashes. 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/7500948/client.log)

### Steps to reproduce

1. Open workshop
2. Install any mod
3. Delete it
4. Reselect it
5. Delete it again
6. Profit :(

### Additional Information

AMD RX 5700 graphics card

**Comment by Solxanich** [comment]
@Truhard - this issue should be resolved.
Please close if it is the case
