### ISSUE TITLE
ItemFrame does not preserve custom data

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#207]
ItemFrame does not preserve custom data (GlobalItem/ModItem)

We'll have to fix the code.

**Comment by Jofairden** [comment]
Better to wait for 1.3.6 now. Yoraiz0r said the code for item frames and mannequins improved.

**Comment by Jofairden** [comment]
Read my previous comment.. lol
There is no need to confirm anything here. It's been known since the beginning of time, really. Just wait for the update.

**Comment by AngelAnima** [comment]
> Also note, I received this error message while troubleshooting, but I'm unsure if it's related:
> 
> ![error](https://camo.githubusercontent.com/aee2a55bf3170f803c9d74f0ff32b9e45802a4ec/68747470733a2f2f692e696d6775722e636f6d2f58566468594b552e706e67)

I can confirm that that error was likely terraria rendering light beyond the map.

**Comment by Mirsario** [comment]
12cd989, woo
