### ISSUE TITLE
WorldGen.Chlorophyte bug

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#217]
"WorldGen.Chlorophyte only checks the x coordinate is inside the world, so if mud is too low down it throws exceptions when it counts how many chlorophyte are nearby"

(This is likely a vanilla bug too.)

**Comment by Jofairden** [comment]
Just for reference, I think I recall yorai saying it's a vanilla bug.

**Comment by Jofairden** [comment]
Should be fixed in 1.4 by Yorai 👍
