### ISSUE TITLE
AltFunctionUse (right click) causing a tick of delay between consecutive uses

### ISSUE THREAD

**Issue by hollowstrawberry** [tModLoader/tModLoader#271]
### Description

With a weapon's right-click use, there is a single tick of pause between consecutive uses, where the hand returns to resting position. At lower use speeds this makes the hand appear to glitch out, moving back and forth rapidly. Normally, with left click, the hand just stays out as long as the weapon is in use.

### Steps to Reproduce

1. Create a weapon with `override bool AltFunctionUse(Player player) ` returning true, and `item.autoReuse `set to true in `SetDefaults()`.
2. Run the game with the modded weapon active.
3. Select the weapon and hold Right Click.

### Expected behavior 

There is 1 frame where nothing happens between uses of the weapon, the hand moving back to resting position and then back to the use animation.

### Actual behavior

The hand should stay out, as left click does, and no delay should occur between uses.

### Reproduction frequency

Every time, with any standard weapon with an altFunctionUse. This is most noticeable with useStyles 3 and 5, however.

### Versions

tModLoader v0.10.1

### Additional Information

It appears that this happens because the alternate function code is called near the end of the player update method, and there's the check `if (this.itemAnimation == 0 || PlayerInput.Triggers.JustPressed.MouseRight)`, the logical conclusion being that the code for using the weapon doesn't run unless the player has already stopped swinging, causing the 1 tick of pause.

**Comment by Jofairden** [comment]
Uhm, isn't this a vanilla thing? I'm fairly sure this is done due to certain alternate fire needing it, as vanilla behaviour is intended for specific purposes.

**Comment by Samrux** [comment]
It might be from vanilla, but there are reasons to fix it in future versions of tModLoader. It _looks_ very glitchy, and there is currently no fix for a behavior that is, by all means, unintended, for anyone that wants to give their weapons a smooth alternate use.

**Comment by Jofairden** [comment]
This is a vanilla bug (forwarded to Yoraiz0r), but very low priority for a fix. How does it look very glitchy to you? How much FPS do you have? With my game running stable, this is barely noticeable (if at all if you're not actively looking for it)

**Comment by Samrux** [comment]
I have a stable 60 FPS. The lower the useAnimation of the weapon, the more the hand appears to vibrate rapidly by coming back to the resting position; this is more obvious with useStyles 3 or 5 as the hand would normally stay out in the same place during the animation. With frame skip turned off and an item below useAnimation 20, I find it becomes quite obvious that the hand is moving back and forth every use. Below useAnimation 8, the hand starts to seemingly glitch back and forth from the effect of there being a delay between every consecutive use.
I don't understand the suggestion of setting itemAnimation to 0, as weapons have never seemed to work at all at values below 2.
Also, thanks a lot for replying and forwarding it to the Terraria team!

**Comment by Jofairden** [comment]
itemAnimation is not item.useTime or item.useAnimation
player.itemAnimation is a different thing here, which you showcased yourself is check to be 0 to continue, hence try setting it to 0 when it reaches 1 to attempt avoiding the 1 tick delay.

**Comment by Samrux** [comment]
Ah, you meant player.itemAnimation, sorry!

It's a good idea to try setting it to 0, but sadly it didn't work in either ModItem.CanUseItem, ModPlayer.PreUpdate or ModPlayer.PostUpdate.

However, I got the following to work inside CanUseItem! It's a little hacky but it got the job done.
`if (player.altFuctionUse == 2)
{
    if (player.itemAnimation == 1) //Doesn't let the hand return to resting position
    {
        player.altFunctionUse = 1;
        player.controlUseItem = true;
    }

    if (PlayerInput.Triggers.JustReleased.MouseRight) //Stops the animation manually
    {
        player.altFunctionUse = 0;
        player.controlUseItem = false;
        return false;
    }
}`

if there's nothing else to be said, should we close the issue?

**Comment by Jofairden** [comment]
I suppose it might be best to keep the issue open so possible workarounds are more visible. Again to anyone reading, the vanilla issue is forwarded but it's unlikely to see a fix anytime soon.

**Comment by Chicken-Bones** [comment]
This was probably fixed by #2351 and related issues
