### ISSUE TITLE
Freeze attempting to load resources (Linux)

### ISSUE THREAD

**Issue by kennethdhau** [tModLoader/tModLoader#299]
### Description

Terraria freezes while loading resources from mods.

### Steps to Reproduce

1. Attempt to start Terraria (note - Terraria.exe is symlinked to Terraria_tmodloader.exe)

### Expected behavior 

Expected program to continue beyond starting phase.

### Actual behavior

Attempts to load mods (note detail under _Mods_ section), then program stalls, consuming max. CPU.  _strace_ indicates frequent request for unavailable resource.

Screen indicates "Initializing: <mod name>" and "Finishing Resource Loading"

### Reproduction frequency

Failure present 100% of attempts. (4/4 attempts)

### Versions

0.10.1.2

### Mods

Currently attempted with various combinations of mods.  Note -- some mods fail due to being compiled for incorrect version of tModLoader. Will attempt to provide more conclusive list time-permitting.

### Additional Information

Currently, Terraria.exe is symlinked to Terraria_tmodloader.exe.
Linux installation:
    Linux 4.15.3-2 (Arch) 64-bit
    Intel HD Graphics 530 (xf86-video-intel)
    NVIDIA M2000M (nvidia 390.25) [set to run on discrete graphics via primusrun (bumblebee)]

Willing to submit additional hardware/software specs as well as _lsof_ and _strace_ data per request.

**Comment by Jofairden** [comment]
I think this is an issue on both Linux and Mac introduced to changed made to resources by @chicken bones

**Comment by curz46** [comment]
I'm also experiencing this issue on the same distro.

**Comment by Chicken-Bones** [comment]
I will investigate this today, I have a Ubuntu 16 machine

**Comment by kennethdhau** [comment]
Just an update, I was able to successfully procede beyond the loading screen twice (out of 4 additional tries).  However, attempting to reload after changing a mod from _Disabled_ to _Enabled_ caused the process to crash. The mod was compiled for the incorrect version and immediately before crashing, I attempted to select "Continue" on the notification.

**Comment by PoroCYon** [comment]
kennethdhau: That's a problem with the mod then, try  replicating the issue *without* using broken mods.

**Comment by kennethdhau** [comment]
@PoroCYon wouldn't it be problematic if a broken mod could cause crashes?

I'll disable them via 10.1 and try again using 10.2.

**Comment by kennethdhau** [comment]
Of two attempts, one crashes while one stalls as described in the initial report.  The only mod enabled was _Thorium_ which did not raise warnings about an incompatible build.

**Comment by PoroCYon** [comment]
Yes, broken mods are problematic, but it's the *modder*'s fault, not the tModLoader devs'.

**Comment by Chicken-Bones** [comment]
I managed to get a dev environment setup on Ubuntu with Rider and Mono 5.8.0 on which I noticed zero issues. However when I ran through the pre-packaged mono kickstart, I experienced a variety of crashes and stalls, one of which I fixed in 40cb7e17ef72179c417086808ad501987e585e63
I didn't experience the exact stall here, and that commit *may* help but I wouldn't count on much.

My official recommendation is that we ship a non-archaic version of Mono with tModLoader, because seriously.

**Comment by kennethdhau** [comment]
I'm not familiar with the interconnect between Mono and tModLoader and Terraria. What would that entail?

**Comment by PoroCYon** [comment]
kennethdhau: vanilla Terraria ships with its own Mono runtime, packed in something called [MonoKickstart](https://github.com/flibitijibibo/MonoKickstart). Problem is, the version of Mono embedded within this is *old*, causing various problems.

Instead, tModLoader should use the normal Mono installed on one's machine. [Prism already did this](https://github.com/TerrariaPrismTeam/Prism/blob/develop/Prism.sh), so feel free to copy the code, Chicken-Bones.

**Comment by Chicken-Bones** [comment]
@kennethdhau We'll get back to you on this shortly, we're looking into shipping a newer Mono version and also allowing people to run their own (without kickstart).

**Comment by kennethdhau** [comment]
Did that appear in the latest release? Also, looks pretty solved in 10.3. I'll keep an eye out for crashes in the meantime.

**Comment by wanybae** [comment]
Is this same issue #208 ?

**Comment by Chicken-Bones** [comment]
This should all be fixed in beta 6, and the upcoming 0.11 release. Please test for us and re-open if it occurs again
