### ISSUE TITLE
Prevent ModItem from accepting a prefix

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#388]
Attempting to prevent any prefix from applying to an item via
`		public override int ChoosePrefix(UnifiedRandom rand)
		{
			return 0;
		}`
causes some issues. It correctly prevents a prefix on crafting the item, but it will crash when placed in Goblin Tinkerer. I think the issue is the item shouldn't return true when item.prefix(-3) is called, but since we don't the code assumes it needs to continue to try for a non 0 prefix when item.prefix(-2) is called. Since ChoosePrefix is random, the computer can't know if it is always suppose to return 0 or if it is just random. (returning 0 some of the time would be a normal thing to do, but the -3 call forces the process to repeat until a valid non-0 prefix is rolled.) I think the solution is just a property or hook for CanHavePrefix or something and make sure to return false if prefix(-3) is called.

Reminder: 
Prefix(-1): 75% chance roll prefix. OnCraft
Prefix(-2): Roll non-0 prefix. Goblin Tinkerer
Prefix(-3): return true if item can be prefixed
Prefix(0+): Assign specified prefix

**Comment by Jofairden** [comment]
Well, shouldn't we just check if it returns 0? If it does, do not roll. (0 if empty prefix)
And -1 is vanilla behaviour.

**Comment by JavidPack** [comment]
The problem is I think ChoosePrefix returning 0 sometimes is a valid thing to do in a mod. Imagine you want your item to be 10x more likely to be crafted (-1) without a prefix, you can return 0 90% of the time and -1 the other 10%. This would still work with tinkerer (-2) but not reliably with the tinkerers slot (-3). I guess you can say this is an example of the halting problem.

We don't know if the 0 return represents "never give this item a prefix" or "this roll for prefix resulted in 0....but it could still roll something else if you try again."

I think we also discussed before allowing ModItems to manually specify which Prefix set they want to use. Currently we use some item fields to guess, but that might not work for all mods.

**Comment by direwolf420** [comment]
Bumping because of frequent requests in the discord. More example uses:
preserving the rarity color on an item
wiping all other modded prefixes on an item without any vanilla damage types

**Comment by GoodPro712** [comment]
could this get closed now?
