### ISSUE TITLE
Download mods from other places instead of the game server

### ISSUE THREAD

**Issue by AxeelAnder** [tModLoader/tModLoader#416]
Download some huge mods like CalamityMod when syncing mods with the server would use much bandwidth of server. If clients can download from a url sent by server, it will benefit both sides

**Comment by Chicken-Bones** [comment]
I think this is a reasonable idea to be honest, we'll look into it

**Comment by AxeelAnder** [comment]
The original post would be somewhat confusing. here's what I mean: server can send URLs of mods when syncing them with clients.Thus, clients can download mods directly from links given by server, which saves a lot of bandwidth.

**Comment by JavidPack** [comment]
We should also consider allowing a server to prevent downloading from the server.

For downloading from Mod Browser when joining a server, maybe we should prompt for user input if downloading is allowed (or some file size criteria). Otherwise just open Mod Browser with mod name filter.

**Comment by Chicken-Bones** [comment]
The main problem with this is if the server isn't using the latest version on the mod browser then the client will have no way of obtaining the correct version. This means a mod updating could spontaneously break the ability for new players to joint the server

**Comment by Chicken-Bones** [comment]
I think we need to change this to just a way for a server to prevent auto-downloading, and then to show an informative UI of what mods and versions the player needs to get. Possibly the server could allow auto-downloading below a certain threshold.

This will be low priority unless it gets more votes (thumbs up this comment)

**Comment by Jofairden** [comment]
I agree, chicken-bones. We simply have the issue that the mod- browser doesn't really store history of mod releases, does it? If it did, it would be easier.

**Comment by Jofairden** [comment]
Closing for now; not really possible. However, SW support likely coming soon. Would be a new source.
