### ISSUE TITLE
Patreon link in the main menu sometimes works from other windows

### ISSUE THREAD

**Issue by Tyfyter** [tModLoader/tModLoader#446]
### Description
The patreon link in the main menu works regardless of what window you clicked on.

### Steps to Reproduce

1. open terraria (obviously with tmodloader).
2. open another window and have it in front of terraria.
3. click where the link is in the terraria window in a different window.

### Expected behavior 
Absolutely nothing, the window isn't even in focus.

### Actual behavior
The link is opened.

### Reproduction frequency
I haven't been able to intentionally reproduce this issue, but it happens somewhat frequently when I'm not trying to reproduce it.

### Versions
0.10.1.5

**Comment by Chicken-Bones** [comment]
I saw this happen once but couldn't replicate it either. Unfortunately sometimes doesn't let us fix it.

**Comment by Chicken-Bones** [comment]
Platform non-windows?

**Comment by Jofairden** [comment]
I can't reproduce this on windows.

**Comment by JavidPack** [comment]
Reproduced. We needed to never focus tmodloader to trigger it (and as such, not launch from visual studio)

IsActive is mistakenly true in this situation, so hasFocus was the fix.
