### ISSUE TITLE
Left handed mode

### ISSUE THREAD

**Issue by NLZ** [tModLoader/tModLoader#450]
I'd like to request a feature to swap the Left and Right mouse buttons.
RomSteady said that it's a relatively simple thing to patch, and even implemented it in RomTerraria 4, but he didn't ported this function over to 1.3.5 so it wasn't merged into tModLoader when he quit Terraria.
Would anyone be willing to make it?

https://www.reddit.com/r/Terraria/comments/3bpjuu/as_a_lefthanded_player_im_still_a_bit_upset_you/csoar4q/
https://romsteady.blogspot.com/2015/09/romterraria-4-v09-released.html

**Comment by Jofairden** [comment]
In the next version, we have the functionality of modifying methods native to vanilla. (0xade and chicken-bones know more about this). This means you could make the edit in your mod that reverses the mouse clicks.

**Comment by thesuzerain** [comment]
^ out of curiosity, with the vanilla method editing functionality, how extensive will this be? For example, would it be possible to edit the UI + options (such as small, medium, large) before world gen? (An example mod for this would be a mod to force Crimson on a given world). 

Thanks!

**Comment by Chicken-Bones** [comment]
Of course, I mean once you beat the game there's already a Crimson/Corruption selection option but you could always just override the check and force the menu

**Comment by thesuzerain** [comment]
Right, it was just the first thing that I thought of. I guess a better example would have been making an additional world size. I was more just asking about the method overriding part. This is awesome though- thanks!

**Comment by Chicken-Bones** [comment]
I believe we currently have an example that makes the slime statue spawn lava slimes
