### ISSUE TITLE
GetPrototypeItem Item Cache

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#474]
For modders to easily query Item default values. Make sure to reset after loading mods. IsVanitySet could also benefit.

**Comment by Jofairden** [comment]
What if we store an item cache, you can get one by ID and then grab an instance of it
e.g. `GetCachedItem(ItemID.WoodenSword)`
We clear the cache after mods are loaded

**Comment by GoodPro712** [comment]
are contributions welcome?

**Comment by Jofairden** [comment]
> 
> 
> are contributions welcome?

They're always welcome

**Comment by Jofairden** [comment]
1.4 will have something similar to this, we should see if we can expand it if needed.

**Comment by direwolf420** [comment]
Yep, there is now a ContentSamples class that contains cached item, npc etc. instances. In the current state of 1.4, it also supports modded content.
