### ISSUE TITLE
Multiplayer hosting crashes the game on Linux

### ISSUE THREAD

**Issue by jvschiavo** [tModLoader/tModLoader#491]
### Description
When I try to start a multiplayer server from Linux with tModLoader the game crashes.

### Steps to Reproduce
1. Simply install tModLoader stable (v0.10.1.5) copying the files over to the ~/.steam/steam/steamapps/common/Terraria folder.
2. Open Terraria from Steam.
3. Click Multiplayer > Host & Play > (on your char) Play > (on your world) Play
(don't even need to install any mod yet).

Sever Settings:
Steam Multiplayer: Enabled
Allowed Users: Friends
Allow Friends Of Friends: Off

4. Click Start then Accept (doesn't matter if you put a password)
5. Game crashes

### Expected behavior 
Game should start with server hosted

### Actual behavior
Game crashes and I have to reopen it. But I can't play multiplayer with tModLoader. With Vanilla Terraria I can play normally together with a friend.

### Reproduction frequency
100% of times

### Versions
Terraria v1.3.5.2
tModLoader v0.10.1.5

### Mods
None. Doesn't matter.

### Additional Information
My friend tested with v0.11 too and the same happened. He then hosted vanilla Terraria and I could join normally.

**Comment by VitinhoCarneiro** [comment]
Can confirm, the issue happens with v0.11 Beta 1 as well.

The issue is only apparent when hosting a server - joining other servers works just fine. But hosting servers only seems to work under Windows.

Hosting servers with vanilla Terraria under GNU/Linux is indeed working fine - the issue only appears with tModLoader installed.

**Comment by jvschiavo** [comment]
Just tested with v0.11 beta 1 and the same happens.

**Comment by JavidPack** [comment]
Can you show us the error? Can you launch the server manually so we can see the output? We need more info because 0.10.1.5 server has worked on linux for the past 6 months from what we have heard.

**Comment by VitinhoCarneiro** [comment]
tModLoaderServer exits with no output in the terminal; tried launching it from both the sh script and directly launching the executable.

When trying to launch the server, this is the output given in the client-crashlog.txt:

```2/7/2019 2:17:15 PM
System.TypeInitializationException: The type initializer for 'System.Console' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.ConsoleDriver' threw an exception. ---> System.Exception: Magic number is wrong: 542
  at System.TermInfoReader.ReadHeader (System.Byte[] buffer, System.Int32& position) [0x0002b] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.TermInfoReader..ctor (System.String term, System.String filename) [0x00065] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.TermInfoDriver..ctor (System.String term) [0x00058] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.ConsoleDriver.CreateTermInfoDriver (System.String term) [0x00000] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.ConsoleDriver..cctor () [0x00062] in <1170fb08300b4d0db71c1d1db8555768>:0 
   --- End of inner exception stack trace ---
  at System.Console.SetupStreams (System.Text.Encoding inputEncoding, System.Text.Encoding outputEncoding) [0x0000a] in <1170fb08300b4d0db71c1d1db8555768>:0 
  at System.Console..cctor () [0x000a8] in <1170fb08300b4d0db71c1d1db8555768>:0 
   --- End of inner exception stack trace ---
  at Terraria.Main.DedServ () [0x00051] in <5b18054a85ea45ef82cf3fe4603df1f5>:0 
  at Terraria.Program.LaunchGame_ () [0x00090] in <5b18054a85ea45ef82cf3fe4603df1f5>:0 ```

**Comment by VitinhoCarneiro** [comment]
I have discovered the problem.

When installing the mod manually (by copying the files over to the Terraria folder), you must give execution permission to the tModLoaderServer script and executables, since these are not given due to the files being extracted from a ZIP. Else, the server will fail to launch.

By doing `chmod +x tModLoaderServer*`, the issue is resolved.

**Comment by jvschiavo** [comment]
> I have discovered the problem.
> 
> When installing the mod manually (by copying the files over to the Terraria folder), you must give execution permission to the tModLoaderServer script and executables, since these are not given due to the files being extracted from a ZIP. Else, the server will fail to launch.
> 
> By doing `chmod +x tModLoaderServer*` inside the Terraria folder, the issue is resolved. It'd be a good idea to put a notice in the installation notes about this.

Maybe by installing with the jar this doesn't happen?

I did the manual install because I didn't want to install Java.

**Comment by jvschiavo** [comment]
Hey, I suggest a solution. Instead of packing it in .zip, you guys should distribute the Linux version of tModLoader inside tarballs (.tar/.tar.gz). That way you can grant execution permissions to the correct files beforehand and it will work.

**Comment by Chicken-Bones** [comment]
I'll upvote that. If you're using linux surely you can extract a tar.gz (or we could provide the terminal command for extract)

**Comment by heav-4** [comment]
installed using a jar here, same issue. will try chmod +x tModLoaderServer
