### ISSUE TITLE
Deleting input profiles.json with mods active crashes game

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#492]
It seems like the keys aren't generated when a new input profiles json file is generated.

**Comment by Jofairden** [comment]
How do you trigger this?
I am not able to reproduce the issue. I deleted input profiles.json several times in game, with some mods enabled, but everytime I open the menu it regenerates itself.

**Comment by wooden-utensil** [comment]
Maybe inside the running game? When the game is running, maybe delete `profiles.json`?

**Comment by Jofairden** [comment]
That's what I did, as I mentioned I deleted them in game and was not able to reproduce the issue.

**Comment by wooden-utensil** [comment]
Any more information @JavidPack ? Do you mean while reloading or something?

**Comment by JavidPack** [comment]
I'll check this again sometime.
