### ISSUE TITLE
OSX system cursor is not hidden when running system mono

### ISSUE THREAD

**Issue by Chicken-Bones** [tModLoader/tModLoader#513]
Known issue, when running Mono 5.20 on Mac, the system cursor is visible over the ingame one in windowed mode. Possibly related to the lack of correct icon and the fact the process displays as "mono". May need to investigate mac app logic.

**Comment by Mirsario** [comment]
Mono & .NET Framework have now been replaced with .NET 5+ on all platforms in TML for 1.4.
