### ISSUE TITLE
"An error occured while loading ModLoader"

### ISSUE THREAD

**Issue by dim20** [tModLoader/tModLoader#544]
After installing the Linux version of tModLoader on Linux the game boots fine but I am greeted with an error. Everything is up to date and I'm not quite sure what is causing this or why its happening.

I use Solus Budgie for what its worth though I doubt it has much to do with it.

![image](https://user-images.githubusercontent.com/50924414/58195074-c9f71b00-7ccf-11e9-9ff6-a5af61d4f1e5.png)

**Comment by dim20** [comment]
UPDATE: So after a bit of fiddling around, just 30 minutes after discovering the issue. I managed to get my game to work by disabling the linux native runtime from Linux Steam Intergration. Hope someone finds this useful!

**Comment by Itamiko** [comment]
same had to disable native run-time from Linux steam integration as well
