### ISSUE TITLE
GoG doesn't work on Mac/Linux (awaiting hashes)

### ISSUE THREAD

**Issue by mindbound** [tModLoader/tModLoader#554]
After manually installing (it appears that the installer JAR isn't yet updated for GOG-based installation) v0.11 Beta 6 with Terraria 1.3.5.3 (GOG 2.17.0.20) on Arch Linux x86_64, starting the game (via `start.sh`) fails with

> Running Terraria
> [17:01:31] [1/INFO] [tML]: Starting tModLoader v0.11 Beta 6l client
> [17:01:31] [1/INFO] [tML]: Running on Mono 4.6.1
> [17:01:31] [1/INFO] [tML]: Executable: /home/mindbound/Games/Terraria/game/tModLoader.exe
> [17:01:31] [1/INFO] [tML]: Working Directory: /home/mindbound/Games/Terraria/game
> [17:01:31] [1/INFO] [tML]: Launch Parameters: 
> [17:01:31] [1/DEBUG] [tML]: Assembly Resolve: Terraria, Version=1.3.5.1, Culture=neutral, PublicKeyToken=null -> MonoMod.RuntimeDetour, Version=19.5.19.1, Culture=neutral, PublicKeyToken=null
> [17:01:31] [1/DEBUG] [tML]: Assembly Resolve: Terraria, Version=1.3.5.1, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=19.5.19.1, Culture=neutral, PublicKeyToken=null
> [17:01:31] [1/WARN] [tML]: First-chance exception reporting is not implemented on Mono
> [17:01:32] [1/DEBUG] [tML]: Assembly Resolve: Terraria, Version=1.3.5.1, Culture=neutral, PublicKeyToken=null -> Steamworks.NET, Version=9.1.0.0, Culture=neutral, PublicKeyToken=null
> [17:01:32] [1/DEBUG] [tML]: Assembly Resolve: System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 -> Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> [17:01:32] [1/DEBUG] [tML]: Assembly Resolve: System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 -> Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> [17:01:32] [1/FATAL] [Terraria]: Main engine crash
> System.DllNotFoundException: CSteamworks
>   at (wrapper managed-to-native) Steamworks.NativeMethods:SteamAPI_RestartAppIfNecessary (AppId_t)
>   at Steamworks.SteamAPI.RestartAppIfNecessary (AppId_t unOwnAppID) [0x00005] in data-0x373bbb0 
>   at Terraria.Social.Steam.CoreSocialModule.Initialize () [0x00010] in tModLoader.exe 
>   at Terraria.Social.SocialAPI.Initialize (Nullable[T] mode) [0x00057] in tModLoader.exe 
>   at Terraria.Program.LaunchGame_ () [0x0005f] in tModLoader.exe

If I understand it correctly, then v0.11 Beta 6 should be able to run using GOG installation of the game. Please advise.

**Comment by JavidPack** [comment]
Ah, I'll make it clear here on the release page that GOG is Windows only for now. Sorry about the confusion. 

We'll support Linux and Mac once we have some testers on the discord help us out with those.

**Comment by mindbound** [comment]
@JavidPack Thank you! I'll wait until that's supported, then.

**Comment by Chicken-Bones** [comment]
Come talk to me on Discord! We just need the md5 and length of vanilla GoG on Mac, as well as a list of files in the Terraria bin folder

**Comment by mindbound** [comment]
@Chicken-Bones I can provide the same for Linux. Would you be interested in that?

**Comment by Chicken-Bones** [comment]
Absolutely

**Comment by Chicken-Bones** [comment]
Going to reopen this while we wait for mac hash. Also I have a linux build for you to test @mindbound

**Comment by mindbound** [comment]
@Chicken-Bones I can confirm that the Linux build starts and runs a new game without issues. I did, however, have issues while downloading mods from the server:

> [03:00:05] [Threadpool worker/INFO] [tML]: Instantiating Mods...
> [03:00:05] [Threadpool worker/INFO] [tML]: Initializing: ModLoader v0.11
> [03:00:06] [Threadpool worker/INFO] [tML]: Setting up...
> [03:00:07] [Threadpool worker/INFO] [tML]: Loading: ModLoader v0.11
> [03:00:07] [Threadpool worker/INFO] [tML]: Adding Recipes...
> [03:00:15] [Threadpool worker/INFO] [tML]: DownloadManager handling new download
> [03:00:15] [Threadpool worker/WARN] [tML]: A download errored
> System.AggregateException: One or more errors occurred. ---> System.NotImplementedException: The method or operation is not implemented.
>   at System.Net.ServicePoint.set_ReceiveBufferSize (Int32 value) [0x00005] in System.dll 
>   at Terraria.ModLoader.UI.DownloadManager.HttpDownloadRequest.Execute () [0x00038] in tModLoader.exe 
>   at Terraria.ModLoader.UI.DownloadManager.DownloadRequest+<>c__DisplayClass28_0.<Start>b__0 () [0x00000] in tModLoader.exe 
>   at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in mscorlib.dll 
>   at System.Threading.Tasks.Task.Execute () [0x00016] in mscorlib.dll 
>    --- End of inner exception stack trace ---
>   at System.Threading.Tasks.Task.ThrowIfExceptional (Boolean includeTaskCanceledExceptions) [0x00014] in mscorlib.dll 
>   at System.Threading.Tasks.Task.Wait (Int32 millisecondsTimeout, CancellationToken cancellationToken) [0x00052] in mscorlib.dll 
>   at System.Threading.Tasks.Task.Wait () [0x00000] in mscorlib.dll 
>   at Terraria.ModLoader.UI.DownloadManager.UIDownloadManager.DispatchWorkersFromQueue () [0x0005e] in tModLoader.exe 
> ---> (Inner Exception #0) System.NotImplementedException: The method or operation is not implemented.
>   at System.Net.ServicePoint.set_ReceiveBufferSize (Int32 value) [0x00005] in System.dll 
>   at Terraria.ModLoader.UI.DownloadManager.HttpDownloadRequest.Execute () [0x00038] in tModLoader.exe 
>   at Terraria.ModLoader.UI.DownloadManager.DownloadRequest+<>c__DisplayClass28_0.<Start>b__0 () [0x00000] in tModLoader.exe 
>   at System.Threading.Tasks.Task.InnerInvoke () [0x00012] in mscorlib.dll 
>   at System.Threading.Tasks.Task.Execute () [0x00016] in mscorlib.dll <---

Are these to be expected at this stage of the 0.11 beta?

**Comment by Chicken-Bones** [comment]
New issue and full log please

**Comment by mindbound** [comment]
Done.

**Comment by Jofairden** [comment]
Related issue can be found here #556 
I assume this can be closed now, but feel free to re-open.

**Comment by Chicken-Bones** [comment]
Need Mac hashes

**Comment by bin-cat** [comment]
[Gist](https://gist.github.com/bin-cat/a590a78c774e8e370fe01b9f47bf19ab) with sizes and hashes for executables of GOG 1.3.5.3 for Mac. It's actually possible to get them without Mac just by digging through offline installer for Mac version with 7-zip, extracted files will be the same with the ones that are installed.

**Comment by Chicken-Bones** [comment]
@bin-cat can you send me the mac hash?

**Comment by mindbound** [comment]
@Chicken-Bones I think it's in the gist link in the previous comment, https://gist.github.com/bin-cat/a590a78c774e8e370fe01b9f47bf19ab

**Comment by Chicken-Bones** [comment]
https://github.com/tModLoader/tModLoader/commit/640729fd9b34e7731d8c4bebcae5b710cbe44f64 Thanks!
