### ISSUE TITLE
Can't download from mod browser

### ISSUE THREAD

**Issue by mindbound** [tModLoader/tModLoader#556]
Using Terraria Linux x86_64 GoG installation and tML v0.11 Beta 6 Linux build provided by @Chicken-Bones, I am unable to download any mods from the mod browser. It fails silently with a `System.NotImplementedException`. Please see the attached log file for full detail.

[client.log](https://github.com/blushiemagic/tModLoader/files/3297091/client.log)

**Comment by Chicken-Bones** [comment]
https://github.com/tModLoader/tModLoader/commit/135b2b98e7b98e028f8576a5a531784363d5eecd
