### ISSUE TITLE
Tmod Linux multiplayer crashes the game

### ISSUE THREAD

**Issue by macroboy** [tModLoader/tModLoader#562]
### Steps to Reproduce

1. Install Tmod for Linux
2. Open Game
3. Click Host and play and start your world

### Expected behavior 
the game should start the world normally
### Actual behavior
The game crashes. there is no crash window, the game just closes

### Reproduction frequency
Every single time i try to host a game or join a friend

### Versions
v0.10.1.5 tModLoader / 1.3.5.2
### Mods

[]https://imgur.com/jLjvntL
### Additional Information
N/A

**Comment by Hydro95** [comment]
Try having a look at #491, there's a workaround there (specifically https://github.com/tModLoader/tModLoader/issues/491#issuecomment-461498564 ). I ran into this yesterday and it fixed the problem for me.

**Comment by Chicken-Bones** [comment]
Closing duplicate, follow #491 for information
