### ISSUE TITLE
MenuOpen sound in ExampleMod, ExampleUI

### ISSUE THREAD

**Issue by KryptonIon** [tModLoader/tModLoader#563]
### Description
When closing/disposing of the coin UI, the sound played is MenuOpen

### Steps to Reproduce
1. do /coin in-game
2. click the trash can

### Expected behavior 
The Sound played should be MenuClose

### Actual behavior
MenuOpen is playing when disposing of the UI

### Reproduction frequency
100%

### Versions
Version > 1.10 and Version < 1.10

### Mods
ExampleMod

**Comment by Jofairden** [comment]
Even though it's very minor, thanks for reporting!
