### ISSUE TITLE
GOG hash mismatch for Windows version

### ISSUE THREAD

**Issue by bin-cat** [tModLoader/tModLoader#567]
### Description
tModLoader expects original executable of 1.3.5.3 from GOG with name Terraria_v1.3.5.3.exe and hash b92f242bc874dddbf08f705661b313a9 but actual hash of executable is 81ef4a9337ae6d7a1698fdeb3137580d.

### Steps to Reproduce
1. Install 1.3.5.3 via either GOG Galaxy or offline installer
2. Install tModLoader v0.11 Beta 6

### Expected behavior 
Game launching successfully with tModLoader enabled.

### Actual behavior
Due to hash mismatch it just complains about missing Steam library and exits.

### Reproduction frequency
Every launch

### Versions
tModLoader v0.11 Beta 6

### Additional Information
Checked hash for Linux version, it matches with the one from source code.

**Comment by Chicken-Bones** [comment]
Thankyou for this, I believe I had the hash for 1.3.5.2 (from the setup tool). I'll put this in with the mac hash

**Comment by Chicken-Bones** [comment]
https://github.com/tModLoader/tModLoader/commit/640729fd9b34e7731d8c4bebcae5b710cbe44f64 Thanks!
