### ISSUE TITLE
Vanilla Twilight Hair Dye causes crash on player save

### ISSUE THREAD

**Issue by DRKV333** [tModLoader/tModLoader#568]
### Description
The current beta version of tModLoder will consistently crash (no crash handler, the game just quits) every time it tries to save a character that has the "Twilight Hair Dye" applied.

### Steps to Reproduce
1. Open any player and world
2. Consume Twilight Hair Dye
3. Save and exit

### Expected behavior 
The game should not crash.

### Actual behavior
The game crashes.

### Reproduction frequency
Happens reliably.

### Versions

Tested on tModLoader v0.11 Beta 6

### Mods

None

### Additional Information

[client.log](https://github.com/tModLoader/tModLoader/files/3330769/client.log)

	public static string SaveHairDye(short hairDye)
	{
		if ((int)hairDye < EffectsTracker.vanillaHairShaderCount)
		{
			return "";
		}
		ModItem item = ItemLoader.GetItem(GameShaders.Hair._reverseShaderLookupDictionary[hairDye]);
		return item.mod.Name + "/" + item.Name; // <-- Exception Here
	}

Locals:
```
		hairDye	12	short
		item	null	Terraria.ModLoader.ModItem
```
Relevant globals:
```
		EffectsTracker.vanillaHairShaderCount	12	int
-		GameShaders.Hair._reverseShaderLookupDictionary	Count = 12	System.Collections.Generic.Dictionary<short, int>
+		[0]	[1, 1977]	System.Collections.Generic.KeyValuePair<short, int>
+		[1]	[2, 1978]	System.Collections.Generic.KeyValuePair<short, int>
+		[2]	[3, 1979]	System.Collections.Generic.KeyValuePair<short, int>
+		[3]	[4, 1980]	System.Collections.Generic.KeyValuePair<short, int>
+		[4]	[5, 1981]	System.Collections.Generic.KeyValuePair<short, int>
+		[5]	[6, 1982]	System.Collections.Generic.KeyValuePair<short, int>
+		[6]	[7, 1983]	System.Collections.Generic.KeyValuePair<short, int>
+		[7]	[8, 1984]	System.Collections.Generic.KeyValuePair<short, int>
+		[8]	[9, 1985]	System.Collections.Generic.KeyValuePair<short, int>
+		[9]	[10, 1986]	System.Collections.Generic.KeyValuePair<short, int>
+		[10]	[11, 2863]	System.Collections.Generic.KeyValuePair<short, int>
+		[11]	[12, 3259]	System.Collections.Generic.KeyValuePair<short, int>
```

**Comment by Chicken-Bones** [comment]
Good catch https://github.com/tModLoader/tModLoader/commit/454c3af9de11d78c68e5e43463e2fccdfebe5456
