### ISSUE TITLE
Retarget tML to .NET 4.5

### ISSUE THREAD

**Issue by Chicken-Bones** [tModLoader/tModLoader#571]
To allow tML to use some .NET 4.5 features (particularly async/await) we should be able to target 4.5, and provided no 4.5 only features are used before `ModLoader.DotNet45Check` then the update method will still be displayed to .NET 4.0 users.

It would definitely be desirable to unit test this on continuous integration

**Comment by Jofairden** [comment]
Would be great, we can refactor a ton of code with async/await

**Comment by Chicken-Bones** [comment]
Lets hope it doesn't explode everything. Tested on .NET 4.0 and the update message box still appears.

**Comment by Jofairden** [comment]
Was it done?
