### ISSUE TITLE
World Backups reportedly slow

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#572]
Some users report many seconds of waiting when leaving a world as the world backup process completes. This necessitates more investigation. 

Please comment below if you see this issue in 0.11.

**Comment by mindbound** [comment]
I can't replicate this but I am experiencing random slowdowns while moving around (running, climbing ropes, flying, etc.) that seem to disappear on changing direction.

**Comment by Jofairden** [comment]
> I can't replicate this but I am experiencing random slowdowns while moving around (running, climbing ropes, flying, etc.) that seem to disappear on changing direction.

That should be unrelated, backups aren't done during gameplay. (If the problem persists, please open a new issue)

**Comment by Jofairden** [comment]
Closing because there's no more activity nor have I heard anyone about this issue.
