### ISSUE TITLE
Mod menu buttons missing text

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#574]
On a rare occurrence involving a mod that failed to load, this is how the Mods menu appeared to a user

![8fae4738d4de2fef70689ac55f51e278](https://user-images.githubusercontent.com/4522492/60395127-fdf20700-9aeb-11e9-82f4-3d2bc8f6e96b.png)

Fix might just be a call to Recalculate, as seen here: https://github.com/tModLoader/tModLoader/commit/277d4668833eafba767e50a9d6f690cc5b312d68

Not sure why it is needed yet, the parent UIelements should already be the correct size to allow the UIAutoScaleTextTextPanel to scale properly

**Comment by imkSushi** [comment]
This also happened to me once in 0.11.1 when I opened up the Mod Sources menu for the first time, having just updated ModCompile.

**Comment by JavidPack** [comment]
Mod Sources menu needs fix too.

**Comment by Jofairden** [comment]
Fixed in https://github.com/tModLoader/tModLoader/commit/5a1045a7ce4b9123cd3ab22bb26a4473d2ac3744 https://github.com/tModLoader/tModLoader/commit/4b41cd012a0f28ad836fa487caf63e421ed9db7c and probably another one I forgot
