### ISSUE TITLE
Random slowdowns while moving

### ISSUE THREAD

**Issue by mindbound** [tModLoader/tModLoader#576]
After upgrading from 0.11.6 beta to 0.11, I've started experiencing random slowdowns while moving the character sprite (running, climbing ropes, flying, etc.) that repeat roughly every minute or so and seem to go away for a short while after pressing a button to change directions. There is no significant messages in the log file. The issue doesn't seem to be affected by lighting settings (multicore, coloured, etc.).

I'm using GoG version of Terraria 1.3.5.3, Arch Linux x86_x64. I have a large number of mods installed but the same modpack caused no such issues using the beta.

**Comment by Jofairden** [comment]
If you tell us the modpack, that would be appreciated.

**Comment by mindbound** [comment]
Of course. There you go: [mods.txt](https://github.com/tModLoader/tModLoader/files/3346855/mods.txt)

**Comment by GoodPro712** [comment]
Try turning frameskip on

**Comment by GoodPro712** [comment]
Close(?)

**Comment by Solxanich** [comment]
Hello @mindbound,
I'm currently reviewing stale issues, and would like to confirm if you are still experiencing this issue in the latest version 0.11.8.1 of tModLoader.
If not, could you please close the issue?
If so, could you please provide the most recent information from its occurrence?

Thank you for your time.
