### ISSUE TITLE
GOG user installation prone to failure

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#577]
A drag and drop install will overwrite Terraria.exe, which is used for gog verification.

The installer won't know where to install, so we won't get Terraria_v1.3.5.3.exe since the installer won't be used by GoG users.

**Comment by JavidPack** [comment]
I added some instructions to 5f622058e8084f00c16b15c3775a3a0d78168aac, but we'll still probably just need a folder chooser dialog to make the installer real convenient. 

If the jar could recognize that it is in a zip and extract the files from the zip automatically, that would be neat too. (Is that possible?)

**Comment by Chicken-Bones** [comment]
Of course, java even has methods for reading from your own jar file.

**Comment by JavidPack** [comment]
3ba0cf2 will now provide better info to GOG users.
