### ISSUE TITLE
OSX permission issue running from Steam

### ISSUE THREAD

**Issue by DrNorris** [tModLoader/tModLoader#580]
### Description
Using Steam on OSX 10.14.1 I am unable to open Terraria.  The launcher will start and then immediately go away.

If I go to the command line to run the app ./Library/Application Support/Steam/SteamApps/common/Terraria/Terraria.app/Contents/MacOS/Terraria I get an error that states "/bin/bash: ./Terraria: Permission denied"

However, if I run sudo ./Terraria the game will load correctly

### Steps to Reproduce

1. Download 0.11
2. Try to launch from Steam

### Expected behavior 
Game Loading

### Actual behavior
The game is not loading from Steam, but will load with sudo privileges

### Reproduction frequency
Every Time
### Versions
tModLoader.Mac.v0.11

### Mods
none

**Comment by roadh0use** [comment]
i had this issue on linux as well. ive never used a mac but from what i understand its really similar to linux. can you go into your terraria folder and right click terraria, go to properties, and in there perhaps there is a permissions tab where you can change access to read and write for all groups?

**Comment by DrNorris** [comment]
Turns out this was caused by the Terraria script not having execute permission upon installation.

**Comment by Jofairden** [comment]
_I think_ this is the simple permission issue. For linux/mac we need to be taring the releases so it comes with permissions. See also https://github.com/tModLoader/tModLoader/issues/491#issuecomment-467237250
I'll close this for now.
