### ISSUE TITLE
tModLoaderServer.bin.x86_64 does not appear to be in the linux .zip

### ISSUE THREAD

**Issue by roadh0use** [tModLoader/tModLoader#581]
### Description
running ./tModLoaderServer on ubuntu server 18.04 gives

`cp: cannot stat './Terraria.bin.x86_64': No such file or directory
./tModLoaderServer: line 51: ./tModLoaderServer.bin.x86_64: No such file or directory`

### Steps to Reproduce
`mkdir ~/terraria`

`cd terraria`

`wget http://terraria.org/system/dedicated_servers/archives/000/000/032/original/terraria-server-1353.zip`

`wget https://github.com/tModLoader/tModLoader/releases/download/v0.11/tModLoader.Linux.v0.11.zip`

`unzip terraria-server-1353.zip`

`cp -r ./1353/Linux/* ./`

`unzip tModLoader.Linux.v0.11.zip`

`chmod u+x tModLoaderServer*`

`./tModLoaderServer`

### Expected behavior
the server starts i think

### Actual behavior
it is giving
`cp: cannot stat './Terraria.bin.x86_64': No such file or directory
./tModLoaderServer: line 51: ./tModLoaderServer.bin.x86_64: No such file or directory`

### Reproduction frequency
100% of the time all the time

### Versions
terraria server v1.3.5.3
tmodloader v0.11

### Mods
fresh install

### Additional Information
terraria is a fun game and thank you for your mod loader

**Comment by JavidPack** [comment]
We've hopefully fixed this for next release. Stay tuned.

**Comment by JavidPack** [comment]
In the meantime, you can copy TerrariaServer.bin.x86_64 to Terraria.bin.x86_64

**Comment by roadh0use** [comment]
> In the meantime, you can copy TerrariaServer.bin.x86_64 to Terraria.bin.x86_64

im sorry do you mean like rename it?

**Comment by roadh0use** [comment]
alright so i think you meant rename it so I did with

`mv ./TerrariaServer.bin.x86 ./Terraria.bin.x86_64`

then when i run

`./tModLoaderServer`

i get 

`./tModLoaderServer: line 51: ./tModLoaderServer.bin.x86_64: No such file or directory`

**Comment by roadh0use** [comment]
actually im dumb and you definitely meant copy the file. started from scratch and then did

`cp TerrariaServer.bin.x86_64 ./Terraria.bin.x86_64`

now when i run

`./tModLoaderServer`

i get 

`tModLoader.ServerCrash`

**Comment by JavidPack** [comment]
I made this to fix a similar bug, it might be related: https://github.com/tModLoader/tModLoader/files/3342738/tModLoader.Linux.v0.11.zip

If that doesn't work, we might have a 0.11.0.1 out in a day or 2 that should address the installation and running issues.

**Comment by roadh0use** [comment]
> I made this to fix a similar bug, it might be related. You can try this version: https://github.com/tModLoader/tModLoader/files/3342738/tModLoader.Linux.v0.11.zip
> 
> If that doesn't work, we might have a 0.11.0.1 out in a day or 2 that should address the installation and running issues.

hey that worked thank you very much!

**Comment by JoeStratton** [comment]
This issue is still present in 0.11.1

**Comment by Chicken-Bones** [comment]
It's not supposed to exist, the script has been updated to copy it from TerrariaServer.bin.x86_64
