### ISSUE TITLE
More player.allDamage problems

### ISSUE THREAD

**Issue by DarkLight66** [tModLoader/tModLoader#582]
### Description
* Some special damage dealing effects that are affected by certain vanilla damage bonuses that don't rely on `player.GetWeaponDamage` to calculate damage dealt, like some vanilla dashes and mounts like minecarts, aren't affected by the new `allDamage` field or any of the new `damageMult` fields.
* Items that had no damage type listed but still dealt damage, like the flare gun and   holy water, are affected by `allDamage` and `allDamageMult`, which differs from vanilla.
* Items that had more than somehow had more than one damage type set are now affected by all damage bonuses related to those types, rather than only being affected by the one with the highest priority, with the priority chain shown in tooltips and used by projectiles being being melee => ranged => thrown => magic => summon. As far as i know there's no example of an item with multiple damage types set in vanilla though.

### Steps to Reproduce
Equip items that increase all damage dealt

### Expected behavior 
Damage from things like dashes and mounts is increased, while damage of items like the flare gun and holy water remains the same

### Actual behavior
Damage from things like dashes and mounts isn't affected, while damage of items like the flare gun and holy water is increased

### Reproduction frequency
Always

### Versions
`tModLoader v0.11`

### Mods
None

### Additional Information
List of the special vanilla damage dealing effects that are affected by some vanilla damage bonuses:
* Shield of Cthulhu and Solar Flare armor dashes (melee damage)
* Forbidden armor ancient storm (magic and minion damage)
* Slime mount while jumping on top of enemies (minion damage)
* Unicorn and Basilisk mounts while charging (minion damage)
* ~~Minecarts while moving fast (highest damage multiplier out of melee, magic and ranged)~~ This was actually referring to crit change rather than damage, oops.
* Stardust Guardian's explosion attack (minion damage)

List of items with no listed damage type that deal damage in vanilla that i have found:
* Flare Gun (ID 930)
* Holy Water (ID 422)
* Unholy Water (ID 423)
* Blood Water (ID 3477)

A note on the damage type priority chain, for weapons that do damage on melee contact, the chain would be thrown => summon => magic => ranged => melee for some reason, though since all melee weapons in vanilla do melee damage, it's safe to assume that it'd be better to use the priority chain used for everything else.

**Comment by Chicken-Bones** [comment]
Good list, we definitely want to fix the accidental nerfs, but I'm less concerned about buffs

**Comment by DarkLight66** [comment]
All things here could be buffs or nerfs, depending on how the damage bonus fields are used. For example, Thorium has equipment that increases damage for healer weapons, but reduces it for everything else. Things not being affected by `allDamage` would receive a buff in this case, while things that are but shouldn't would get a nerf.

**Comment by Jofairden** [comment]
I _would_ like allDamage to be inclusive, but only of the vanilla damage types (the entire reason it was created)

So, as for point 1: This is correct behavior. If they don't have any specific damage type, they shouldn't be modified. They aren't weapons melee/ranged/magic/thrown/summon

Point 2: This should be fixed. If they have no damage type, they normally wouldn't be modified by them either.

Point 3: This is correct behavior, and I'm fairly sure I reported this bug to yorai a very long time ago (as items not being modified by multiple was a vanilla bug). We probably fixed it ourselves in the meantime. This is useful for custom damage types you want affected by multiple vanilla types (e.g. I had a type affected by ranged and thrown).

**Comment by DarkLight66** [comment]
On point 1: Those effects i mentioned **are** affected by certain specific damage type bonuses though, which i mentioned in the additional information section. And the SoC, for example, specifically mentions in the tooltip that it deals melee damage, although the damage the dash deals isn't even affected by the item's stats.

On point 3: Fair enough, and it would be nice to be able to have items that are affected by multiple damage types easily, although the tooltip would only reflect one of the damage types by default.

**Comment by Jofairden** [comment]
You said this though:

> Some special damage dealing effects that are affected by certain vanilla damage bonuses that don't rely on player.GetWeaponDamage to calculate damage dealt, like some vanilla dashes and mounts like minecarts, **aren't affected** by the new allDamage field or any of the new damageMult fields.

So you contradict yourself :P
If vanilla doesn't do it, I don't think we should either. Too many changes

**Comment by Chicken-Bones** [comment]
I understood what he was saying

**Comment by DarkLight66** [comment]
@Jofairden What i meant is that, for example, the Slime Mount's damage is affected by `player.minionDamage` in vanilla, so shouldn't it also be affected by the newly added `player.minionDamageMult`, `player.allDamage` and `player.allDamageMult` ?

**Comment by Jofairden** [comment]
They should

**Comment by Jofairden** [comment]
Adding 1.4 tag since throwing damage is removed, we should have another look at damage types and potentially ModDamageType or something.

**Comment by direwolf420** [comment]
@ThomasSpeedrunner You were the most recent contributor working on DamageClass, any news/updates on this issue in particular that still needs addressing in 1.4?

**Comment by ThomasSpeedrunner** [comment]
To my knowledge, pretty much all of this has already been addressed for 1.4 with the addition (and subsequent overhaul) of DamageClass and how damage calcs as a whole are done. Given the sheer amount of edge cases that were covered during the over 2 months that the PR related to DamageClass' overhaul was open and discussed, there is no reason any of this should be a problem going into 1.4 --- and if it is a problem, I'll tackle it when I see the evidence that it is one.
