### ISSUE TITLE
Clicking the 'view mod dependencies' button filters the mod browser list by the mod's internal name (instead of display name), sometimes not showing up

### ISSUE THREAD

**Issue by hamstar0** [tModLoader/tModLoader#583]
### Description
See title.

### Steps to Reproduce
See title.

### Expected behavior 
See title.

### Actual behavior
See title.

### Reproduction frequency
Always

### Versions
tModLoader v0.11

### Mods
Any mods with dependencies listed in the mod browser.

**Comment by Jofairden** [comment]
Thanks, will look into it.

**Comment by JavidPack** [comment]
Seems to be fixed somehow.

**Comment by Jofairden** [comment]
Is that true? @hamstar0 can you confirm?

**Comment by hamstar0** [comment]
Yes. Hence why he closed it.
