### ISSUE TITLE
Linux Bin file still does not exist

### ISSUE THREAD

**Issue by JoeStratton** [tModLoader/tModLoader#586]
See https://github.com/tModLoader/tModLoader/issues/581#issue-463021686

It has not been resolved yet

### Description
running ./tModLoaderServer on ubuntu server 18.04 gives

cp: cannot stat './Terraria.bin.x86_64': No such file or directory ./tModLoaderServer: line 51: ./tModLoaderServer.bin.x86_64: No such file or directory

### Steps to Reproduce
mkdir ~/terraria

cd terraria

wget http://terraria.org/system/dedicated_servers/archives/000/000/032/original/terraria-server-1353.zip

wget https://github.com/tModLoader/tModLoader/releases/download/v0.11/tModLoader.Linux.v0.11.zip

unzip terraria-server-1353.zip

cp -r ./1353/Linux/* ./

unzip tModLoader.Linux.v0.11.zip

chmod u+x tModLoaderServer*

./tModLoaderServer
### Expected behavior 
the server starts i think

### Actual behavior
it is giving
cp: cannot stat './Terraria.bin.x86_64': No such file or directory ./tModLoaderServer: line 51: ./tModLoaderServer.bin.x86_64: No such file or directory

### Reproduction frequency
100% of the time all the time

### Versions
terraria server v1.3.5.3
tmodloader v0.11.1

### Mods
fresh install

### Additional Information
terraria is a fun game and thank you for your mod loader

**Comment by Jofairden** [comment]
Have you chmod +x ./Terraria and try running the script? It should copy the relevant files

**Comment by JoeStratton** [comment]
I was able to solve the issue, the file did exist it was just a permissions error, after I added a chmod to the bin file the server started up fine. 

Thanks

**Comment by Jofairden** [comment]
Ok thanks for reporting that. We also fixed a permission issue in an earlier commit so this is probably also fixed for future releases.
