### ISSUE TITLE
UseTimeMultiplier can cause items to have <1 usetime; makes them unusable

### ISSUE THREAD

**Issue by bobbymonboy** [tModLoader/tModLoader#590]
### Description
If UseTimeMultiplier causes an item's usetime to be lower than 1, nothing catches the problem and the item is rendered unusable until usetime is set greater than 1 by other means.

### Steps to Reproduce
1. have UseTimeMultiplier return a high value:
public override float UseTimeMultiplier(Item item) { return 10f; }

2. Attempt to use minishark or other quick-firing item ingame. Works with blocks and walls as well.

### Expected behavior 
The item's usetime should be reduced to a minimum of 1, preventing items from becoming unusable.

### Actual behavior
The item's usetime is reduced beyond 1, rendering it unusable.

### Reproduction frequency
Every time, if done correctly.

### Versions
`tModLoader v0.10.1.5`
Probably earlier versions as well.

### Mods
None except the one that modifies UseTimeMultiplier.

### Additional Information
Doesn't work with items that seem to have a forced usetime, like the Solar Eruption.
Holding a block or wall in your hotbar and selecting it quickly consumes the items without placing anything.

**Comment by Jofairden** [comment]
This isn't really a 'bug' on our end, since this has always been the case even in vanilla. It's just that modders get the freedom to change it. If there aren't many cases where usetime changes, we can add a minimum of 2 frames use time.
