### ISSUE TITLE
How to make a window in UI ?

### ISSUE THREAD

**Issue by Valera231Rus** [tModLoader/tModLoader#594]
Hi, tell me how to make UI a window in which the text would be displayed and it would change? Or where you can find something like a textbook or an article on the creation of  UI, since it is not clear in ExampleMod .

**Comment by Jofairden** [comment]
Hey, kindly do not make issues for help request. These are solely meant for actual issues with the API.
If you require help, the best course of action is to join our Discord server which has lots of people in it that can help you. Join here: https://www.tmodloader.net/discord
