### ISSUE TITLE
Player position jitter while in mid air

### ISSUE THREAD

**Issue by DarkLight66** [tModLoader/tModLoader#603]
### Description
While the player is mid air, their position shifts up and down slightly from their screen's normal position. This has been mentioned by multiple users as a bug that happens on windowed mode only. This didn't happen on previous release versions of tModLoader.

### Steps to Reproduce
1. Set the game to windowed mode
2. Jump or fly through the world

### Expected behavior 
The Player's position should remain constant (as long as they aren't near the edges of the world)

### Actual behavior
The Player's shifts up and down slightly

### Reproduction frequency
Always

### Versions
`tModLoader v0.11.1`

### Mods
None

### Additional Information
The user direwolf420 on the discord server mentioned that this bug didn't happen in 0.11 beta 3

**Comment by JavidPack** [comment]
We'll need a video of this, can't replicate myself.

**Comment by KryptonIon** [comment]
> We'll need a video of this, can't replicate myself.

[Video](https://cdn.discordapp.com/attachments/582730364871508009/642366199522394154/Jitter.mp4)

**Comment by JavidPack** [comment]
Thanks. The issue has to do with non-multiple of 2 resolutions from what I've seen (odd numbers, it's probably an xna bug maybe?), we changed the logic for screen resizing and we might need to revert this particular change and test.

**Comment by KryptonIon** [comment]
My screen is 1920x1080, in Terraria with the title bar excluded, it's 1920x1017

**Comment by JavidPack** [comment]
As a note, I noticed this while using non-100% in-game zoom
