### ISSUE TITLE
Cancel button during mod loading

### ISSUE THREAD

**Issue by Jofairden** [tModLoader/tModLoader#605]
Some people have requested a way to cancel mod loading that's obvious (instead of keyboard button). Useful if you want to skip loading / know you will change mod list etc.

Upvote this issue if you want this feature.

**Comment by Jofairden** [comment]
Initial work done: 4de895b0bbe36307d6f4e81cf3ec9695a6bb0eed
But, not sure yet if it's 100% safe. This needs more testing from 0.11.2.2 users.

**Comment by Jofairden** [comment]
So far reports are that it seems to work fine. An unload progress might be desired (if you normally unload mods, the progress waits until mods are unloaded before continuing to reload ModLoader)

**Comment by Chicken-Bones** [comment]
65c8feba7a3deb8f946da4ecf5eda1ec4ef560c5
