### ISSUE TITLE
Weak references to mods with their own copies of referenced dlls causes compile crash

### ISSUE THREAD

**Issue by direwolf420** [tModLoader/tModLoader#609]
### Description
Adding weak reference in built.txt to a mod that packages its own copies of already existing dlls causes a compile crash

### Steps to Reproduce
1. Clean and regenerate ModCompile, references folders
2. Create empty mod skeleton from ingame
3. Download for example TerrariaOverhaul so it is in the Mods folder
4. Add for example `weakReferences = TerrariaOverhaul@3.2.2` to build.txt
5. Click "Build" on the mod

### Expected behavior 
No crash

### Actual behavior
Crashing with an error about dlls already being imported (log at the bottom)

### Reproduction frequency
Always with the same error as long as you do the steps 1-3. Not doing step 4 compiles just fine

### Versions
0.11.1 crashes. Doing weakRef on 0.10.1.5 worked when building from ingame

### Mods
The test mod created in step 2.

### Additional Information
* Compiling via VS (and having the TerrariaOverhaul.dll imported in the csproj) works fine
* Tested with a whole bunch of different mods listed as a weakRef, always crashes with TerrariaOverhaul, 3.2.2 or 4.0.0
* Removing the following files from the references folder made the mod compile again: `Mono.Cecil.dll, Mono.Cecil.Mdb.dll, Mono.Cecil.Pdb.dll, MonoMod.RuntimeDetour.dll, MonoMod.Utils.dll, NVorbis.dll`. Removing them one by one always came up with the same error, just the dll name changed, until there were no errors
* Crash log when doing so: [Crash log](https://pastebin.com/mYq6q6vS)

**Comment by Chicken-Bones** [comment]
This is just Overhaul doing things it probably shouldn't because @Mirsario is special. Won't fix.

Workaround 1: delete those files from ModCompile (and get them again when building another mod or something)
Workaround 2: use mod-reader to extract overhaul, remove those dlls, and rebuild it with noCompile.
Workaround 2a: Get Mirsario to send you a copy which doesn't have those dlls in it.
