### ISSUE TITLE
Search Bar function for ModConfig

### ISSUE THREAD

**Issue by NuovaPrime** [tModLoader/tModLoader#610]
The addition of a search bar inside the modconfig UI to allow the player to search for the config element they wish could be very useful for mods that have dozens of options to configurate.

### Description

There is no search bar in the modconfig, making it tough to find the element you want.

### Expected behavior 

The declaration of a SearchBar attribute that can also be moved and resized could be very useful.

### Versions
 
tModLoader v0.11.1

**Comment by Jofairden** [comment]
Ok, we need some discussion on how the searchbar would operate.
Would all the elements that don't match the search query disappear?
Or, would the elements that match the search query become highlighted?
