### ISSUE TITLE
Question about the working way of this mod tool.

### ISSUE THREAD

**Issue by neoedmund** [tModLoader/tModLoader#611]
First of all, Thank you for writing so good tool and detailed documents.

I wonder how this tool works, compared  https://github.com/pardeike/Harmony , in the way it can patch a lot of C# .Net games. What's the difference in implementation ? Did this tool has features like Prefix, Postfix for a C# method? When does this tool call the user patched methods?

Thank you!

**Comment by Chicken-Bones** [comment]
I suggest you take a look at the source code for ExampleMod. We recently added something Harmony like in MonoMod by 0x0ade, but that's bit the core focus of tModLoader. We have a very Terraria centric API rather than a generic modding framework

**Comment by Jofairden** [comment]
What cb said. You can basically do two types of modifications: hooking or IL edits.
Hooking is what you describe with pre/post on an existing method. With IL edit you can quite literally change the IL of a method. The most common way, that 99% of modders use, is by using classes and methods we expose in the API.

**Comment by Jofairden** [comment]
See:
https://github.com/tModLoader/tModLoader/wiki/Expert-IL-Editing
https://github.com/tModLoader/tModLoader/blob/master/ExampleMod/Items/ExampleDamageClass/Mundane.cs#L11-L41
https://github.com/tModLoader/tModLoader/blob/af6349e47fa95c35add0f2b0521cfce9fa9608c9/ExampleMod/NPCs/ExampleCritter.cs

**Comment by neoedmund** [comment]
Okay I'll look into it, thanks for the clues.
