### ISSUE TITLE
Hover over unloaded Tiles for info

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#613]
A suggestion has been made to allow for hovering over the pink unloaded tiles to view the source mod and tile name. This could be useful.

**Comment by Jofairden** [comment]
Looks like the mystery tile saving/loading will need to be changed to make this happen, as the current format does not support this feature.

**Comment by GoodPro712** [comment]
Contributions Welcome tag?

**Comment by Jofairden** [comment]
Solved by #824. Closed.
