### ISSUE TITLE
[tModLoader v0.11.2.2] - Strangely unable to install some mods

### ISSUE THREAD

**Issue by KronoTrigger** [tModLoader/tModLoader#616]
When installing some mods, the progress bar doesn’t progress or install the mod.

List of mods I had issues installing:
1. HeroSickle
2. Archaea Mod
3. New Mythical Items Plus
4. Endless Explosive Cannons

I’m sure there is more but I’m not sure what’s causing the issue.

**Comment by Jofairden** [comment]
Interesting, I'm having similar results. Error:
`System.Net.WebException: 'The request was aborted: The connection was closed unexpectedly.'`
The reason why, it no longer exists on Github. Try in browser:
https://github.com/LemmoNadeYT/HeroSickle/releases/download/v4.3.3.1/HeroSickle.tmod
Results in 404 not found.
We'll need to track if github releases are removed/broken.

**Comment by GoodPro712** [comment]
Close
