### ISSUE TITLE
Request: ILoadable automatically has `Load()` and `Unload()` called for any implementing classes on mod Load and Unload

### ISSUE THREAD

**Issue by hamstar0** [tModLoader/tModLoader#618]
### Description
See title.

### Steps to Reproduce
Buy chocolates. Find prospect. ??? Profit!

### Expected behavior 
See title.

### Actual behavior
Needs a timeout and docked allowance.

### Reproduction frequency
NSFW

### Versions
Latest?

### Mods
Probably.

### Additional Information
Yesn't.

**Comment by Jofairden** [comment]
Upvote if you want this.

**Comment by hamstar0** [comment]
Maybe use a different interface and add a `PostSetupContent` hook as well?

**Comment by Jofairden** [comment]
We're up for this, it's  a nice means of autoloading like the rest of things.

**Comment by Chicken-Bones** [comment]
Follow #848 for implementation
