### ISSUE TITLE
QA: Naming of directories on linux

### ISSUE THREAD

**Issue by Kreyren** [tModLoader/tModLoader#624]
tModLoader is using spaces ` ` on linux which is making it pita to handle -> Requesting name change alike `Mod Sources` -> `ModSources`

```
(base) kreyren@rogisek:~/.local/share/Terraria/ModLoader$ ls
 config.json     'input profiles.json'   Mods           Players        Worlds
 favorites.json   Logs                  'Mod Sources'   TexturePacks
```

**Comment by Jofairden** [comment]
Hm, I dunno, care to elaborate what's so PITA about it? I never had any issues with it

**Comment by Kreyren** [comment]
@Jofairden Linux is usually using bash shell for terminal and spaces are represented as `\ ` so filename is `Mod\ Sources` in terminal which makes it uneffective to work with since it requires additional pressing of `\` key + Tab key and pain to make scripts for since scripts has to have `path/Mod\ Source/stuff` or `path/'Mod Sources'/stuff`.. 

Referencing https://unix.stackexchange.com/questions/148043/is-space-not-allowed-in-a-filename

Generally it's bad practice to use pathnames with spaces.

**Comment by Jofairden** [comment]
Ok so, as noted, it's not really 'an issue' or not allowed. But rather an inconvenience
It's stated that it's avoided because of software not dealing with it properly, well I think tModLoader does.

But I do agree, if it's against the norm and it's less tedious to deal with non special character names, we could adjust it for Linux.

**Comment by Jofairden** [comment]
Tagging @Chicken-Bones for input and final decision making

**Comment by JavidPack** [comment]
I don't agree with changing it. We have long established the expected directory names, and both windows and linux are equally annoying when typing them out on a console.

**Comment by Chicken-Bones** [comment]
I honestly think we should've made them without spaces in the beginning, because spaces in paths are just annoying, and because "TexturePacks" doesn't have a space. We could (should?) consider searching both and changing the default

**Comment by Jofairden** [comment]
Let's pick this up at least for 1.4 @Chicken-Bones ? We can simply search the old folders and rename them if there are files present for old version migration.
