### ISSUE TITLE
zoom bug

### ISSUE THREAD

**Issue by M1cr0waveChan** [tModLoader/tModLoader#625]
### Description

zooming in makes npcs float (they dont change scale )
### Steps to Reproduce

zoom in 
1. [First Step]
2. [Second Step]
3. [And so on...]

### Expected behavior 

zooming in should not glitch out npcs
### Actual behavior

zooming in dosnt effect npcs causing them to float (also happens with the pillars)
### Reproduction frequency

100%
### Mods
tremor remastered
calamity (no music)
thorium
fargos mod and soul mod
luiafk
cheat sheet
wing slot
auto trash
boss checklist
imksushi's death counter

### Additional Information
  this only started when i updated tmodloader 
![20190725173126_1](https://user-images.githubusercontent.com/53319156/61913227-0fb7a600-af02-11e9-9720-77ea6b0da5dc.jpg)
![20190725173129_1](https://user-images.githubusercontent.com/53319156/61913228-11816980-af02-11e9-82ad-f1e7c8f2efeb.jpg)

**Comment by JavidPack** [comment]
iirc, this is a Tremor bug. As a reminder, please make sure you confirm that a bug is a tModLoader bug by disabling all other mods and freshly restarting tModLoader before making an issue here.
