### ISSUE TITLE
Huge Feature: tModLoader On Nintendo Switch!!

### ISSUE THREAD

**Issue by RetroPixelYT** [tModLoader/tModLoader#627]
Yo, TModLoader. It will be very helpful if you can make tModLoader on The Nintendo Switch system. I really want to be able to play different Mods on my Nintendo Switch.

**Comment by DrPyxel** [comment]
I'm pretty sure installing tModloader on thr Nintendo Switch, even if it's possible would break Nintendo's ToS since it's a third party program.

**Comment by Jofairden** [comment]
Yeah, we're not in for this. As much as we like the suggestion, _and it would be fun_, it would  be a tedious amount of work and well.. yeah.. if it's against their ToS I don't think we're a fan.
