### ISSUE TITLE
Jittering bug

### ISSUE THREAD

**Issue by Chais** [tModLoader/tModLoader#632]
### Description

When starting to walk the character will slow down unless a second input is given at least briefly.
[Demonstration](https://imgur.com/a/cpVPC7G)

### Steps to Reproduce

1. Start a game (with or without mods, only tModLoader required)
1. Walk left/right
1. See character starting at regular speed

### Expected behavior 

4. Keep walking as you'd expect

### Actual behavior

4. Notice character coming to a jittering halt

### Reproduction frequency

Every time

### Versions

tModLoader v0.10.1.4
tModLoader v0.11.3

### Mods

None

### Additional Information

Only reproduced on Linux.
Arch Linux 5.2.1
libinput 1.13.4

**Comment by Jofairden** [comment]
Ty for report. The issue is already known for us and pending for a fix.

**Comment by JavidPack** [comment]
Did this ever fix itself @Chais ? This actually doesn't look like anything I know of, and we wouldn't really know how to figure out the reason for the weird movement in the video you posted.

**Comment by Chais** [comment]
Just tested with 0.11.6.2. Still an issue, even without any mods active.

**Comment by JavidPack** [comment]
It has been reported that following this has solved this for someone else: http://xahlee.info/linux/linux_set_key_repeat_rate.html

"Changing the delay to a high value (2000) is what did it."

**Comment by Chais** [comment]
Yes, that mitigates the problem.

Running some tests I was able to narrow the issue down to the ratio between delay and repeat rate. A 2 second delay with 11 characters/second (cps) will make the game playable, while 20 cps will not.  
So until the first other key than the current direction of movement is pressed every key repeat is taken as a new input.

2 seconds are not really practical for everyday use, though, which means I have to set and reset the delay before and after playing.
When can we hope for the fix?

**Comment by JavidPack** [comment]
We have no idea why this would manifest in tModLoader and not Terraria. I'm pretty sure we haven't changed any related code. 

A fix would require tracking down the cause of the disparity, and that cause is still unknown.

**Comment by Chicken-Bones** [comment]
Looks reproducible now. Self-assigning

**Comment by benjamin-luker** [comment]
Any news on this? I have the same issue on Ubuntu 18.04

**Comment by Mirsario** [comment]
> 
> 
> Any news on this? I have the same issue on Ubuntu 18.04 - it makes playing very difficult.

Please check if it happens on the 1.4 branch. Cross-platform nightly builds are available at 
https://github.com/tModLoader/tModLoader/actions?query=branch%3A1.4
(Install into an empty folder that itself is next to Terraria's, run `start-tModLoader.sh`)

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.

**Comment by thenoobestman** [comment]
> ### Description
> When starting to walk the character will slow down unless a second input is given at least briefly. [Demonstration](https://imgur.com/a/cpVPC7G)
> 
> ### Steps to Reproduce
> 1. Start a game (with or without mods, only tModLoader required)
> 2. Walk left/right
> 3. See character starting at regular speed
> 
> ### Expected behavior
> 4. Keep walking as you'd expect
> 
> ### Actual behavior
> 4. Notice character coming to a jittering halt
> 
> ### Reproduction frequency
> Every time
> 
> ### Versions
> tModLoader v0.10.1.4 tModLoader v0.11.3
> 
> ### Mods
> None
> 
> ### Additional Information
> Only reproduced on Linux. Arch Linux 5.2.1 libinput 1.13.4

> This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.

I know Im extremely late (almost 1 year)
but i still want to say stuff here


1. its on all computer terraria
2. its on terraria not tmod (caused in tmod cuz its still terraria) 
3. its still to this day (latest version)
4. I couldn't find a fix but if there is one please write here cuz this is one of the first ones that show up
