### ISSUE TITLE
[Suggestion] Filtering the mod browser by installed

### ISSUE THREAD

**Issue by GreatestFool** [tModLoader/tModLoader#637]
I doubt I'm the only one who would enjoy such a feature. I feel its addition is especially prevalent now because of the recent v0.11.x update adding configs and the like. The mod browser is a really nice way to check when the mod was last updated, but, unless I am blind, there isn't really a way to sort by installed which would alleviate a lot of time searching up a lot of the names manually. I personally have a good few popular mods and quite some not as known ones, which makes the latter that much more time consuming to find.

I for one, think it'd be a neat addition to tModLoader.

**Comment by JavidPack** [comment]
There is an Update filter which sounds like what you want. If you knew about that, and your question is about seeing how abandoned the mods you have are, then I guess an installed filter could make sense too.

![image](https://user-images.githubusercontent.com/4522492/62398908-5a0ad980-b537-11e9-8a8e-cc0687701a9b.png)

**Comment by GreatestFool** [comment]
The update filter is nice, but while it does help significantly when I want to view what has an update when there is one, viewing how abandoned mods are is still pretty time consuming and an installed mods filter would help a lot with that.

**Comment by Jofairden** [comment]
But, that doesn't change anything? If the 'abandoned' mod doesn't show, you know it doesn't have an update.

**Comment by GreatestFool** [comment]
That's what the _Show only updates_ filter is for, if there is an update I'll find out. However, to check which mods have been updated and not when there are no newly released updates for the mod, I still have to search them up manually. I.e. when they're [popular](https://i.imgur.com/0s1F5ft.png) it is no issue, how long since last update is on the right of the mod. When they're not popular I have to manually search them up and check, because there has been no recent updates, for example [this mod](https://i.imgur.com/UEXbTrY.png) I like but hasn't been updated in two years. Due to that, I won't know if it has or not without checking. It is not the only example, there are quite a few mods in my modpack that haven't had an update in a long while, and sometimes I like to check so I can disable them to avoid potential issues with more updated mods, or in this case, an updated version of tModLoader.
