### ISSUE TITLE
Cannot dispose shaders in v11

### ISSUE THREAD

**Issue by chatrat12** [tModLoader/tModLoader#638]
So I technically can dispose my shaders, but then I cannot get them back. 

So when I unload my mod, I clean up my resources like a good little programmer does. When I dispose my shader and then reload the mod and call `GetEffect`, I get back a reference to the disposed object. This was not the case in v10 nor is it the case with textures. 

My fix for now is to just let my shaders hang around in memory.

Here is an example of the issue:
```cs
private Effect _effect;
private Texture2D _texture;

public override void Load()
{
    // Load shader
    _effect = GetEffect("Effects/Effect");
    // Also testing texture
    _texture = GetTexture("Images/Texture");

    // This exception does not get thrown meaning that 
    // textures can be disposed and reloaded.
    if (_texture.IsDisposed)
        throw new ObjectDisposedException("texture");
    // This exception will be thrown after the mod is unloaded 
    // and then reloaded
    if (_effect.IsDisposed)
        throw new ObjectDisposedException("effect");
}

public override void Unload()
{
    // Dispose of our resources
    _effect?.Dispose();
    _texture?.Dispose();
    _effect = null;
    _texture = null;
}
```

**Comment by Chicken-Bones** [comment]
Looks like a bug to me. Though for reference, tML cleans up textures for you. Not sure about shaders

**Comment by Jofairden** [comment]
Most likely a bug if it was fine in v0.10
Can't recall of any change related to this (that would require modder changes to not get a disposed instance etc.)
