### ISSUE TITLE
Duplicate copies of .tmod mods freeze game

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#639]
If you have something like this in your Mods folder:
```
ShorterRespawn - Copy.tmod
ShorterRespawn.tmod
```
The game will get stuck in the loading mods menu. Cancel doesn't even work.

**Comment by Chicken-Bones** [comment]
Failed to replicate with EvenMoreModifiers (Loot.tmod)

**Comment by JavidPack** [comment]
More info: enable the mod and attempt to reload. ModOrganizer.FindMods().SingleOrDefault crashes.

**Comment by Chicken-Bones** [comment]
Turns out we have an error case "Two mods share the same internal name" but the new error handling calls `ModOrganizer.FindMods().SingleOrDefault` and bombs out
