### ISSUE TITLE
Game doesnt launch, i updated it from 0.10.1.5 to 0.11.3, i double click it/press enter and nothing happens, doesnt even appear on task manager

### ISSUE THREAD

**Issue by Boisq** [tModLoader/tModLoader#641]

**Comment by JavidPack** [comment]
We need log files to help you. You'll find the log files in the logs folder. Look for client.log. 
Windows Logs: C:\Documents\My Games\Terraria\ModLoader\Logs
Linux Logs: ~/.local/share/Terraria/ModLoader/Logs/ or $XDG_DATA_HOME/Terraria/ModLoader/Logs/
Mac Logs: ~/Library/Application support/Terraria/ModLoader/Logs/

**Comment by egor1654** [comment]
I think you have a Pirated terraria, Boisq.

**Comment by Boisq** [comment]
> I think you have a Pirated terraria, Boisq. Try using Tmodloader v.1.10.5

ah, so thats the problem, i see

**Comment by Chicken-Bones** [comment]
Or try buying the game
