### ISSUE TITLE
Не могу войти в игру

### ISSUE THREAD

**Issue by Kush171** [tModLoader/tModLoader#643]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [And so on...]

**Comment by Kush171** [comment]
Здравствуйте! У меня был установлен TmodLoager более старой версии,а точнее 0.10.1.5 и я установил версию 1.11.3. после установки у меня не запускается игра. Что делать? поможете?

**Comment by JavidPack** [comment]
Check the logs. If you pirated terraria, it won't work.

**Comment by Kush171** [comment]
Если у меня пиратская террария то я не смогу установить tmodloager 0.11.3?

**Comment by Kush171** [comment]
Я праввильно вас понял?

**Comment by JavidPack** [comment]
Yes. That is correct.

**Comment by Kush171** [comment]
А будет ли  tmodloager 0.11.3 на пиратку?

**Comment by JavidPack** [comment]
Please do not discuss piracy. We do not condone piracy.

**Comment by Chicken-Bones** [comment]
Buy the game
