### ISSUE TITLE
Wont get to the main menu.

### ISSUE THREAD

**Issue by Thunderraiders2** [tModLoader/tModLoader#645]
When i open terraria and it gets to the loading mods thing it says a error occurred and it says the mod responsible is unknown and to restart tmodloader. when i do this it doesn't work and i tried uninstalling and installing nothing works.

**Comment by Thunderraiders2** [comment]
oops i mess up

**Comment by Jofairden** [comment]
So, have you tried running without enabling any mods?

**Comment by Thunderraiders2** [comment]
Yeah all of my mods are out of my mod folder

**Comment by Thunderraiders2** [comment]
oh there was one mod still in there now it works
