### ISSUE TITLE
Cant Install any Mods.

### ISSUE THREAD

**Issue by Thunderraiders2** [tModLoader/tModLoader#647]
When I try to download a mod it gets to the very end and stops forever, when i cancel it it says its downloaded and then i cant get into my game. I know how to get back in but I cant download any mods.

**Comment by GoodPro712** [comment]
Show logs

**Comment by JavidPack** [comment]
Try 0.11.4 and tell me if it is fixed.

**Comment by Thunderraiders2** [comment]
Yeah it’s fixed thanks
