### ISSUE TITLE
Logging injection (probably) breaks HttpClient constructor

### ISSUE THREAD

**Issue by KindRedSand** [tModLoader/tModLoader#648]
### Description
After tML 0.11 update any attempt create a new `HttClient` will fails with
```
System.MethodAccessException: Мethod "System.Net.Http.HttpMessageHandler..ctor()" can't access a method "System.Net.Logging.get_On()".
```
In tML 0.10.5 all works fine

### Steps to Reproduce
Anywhere in mod create a new `HttpClient` instance from `System.Net.Http`

### Versions
0.11.3

### Log
From dummy line `var http = new HttpClient();`
[client.log](https://github.com/tModLoader/tModLoader/files/3498407/client.log)

### Additional Information
I use `HttpClient` to easy fetch emoticons images from twitch cdn ( http://static-cdn.jtvnw.net/emoticons/v1/{id}/2.0 ) and long time can't understand why some of users don't see emoticons. All my attempts to reproduce environment will fals since i use debugging tool (VS). After redownloading mod from mod browser i found what in 0.11 version creating `HttpClient` was failing in class constructor (so, this is not my fault of using client)

**Comment by Chicken-Bones** [comment]
Please post simple test mod and full client.log

**Comment by KindRedSand** [comment]
Test mod:
[TestCase.zip](https://github.com/tModLoader/tModLoader/files/3505871/TestCase.zip)

After futher inspectation i noticed what HttpClient fails FriendlyAccess to System.Net.Logger since tML rename assembly to ModName_AssemlyName ( `TwitchChat_System.Net.Http` at least like what it shows in logs). 
// I post this issue late night so i don't inspect trace properly. Logger used by default in assembly, not injection from tML or any other source

**Comment by Chicken-Bones** [comment]
Is there a reason why you need to include System.Net.Http?
Is that not included by default in .NET 4.5?
You're right about the `[FriendAccessAllowed]` not mapping because we rename your assembly.

**Comment by KindRedSand** [comment]
`System.Net.Http` comes together with .Net redist, but not enables in assemblies by default (need include it manually or use NuGet). 
`WebClient` can't establish an SSL connection and implementation can download only one file per time (open one connection per time) what force to use `lock (webClient)` (or `Semaphore` sequence) in multithread tasks what blocks any other threads until first complete request. `HttpClient` max connections can be managed using `ServicePointManager.DefaultConnectionLimit` and awaiting result won't block thread in place.

Correct if I'm wrong

**Comment by Chicken-Bones** [comment]
You can use HttpWebRequest, or create multiple WebClient instances

**Comment by Chicken-Bones** [comment]
Send me a PM in Discord if you're still working on this, I can probably help you get concurrent downloads working

**Comment by KindRedSand** [comment]
Close this issue since it can't be fixed untill revert assembly renaming and i'm pretty sure what this never be needed for anyone in future.
