### ISSUE TITLE
[MacOS_10.14.6][Steam][TmodLoaderV0.11.3] Terraria won't start

### ISSUE THREAD

**Issue by Radamanth-Amaury** [tModLoader/tModLoader#649]
### Steps to Reproduce

1. Install Tmodloader on a working vanilla Terraria
2. Launch Terraria

### Expected behavior 

Terraria's loading screen starts normally

### Actual behavior

Terraria engine crashes and doesn't even start(visually)

### Reproduction frequency

100% (on that particular mac at least)
Other versions of Tmodloader either starts the game (and refuses to go further without newer version) or works fine(with old mod)

### Versions

tModLoader v0.11.3.X
### Mods

No mods
### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/3503370/client.log)

### Additional Information

MacOS_10.14.6 with Steam
Terraria was used with old version (0.10.x) of Tmodloader and worked. Game as been uninstalled and the folder was cleared after unsuccessful the update to v0.11.3

**Comment by JavidPack** [comment]
You messed up the install, deleting the contents of the osx folder because you did not follow step 3 in the readme correctly. Read the readme, it tells you how to restore those files and reinstall
