### ISSUE TITLE
Summon targeting broken

### ISSUE THREAD

**Issue by supercelebi14** [tModLoader/tModLoader#650]
I've discovered an issue with the summoner weapons and their staves. Whenever you use the summon targeting ability with right click it happens... Twice! Meaning two things could happen, a NPC gets targeted and then it doesn't or a NPC gets targeted and it replaces the target with a incorrect NPC. This is important as now the summoner class is more irritating and slow.

**Comment by JavidPack** [comment]
Confirmed to be working in 0.10.1.5
