### ISSUE TITLE
Item useTime, useAnimation and reuseDelay bugs

### ISSUE THREAD

**Issue by DarkLight66** [tModLoader/tModLoader#651]
### Description
Due to the change capping the minimum `useTime` and `useAnimation` to 2 ticks, any item with a `useStyle` higher than 0 that's a non-melee damage weapon and non-placeable item will have a minimum delay of 2 ticks after each use, this is due to `reuseDelay` being affected by the change, even when `reuseDelay` is set to 0, and as such shouldn't be taken into account.

The above problem extends to any item with a `useStyle` higher than 0 which had their `useTime` and `useAnimation` set to 0 for any reson, as they'll be set to the minimum of 2, and make item usable when it shouldn't.

Because of this bug, extra `useTime` delays for non-melee damage or placeable items are nullified due to `reuseDelay` not only overwriting the player's `itemAnimation`, but also their `itemTime` when the item's animation ends.

This bug is more noticeable when using using items that act like swords but with a non-melee damage type, as the item will hit a single enemy twice per use.

### Steps to Reproduce
1. Make a sword that deals damage from any damage type but melee.
2. Hit an enemy with the non-melee sword, while making sure to hit it at the very beginning of the animation.

### Expected behavior 
The sword hits the enemy once per swing.

### Actual behavior
The sword hits the enemy twice, once at the beginning and once at the end of the animation.

### Reproduction frequency
Always

### Versions
tModLoader v0.11.3

### Mods
None. Even though the example above uses an item not found in vanilla (a non-melee damage sword), the bug itself affects all items that meet the criteria.

### Additional Information
This bug is what causes #650

**Comment by direwolf420** [comment]
This behavior is noticeable with the Last Prism, print out player.itemAnimation during use and you see the value jumping when you let go of the left mouse button
