### ISSUE TITLE
Strange file permissions issues for Log files since 0.11.4

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#656]
Since 0.11.4 was released, there have been many reports of crashes due to various file issues while initializing logs. We'll need to collect those issues and find a solution

**Comment by JavidPack** [comment]
![](https://i.imgur.com/dKTtSnW.png)

Downgrading to 0.11.3 fixed the issue for this user.

**Comment by JavidPack** [comment]
![](https://i.imgur.com/mhSPkyZ.png)

I think this user fixed the issue by deleting the Logs folder, not positive, they didn't respond

**Comment by JavidPack** [comment]
![](https://i.imgur.com/Gc7Gf1T.png)

This user also had to downgrade to 0.11.3 to fix.

**Comment by Chicken-Bones** [comment]
> ![](https://camo.githubusercontent.com/a93baa49ff4b1a691823699f53d19d70e680ae82/68747470733a2f2f692e696d6775722e636f6d2f644b5474536e572e706e67)
> 
> Downgrading to 0.11.3 fixed the issue for this user.

This one seems to violate the spec of https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.createdirectory?view=netframework-4.5
