### ISSUE TITLE
Could not load file or assembly mscorlib

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#657]
Many modders are seeing issues similar to this:

```Could not load file or assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required.```

We'll track this issue here by posting various logs.

**Comment by JavidPack** [comment]
[client (24).log](https://github.com/tModLoader/tModLoader/files/3524819/client.24.log)

This log provided by Krypton Ion on Discord.
Installed v4.5 Reference Assemblies rather than Visual Studio.
Had no issues building mods on his normal computer. (This is a temp computer.)
Running .Net Framework 4.6.2

**Comment by Lithobraker** [comment]
[client.log](https://github.com/tModLoader/tModLoader/files/3528151/client.log)
Getting the same error here. I can't compile any mod at all- even a blank skeleton mod doesn't work.

**Comment by JavidPack** [comment]
Updating .net framework to 4.7.2 fixed the issue for krypton.

**Comment by Lithobraker** [comment]
Confirmed, that did the trick. Every problem except the mouse freezing in the mods menu was completely fixed- however, the freezing was caused by some older mods sitting in my mods folder- and clearing them out resolved that as well.

**Comment by GoodPro712** [comment]
Close

**Comment by Chicken-Bones** [comment]
This is probably a less common variation of https://github.com/tModLoader/tModLoader/issues/720
The main cause is at least fixed, but some mods may need to watch out for the compatibility of their dll refs
