### ISSUE TITLE
Updating a Disabled Mod Forces it to be Enabled

### ISSUE THREAD

**Issue by zauberparacelsus** [tModLoader/tModLoader#658]
### Description
When using the mod browser to update a mod that you have set to disabled, it will forcibly enable that mod.

### Expected behavior 
Disabled mods should stay disabled when they are updated.

### Versions
tModLoader v0.11.4

**Comment by Jofairden** [comment]
Well, it also begs the question, why update a disabled mod? You aren't using it. The assumption is that you want to use it when you update it

**Comment by DarkLight66** [comment]
What about the Update All button? If the user shouldn't be updating disabled mods unless they want to enable them too, then Update All button should only update enabled mods, but that's not really the function of the button.

**Comment by zauberparacelsus** [comment]
Yeah, that was the case for me, I had pressed the Update All button.  Also, sometimes I'll update disabled mods just to clear out the indicator for there being updates available, as otherwise I'll be unable to tell if there were new updates aside from ones for the disabled mods.

**Comment by Chicken-Bones** [comment]
I'll vote for updating not changing the state. It also means a reload wouldn't be required if only disabled mods are updated
