### ISSUE TITLE
ServerSide ModConfigs don't save the config to the file when receiving and accepting changes

### ISSUE THREAD

**Issue by direwolf420** [tModLoader/tModLoader#661]
### Description
If a client changes some serverside config, sends a request, server accepts it and the config updates, it never is actually written to the file. So when the server then closes and rehosts, it will use the unchanged config again

### Steps to Reproduce
Create a simple serverside config that accepts client changes
Host, join with a client, change a value and request changes
Close server, host again, join again, and check the config, it won't have the previous change in it

### Expected behavior 
Server saves the changed config just like in singleplayer inside the json file

### Actual behavior
Server never writes to the file (having the file open in n++ it will prompt you to reload the file if there were changes made, but that never happens if it's on a server. On singleplayer, it prompts you with a reload)

### Reproduction frequency
Always

### Versions
0.11.4

### Mods
The test mod with the config from above

### Log File
No logs

### Additional Information
[Related code upon "successfully applying client request"](https://github.com/tModLoader/tModLoader/blob/9455776e83860141dafb20fb8dee0e94fb560709/patches/tModLoader/Terraria.ModLoader.Config/ConfigManager.cs#L243)
Maybe if there is a usage for non-permanent configs, make a property in ModConfig to allow or not allow saving to file on change

**Comment by JavidPack** [comment]
Thanks for making this issue, it really helps to track bugs.
