### ISSUE TITLE
(Suggestion) Gui is extremly unorganized and desperately needs to be fixed

### ISSUE THREAD

**Issue by RyguyG** [tModLoader/tModLoader#667]
The searching Gui is very unorganized there are no genres of what it adds Examples "Bosses" "Town Npcs" "Cosmetics" "Enemies" basically a mod maker when uploading there mod choose what genres they fit with (which would be mandatory) another thing that would be mandatory is a detailed mod description basically in the mod description its mandatory to state

.How many items, enemies, bosses, town npcs and biomes it adds (if it adds 712 items state 700+ items added)

. what piont in the progression the mod adds to so it would state if it adds content to  

early/mid/late pre hardmode or hardmode
.
.if they plan to expand upon the mod/or if the mod is no longer developed

this brings up a question on how you would uphold this

basically when your creating an account on something it says "This field is required"

have a system similiar to this if they dont add any genres say "atleast one genre required" basically it would be a list of all the genres and you need to click one of them at the least

for the proggresion piont something similair to the m/d/y you have to fill in when creating account

E/M/L (early middle or late) Hardmode   E/M/L Pre hardmode
 you would pick to all that apply

Do you plan on updating this mod Y/N/M ( Yes No or Maybe)

With the what content it adds simply add

Example 

Bosses (choices) 1/2/3/4/5/5+/10+/15+/20+/50+/100+200+

same with items or town npcs

Complete list of searchable genres there should be/what mod makers can choose as a category

Npcs

Npc categorys

-Bosses
-Mini Bosses
-Events
-Enemies
-Town npcs

-Items

Item Categories

-Accessories
-Weapons
-Cosmetics
-Expert Items
-Tools
-ores

Biomes

Biome categories

-Surface
-Underground
-Mini
-Hell
-Sky

E/M/L Hardmode or Pre Harmode

anything i have not listed but is said is only said when you click on the mod

so when i said adds 1/2/3/4/5/5+ of an item or boss ect

that would only show when your in the mods description

Shortened version

Mandatory description
-how much content it adds and what content it adds
-When in progression does it add it E/M/L Pre harmode or hardmode
If the mod will be continually developed Y/N/M

Search by genre
-Biomes
-Npcs
-Items
-E/M/L Pre Hardmode or Hardmode

One last thing instead of scrolling through mods can we have pages the scrolling feature is only usefull when you want to go to the very bottom or very top having a page listing 20 mods then clicking to the next one would be so much easier

Sorry if this is a lot to read but it would make tmodloader easier to use and control low effort descriptions the thing that made me want to write this is mostly mod descriptions how a bunch of people just trying to be funny when in reality its just low effort and a lot of smaller mods would get a lot more appreciation and people trying out there mod if they put an actual description instead of "Check out my mod plz OwO" or "Play the mod to know whats in it"

**Comment by BigBoyBrine** [comment]
Well, a mod isn't quantified by the number of things it has. This would only lead to people artificially inflating item and boss count even more for more downloads, since genuine content doesn't just come in a number.

**Comment by Chicken-Bones** [comment]
See #245
I'm in favour of tags, possibly community regulated.
Mods with poor descriptions just don't get downloaded, and that's the author's responsibility. Quality and care go hand in hand

**Comment by RyguyG** [comment]
> Well, a mod isn't quantified by the number of things it has. This would only lead to people artificially inflating item and boss count even more for more downloads, since genuine content doesn't just come in a number.

I never said it did i totally agree that a big mod does not mean a good mod quality over quantity but yes i see what your saying with people lying to get more mod downloads the thing is i have never seen this happen i have never gone to a mod description that says it adds alot of items but it doesnt i have never seen anyone lie in there description also if they did a rating system could be in place a simple 0-5 stars

**Comment by RyguyG** [comment]
> See #245
> I'm in favour of tags, possibly community regulated.
> Mods with poor descriptions just don't get downloaded, and that's the author's responsibility. Quality and care go hand in hand

thanks for reading this and i agree with you but one thing that would make descriptions a lot better just by adding one requirment is the

E/M/L pre hardmode or hardmode requirment if that was just added that would be a massive improvment

and the reason is even good descriptions on mods usually dont state what time in the progression content is added

**would make it so much easier to make modpacks** 

again thank you for taking the time to read this and respond

**Comment by Jofairden** [comment]
Closing this in favor of #245 which is a long-term endeavor.
