### ISSUE TITLE
i want to play terraia mods but there's an error

### ISSUE THREAD

**Issue by ineedausernamehelp** [tModLoader/tModLoader#669]
so i will start up tmodloder but when it says that the mods are installing i get an error

here's the screenshot: 

![Schermopname (7)](https://user-images.githubusercontent.com/54716860/64032617-24174000-cb4b-11e9-9a3a-ca887fc1d420.png)

and here are the files
[steam_appid.txt](https://github.com/tModLoader/tModLoader/files/3560545/steam_appid.txt)

[changelog.txt](https://github.com/tModLoader/tModLoader/files/3560546/changelog.txt)

[README.txt](https://github.com/tModLoader/tModLoader/files/3560547/README.txt)

[serverconfig.txt](https://github.com/tModLoader/tModLoader/files/3560548/serverconfig.txt)

**Comment by ineedausernamehelp** [comment]
sry i clicked enter

**Comment by JavidPack** [comment]
None of these files are the client.log file.  C:\Documents\My Games\Terraria\ModLoader\Logs\client.log

The issue might be a duplicate or misnamed .tmod file in   C:\Documents\My Games\Terraria\ModLoader\Mods. You should probably check that first, look for ModName (1).tmod or similar renamings.

**Comment by ineedausernamehelp** [comment]
ty it worked
