### ISSUE TITLE
hideResources doesn't stop resources from being extracted

### ISSUE THREAD

**Issue by Ozzatron** [tModLoader/tModLoader#673]
### Description
hideResources in build.txt doesn't stop resources from being extracted

### Steps to Reproduce
1) Enable developer mode in TML 0.11.4
2) Download a mod known to have hidden assets from the Mod Browser (ex. Calamity Mod)
3) Open mods menu and press Extract on that mod

### Expected behavior 
The extracted content folder contains no resources (sprites and sounds mostly).

### Actual behavior
Sprites and sound files are present in the extracted content folder.

### Reproduction frequency
100% with Calamity, DarkLight has tested this issue with Thorium as well.

### Versions
0.11.4 tModLoader
Possibly earlier versions
Does NOT work on 0.10.1.5 tModLoader

### Mods
No mods need to be enabled to reproduce this behavior, it occurs in TML's menus.

### Additional Information
In the extracted content folder, the build.txt is missing lines. Notably, it's missing the lines hideCode and hideResources.

**Comment by Sharkanoly** [comment]
are you gonna tell me where the extracted content folder is?
