### ISSUE TITLE
API restructuring (Terraria.ModLoader namespace)

### ISSUE THREAD

**Issue by Chicken-Bones** [tModLoader/tModLoader#674]
The core ModLoader namespace has always suffered from scope creep and bloating. Some classes have been moved to the Core and Engine namespaces, but there's currently no bookkeeping thread for  the class list and naming conventions. First we'll categorise all classes in this namespace, then we'll provide refactoring/restructuring suggestions. Most of this will likely not happen till 1.4 for compatibility but we should be prepared with our designs.

### Content Classes
These classes correspond to Terraria game objects, and need to be tracked by tML with data and hooks. Instantiated at load time.

| Content | Global | Loader | Extra |
| -- | -- | -- | -- |
|Mod||ModLoader|ModProperties, ModSide|
|ModBackgroundStyle|GlobalBackgroundStyle|BackgroundStyleLoaders||
|||BackgroundTextureLoader||
|ModBuff|GlobalBuff|BuffLoader||
|ModCommand||CommandLoader||
|ModDust||DustLoader||
|EquipTexture||EquipLoader|EquipType, AutoloadEquip|
|ModGore||GoreLoader||
|ModKeybind||KeybindLoader||
|ModItem|GlobalItem|ItemLoader||
|MapEntry||MapLoader|MapLegend|
|ModMount||MountLoader|MountTextureType|
|ModNPC|GlobalNPC|NPCLoader|NPCSpawnInfo|
|||NPCHeadLoader|AutoloadHead|
|ModPlayer||PlayerLoader||
|ModPrefix||PrefixLoader||
|ModProjectile|GlobalProjectile|ProjectileLoader||
|ModRecipe|GlobalRecipe|RecipeLoader||
|ModSound||SoundLoader|SoundType|
|ModTile|GlobalTile|TileLoader||
|ModTileEntity||missing||
|ModTranslation||LocalizationLoader||
|ModWall|GlobalWall|WallLoader||
|ModWaterStyle||WaterStyleLoader||
|ModSystem||SystemLoader||
|ModTree/ ModPalmTree/ ModCactus||> TileLoader||
|PlayerDrawLayer||PlayerDrawLayerLoader||

### Utility Classes
Public classes which are used by mods to interact with hooks or perform common functions. Instantiated during gameplay. Classified as either hooks or helpers.

|Class|Designation|
| -- | -- |
|DrawableTooltipLine|Hook|
|DrawInfo|Hook|
|DrawLayer|Hook|
|ModPacket|Hook|
|NPCSpawnHelper|Helper|
|RecipeGroupHelper|Helper|
|MusicPriority|Hook|
|TooltipLine|Hook|

### ModLoader Core Classes
Core mod content management classes, with public functions mods are expected to use.

|Class|
| -- |
|CombinedHooks|
|ErrorLogger (Deprecated)|
|FrameworkVersion|
|Logging|
|ModContent|
|ModNet|
|MonoModHooks|
|TopoSort|
|MusicWrappers|

## Proposed Refactors

- [x] ~ModProperties -> AutoloadProperties~ removed
- [x] Move helper utilities to "Helper" or "Utilities" sub-namespace
- [x] ~Check ModUgBgStyle/ModSurfaceBgStyle for common code~ unified via ModBackgroundStyle
- [x] ModMountData -> ModMount
- [x] Loader vs Hooks naming. Currently roughly LoaderX if GlobalX exists, otherwise HookX. Should we keep this, and fix the non-conformers, or just pick one and stick to it.
- [x] Missing loader classes. Should all static bookkeeping be done in a separate Loader/Hook class? Most of the missing loader classes just weren't made because there weren't enough hooks required, or just a single id array/dictionary.
- [x] Mod Translation loader, the autoloader is currently in ModInternals, and ModContent handles all the Translation -> LocalizedText updates, should we split this out?
- [x] Pretty much every content class has common fields `Mod mod; string name;`. Make a parent class for all tracked mod content.
- [x] Move all autoloading code out of Mod, or at least to partial class with more shared code between functions
- [x] Merge a lot of the Mod.AddX common code, and move the other parts to the loader classes]

**Comment by Jofairden** [comment]
I approve of this discussion.

I'd like to see appropriate loading classes for the ones that are missing, like ModDust and ModGore etc. I think sticking with the one approach keeps things clear/concise/separated. Let's not over complicate the ideas/design, even if for some they'd be very low LOC classes. (With a Loader class at least everyone would know where to look, even non api developers, without having to think about it)

I am missing a part for our UI classes. We have been refactoring some of it lately. I recall we discussed the current mess that is swapping/activating to new UIs, where we check for the menu ID and then activate the menu with a giant if-else chain. I'd like to see a simple manager for this, where we (internally) just register our own UI classes and they get assigned their unique IDs and can get activated. We propagate to it from vanilla in a fashion like `UIManager.ActivateUI(id)` or something.

For ModPacket it'd be nice if modders can just instantiate it as a new object rather than a hook: `new ModPacket()`. Can we just check the calling site and set the calling mod as the sending mod for the instantiated packet? [ Rather than GetModPacket()? ]

**Comment by Chicken-Bones** [comment]
Callsite detection is never recommended, due to terrible performance. Unfortunately they need some way to get their mod id into the packet, which means some sort of reference. We should seriously review ExampleMod and bring in tons of good design practice, but yikes, who has time for that.

tML's `Interface.cs` should defintely be way less copy paste than it is. We really don't even need all the ids

**Comment by Jofairden** [comment]
`We should seriously review ExampleMod and bring in tons of good design practice, but yikes, who has time for that.`
🤣 Too accurate

`tML's Interface.cs should defintely be way less copy paste than it is. We really don't even need all the ids`
Agreed, and I think it's one of the primary focuses for improvement here.

**Comment by JavidPack** [comment]
I want to make sure we throw an error in XType and GetX, rather than return 0 or null. A TryGetX or something would be needed.

Returning 0 isn't usually an issue, but it's a little weird.

**Comment by Chicken-Bones** [comment]
This is mostly done. Closing.
Remaining issues #1347, #1506
