### ISSUE TITLE
calamitymod does not exist on the browser.

### ISSUE THREAD

**Issue by blehhi** [tModLoader/tModLoader#675]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [And so on...]

**Comment by JavidPack** [comment]
It does. Make sure you are on 0.11.4, that you don't already have the mod, and that you are spelling it right in the search. Here is an alternate link if you need it: http://javid.ddns.net/tModLoader/download.php?Down=mods/CalamityMod.tmod

**Comment by blehhi** [comment]
Sorry, what i meant was it isn't on mine, I might disable it and then
update tmod, sorry for being late and sorry if I wasted your time. Hope you
have a good day, Thanks!
