### ISSUE TITLE
tModLoader for Terraria Mobile?

### ISSUE THREAD

**Issue by DayatXD** [tModLoader/tModLoader#677]
Can we get tModLoader Support for Terraria Mobile?, so we can load a PC Mod into Mobile Terraria like Stardew Valley SMAPI Mobile did!

**Comment by Chicken-Bones** [comment]
It might be technically possible. I can guarantee it'd take hundreds or thousands of hours to develop though. We don't have that time. But nothing's stopping someone who does

**Comment by Slimemaster0** [comment]
Actualy it is possible by making the Terraria for PC run on mobile, and as im writing this comment its allrady been done, however i have only been able to find prebuilt apks making using this build piracy.

Edit:
Tldr: There are 3 diffrent ways to run tModLoader on android. (All metheads use the PC build and are 100% legal if you own the PC build)
  1: Emulation: run tML with something like Winlator.
  2: Termux (Native): Patch tML to run on AArch64 linux then run that build using termux.
  3: Native: Patch tML to run on android natively, idealy providing a script to build an APK from the pc version.

**Comment by ghost** [comment]
@Slimemaster0 can you help me turn it into an apk? my discord is killerdogeempire.
I own terraria and want to use tmodloader on android
