### ISSUE TITLE
Linux initialising mods exhausts file descriptor limit

### ISSUE THREAD

**Issue by fsckmc** [tModLoader/tModLoader#678]
Hi there,

On the latest release of tModLoader (v0.11.4) if I install a large number of mods on Linux, whenever I restart the game when it tries to initialise the mods I get a segfault due to lack of open file descriptors, other applications also start to crash on my system.

My fd limit is 65535 and I've verified that it is indeed opening handles and not closing them properly, I'm assuming it's because the handles are only closed after loading them fully, which in this case never happens.

Perhaps we could close the file descriptors after every mod is loaded and the assembly is in memory?

**Comment by Chicken-Bones** [comment]
Hoo boy how many mods are we talking. 1 fd per mod is how I implemented it.

**Comment by fsckmc** [comment]
20 mods, when it loads the tmod it opens a file descriptor for every cs file

**Comment by zauberparacelsus** [comment]
I've used more than 20 mods on tmodloader 0.11.4 under Linux without exhausting file descriptors.

What mods do you have installed?  It's entirely possible that one of those mods is opening tons of files.

**Comment by fsckmc** [comment]
Have they already been compiled? I went from 0 mods to 20 in one instance, when I restarted it crashed repeatedly. I guess that's not a normal use case, but you may have installed them gradually.

**Comment by Chicken-Bones** [comment]
I think we did figure this out eventually? But it was a really strange quirk of your system, something todo with texture uploading to the GPU?
