### ISSUE TITLE
Could not find the "mod source" on main menu,,

### ISSUE THREAD

**Issue by MeteorAtNorthGate** [tModLoader/tModLoader#679]
I used the v0.11.4 release for windows, install it with running tModLoaderInstaller.jar. But on terraria's main menu, I Could only find "Mods" and "Mod Browser". Did I missed something? 
### Versions

tmodloader 0.11.4
terraria 1.3.5.2

### Mods

none

**Comment by JavidPack** [comment]
What guide are you looking at?

The guide should mention the Enable Developer Mode button on the bottom right corner of the screen. You need to press that.
