### ISSUE TITLE
TML failed to load textures for hidef graphic devices

### ISSUE THREAD

**Issue by cc004** [tModLoader/tModLoader#684]
### Description

When a shader or texture is compiled to hidef device, the tml failed to load with an exception "
XNA Framework Reach profile supports a maxium Texture2D size of 4096. However, hidef texture should be supported in 0.11 (HiDef defaults to true regardless of resolution (better shader support)).
### Steps to Reproduce

Load a Texture2D xnb bigger than 4096.

### Reproduction frequency

Always

### Versions

tModloader v0.11.4

### Mods

FallerStar49 or RainbowFlouresense

### Log File

There's no log file but a loading error screen shot, for somebody else has this issue and I solved it with dnspy.
![QQ图片20190921223506](https://user-images.githubusercontent.com/34051396/65374777-4884b900-dcc0-11e9-972c-9b1191c242de.jpg)

### Additional Information

This issue can be solved by changing the content of resource file Microsoft.Xna.Framework.RuntimeProfile to "Windows.v4.0.HiDef".

**Comment by Chicken-Bones** [comment]
1.4 is now HiDef only
