### ISSUE TITLE
Cursor is incredibly laggy

### ISSUE THREAD

**Issue by DerpyGuy33** [tModLoader/tModLoader#685]
The game starts up fine, but as soon as I click on one of the menus on the home screen, the cursor, the sun in the background and the Terraria logo start to lag a lot to the point where they don't even move, but everything else is fine.

**Comment by JavidPack** [comment]
A laggy cursor is not something we have seen reported. If you could post your client.log file, that would help a lot.

**Comment by GoodPro712** [comment]
This is just caused by low ram left, probably close

**Comment by Solxanich** [comment]
Hello @DerpyGuy33,
I'm currently reviewing stale issues, and would like to confirm if you are still experiencing this issue in the latest version 0.11.8.1 of tModLoader.
If not, could you please close the issue?
If so, could you please provide the most recent information from its occurrence?
