### ISSUE TITLE
Game crashes when opening mod browser

### ISSUE THREAD

**Issue by TheRealKingslayer51** [tModLoader/tModLoader#686]
Desc:
As the title says, the game crashes whenever I open the mod browser in modloader 0.11.4

Frequency:
This happens on a 100% basis, without fail 

I've loaded it up without mods, an with them, it still harbors the same result.
I can provide a list of mods if necessary, but it is quite a long list.

**Comment by JavidPack** [comment]
Disable all your mods, then close and reopen tmodloader, and try again. I just tested and it's working fine for me.

If that doesn't work, you can post the client.log file in the logs folder here.

Another possibility is that imgur is banned in your country. If you know that imgur is banned in your country, edit the config.json file and set AvoidImgur to true, save, then open terraria.
