### ISSUE TITLE
Mod loading cancellation and unload behavior

### ISSUE THREAD

**Issue by direwolf420** [tModLoader/tModLoader#688]
### Description
EDIT: Got the answer, updated the mod appropriately (reproduction steps won't work anymore).

Cancelling mod loading at a point where a mod (that has an `Unload` override that depends on data being present set in `Load`) hasn't loaded yet causes unload exception.

Disclaimer: The unloading error message says: "Modders must use defensive programming to ensure unloading completes regardless of any errors during loading." Which I obviously violated here, but I am working under the impression that a mods Unload is only called when Load was.

### Steps to Reproduce
1. Download Vinelight from mod browser (my own mod with a faulty unload)
2. enable a bunch of other mods so loading takes a few seconds
3. cancel mod loading as soon as a bunch of mods start loading

### Expected behavior 
`Mod.Unload()` will be called on all loaded mods _so far_ in reverse alphabetic order

### Actual behavior
`Mod.Unload()` is called on all enabled mods (loaded or not) in reverse alphabetic order

### Reproduction frequency
100% with the steps above

### Versions
0.11.4 (and 5)

### Mods
Vinelight
handful of other random mods to artificially prolong loading time

### Log File
```
[13:15:39] [16/INFO] [tML]: Instantiating Mods...
[13:15:39] [16/INFO] [tML]: Initializing: ModLoader v0.11.4
<other mods loading here>
[13:15:40] [1/INFO] [tML]: Loading Cancelled
[13:15:40] [16/INFO] [tML]: Unloading: Vinelight
[13:15:40] [16/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException
```

### Additional Information
Code responsible for this error to occur:
```cs
public override void Unload()
{
	// vinesThatBlockLight initialized in Load()
	for (int i = 0; i < vinesThatBlockLight.Length; i++)
	{
		Main.tileBlockLight[vinesThatBlockLight[i]] = true;
	}
	vinesThatBlockLight = null;
}
```

**Comment by Chicken-Bones** [comment]
Reasons we can't do that.
A. Errors can happen at any point during load, including an inter-mod
conflict.
B. Some mods do things in constructors
C. There are multiple load phases

But I do hear you and it is confusing. It was a difficult decision to make
but I couldn't see a reliable alternative.

**Comment by Jofairden** [comment]
Yep, just wrap the vinesThatBlockLight reset in a nullcheck
