### ISSUE TITLE
[Suggestion] ModNPC Emote Chance Adjustment 

### ISSUE THREAD

**Issue by Plantterror** [tModLoader/tModLoader#689]
**Reference:** https://terraria.gamepedia.com/NPCs#Emotes

An idea I've had for a while is to allow adjustment of the emote chances of ModNPCs. Similar to how the arms dealer causes more "angry" emotes when talking to the guide, there should be a similar hook to adjust the chances of each emote. Also should be usable in GlobalNPC to change the vanilla NPCs, if needed.

From the Wiki, it shows many different examples of what needs to be true in order to increase the chances of a certain emote. Focusing more on the "Specific NPC Behavior" tab, there should be options to filter also by talking to a specific NPC or during a certain event.

Probably is deserving of it's own class. In which case, a fitting name would likely be ``ModifyNPCEmotes``.

**What does this change?**
This is more of a vanity/lore change that could be applied, but it can help the Modded NPCs stand out more compared to the vanilla ones. 

**Optional Ideas**
- Adding your own custom dialogue emotes.
- extra emote settings for Modded Events (Spirit's Blue Moon, etc), in a certain Modded Biome (Calamity's Sulfurous Sea, etc), after beating a certain Modded boss (Fargowilas's Duke Ex, Bluemagic's SOP, etc)

**Examplemod Changes**
-Exampleperson reacts with angry emotes against the painter
-ExampleBiome gets it's own emote (Template bubble?)
-Exampleperson gets it's own emote (when he is alive in the world)

EDIT- clarified things, added more ideas

**Comment by GoodPro712** [comment]
Do this yes.

**Comment by Plantterror** [comment]
I did want to add that there are town NPC head emotes too, so maybe autoloading that with the NPC could be done?

**Comment by cheeeeeeeeeen** [comment]
I want to add the the NPC emotes also vary when you defeated a certain boss already. Would be great to see them talk about Mutant or any other mod bosses.

**Comment by Jofairden** [comment]
I'm closing this issue for now; 1.4 is coming with player-usable emotes. It is extremely likely this becomes moddable with TML. "Stay tuned"

**Comment by Jofairden** [comment]
Actually, gonna re-open. Will use this issue as reference.

**Comment by JavidPack** [comment]
This should now be possible with the GlobalNPC.PickEmote hook that will soon be in Preview. It was added in https://github.com/tModLoader/tModLoader/pull/2918
