### ISSUE TITLE
Error thrown when adding new value to a <string, int> dictionary through the ModConfig UI

### ISSUE THREAD

**Issue by atenfyr** [tModLoader/tModLoader#692]
### Description
Attempting to add a new field to a <String, int> dictionary through the ModConfig UI results in the error "Cannot populate JSON object onto type 'System.String'" thrown.

### Log File
[client.log](https://github.com/tModLoader/tModLoader/files/3721000/client.log)

### Steps to Reproduce
1. Create a mod with a config file which contains a dictionary mapping Strings to ints.
2. Click the Add button (marked with a plus sign).

### Expected behavior 
A blank key mapped to a blank value should be added to the dictionary and displayed in the UI.

### Actual behavior
The error "Cannot populate JSON object onto 'System.String'." is thrown and displayed in the notification bar. The dictionary and the UI are not noticeably modified in any other way.

### Reproduction frequency
Consistently.

### Additional Information
In issue #626, the sample mod I attached ([DictionaryYikes.zip](https://github.com/tModLoader/tModLoader/files/3434134/DictionaryYikes.zip)) which worked at the time it was created (tModLoader v0.11.3) now produces the same error consistently (tModLoader v0.11.5), meaning that this is likely not my own mistake.

**Comment by direwolf420** [comment]
String or string? string can be null by default hence the error maybe.
Do you have a [JsonDefaultDictionaryKeyValue("\"\"")] attribute above your dictionary declaration?

**Comment by atenfyr** [comment]
> 
> 
> String or string? string is null by default hence the error maybe.
> Do you have a `[DefaultDictionaryKeyValue("")]` attribute above your dictionary declaration?
> I can confirm your error occurs when I don't use this attribute, and doesn't occur if I use it

Yeah, I haven't written anything in C# for a while, so my bad with the capitalization.
Is DefaultDictionaryKeyValue a new feature? It doesn't seem to be listed in the list of things that mod authors must change.

**Comment by direwolf420** [comment]
It was added in 0.11.4 
https://github.com/tModLoader/tModLoader/blob/v0.11.4/ExampleMod/ExampleConfig.cs?ts=4#L317

**Comment by atenfyr** [comment]
> 
> 
> It was added in 0.11.4
> https://github.com/tModLoader/tModLoader/blob/v0.11.4/ExampleMod/ExampleConfig.cs?ts=4#L317

It would be ideal if there was a default that it lied back on, but thank you!

**Comment by direwolf420** [comment]
"ModConfig now supports default values for reference fields, greatly simplifying ModConfig code"
from 0.11.4 changelogs
basically just look at ExampleConfig again

**Comment by direwolf420** [comment]
And there is a default for primitive non-null types
string isnt one of them, it can be null when you initialize it
```cs
int i; //implicitely 0
string s; //null
```

**Comment by JavidPack** [comment]
This is a bug, thanks, fixed. Having to use DefaultDictionaryKeyValue is not intended.
