### ISSUE TITLE
A somehow unknown issue with Tmod installer program.

### ISSUE THREAD

**Issue by TheOfficialUncleBoneless** [tModLoader/tModLoader#693]
Latest Java installed
Tmod loader downloaded, Windows v0.11.5
Terraria v1.3.5.3 from Steam

The instructions are simple and clear, couldn't be easier as long as you just read through the list.. But for some reason it seems like nothing that should be happening when I do what the list tells me is _happening._

And I've already taken three different measures for this, tried to find video walkthroughs as recent as July of this year, I've looked for properties that don't exist and I've downloaded this program **5 times in a row** having to delete each one because the files literally do nothing.

You'd think the "issues" tab of this entire operation would have what I need, "Excellent, download of modloader isn't working for Windows, here's all the reasons why it could possibly be happening, right here for everyone to see" But lo and behold, what do I find?

**There is not a single document, thread, video or study on why this simple download decides that it's not going to function as anything but a text file**. There are no issues in this entire list that try to ask the question "why the f is this just not working, I've done everything it asked" so this is a problem that only I seem to have (as far as I've been able to find out for the past half hour) and nobody even thought it was a possibility!

You got anything for this one? Am I braindead? Is my computer broken? Are the instructions outdated? How is it that this has never been asked before? Just a paragraph or two of your time, please.

**Comment by JavidPack** [comment]
So, the zip file is acting like a text file? That doesn't seem like a familiar issue we've had. For this kind of thing, visiting the support chat in the discord will get you the fastest help: https://tmodloader.net/discord

If you want to continue here, I'll need screenshots of the issues you are having, with screenshots of what you are trying to open and what is happening.

**Comment by TheOfficialUncleBoneless** [comment]
This could be very helpful, thank you.. I've gotten over the initial frustration for a while now, this has never happened with a download before so I'm questioning a couple things. I'll try this discord first.

**Comment by DrPyxel** [comment]
Have you tried changing the file extension of the text file toba zip file? Or use third-party software like 7-zip to try and extract it?
