### ISSUE TITLE
Browser problem

### ISSUE THREAD

**Issue by Endermnce** [tModLoader/tModLoader#697]
I have waited a few days trying to use the mod browser but it keeps saying its offline. It worked before but not now. My internet is fine and I allowed to go through the firewall.

**Comment by zauberparacelsus** [comment]
Yeah, its down for everyone.  I don't know any further details, however.

**Comment by Endermnce** [comment]
Thank you either way.

**Comment by osciuto77** [comment]
Same problem with V0.11.5 on Linux Mint 19.2 no proxy older version 0.10 works fine.
[client.log](https://github.com/tModLoader/tModLoader/files/3753189/client.log)

**Comment by JavidPack** [comment]
Mod Browser is back, those with linux specific issues can see #670
