### ISSUE TITLE
Some mods are stuck on downloading.

### ISSUE THREAD

**Issue by Fredyflugger** [tModLoader/tModLoader#698]
### Description

Bunch of mods are stuck on empty downloading, someone on forums said the same.
Every mod from the list on the screenshots below is stuck on downloading.

terraria v1.3.5.2
tModLoader v0.11.5

### Screenshots
https://i.imgur.com/v1aILEo.png
https://i.imgur.com/WPEslj6.png
https://i.imgur.com/WbS1r1k.png

### Additional Information

I tried installing mods on vanilla terraria.
I'm on PC win10. Tried using VPN, didn't help.

**Comment by osciuto77** [comment]
Same problem with V0.11.5 on Linux Mint 19.2 no proxy older version 0.10 works fine.
[client.log](https://github.com/tModLoader/tModLoader/files/3753187/client.log)

**Comment by Fredyflugger** [comment]
Fixed now.
