### ISSUE TITLE
Other backgrounds show in main menu

### ISSUE THREAD

**Issue by GoodPro712** [tModLoader/tModLoader#701]
### Description
When you load into a world that has a forest background when your about 85% loaded into the world it changes the main menu background to the forest background. When exiting that world, the main menu stays with that background.

### Steps to Reproduce
Go into a world that has a forest background at its spawn point. If you need be Im abke to send a world that it happens on

### Expected behavior 
It should stay the one background as the main menu (173 front, 172 middle, 171 back

### Actual behavior
It changes to a differant background

### Reproduction frequency
Whenever I go into my world

**Comment by GoodPro712** [comment]
https://discordapp.com/channels/103110554649894912/534215632795729922/637388818751815702

this background is one that can be shown

**Comment by GoodPro712** [comment]
This can hapoen with like 5 sets of backgrounds from what i have tested

**Comment by JavidPack** [comment]
This is intended behavior
