### ISSUE TITLE
Load Cancel skips loading ModLoaderMod

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#702]
The fix for this will likely fix #695 , but I'm not positive.

Mod load canceling doesn't force a reload, breaking the game if you attempt to load a character.

**Comment by Plantterror** [comment]
That's probably the issue I'm running into, since clearing enabled.json doesn't have this effect, and neither does holding shift. 

Best of luck on fixing it. Close #695 in that case?
