### ISSUE TITLE
Mouse Cursor Frozen After Unloading World

### ISSUE THREAD

**Issue by zauberparacelsus** [tModLoader/tModLoader#706]
### Description
When unloading a world, my mouse cursor is frozen.  I am required to force-kill Terraria and restart it if I want to load another world.

### Log File
[client.log](https://github.com/tModLoader/tModLoader/files/3801406/client.log)

### Steps to Reproduce
1. Open a world
2. Save and quit
3. Attempt to move the cursor

### Expected behavior 
The cursor should move

### Actual behavior
The cursor is not moving

### Reproduction frequency
Every single time I unload a world today

### Additional Information
Copy of enabled.json file: 
[enabled.json.txt](https://github.com/tModLoader/tModLoader/files/3801408/enabled.json.txt)

**Comment by Plantterror** [comment]
Are all your mods updated to the latest version? Hold shift while loading mods and obtain the latest from the Mod Browser, then see if the problem persists.

**Comment by zauberparacelsus** [comment]
Yeah, this occurred after I updated all of my mods that had updates available.

**Comment by direwolf420** [comment]
update HamstarHelpers to v5.3.1.1

**Comment by zauberparacelsus** [comment]
That fixed it, thanks!
