### ISSUE TITLE
Game Freezes when opening mod list, and crashes when I try to download mods. It also will crash once it finishes loading up a world.

### ISSUE THREAD

**Issue by ShotTarsier90** [tModLoader/tModLoader#707]
Like the title of this issue states, I’ve been having three unique issues that all lead to the same result, the game shuts down. Now let me clarify something, this has only happened recently when I decided that I wanted to get back into playing modded terraria. I had originally been using I think version 10.5 before it asked me to update it to the latest version, which I did. Thinking that not much would’ve changed, I went in to check my mods and found nothing strange occurring with the exception of not being able to delete unwanted mods. Then I decide to try and download more mods. This is where everything finally started going bad. I tried searching for mods but nothing would show up. In fact, I’m pretty sure that the thing just completely froze and wouldn’t let me type or move my cursor, despite the still animated background showing that it hadn’t truly froze. I close the game using task manager and reopened it, thinking that I just needed to restart the game to fix the issues. But that apparently made everything much worse. Trying to look at my mods would result in the complete disabling of my cursor’s movement, essentially freezing the program with the exception of the animated background of terraria. I shut down the game again and reopened it, planning on instead trying to just download more mods. The second that I clicked on “browse mods”, the game crashed and a very lengthy and confusing error message appeared in terraria’s place. I closed the message and decided to just throw everything else out the window and just play with what I already had on there. However, this resulted in the game fully loading the world, freezing right as it starts showing the area that I spawn in, then crashing without an error message. I tried over and over and over again to make it work, downloading 11.4 and trying it with no luck, resetting terraria and then reinstalling 11.5 with no luck again. I’m probably the most confused that I’ve ever been in my life right now. I don’t know if this is and issue with TModLoader, Terraria, the way that I install it, or if it’s just my computer. Someone please help me. I’m starting to get bored of modded Minecraft and of playing the other games that I have on steam. I want to play terraria again, but I don’t want to play vanilla, which has been to only way so far for me to play the game. I’m sorry that this has been so long but I needed to lay out every detail of what happened and what I did. I’m pretty sure that these issues are stemming from me doing something wrong but I don’t know what I could be doing wrong. And yes, I’ve been downloading the right files (the windows files to be specific).

**Comment by JavidPack** [comment]
Seems like there is a lot going on here, I'd suggest coming to the discord chat to quickly identify the issue: tModLoader.net/discord

**Comment by GoodPro712** [comment]
Is this solved? Did they join?
