### ISSUE TITLE
ModRecipe.ConsumeItem is insufficient

### ISSUE THREAD

**Issue by hamstar0** [tModLoader/tModLoader#708]
### Description
There exists no easy way to get the exact ingredient items (nor their array indices in the player's item inventory) that a recipe uses for its crafting. Also, for recipe group ingredients of an item's recipe, `ConsumeItem` is only supplied the item type representing the recipe group; not the item type of the ingredient being used itself. Neither behavior is convenient for some uses (e.g. [Dynamic Invasions mod's "Cross Dimensional Aggregator" recipe](https://github.com/hamstar0/tml-dynamicinvasions-mod/blob/master/Items/CrossDimensionaAggregatorItemRecipe.cs)).

### Log File
Not relevant.

### Steps to Reproduce
Probably a tango.

### Expected behavior 
Leaves the toilet seat down.

### Actual behavior
...it's on the ceiling.

### Reproduction frequency
1 Hz.

### Additional Information
There's too much already.

**Comment by Chicken-Bones** [comment]
If this would be a breaking change, by all means PR a solution and we'll
put it on a branch for 1.4

**Comment by hamstar0** [comment]
I think a separate `ConsumeItemAt` hook to specify item and item index in the inventory might work.

**Comment by JavidPack** [comment]
Handled in #2716, it seems
