### ISSUE TITLE
Begin has been called before calling End after the last call to Begin error with all mods disabled

### ISSUE THREAD

**Issue by Witherking25** [tModLoader/tModLoader#712]
### Description

When I press the options button after i pause the game my game crashes to desktop and tells me System.InvalidOperationException: Begin has been called before calling End after the last call to Begin. Begin cannot be called again until End has been successfully called.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/3829230/client.log)

### Steps to Reproduce

1. load tmodloader on ubuntu 18.04.3
2. Load a world
3. press escape and press the options button
4. Get crashed to desktop

### Expected behavior 

the options button should not crash me
### Actual behavior

nasty crash preventing me from saving my game
### Reproduction frequency

almost every time even with all my mods disabled
### Additional Information

i was able to get it to not crash once, but i dont know how i did it

**Comment by JavidPack** [comment]
Just because you unloaded mods doesn't guarantee that a mod with a bug isn't affecting things. Close the game after disabling all mods and see if you get the same error on a fresh start of the game, then post the log file if that is the case.

**Comment by Witherking25** [comment]
i unloaded everything, restarted the game, loaded a world and pressed the settings button and the crash still happened
[client.log](https://github.com/tModLoader/tModLoader/files/3856075/client.log)

**Comment by JavidPack** [comment]
I don't see anything, but on Linux we can't capture all the relevant errors in the logs, so we don't quite always know the issue. 

My other suggestion is to rename the ModLoader save folder to ModLoaderOld and seeing if it works then on a fresh launch of the game. There have been some cases of a bad file in the ModLoader folder crashing the game, such as input profiles.json or config.json.

**Comment by Witherking25** [comment]
that fixed it
