### ISSUE TITLE
OutOfMemory should crash to desktop (reopened)

### ISSUE THREAD

**Issue by Mirsario** [tModLoader/tModLoader#713]
Quoting @JavidPack from #660, which got accidentally closed.
> Sometimes an OutOfMemory exception happens and we catch the exception. It has been suggested that when this particular exception happens that we crash to desktop and show a MessageBox explaining how to avoid OutOfMemory exceptions. The idea is that the exception is pretty much unrecoverable from, and catching it might put the game in a weird state.

Here's an exception in Terraria Overhaul that some had with 0.11.5 tML.
![image](https://user-images.githubusercontent.com/6795251/68674214-8090d580-0566-11ea-992b-dc10eb69520a.png)

**Comment by Chicken-Bones** [comment]
FirstChanceException handler doesn't work on Linux. I'd rather try and fix the catch handlers but that may be a messy exercise. We could also just try allocating 2MB or so every few frames, or on a background thread and catch OOM there

**Comment by Mirsario** [comment]
That'd be quite too random in comparison to FirstChanceException approach, I'd prefer if we had it for XNA at least. I also don't remember seeing OOM thrown more than twice, it might not be spammed every frame, though the game is broken after the first one nonetheless.
