### ISSUE TITLE
[Suggestion] For the tModLoaderServer script on Linux, add "TERM=xterm"

### ISSUE THREAD

**Issue by alentoghostflame** [tModLoader/tModLoader#716]
### Description

When using the tModLoaderServer script on Linux, it exits silently after around one second with no error in the terminal.

Adding `TERM=xterm` to the script causes the server to start normally without crashing.

### Log File

[server.log](https://github.com/tModLoader/tModLoader/files/3855868/server.log)
### Steps to Reproduce

1. Setup environment to start up the tModLoaderServer as specified in the README.txt
2. Chown files as needed.
3. `./tModLoaderServer`

### Expected behavior 

Server should start up normally without changes to the script.

### Actual behavior

Server doesn't start up until changes to the script are made.

### Reproduction frequency

Every time.

### Additional Information

Running Ubuntu 19.10

**Comment by JavidPack** [comment]
We are a bit confused by this suggestion, as it suggests that un-modded Terraria server should also have this issue. We're also not sure the ramifications of that statement on linux machines where it wasn't originally necessary.

Does anyone know why vanilla would work but modded wouldn't without this addition?

**Comment by alentoghostflame** [comment]
For me at least, unmodded Terraria will not start without the change as well.

**Comment by JavidPack** [comment]
Thank you @alentoghostflame , if that is the case, then it looks like this is a good idea.

**Comment by Chicken-Bones** [comment]
I've seen this fix a few times on the steam forums. Give it a try jopo
