### ISSUE TITLE
Terraria will not launch with the latest TModLoader Update

### ISSUE THREAD

**Issue by JacobMuken** [tModLoader/tModLoader#718]
### Description
I could not get JoostMod to show up in my mod list no matter what i did, wasn't in the browser, downloaded it manually and placed it in the mod folder and it wouldn't show up ingame, so i decided to update TModLoader, and now whenever I try to launch Terraria, It claims to be running, there is a running task in Task Manager taking 30% of my CPU, but, after approx. 10 minutes, there is no game. No popups. It's like i never tried to open terraria.

### Log File
Here ya go:
[05:05:25] [1/INFO] [tML]: Starting tModLoader v0.11.5 Windows client
[05:05:25] [1/INFO] [tML]: Running on NetFramework 4.7.2
[05:05:25] [1/INFO] [tML]: Executable: E:\Steam\steamapps\common\Terraria\Terraria.exe
[05:05:25] [1/INFO] [tML]: Working Directory: E:\Steam\steamapps\common\Terraria
[05:05:25] [1/INFO] [tML]: Launch Parameters: 

...that's it. That's where it ends.

### Steps to Reproduce

1. Install Terraria
2. Install tModLoader 0.11.5
3. Start Terraria

### Expected behavior 
Terraria's window should open fairly soon after starting the executable. 

### Actual behavior
There is a process running in the background taking up CPU power, Steam says it's running, but there is absolutely nothing.

### Reproduction frequency
100% of the time.

**Comment by Chicken-Bones** [comment]
Sorry we missed this. Have you had any luck since? Does 0.11.4 work for you?

**Comment by GoodPro712** [comment]
@JacobMuken Try 0.11.6.2 and report back

**Comment by Jofairden** [comment]
No follow-up since nov-dec, closing. Feel free to re-open if you still experience this issue @JacobMuken
