### ISSUE TITLE
UpdateMusic doesn't allow changing title track

### ISSUE THREAD

**Issue by Mirsario** [tModLoader/tModLoader#719]
**Description**
Not sure if this is by design or not, but since the commit that added music priorities (https://github.com/tModLoader/tModLoader/commit/6406886c2f3e754e15b54a4497bc4ce6bb8af4fd), it is impossible to change music in main menu (without code injections, which I personally do use). While I personally would be against having tons of small mods compete for modifying main menu's track, this should either get fixed or get a solid quotable reply by a tML dev.

**Example Snippet**
```cs
public override void UpdateMusic(ref int music, ref MusicPriority priority)
{
    if (Main.gameMenu) {
        priority = MusicPriority.BossHigh; //Don't think that this matters.
        music = MusicID.TheHallow;
    }
}
```

**Expected behavior**
Music changes to The Hallow's track.

**Current behavior**
Nothing happens.

**Comment by GoodPro712** [comment]
Honestly im with Mirsario's opinion, as much as im wanting to do this as an easier option

**Comment by stb06** [comment]
I'm with Mirsario, cause I really need to change the title track for my mod.

**Comment by GoodPro712** [comment]
I guess the guy above doesn't understand

**Comment by Mirsario** [comment]
1.4 branch now has modmenus, which can control music.
