### ISSUE TITLE
having issues with loading certain mods (thorium and hamstar helpers)

### ISSUE THREAD

**Issue by thefoolone** [tModLoader/tModLoader#721]
[client.log](https://github.com/tModLoader/tModLoader/files/3880521/client.log)

**Comment by Chapsteck4yurlipis** [comment]
Same thing's happening to me. In addition, starting multiplayer servers often quickly skips to "Found server" and is stuck at that. In addition, some features of mods (Cheat Sheet and HEROs Mod particularly) don't seem to work properly.

**Comment by JavidPack** [comment]
Duplicate of #720
