### ISSUE TITLE
[BUG] Starting the game with '-join' arg, or through steam invites is completely broken.

### ISSUE THREAD

**Issue by Mirsario** [tModLoader/tModLoader#724]
### **Description**
Whenever tML is launched with '-join' argument, or, for example, from a steam invite, tML will skip mod loading (and loading of tML itself???) and immediately get to character selection screen, with all characters looking default and none being selectable at all.

![image](https://user-images.githubusercontent.com/6795251/69664548-a6a39300-1099-11ea-9519-1813f37e66fd.png)

### **Reproduction**
**Either:**
- Launch the game with "-join 127.0.0.1" command-line argument.

**Or:**
- Have someone invite you to their server in steam, and accept their invite while having the game closed.

### **Reproduction frequency**
100%, ez.

### **Expected behavior** 
tML loads itself and its mods before switching to character selection screen.

Alternatively, it would connect to the server to figure out what mods it has, load these mods, and only then go to character selection.

### **Actual behavior**
tML skips all loading, and shows a character selection screen where all characters look default and cannot be selected.

**Comment by GoodPro712** [comment]
I also get this when I cancel loading when its loaded a spefifc amount

**Comment by Plantterror** [comment]
@GoodPro712 There's already a fix for that coming.

**Comment by P3rf3ctXZer0** [comment]
Oh so it was a bug - I was originally going to look into to it more. Thanks poster :D

**Comment by Chicken-Bones** [comment]
Love a 2 line bugfix
