### ISSUE TITLE
Slow motion, less than 20 frames

### ISSUE THREAD

**Issue by DoctorGamer** [tModLoader/tModLoader#725]
### Description 
No matter what I do, when TML is installed, mods loaded or not, my game runs at less than 20 frames at all times
### Log File
[client.log](https://github.com/tModLoader/tModLoader/files/3894647/client.log)
### Steps to Reproduce
Step 1) Load game up
Step 2) Done
### Expected behavior 
My PC is more than capable to run games like RDR2 max graphics, so i know its not hardware. It should run smoothly, as I have used TML in the past and just got back into playing.
### Actual behavior
The game runs at a unreasonably low FPS, making the game run in slow motion
### Reproduction frequency
Every single time I load up the game.
### Additional Information
I have fully reinstalled the game, manually deleting every single file and reinstalling, but it is still happening. I also tried re-downloading TML itself, but that didn't help

**Comment by Mirsario** [comment]
1. What's your CPU? There were some issues with early Ryzens in the past.

2. If you're on a laptop - do make sure that the game's not using your integrated GPU via your GPU vendor's control panel.

3. Have you played around with frameskip & lighting multithreading settings?

4. This can be annoying, but could you record a performance snapshot?
Here's a copy-pasted tutorial from discord:
```How to record your performance issues with dotTrace:
0. Get dotTrace from <https://www.jetbrains.com/profiler/> (30 days trial is enough)
1. Load Terraria with all your mods and open your world.
2. Start dotTrace, click "Attach to Running App", click "Show All Processes", select "Terraria.exe", choose "Sampling" on the right panel, untick "Start Immediately", click "Run".
3. A small "Profilling Controller" window will appear. Click the pin button to make it appear on top of other windows if it doesn't do that already.
4. Switch back to your game. Press "Start" on the profilling controller.
5. Run around in your game and make it lag.
6. After half a minute or so, click "Get Snapshot and Wait" button on the profilling controller.
7. Performance Viewer window will open. Select it and press Ctrl+S. Choose a convenient location for the snapshot. Then find it in Explorer and upload it to some file sharing site (MEGA/Dropbox/FileDropper/etc), then post it.
```

**Comment by DoctorGamer** [comment]
1. CPU is a Intel I5 gen 9, so im good there

2. Im on a desktop

3. I have cause everyone told me to do that, and it helped the framerate for less than a second (I hit f10 to see in game frame rate)

4. I just tried that and it wouldn't actually let me attach it to Terraria, but im working on finding a program that will

**Comment by DoctorGamer** [comment]
I talked to a coding buddy of mine and he helped me fix it, i had to update my operating system, my graphics drivers, and for some reason my java, and that fixed it, thank you
