### ISSUE TITLE
Item Name Limitation

### ISSUE THREAD

**Issue by Byzantium2100** [tModLoader/tModLoader#728]
There appears to be a limitation on the unique names of items in the game. The limit appears to be at around 32,767 so it may tie in to a signed integer. Details for reproduction below (and I will provide modpack .json for testing to achieve going over the limit)

For the following screenshots, I took one item from Zoaklen for reference. 01 is how it shows up in recipe browser, 02 is how it shows up in inventory, and 03 is how it shows up in magic storage. In the 03 screenshot, you can see that there is a version of the item name that shows up because the 'DisplayTechnicalNames' mod configuration option has been set to true in 'What Mod Is This From' and 'What Tile Is This' mods.

![01](https://user-images.githubusercontent.com/58355404/69897354-fd6ad000-1318-11ea-948a-04d7ea94c6b7.png)

![02](https://user-images.githubusercontent.com/58355404/69897375-3f941180-1319-11ea-82ac-ac242489ccd0.png)

![03](https://user-images.githubusercontent.com/58355404/69897404-a9142000-1319-11ea-8237-1db77986905e.png)

The items ppear to be not showing up in reverse alphabetical order depending on the name of the mod itself: i.e. it starts from ZoaklenMod and works its way backwards. The cutoff point with the amount of items that I have is in the Solutions Mod, so item names do not show up for all the mods between the cutoff in solutions mod through Zoaklen mod.  The following 2 screenshots are an item in the mod without a name showing up, and the previous item that starts showing the name:

![04](https://user-images.githubusercontent.com/58355404/69897480-bb428e00-131a-11ea-9766-bbccfe35da20.png)

![05](https://user-images.githubusercontent.com/58355404/69897491-d1504e80-131a-11ea-918e-8c0330b63dfc.png)

So if I say, add a mod that adds 20 items, then 20 more names will disappear moving in reverse order, or the reverse would happen if I remove a mod that has 20 items, 20 more names will start showing up. The last picture is the amount of unique named items that I have currently, as shown by the item checklist mod, 35,055. Also attached is a .txt of my modpack .json, as .json doesn't seem to be supported for upload on github. Any more information needed, please let me know. Thanks!

![06](https://user-images.githubusercontent.com/58355404/69897528-53d90e00-131b-11ea-8b59-e9bf4900582c.png)

[GithubTest.txt](https://github.com/tModLoader/tModLoader/files/3906853/GithubTest.txt)

**Comment by Byzantium2100** [comment]
Addendum: the item names that aren't showing up tie in to any function where you would search by item name, say in recipe browser, or item browser in Hero's mod or cheat sheet making it so you are unable to search by item name.

**Comment by Byzantium2100** [comment]
Addendum: 

The item  names not showing up tie into any feature that allows you to search items, i.e in the item browser in either Hero's mod, Cheat Sheet mod, recipe browser or Magic Storage mod. Searching for the item name yields no results

**Comment by GoodPro712** [comment]
The limit is 32768 afaik but seen nothing in source code
