### ISSUE TITLE
GoG Install Instructions seem wrong

### ISSUE THREAD

**Issue by NaturesWitness** [tModLoader/tModLoader#734]
When trying to install Tmod with GoG version, instructions say to rename Terraria.exe to Terraria_v1.3.5.3.exe.

However, this doesn't actually work, as it seems the Tmod .exe is still looking for "Terraria.exe" as the original executable for validation.  I finally got things working by renaming the Tmod executable to something else, then putting it in with the original .exe with the original name.

**Comment by JavidPack** [comment]
I double checked the code, it should properly work the way the install instructions instruct, as well as the other way with the tmod exe being a different name.

My guess is there was a tiny typo you didn't notice.

If anyone else has this issue, please re-open this issue with a log and we can look further into this.
