### ISSUE TITLE
Prevent 0.10 mods from being placed in the "UpgradeBackup" folder when downloading a mod off the browser

### ISSUE THREAD

**Issue by Plantterror** [tModLoader/tModLoader#735]
### Description
Currently, when you download any mod off the mod browser (even mods you have never installed before) a 0.10 copy will go straight to the UpgradeBackup folder. I think now's a good time to remove this since the majority of players (not counting pirates) have already made the migration and many mods have updated, with exceptions of course.

### Log File
N/A

### Steps to Reproduce
1. Download a mod that was migrated to 0.11 or is still on 0.10 with a client past 0.11.
2. Go to your mods folder and find the UpgradeBackup folder. You will see a 0.10 version in there.
3. I dunno, delete it?

### Behavior 
N/A, as it's working as intended but I feel it's good to remove it.

### Reproduction frequency

> The average number of offspring that a female produces during her lifetime is called the net reproductive rate (R0). If all females survived to the oldest possible age for that population, the net reproductive rate would simply be the sum of the average number of offspring produced by females at each age.

### Additional Information
I only see one benefit to keeping this system, that being to play mods that are unusable on the current version. The only two that are major and fall under this category are Tremor (removed off the browser anyways) and DAlib and dependancies. I really don't see why though as pretty much every other mod has migrated and is unavailable on a 0.10 client.

**Comment by Chicken-Bones** [comment]
This feature was initially so people could revert to 0.10 and not have lost their mods. Especially of they had a precious copy or slow internet connection.

By the way, copies are only made for mods which haven't been published with 0.11, so once all the mod authors stop using 0.10 it'll disappear anyway

**Comment by Plantterror** [comment]
Fair enough.
