### ISSUE TITLE
tModLoaderServer: line 58: ./tModLoaderServer.bin.x86_64: Permission denied

### ISSUE THREAD

**Issue by henriquelino** [tModLoader/tModLoader#737]
### Description
Trying to run tmodloader on a headless debian. After installing and running ./tModLoaderServer it throws back "**tModLoaderServer: line 58: ./tModLoaderServer.bin.x86_64: Permission denied**"

this error are on latest version, on late 10.1.5 it runs fine

### Steps to Reproduce

1. get latest tmodloader for linux
2. get latest terraria for linux
3. bang (kidding). After these two, I'm running  "chmod u+x tModLoaderServer*" then every shell to run the command, bash, sh, sudo, etc

ps. I have tried to change file/folder permissions and everything to rwx, running as root annd the same error happens.

### Expected behavior 

Server starts and we have fun
### Actual behavior

it throws the error:
tModLoaderServer: line 58: ./tModLoaderServer.bin.x86_64: Permission denied
### Reproduction frequency

everytime boys
### Additional Information

this is SUPER important, I can start server using tmodloader v10.1.5 but not latest versions. RN I was trying to create a Docker container to run tmodloader and come across this container:
https://hub.docker.com/r/ldericher/tmodloader/dockerfile

In dockerfile section we can see that it mostly fresh-installs tmod+terraria, and since this are old I update the links to the new version, and **when using old links terraria starts**, but using updated ones it does not! Taking the two "tModLoaderServer" from v10.1.5 and from the latest version I can spot some differences but I dont understand rn how to solve this, but I smell that may be related to mono.

If I success solving I may post the solution if I remember, sadly I forgot really often to update things in github or forums :(

**Comment by warren-fisher** [comment]
For anyone who runs into this error: 

I used chmod +x on the that file and it worked, although I am not sure if this is advisable.

**Comment by henriquelino** [comment]
I am running chmod +x tModLoader* and didnt work, same output. As I said, older version works on same setup step by step, but if use newer I got this error.

Still clueless why tho

**Comment by warren-fisher** [comment]
I meant on `tModLoaderServer.bin.x86_64`

**Comment by henriquelino** [comment]
When using * symbol means everything that completes, so tModLoaderServer* includes .bin.x86_64

**Comment by warren-fisher** [comment]
You are right (I think I missed that part in my installation and thats why I had to add that extra step). Mine is currently working on headless Ubuntu, I will try using that dockerfile and seeing if I run into the same error as you. I will get back to you shortly.

**Comment by henriquelino** [comment]
When running the docker beware that it is using and old version of tModLoader, its using:
	wget https://github.com/blushiemagic/tModLoader/releases/download/v0.10.1.5/**tModLoader.Linux.v0.10.1.5.zip** &&\

this DOES work, but when updating to a newer version using same docker but with the following link:
	wget https://github.com/tModLoader/tModLoader/releases/download/v0.11.5/**tModLoader.Linux.v0.11.5.tar.gz** &&\

it throws the error


This is the "new" dockerfile I was trying to use:

`# METADATA
FROM debian:testing-slim
LABEL maintainer="henriquelino"

RUN \
	# system update \
	apt-get -y update &&\
	apt-get -y install wget unzip &&\
	apt-get -y clean &&\
	\
	# prepare directory \
	mkdir /terraria-server &&\
	cd /terraria-server &&\
	mkdir /worlds &&\
	\
	# get vanilla server \
	wget http://terraria.org/server/terraria-server-1353.zip &&\
	unzip terraria-server-*.zip &&\
	rm terraria-server-*.zip &&\
	cp --verbose -a 1353/. . &&\
	rm -rf 1353 &&\
	\
	# add in tModLoader \
	cd Linux &&\
	wget https://github.com/tModLoader/tModLoader/releases/download/v0.11.5/tModLoader.Linux.v0.11.5.tar.gz &&\
	tar xvzf tModLoader.Linux.v*.tar.gz &&\
	rm tModLoader.Linux.v*.tar.gz &&\
	chmod u+x tModLoaderServer* &&\
	\
	# access data directory \
	ln -s ${HOME}/.local/share/Terraria/ /terraria &&\
	# remove Leftovers \
	cd .. &&\
	rm -rf Windows Mac

# ports used
EXPOSE 7777/udp
EXPOSE 7777/tcp

# start server
CMD [ "/terraria-server/Linux/tModLoaderServer" ]`

**Comment by warren-fisher** [comment]
I got it working using my own [modified dockerfile](https://github.com/warren-fisher/docker-tmodloader). Its not very elegant, but it gets the job done. The problem lay with the new JAR installer they added, as far as I can tell.

**Comment by warren-fisher** [comment]
Found [a much better solution ](https://github.com/Rfvgyhn/tmodloader-docker/blob/master/Dockerfile) that I would probably recommend using instead. Guess I just needed to chmod u+x more files...

**Comment by henriquelino** [comment]
I managed to set up using this docker:
https://hub.docker.com/r/rfvgyhn/tmodloader

the same that you found, but my docker keeps restarting and I cant log to server, and I realised my server is too bad to run the game, 2gb DDR2 with intel N455 cpu.

Just to have more info, I'm running OpenMediaVault, and running terraria server into the docker plugin.

I think its not fair to close this issue since it still happens on said setup, but I will move foward from running this on remote server, too clumsy.

**Comment by GoodPro712** [comment]
I think this *can* be closed

**Comment by Rfvgyhn** [comment]
@warren-fisher @henriquelino Just wanted to add that the dockerfile of mine you were using was a work in progress. I have updated it to be a proper docker image. 36MB compressed, graceful shutdown (responds properly to SIGTERM (e.g. docker stop) by sending the terraria `exit` command to the running process) and has autosave capability.

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
