### ISSUE TITLE
Question - How do I compile tmodloader

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [tModLoader/tModLoader#739]
I would like to always have the latest fixes.

**Comment by JavidPack** [comment]
Follow the tmodloader developer guide to get the patched code and project files: https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-contributors

Then to build, simply build the Windows and WindowsServer solution configurations from within tModLoader.sln. This should copy the built .exe files to your install directory if all went well.
