### ISSUE TITLE
ClearBuff calls all buff slots, even if MaxBuffSlots is set higher through another mod

### ISSUE THREAD

**Issue by Plantterror** [tModLoader/tModLoader#744]
### Description/Scenario

When a mod sets the Max buff slots higher than the normal limit, ClearBuff checks all of them. On paper, this appears flawless, but when ClearBuff is called repeatedly, this severely drops frames.

This scenario only happens with Fargo's Souls mod's Antisocial debuff (removes all summons and pets) paired with Lan's Unlimited Buff Slots to my knowledge.

### Log File
Not Applicable.
Stack Trace for scenario mentioned above: ![](https://media.discordapp.net/attachments/232328308757364736/658708927688736778/killpets.png)

### Steps to Reproduce
1. Call ClearBuff repeatedly while increasing the amount of buff slots
2. ???
3. No Profit

#### Alternate Steps
1. Enable Fargo's Soul Mod and Lan's Unlimited Buff Slots
2. Enable Masochist Mode and get hit by a Mother Slime (or another enemy that inflicts the Antisocial debuff)
3. Watch your FPS tank.

### Expected behavior
Clearbuff should reliably adjust to large max slots to prevent this when it's being called every tick.

### Actual behavior
It kinda doesn't.

### Reproduction frequency
N/A

### Additional Information
@Fargowilta @terrynmuse @Lanboost

**Comment by JavidPack** [comment]
> Call ClearBuff repeatedly while increasing the amount of buff slots

This isn't allowed, modifying the amount of buffs is only allowed at mod loading, so I'm not sure I understand the issue here.

**Comment by Plantterror** [comment]
I don't mean at the same time.

**Comment by Chicken-Bones** [comment]
How many buff slots to Lan's unlimited buff slots add??
Also, any chance you can get us a profiler report, from dotTrace or similar?

**Comment by Plantterror** [comment]
200 (configurable), and see the screenshot for dotTrace @Chicken-Bones, unless you were looking for the entire thing?

**Comment by Plantterror** [comment]
For future reference

KillPets from Faro's Souls: https://github.com/Fargowilta/FargowiltasSouls/blob/master/FargoPlayer.cs#L3193
