### ISSUE TITLE
Achievements reset occasionally

### ISSUE THREAD

**Issue by SheepishShepherd** [tModLoader/tModLoader#746]
### Description
Achievements sometimes seem to reset when relaunching tModLoader. **May or may not have to due with new Steam Library UI**, as its been happening since that beta was released and used. Seems to nearly always happen on computer reboot, and when relaunching Steam.

### Steps to Reproduce
1. Reboot computer/ relaunch Steam (I think it has happened with both of these on occasion)
2. Launch tModLoader through normal means, or through debugging
3. Enter a world with a character
4. Brace for incoming (obtainable) achievement spam

### Expected behavior 
Achievements should be maintained as completed when completed when relaunching the game.

### Actual behavior
Achievements are re-obtainable and marked as incomplete.

### Reproduction frequency
Achievement reset doesn't seem to happen EVERY time, but when rebooting computer its almost guaranteed.

**Comment by SheepishShepherd** [comment]
![achievements](https://user-images.githubusercontent.com/36808587/71424196-84cc0a80-265d-11ea-9e90-ecd7ee3a1d42.png)

**Comment by GoodPro712** [comment]
I get this too

**Comment by SheepishShepherd** [comment]
Seems to be the same issue as #342

**Comment by Jofairden** [comment]
Should be fixed, if not, it will be fixed in 1.4
