### ISSUE TITLE
So i have a problem, every so often my character's and maps get all their info deleted and go blank as well as become un-playable, and i have reintalled both the tmodloader and Terraria as a whole, but it mostly started after the 0.11.5 update

### ISSUE THREAD

**Issue by SirMeepsAlot** [tModLoader/tModLoader#748]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [And so on...]

**Comment by Jofairden** [comment]
Can you actually share some more information? Your title suggests files going corrupt, but we have the issue template for a reason. Please upload your client.log file and mod list. Closing for now but re-open it when you have done so.
