### ISSUE TITLE
i downloaded the update, placed the zip in the terraria file replacing files and the game is still at v0.11.5

### ISSUE THREAD

**Issue by lystrosaur** [tModLoader/tModLoader#750]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [And so on...]

**Comment by Chicken-Bones** [comment]
Please come see us on Discord for problems like this. There's not much we can say here other than, "try again? the update isn't broken"

We'd have to figure out what you're missing (or what's different about your computer) compared to everyone who has successfully updated, and the best place for that is Discord.
