### ISSUE TITLE
Cannot host a server when everything is installed correctly

### ISSUE THREAD

**Issue by Fuxkcreeper** [tModLoader/tModLoader#753]
### Description

When I try to host a server, the game crashes. I have read the FAQ and tried copy&pasting the tModLoaderServer.exe to the folder but the problem still happens. When I was just playing with the tModLoader version 1.11.5 there were no crashes. But when I updated to 1.11.6.1 I couldn't host a server.

### Steps to Reproduce

1. Click Multiplayer
2. Click Host&Play
3. Select character and world to play on
4. Host a server

### Expected behavior 

The game shouldn't crash but host a server

### Actual behavior

The game crashes

### Reproduction frequency

Always

**Comment by Fuxkcreeper** [comment]
Sorry, forgot to attach the log file.
[client.log](https://github.com/tModLoader/tModLoader/files/4007698/client.log)

**Comment by JavidPack** [comment]
The log says the tModLoaderServer.exe file can't be found. I think the easiest way to solve this is to come to the discord chat and get some help there, it's a bit difficult to troubleshoot this type of issue via github.

tmodloader.net/discord

**Comment by GoodPro712** [comment]
Close
