### ISSUE TITLE
Saving List<Item> results in Loading a List of Unloaded Items

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#756]
When using the generic approach to saving and loading a List of Item, you'll end up with undesirable results:

```
public override void Load(TagCompound tag) {
	TestA = tag.Get<List<Item>>("TestA");
	TestB = tag.GetList<TagCompound>("TestB").Select(ItemIO.Load).ToList();
}

public override TagCompound Save() {
	return new TagCompound {
		["TestA"] = TestA,
		["TestB"] = TestB.Select(ItemIO.Save).ToList(),
	};
}
```
In this example,  TestB will Save and Load properly as Air, but TestA will Save and Load as Unloaded Items.

My guess is this logic doesn't expect the "<Type> = Terraria.Item" that will result from the automatic approach:
```
public static void Load(Item item, TagCompound tag) {
	if (tag.Count == 0) {
		item.netDefaults(0);
		return;
	}
```

A possible solution is this, but I'm not sure yet, I'm not sure if I'm missing something or if trimming such tags should happen beforehand:
```
public static void Load(Item item, TagCompound tag) {
	if (tag.Count == 0 || tag.Count == 1 && tag.GetString("<type>") == "Terraria.Item") {
		item.netDefaults(0);
		return;
	}
```

Test Mod:
[ItemListSave.zip](https://github.com/tModLoader/tModLoader/files/4012495/ItemListSave.zip)

**Comment by Jofairden** [comment]
Marked as a bug though doesn't really seem like a bug but more like an oversight
