### ISSUE TITLE
Is this an installation issue on my part?

### ISSUE THREAD

**Issue by dylan8163** [tModLoader/tModLoader#759]
ok so when i open up terraria and try to open the mod browser, it gives me the message 
```
Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attampt to continue. If you click Quit, the application will close immediately.
Object reference not set to an instance of an object.
```
Along with the a Details tab that says this
```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.IconDownloadComplete(Object sender, DownloadDataCompletedEventArgs e)
   at System.Net.WebClient.OnDownloadDataCompleted(DownloadDataCompletedEventArgs e)
   at System.Net.WebClient.DownloadDataOperationCompleted(Object arg)
```
Along with a LOT of other things that im going to try to separate from this so i can actually show all of it, as it is a lot and i would assume it would be needed.
If anyone has also had this issue and/or or knows how fix it please help.

**Comment by dylan8163** [comment]
the rest of it 
************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Terraria
    Assembly Version: 1.3.5.1
    Win32 Version: 1.3.5.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Terraria/Terraria.exe
----------------------------------------
ReLogic
    Assembly Version: 1.0.0.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Terraria/Terraria.exe
----------------------------------------
log4net
    Assembly Version: 2.0.8.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Terraria/Terraria.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MonoMod.RuntimeDetour
    Assembly Version: 19.12.19.1
    Win32 Version: 1.3.5.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Terraria/Terraria.exe
----------------------------------------
MonoMod.Utils
    Assembly Version: 19.12.19.1
    Win32 Version: 1.3.5.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Terraria/Terraria.exe
----------------------------------------
Mono.Cecil
    Assembly Version: 0.11.1.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Terraria/Terraria.exe
----------------------------------------
MonoMod.Utils.GetManagedSizeHelper
    Assembly Version: 0.0.0.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Terraria/Terraria.exe
----------------------------------------
Ionic.Zip.Reduced
    Assembly Version: 1.9.1.8
    Win32 Version: 1.3.5.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Terraria/Terraria.exe
----------------------------------------
Microsoft.Xna.Framework.Game
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.20823.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/Microsoft.Xna.Framework.Game/v4.0_4.0.0.0__842cf8be1de50553/Microsoft.Xna.Framework.Game.dll
----------------------------------------
Microsoft.Xna.Framework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.20823.0 built by: xnabldr
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/Microsoft.Xna.Framework/v4.0_4.0.0.0__842cf8be1de50553/Microsoft.Xna.Framework.dll
----------------------------------------
Microsoft.Xna.Framework.Graphics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.20823.0 built by: xnabldr
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/Microsoft.Xna.Framework.Graphics/v4.0_4.0.0.0__842cf8be1de50553/Microsoft.Xna.Framework.Graphics.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Terraria/Terraria.exe
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3825.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.Xna.Framework.Xact
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.20823.0 built by: xnabldr
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/Microsoft.Xna.Framework.Xact/v4.0_4.0.0.0__842cf8be1de50553/Microsoft.Xna.Framework.Xact.dll
----------------------------------------
Microsoft.Xna.Framework.Input.Touch
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.20823.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Xna.Framework.Input.Touch/v4.0_4.0.0.0__842cf8be1de50553/Microsoft.Xna.Framework.Input.Touch.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4042.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Steamworks.NET
    Assembly Version: 9.1.0.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Terraria/Terraria.exe
----------------------------------------
Microsoft.Xna.Framework.GamerServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.20823.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Xna.Framework.GamerServices/v4.0_4.0.0.0__842cf8be1de50553/Microsoft.Xna.Framework.GamerServices.dll
----------------------------------------
MP3Sharp
    Assembly Version: 1.0.0.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Terraria/Terraria.exe
----------------------------------------
NVorbis
    Assembly Version: 0.8.4.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Terraria/Terraria.exe
----------------------------------------
Mono.Cecil.Mdb
    Assembly Version: 0.11.1.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Terraria/Terraria.exe
----------------------------------------
Mono.Cecil.Pdb
    Assembly Version: 0.11.1.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Terraria/Terraria.exe
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4075.0 built by: NET48REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
CheatSheet_0
    Assembly Version: 0.0.0.0
    Win32 Version: 1.3.5.1
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Terraria/Terraria.exe
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------

**Comment by dylan8163** [comment]
oh and the log file says this

**Comment by JavidPack** [comment]
This kinda looks like the imgur.com issue.

Try this:

You need to tell tModLoader to avoid Imgur. You can instruct tModLoader to avoid Imgur by doing the following: Close tModLoader, Open up %userprofile%\Documents\My Games\Terraria\ModLoader\config.json, change `"AvoidImgur": false,` to `"AvoidImgur": true,` save the file, then open up tModLoader again. If you are on Mac or Linux, the process is the same but the appropriate folder.
