### ISSUE TITLE
my mouse wont work on the home screen

### ISSUE THREAD

**Issue by amsmith212** [tModLoader/tModLoader#760]
[client.log](https://github.com/tModLoader/tModLoader/files/4022616/client.log)
when ever I try to click on things with my mouse it always goes to the thing that was highlighted even if my mouse is highlighting another thing and the only way I can move on the home screen is to use wasd and it wont let me update and I tried to check the mouse without tmodloader and it worked until I put tmodloader back on terraria

**Comment by GoodPro712** [comment]
refrain from using thing

**Comment by Chicken-Bones** [comment]
Grab the latest version, install it fresh, take all your mods out of the mods folder, see if it still happens. If you've got more trouble see if you can find us in Discord

**Comment by Solxanich** [comment]
Hello @amsmith212,
I'm currently reviewing stale issues, and would like to confirm if you are still experiencing this issue in the latest version 0.11.8.1 of tModLoader.
If not, could you please close the issue?
If so, could you please provide the most recent information from its occurrence?
