### ISSUE TITLE
i dont know how to up date

### ISSUE THREAD

**Issue by Ninjastar0640** [tModLoader/tModLoader#761]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [And so on...]

**Comment by Jofairden** [comment]
To update, you can navigate to our [releases](https://github.com/tModLoader/tModLoader/releases), then find the version you want (the latest version is at the top), then under assets download the .zip that corresponds to your OS. (`tModLoader.OS.ver.zip`)
