### ISSUE TITLE
Icons Don't Appear in Mod Sources

### ISSUE THREAD

**Issue by GoodPro712** [tModLoader/tModLoader#763]
### Description
When I go to the Mod Sources menu, icons for my mod don't show up, even if they are linked.

### Steps to Reproduce
1. Head to the mod sources menu
2. Create a mod
3. Provide an icon with that mod and link that mod to github
4. Head back over to the mod sources menu

### Expected behavior 
 Icons should appear on the left of mods that are linked to github and have an icon

### Actual behavior
No icon is showing.

### Reproduction frequency
100% of the time

### Additional Information
I don't know if this was meant to happen, if so, this may be a suggestion.

**Comment by JavidPack** [comment]
Will not fix, most likely. It's a bit of a pain to manage all the UI code for that and it really only matters in the Mods menu, since in that menu we are loading the actual .tmod file
