### ISSUE TITLE
Unable to compile Mod

### ISSUE THREAD

**Issue by Lolozjj** [tModLoader/tModLoader#766]
At first, I used the version of TML v0.10. When I changed to v0.11, I couldn't compile mod source code in the game
![%G~CZ4`HZ}7RQ5G2E){%UX2](https://user-images.githubusercontent.com/49157439/72314631-a2274e00-36ca-11ea-8da8-cc0f0a6ac910.png)

help！

**Comment by GoodPro712** [comment]
@Lolozjj Visit the tmodloader discord at tmodloader.net/discord. When done close the issue, thanks

**Comment by Jofairden** [comment]
You don't follow the issue format nor is this an issue with tML: it's a simple syntax error
Join the discord and people will be glad to help you out
