### ISSUE TITLE
[Suggestion] Ingame credit/support menu

### ISSUE THREAD

**Issue by GoodPro712** [tModLoader/tModLoader#768]
On the main menu could there be a button above the tModLoader patron link in the bottom left corner named `Support and credits`. When pressed it opens a menu that displays the following text.
`Credits
Official Website
Official Discord Server
Github
Releases
Wiki`
When pressing on Official Website, Official Discord Server, Github, Releases, and Wiki, it will Process.Start the links respectively
When pressing on `Credits`, it will open a menu that will display the 4 API developers, Blushiemagic, Jopojelly, Chicken Bones, Jofairden. It would then display `Thank you to all of our contributors` There will also be another tab under the contributor thanking which would be saying `Thanks to all of our Skeletron and above tier patrons ($10)`. When pressed will open a UIInfoMessage and list every skeletron and above tier patron as the patron says "Will be listed in the tModLoader credits"

**Comment by Jofairden** [comment]
Refer to https://github.com/tModLoader/tModLoader/issues/687
Support seems a bit unnecessary to me

**Comment by GoodPro712** [comment]
Jopo gave this the ok to code

**Comment by GoodPro712** [comment]
commented and closed
