### ISSUE TITLE
ModPackets during mod syncing can cause errors

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#770]
On rare occasions, some mods send ModPackets during Mod loading, which will cause the server to kick the client during a NetReload, which in turn will cause null reference exceptions in `new ModPacket(MessageID.SyncMods).Send();` due to netMode suddenly being 0 because of the kick.

1. mod reloading causes client to send invalid packet
1. server kicks the client 
1. the client gets that it got kicked, sets everything to singleplayer
1. then it still calls onmodsdownloaded and tries to send that method's packet

To replicate, a mod can call NewProjectile in Mod.Load, which will cause a netmessage to be sent during the multiplayer connection steps. 

@Mirsario can provide more details if necessary

**Comment by Chicken-Bones** [comment]
What's the goal here? Throw an exception if packets are sent during reload?

**Comment by JavidPack** [comment]
I'm not sure. Either ignore them, or throw exceptions. The issue is some mods do things in Mod.Load for data collection purposes that result in mod packets being sent. Preventing them from being sent at all on the client is probably best, since the vanilla behavior of kicking any client that sends unexpected messages during connection is probably desirable.

**Comment by Chicken-Bones** [comment]
Makes sense as there's no one to send them to. The server is just waiting for the client to try and connect again anyway
