### ISSUE TITLE
ModCactus Improvements

### ISSUE THREAD

**Issue by GoodPro712** [tModLoader/tModLoader#772]
### Description
Add more things to ModCactus

### Things to Add
Something to make the cactus able to give off light
Something to change the frequency of growth
Something to have a minimum axe power required to break the cactus
Something to change the color it is on the map and map hover text (it's always green)

### Use
```cs
public override SetDefaults() {
    minAxe = 15;
    AddMapEntry(new Color(200, 200, 200), "Example Cactus");
}

public override float GrowthRate() {
    //double the speed of growth
    return 2f;
}

//Run when the cactus is destroyed
public override void Kill() {
    //spawn dust or whatever you like
}
```

### Additional Information
`AddMapEntry(new Color(200, 200, 200), "Example Cactus");` instead of #771

**Comment by Chicken-Bones** [comment]
Turn this into a PR

**Comment by Tyfyter** [comment]
This really doesn't seem like it should be closed as completed, as none of the listed functionality has been added, and it doesn't seem like it should be closed as not planned because that seems to be mostly reserved for actual non-issues, this leaves one status it logically should be: open.
