### ISSUE TITLE
Mod Browser Webhook in Discord Error

### ISSUE THREAD

**Issue by GoodPro712** [tModLoader/tModLoader#773]
### Description
There is a " " between the `(` and the homepage for mods

### Log File
N/A

### Steps to Reproduce
1. Go to the discord
2. Go to the mod-browser channel

### Expected behavior 
There shouldn't be a space character

### Actual behavior
There is a space character

### Reproduction frequency
100%

**Comment by Chicken-Bones** [comment]
Just PR a fix rather than making an issue

**Comment by Chicken-Bones** [comment]
Discord problems in Discord?
