### ISSUE TITLE
Calling ErrorLogger.Log in detoured method lead to NullReferenceException

### ISSUE THREAD

**Issue by sgkoishi** [tModLoader/tModLoader#776]
### Description
Calling `Terraria.ModLoader.ErrorLogger.GetCallerName` from a detoured method will trigger a null reference exception

### Log File
(Sample)
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.ModLoader.ErrorLogger.GetCallerName()
   at Terraria.ModLoader.ErrorLogger.Log(String message)
   at PostSetupContent_Patch0(Object )
   at Terraria.ModLoader.ModContent.<>c.<Load>b__39_1(Mod mod)
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction)
   at Terraria.ModLoader.ModContent.Load(CancellationToken token)
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token)
```

### Steps to Reproduce
1. Create a method that calls `Terraria.ModLoader.ErrorLogger.Log` (it calls `GetCallerName` internally)
2. Use Harmony or MonoMod to detour it
3. Execute this method

### Expected behavior 
No exception was thrown, error should be logged correctly.

### Actual behavior
A NullReferenceException was thrown by `GetCallerName`. Since the method was detoured, a [Lightweight Function] will shown instead of a regular method call stack.
https://github.com/tModLoader/tModLoader/blob/9acf3792cd580903eb0102f701e5d1106f410057/patches/tModLoader/Terraria.ModLoader/ErrorLogger.cs#L85-L90

### Reproduction frequency
Always.

### Additional Information
Simply add some null condition checks should be fine.
This is already fixed for new `Terraria.ModLoader.Logging`.

This happens when I try to add localization to [FargowiltasSouls](https://github.com/Fargowilta/FargowiltasSouls), which use `ErrorLogger.Log`.

**Comment by Chicken-Bones** [comment]
The linked issue is the actual fix, but it didn't take me long. It'll be faster to update the mod than wait for the next tML release

**Comment by Ireheart** [comment]
Also getting this issue.

**Comment by Chicken-Bones** [comment]
The tML fix is in the linked commit. You can build a dev version if you like. Otherwise it'll be in the next release
