### ISSUE TITLE
Example exampleDamageSpeed

### ISSUE THREAD

**Issue by Metacinnabar** [tModLoader/tModLoader#780]
### Description

Have an exampleDamageSpeed, like meleeSpeed, in ExampleMod.

### Benifits

This can be used for making buffs that increase speed to a custom damage weapon and other things

**Comment by psznm** [comment]
Hello, I am considering contributing to this project and I'd love clarification to goal of this issue.

As of now player has meleeSpeed and pickSpeed attributes. There are no hooks for getting weapon speed or player attribute for other types.

Is goal of this issue also creating hook for this or should this somehow be achieved with existing tools?

**Comment by JavidPack** [comment]
You can do this with MeleeSpeedMultiplier or UseTimeMultiplier. This issue is just suggesting showing proper usage of these hooks with the ExampleDamage custom damage class

**Comment by Chicken-Bones** [comment]
Implemented in #2196. Just use `player.GetAttackSpeed<ExampleDamageClass>() += 0.1f` for 10% bonus
