### ISSUE TITLE
Music playing while unloading fails to unload mod

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#786]
If you are quick enough, or have mod music playing on the main menu, you can attempt to unload/reload mods while a particular mod music is playing, preventing the mod from unloading properly.

We need to stop all mod music during unload.

Here is an example of the error message and some code I use in one of my mods as a temporary fix:

![index](https://user-images.githubusercontent.com/4522492/73791941-83aff200-4760-11ea-9b8f-2558b435ae8a.png)

```cs
		public override void Close()
		{
			// Fix a tModLoader bug.
			var slots = new int[] {
				GetSoundSlot(SoundType.Music, "Sounds/Music/CrystalKing"),
				GetSoundSlot(SoundType.Music, "Sounds/Music/CrystallineFlows")
			};
			foreach (var slot in slots)
			{
				if (Main.music[slot].IsPlaying)
				{
					Main.music[slot].Stop(Microsoft.Xna.Framework.Audio.AudioStopOptions.Immediate);
				}
			}

			base.Close();
		}
```

**Comment by Chicken-Bones** [comment]
Fixed in 7d024a1cc79cb0335369903afa857ceb44900e8b
