### ISSUE TITLE
Netplay.InnerClientLoop eats up CPU

### ISSUE THREAD

**Issue by sgkoishi** [tModLoader/tModLoader#789]
### Description
https://github.com/tModLoader/tModLoader/blob/4fe763464018d8b886a27c7024fa7e078fd6d3f7/patches/tModLoader/Terraria/Netplay.cs.patch#L53-L58
The `InvokeOnMainThread` creates a Task, `Enqueue` it and `Wait` in the current thread. 
According to [MSDN](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.wait?view=netframework-4.8#System_Threading_Tasks_Task_Wait),
> If the current task has not started execution, the Wait method attempts to remove the task from the scheduler and execute it inline on the current thread.

This means the task will be executed in the current thread where it calls `InvokeOnMainThread`, not the main thread.
So the following two changes do nothing
https://github.com/tModLoader/tModLoader/blob/4fe763464018d8b886a27c7024fa7e078fd6d3f7/patches/tModLoader/Terraria/Netplay.cs.patch#L113-L114
https://github.com/tModLoader/tModLoader/blob/4fe763464018d8b886a27c7024fa7e078fd6d3f7/patches/tModLoader/Terraria/Netplay.cs.patch#L155-L184

The second part of the problem is the removal of `Thread.Sleep`
https://github.com/tModLoader/tModLoader/blob/4fe763464018d8b886a27c7024fa7e078fd6d3f7/patches/tModLoader/Terraria/Netplay.cs.patch#L130
Without sleep, the client loops actually become
```
while true
    CheckBytes in the current thread
    // Thread.Sleep removed
```

### Expected behavior 
tModLoader's CPU usage is at a regular level.

### Actual behavior
One thread is eating up CPU for the infinite CheckBytes without sleep.

### Additional Information
Credit to @qq1176321897

**Comment by Mirsario** [comment]
Resolved with #1272.
