### ISSUE TITLE
GlobalNPC.SetChatButtons not working

### ISSUE THREAD

**Issue by NezbednikSK** [tModLoader/tModLoader#800]
### Description

When i make a GlobalNPC file, i can't do SetChatButtons.

### Log File

"No suitable method found to override"

### Steps to Reproduce

1. I created a file named "ShardiesGlobalNPC.cs"
2. I added "public override void SetChatButtons"
3. On compile & in Visual Studio it says the thing i wrote in the log file section

### Expected behavior 

It should change the NPC's buttons to "Guide is" and "slick!"

### Actual behavior

It doesn't let me compile because of that error

### Reproduction frequency

Every time I try.

### Additional Information

I got nothing to say.

**Comment by JavidPack** [comment]
It's not that it is "not working", but rather that method does not exist in GlobalNPC.

In terms of being accommodating to multiple mods, a potential GlobalNPC.SetChatButtons method is impossible, so we won't be implementing it. We strive to make sure that every hook we implement properly handles multiple mods attempting different behaviors, and it is not feasible for GlobalNPC.SetChatButtons
