### ISSUE TITLE
TML crashing upon opening  "Browse Mods" menu

### ISSUE THREAD

**Issue by GraveLordNito25** [tModLoader/tModLoader#805]
After the latest update, I click browse mods and the game crashes

### Log File
[client-crashlog.txt](https://github.com/tModLoader/tModLoader/files/4288875/client-crashlog.txt)

### Steps to Reproduce
1.Launch Game
2. Click Browse Mods
3. Game instantly crashes

### Expected behavior 
Game should load the browse mod menu

### Actual behavior
Game is crashing

### Reproduction frequency
I have produced this error 3 times in a row
### Additional Information
Running latest version of TML, no mods installed

**Comment by JavidPack** [comment]
The log file the issue template asks for is in C:\Documents\My Games\Terraria\ModLoader\Logs, not clientcrashlog.txt (clientcrashlog.txt is pretty useless.)

Please post that file
