### ISSUE TITLE
install not working, very unhelpful error message

### ISSUE THREAD

**Issue by jackman-chan** [tModLoader/tModLoader#806]
I cant install using the installer, getting a different error message than all the ones in the faq
![image](https://user-images.githubusercontent.com/38991913/76011943-6d25c380-5ee3-11ea-8cef-b29ebb855194.png)

I don't think I'm doing anything wrong installing, I installed fine a few weeks ago on my other pc with no issues.
Theres also nothing in the tmodloader log files

**Comment by Jofairden** [comment]
Can you try a manual installation? 
https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players
Try step 5 instead of 4. It is recommended for now.

**Comment by jackman-chan** [comment]
well, I tried that  earlier and nothing about Terraria changed (with multiple launches from steam)

but this time, it just worked... 
something worth noting was that my internet was being funky when I tried earlier, so I was in offline mode on steam. idk if that could have anything to do with it
