### ISSUE TITLE
Mod Generator sets LangVersion to latest, causing issues for c# 8 features

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#814]
Since the generator sets the LangVersion to "latest", visual studio will allow usage of switch expressions, a new c# 8 feature. This will not compile in-game, causing confusion for the modder. We should make sure the generator sets it to "7.3" instead and consider prompting to upgrad old csproj that have "latest" set, as we do for other old csproj.

An example of code that appears to work but won't.
```cs
			int state = 1;
			int transition = 3;
			state = (state, transition) switch
			{
				(1, 3) => 1,
				(1, 4) => 2,
				(2, 3) => 1,
				(2, 4) => 2,
				_ => throw new InvalidOperationException()
			};
```

**Comment by GUZZ07** [comment]
It seems that more than one person encountered this problem
