### ISSUE TITLE
Disable All button in Mods menu disables all mods, even when they are not enabled.

### ISSUE THREAD

**Issue by Plantterror** [tModLoader/tModLoader#815]
### Description
Mods that aren't enabled will still get disabled when pressing the "Disable All" button in the Mods menu. This can end up causing a lag spike if you have more than 100 mods in the folder.

### Log File
https://cdn.discordapp.com/attachments/534215632795729922/689539123954188512/client.log
(Example log file to showcase)

### Steps to Reproduce

1. Go into the mods menu while some mods are not enabled.
2. Press Disable All 
3. Check the log file.

### Expected behavior 
Mods that are enabled should only be disabled.

### Actual behavior
All mods are being force disabled.

### Reproduction frequency
Guaranteed.

### Additional Information
N/A for now

**Comment by Jofairden** [comment]
What kind of lag spike are you experiencing specifically? That _should_ not happen

**Comment by Plantterror** [comment]
It was unresponsive for about the time it took to disable every mod.

**Comment by Chicken-Bones** [comment]
Do you still get the lag spike with no mods enabled?
Can you show us a profiling report?
