### ISSUE TITLE
.cs File for SimpleAccessory

### ISSUE THREAD

**Issue by eloterito** [tModLoader/tModLoader#817]
It would be helpful to see how you get one item to load two layers separately

**Comment by JavidPack** [comment]
The AutoloadEquip attribute for that class shows how that is done:
```cs
		// Assigning multiple EquipType/Animation textures is easily done.
		[AutoloadEquip(EquipType.Neck, EquipType.Balloon)]
```
https://github.com/tModLoader/tModLoader/blob/master/ExampleMod/SimpleModPlayer.cs#L49

**Comment by eloterito** [comment]
ah, thank you so much
