### ISSUE TITLE
Server hung for more than 10 seconds. Cannot determine cause on Mono

### ISSUE THREAD

**Issue by FredrikM97** [tModLoader/tModLoader#820]
## Description

Server keep repeating "Server hung for more than 10 seconds. Cannot determine cause on Mono" after spawning multiple bosses. Also happens when multiple items is on the ground. Server get stuck and needs restart in order to work again.

### Log File
[server.log](https://github.com/tModLoader/tModLoader/files/4421074/server.log)
[client.log](https://github.com/tModLoader/tModLoader/files/4421075/client.log)

### Steps to Reproduce
1. Install  mono-complete
2. Run tModLoaderServer.exe on Ubuntu 18.04.4
3. Start client and login
4. Spawn bosses in this case I used Brain Storm and spawned ten of those. 
5. Server terminal should then start spamming with the error mentioned in description.

### Expected behavior 
Maybe some lag but otherwise the server should keep responding

### Actual behavior
Server stop responding, not possible to login, all players freeze and no longer possible to interact with the server.
When trying to connect the server displays **IP**  is connecting... and on client it gets stuck on Found server

### Reproduction frequency
At least once a day or when spawning more than 3 bosses. Can happen during pumpkin moon if not all mini bosses are killed instantly.

### Mods installed
* BattleHardenedNPC v1.4
* BossChecklist v1.0.15
* CalamityMod v1.4.3.2
* ElementsAwoken v1.3.12.2
* EAMusic v0.3
* EARetroMusic v0.1.1
* ThoriumMod v1.6.2.0
* Fargowiltas v2.0.1.4
* FargowiltasSouls v1.2.1.3
* JPANsBagsOfHoldingMod v1.4.2.1
* MagicStorage v0.4.3.5
* PureSpirit v0.1.1
* RecipeBrowser v0.8.5.1
* ShorterRespawn v1.0
* VeinMiner v1.3.1

**Comment by Chicken-Bones** [comment]
Probably a mod with poor performance code causing the server to hang. We could disable the message but not the lag, you'd have to find the mod responsible and contact that mod author. Unfortunately, as the messages says, we can't determine the responsible mod automatically.

**Comment by Solxanich** [comment]
Hello @FredrikM97 ,
I'm currently reviewing stale issues, and would like to confirm if you are still experiencing this issue in the latest version 0.11.8.1 of tModLoader.
If not, could you please close the issue?
If so, could you please provide commentary on Chicken-Bones's recommendation to check if a mod is causing it? Feel free to check out our Discord's support channel for quicker responses.

**Comment by GamerPP** [comment]
im having this issue on latest

**Comment by Solxanich** [comment]
@GamerPP - thanks for the comment. 

This issue is likely to remain closed as 1.3 is likely not to see any further updates, as 1.4 becomes the supported version & it does not use mono.

I would recommend seeking help in our discord's `#support` channel https://discord.gg/tmodloader . 
As Chicken-Bones noted, this is likely due to a mod, and the support personnel in that channel on discord would be the best point of contact for resolution.
