### ISSUE TITLE
Is the mod browser offline? I can`t search mods :(

### ISSUE THREAD

**Issue by Draixico** [tModLoader/tModLoader#823]
### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [And so on...]

**Comment by talentlessguy** [comment]
Same issue, also after clicking on a filter the whole game crashes

**Comment by JavidPack** [comment]
Yes it is. It will be back once it gets fixed. Don't ask when.

**Comment by talentlessguy** [comment]
@JavidPack, nice

by the way, just a recommendation: use multiple instances of Mod Browser API. If one is down, another instance should be picked, and so on.

Maybe it's dificcult to implement (to be sure they all use the same version of the database) but at least the chance of server to die will be lower.

I could try deploying an instance on Heroku if instructions are given :)
