### ISSUE TITLE
ModLoader.IsSignedBy not working on Mac/Linux

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#827]
On Mac (and possibly Linux), the `ModLoader.IsSignedBy` method doesn't work, causing mod syncing in multiplayer to fail.

As a workaround, it has been suggested to use the `onlyDownloadSignedMods` setting, but that doesn't work because `ModNet.ReceiveMod` will still fail.

A second workaround is to download and update all mods prior to joining the server, assuming the server is on the latest version of all mods as well.

This issue is likely a mono issue, but remains to be investigated/debugged. 

If this issue can't be figured out, maybe we can add checking `onlyDownloadSignedMods` in `ModNet.ReceiveMod` where the error is thrown.

**Comment by Chicken-Bones** [comment]
Can you provide me some replication instructions? Simply connect to a server on mac/linux where the server has a signed mod and the client has nothing?

**Comment by Chicken-Bones** [comment]
Closing as .NET 5 should fix this
