### ISSUE TITLE
player.moveSpeed can't exceed 24mph

### ISSUE THREAD

**Issue by Tarku** [tModLoader/tModLoader#838]
### Description
I have a problem.
I want to add boots that increases a lot the player's speed, so I used the float player.moveSpeed to do that.
I wanted the boots to increase the player's speed by 250% so I typed in the UpdateEquip void:
"player.moveSpeed *= 2.5f;".
Do anyone know how to prevent that ?

### Log file
It doesn't seem to be in the log file.

### Steps to reproduce

1. Make an example boots accessory without the AutoloadEquip(EquipType.Legs) with a dummy texture.
2. Add "player.moveSpeed *= 2.5f;" to the UpdateEquip function.
3. Test.

### Expected behavior 
The normal running speed of the caracter is 15mph, so the final result would be 37.5mph.

### Actual behavior
When I test the boots and I run, it is blocked at 24mph. Do anyone know how to prevent that ?

### Reproduction frequency
Everytime I test.

**Comment by JavidPack** [comment]
I think moveSpeed accelerates up to accRunSpeed. I'm not quite sure how the game moves from one to the next, but I do know that most boots in the game increase accRunSpeed, not moveSpeed. It seems like reading the source code and seeing how moveSpeed and accRunSpeed are used together would help you out. Basically, the game makes a distinction between moving and running, and you'll need to go off examples from the game to do it right. See the adaption guide in the wiki if you don't know how to search the source code.
