### ISSUE TITLE
Two errors occurring on multiplayer server  

### ISSUE THREAD

**Issue by DoobyDoobyMoo** [tModLoader/tModLoader#839]
![image](https://user-images.githubusercontent.com/62703683/80292817-7a16a480-8727-11ea-8eda-36545796e587.png)
![image](https://user-images.githubusercontent.com/62703683/80292830-acc09d00-8727-11ea-91fe-d48fbb7b57fa.png)
We have been experiencing horrid lag that may or may not be from connection issues. After entering hardmode we have been crashing more commonly with the second error showing. Interestingly, my server.log file doesn't seem to be updating. Any advice on how to fix this would be greatly appreciated. 
(edit: the first error was fixed by removing GREALM, but a similar message will now appear after players have joined.)

**Comment by Trivaxy** [comment]
Looks like either a connection issue or a mod hanging on a packet.
(Try removing boss checklist and see if it works, otherwise remove all mods and check if the issue persists)

**Comment by Solxanich** [comment]
Hello @DoobyDoobyMoo  ,
I'm currently reviewing stale issues, and would like to confirm if you are still experiencing this issue in the latest version 0.11.8.1 of tModLoader.
If not, could you please close the issue?
If so, could you please provide commentary on Trivaxy's recommendation to check if a mod is causing it? Feel free to check out our Discord's support channel for quicker responses.
