### ISSUE TITLE
ModWall setDefaults() Changing Vanilla Blocks

### ISSUE THREAD

**Issue by Q-0** [tModLoader/tModLoader#841]
I've been working on a small mod that creates 3 sets of blocks/walls, some of these utilize ModifyLight , Main.properties[Type]  stuff. however I have found that even though this setting is in a ModWall it appears to affect Vanilla blocks

Below is my mod wall code when this mod is installed crimtane Sand takes on some of the properties of the wall,  The sand no longer blocks light, glows and picks up the sparkle from tileshine. 

Changing this file then reloading does change the crimtane sand properties.  I think also I have a similar wall with less light and I think that's causing Orichalcum Ore to glow now. 

```
using Microsoft.Xna.Framework;
using Terraria;
using Terraria.ModLoader;
using static Terraria.ModLoader.ModContent;

namespace ClearGlass.Walls
{
    public class UltraBrightInvisiGlassWall : ModWall
    {
        public override void SetDefaults()
        {
            Main.wallHouse[Type] = true;
            Main.tileBlockLight[Type] = false;
            Main.tileNoSunLight[Type] = false;
            Main.tileShine[Type] = 1200;
            Main.tileShine2[Type] = true;
            Main.wallLight[Type] = true;
            drop = ItemType<Items.Placeable.UltraBrightInvisiGlassWall>();
            AddMapEntry(new Color(170, 170, 170));            
        }
       public override void ModifyLight(int i, int j, ref float r, ref float g, ref float b)
       {            
           r = 1.3f;
           g = 1.3f;
           b = 1.3f;
       }
    }
}
```

I need to try and rebuild this one from scratch to see if the problem goes away, (or shifts to other tiles) 

To reproduce: presumably unless it's "just my machine" if you build this mod and go to a crimtane desert you'll find a giant glowing sparkly pile of sand. 

[ClearGlass.zip](https://github.com/tModLoader/tModLoader/files/4540239/ClearGlass.zip)

[ClearGlass-Tmod.zip](https://github.com/tModLoader/tModLoader/files/4540251/ClearGlass-Tmod.zip)

**Comment by Mirsario** [comment]
> Main.tileBlockLight[Type] = false;
> Main.tileNoSunLight[Type] = false;
> Main.tileShine[Type] = 1200;
> Main.tileShine2[Type] = true;
This is just your code. You're modifying tile data arrays with a wall index (Type). Just remove those lines.

**Comment by Jofairden** [comment]
What Mirsario said above ^, this is not a bug in TML.
