### ISSUE TITLE
.targets file fails with ampersand &

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#844]
When writing to xml files, we need to escape the paths properly:
Change
`<TerrariaSteamPath>{tMLDir}</TerrariaSteamPath>`
to
`<TerrariaSteamPath>{System.Security.SecurityElement.Escape(tMLDir)}</TerrariaSteamPath>`

Without this fix, modders with special characters in the path to their tModLoader folder fail to load .targets references.

**Comment by Chicken-Bones** [comment]
Wow, & is a valid path character, the more you know.
