### ISSUE TITLE
[Suggestion] Allow the ModTile.Slope Hook to Work on Non-Solid Tiles

### ISSUE THREAD

**Issue by PieKing1215** [tModLoader/tModLoader#849]
### Description
The `ModTile.Slope` hook currently does not get called when hammering non-solid tiles, due to the check to `Main.tileSolid` in `Player.ItemCheck` (I believe):
https://github.com/tModLoader/tModLoader/blob/203f5e8d98d4b4f1a9206bd0c8b0ea30bf1b2bb9/patches/tModLoader/Terraria/Player.cs.patch#L5242

Sloping a non-solid tile is a useful hook to have, and would obsolete the hacky workaround currently used.

### What does this proposal attempt to solve or improve?
There are times when you may want to have custom hammer behavior on non-solid tiles,
as is seen in ExampleMod's Minesweeper tile:
https://github.com/tModLoader/tModLoader/blob/4bb65940e7928af8b6bf8fee30f935d37683505c/ExampleMod/Tiles/Minesweeper.cs#L18

Currently, there exists a workaround to this problem using a `ModPlayer` subclass, where in `PreItemCheck` and `PostItemCheck`, you set the tile's `Main.tileSolid` to be true and false, respectively.

However, since `PostItemCheck` is not called in certain scenarios, you need to do some additional checks to make sure the tile is not set to be solid when `PostItemCheck` can't revert it:

```
class HammerNonSolidPlayer : ModPlayer {
    public override bool PreItemCheck() {

        // hack so that a non-solid tile can be hammered
        // check that we have a hammer selected and that there is nothing on the mouse
        //   (since when mouseItem exists, PostItemCheck isn't called)
        Item selected = Main.LocalPlayer.inventory[Main.LocalPlayer.selectedItem];
        if (selected.hammer > 0 && Main.mouseItem.IsAir) {
            Main.tileSolid[mod.TileType("CoolNonSolidTile")] = true;
        }

        return base.PreItemCheck();
    }

    public override void PostItemCheck() {

        // reset the tile to be non-solid
        Main.tileSolid[mod.TileType("CoolNonSolidTile")] = false;

        base.PostItemCheck();
    }
}
```
Doing this operation lets `ItemCheck` allow you to hammer the tile without the tile being solid during collision.

This workaround is hacky, and it would be much cleaner for there to be a hook for this.
Additionally, more measures would need to be taken for this workaround to work for items on the mouse, since `PostItemCheck` is not called in that case.

### Which (other) solutions should be considered?
Alternatively to the existing `Slope` hook being expanded, a new hook could be added (like `SlopeNonSolid` or something).
However, since the `Slope` hook already has no behavior on non-solid tiles, it would make sense to just expand it.
The only situation where this change could cause unintended behavior is if some mod has the `Slope` function defined in their non-solid `ModTile`, and depends on the function not being called for some reason.
Additionally, mods currently using the workaround would not be _required_ to get rid of it, since the workaround would just have no effect (since `Slope` would be called anyway).

**Comment by Jofairden** [comment]
Good suggestion. Only need some investigating whether removing the check will cause any unintended behavior.

**Comment by Chicken-Bones** [comment]
I'm happy for this to go in the current tML if you want to pull request it. Otherwise it'll probably wait for 1.4

**Comment by PieKing1215** [comment]
Added in #2444 I believe
