### ISSUE TITLE
Mods not being available

### ISSUE THREAD

**Issue by LightningS3** [tModLoader/tModLoader#854]
So recently I've been trying to install some new mods but when i go the my currently installed mods none of the new ones show up. For example Thorium is big and usually takes time to load but its zooms past instantly. When i go into the terraria mods folder it shows up with all my other mods. I've try uninstalling the game and installing them all fresh and deleting all my terraria data but still nothing has changed. Also where the mods would normally display what it's about it would only say "there is a problem, try again"

**Comment by JavidPack** [comment]
For support questions, you should go to Discord: https://tmodloader.net/discord 

We can't really help you very effectively here.

**Comment by LightningS3** [comment]
k

**Comment by Jofairden** [comment]
Gonna close for now, discord is indeed the best place for this kind of problem. But let us know if you still have issues.
