### ISSUE TITLE
If i click on Search mods IT CRASHES

### ISSUE THREAD

**Issue by JJWattf** [tModLoader/tModLoader#867]
HEy there!

if i click on search Mods The whole client crashes and i need to restard Steam to start or even close terraria .... Please help!
![Terraria crash](https://user-images.githubusercontent.com/65015037/81392081-6a7f5e80-911e-11ea-81f1-36b0708e4c18.png)

http://prntscr.com/sd2o9w here is the Link if the screenshot wont work...

**Comment by Jofairden** [comment]
If you look at the error, you can see it's coming from the HamstarHelpers mod not tModLoader.
