### ISSUE TITLE
Resolution issue

### ISSUE THREAD

**Issue by DesolateNeb** [tModLoader/tModLoader#870]
### Description
 
When I load up tmodloader 64 bit, I have a resolution of 1280 by 720 which is my 2nd monitors resolution, however I am playing on my main. When I change it to my main monitors resolution (1920 by 1080) all is fine and I get the screen big and normal again as I am in fullscreen mode and so I have a bigger HUD size. However, when I go off of the game to check something like a mod wiki my screen goes back to 1280 by 720 and I can only change it on the menu on the title screen and not the in world menu. When it goes back to this resolution, I have the small hud which I find hard to fight bosses on etc. I have looked a while how to make tmodloader 64 bit make the game my main monitors size for a while but I cannot find how. Playing on windowed mode no matter the resolution always has the small HUD so I dont want to use it.

### Steps to reproduce

1. [First Step]
Load up terraria tmod loader 64 Bit
2. [Second Step]
Whenever, go out of the game to check something etc
3. [And so on...]
Go back on game and resolution is changed to a smaller size
### Expected behavior 

Resolution should stay 1920 by 1080

### Actual behavior

Whever I load up tmod loacder 64 bit the resolution is 1280 by 720 and always reverts back to this when tabbed out
### Reproduction frequency

Every time as it is not something I can seem to be able to fix
### Additional Information

![Small HUD](https://user-images.githubusercontent.com/65116180/81498772-b5d07300-92be-11ea-9535-ab8b18ca1570.png)
This is what happens when the resolution goes to 1280  by 720 where there is a smaller HUD
![Big HUD](https://user-images.githubusercontent.com/65116180/81498981-ed8bea80-92bf-11ea-94e0-d2baea09c3b9.jpg)
This is what happens when I manually change the resolution to 1920 by 1080 where there is a normal sized HUD. I have had to take the picture with my phone as using lighshot which is what I used for the others instantly makes it the small HUD because it goes off of the game.
![Tabbed out](https://user-images.githubusercontent.com/65116180/81498784-bd901780-92be-11ea-8d6c-f07273e73f31.png)
This is a picture of the terraria 64 bit log. When it says changed to 1920 x 1080 thats where I manually change it and whenever I go off the game for any ammount of time it automatically changes to 1280 by 720
![image](https://user-images.githubusercontent.com/65116180/81499519-1e6e1e80-92c4-11ea-84aa-980c4cf3a0d7.png)
My 2nd monitor is actually 1440 by 900 but I know terraria thinks its 1280 by 720 because windows detects my 2nd monitor as the same name the logs do

**Comment by Jofairden** [comment]
Sounds like an odd driver issue or something
What happens when you unplug the other monitor?
(Also a kind reminder that you're technically in the wrong place, we do not create the 64 bit edition of tModLoader and we do not provide any support for it)

**Comment by DesolateNeb** [comment]
Hey Jofairden, I could not comment as I made my account 2 days ago but I can reply now, sorry to keep you waiting and sorry I did not know that 64 bit was supported here but thanks for the tip. When I unplug my 2nd monitor, with restart and without restart and with updating all my drivers nothing happens, though.

**Comment by Mirsario** [comment]
I definitely remember Dradon messing with the way fullscreen works (i.e. video modes, i.e. resolution) in his fork. If this doesn't happen for you on normal tML - close the issue and talk with him at [his discord](https://discord.gg/DY8cx5T).
