### ISSUE TITLE
ModWall/GlobalWall.CanPlace

### ISSUE THREAD

**Issue by direwolf420** [tModLoader/tModLoader#872]
### Description
ModWall/GlobalWall.CanPlace hook. For tiles, ModTile/GlobalTile.CanPlace already exists, and it's only checked in one place (when the player is about to place a tile). A similar section of code exists for placing walls, where this wall specific CanPlace can fit in.

### What does this proposal attempt to solve or improve?
Restrict wall placement.

### Which (other) solutions should be considered?
Just make walls more in line with tiles.

I was gonna make a PR but concidering 1.3.5.3 tml (and 1.4 vanilla) is just around the corner I made this issue instead for now. Who knows how much of the code changed related to this

**Comment by bhubatz** [comment]
This seems fnished?

**Comment by Steviegt6** [comment]
> 
> 
> This seems finished?

It is.
