### ISSUE TITLE
Camera mode ignores modded backgrounds

### ISSUE THREAD

**Issue by direwolf420** [tModLoader/tModLoader#876]
### Description
Being in a place where a modded background shows, then pressing F1 for camera mode, making sure "Capture background" is on, and doing a snapshot still shows the vanilla background.

### Steps to reproduce
Load Examplemod, place as many "Example Block" tiles as needed for the background to appear, press F1, select enough area to see the difference, press snapshot. Then compare against what you see ingame.

### Reproduction frequency
100%

### Additional Information
This happens with just `public override bool ChooseBgStyle() => true;` too, so not related to examplemod per say.

Screens (had to up contrast cause I took it during ingame night): https://prnt.sc/sgzmpk

**Comment by Jofairden** [comment]
I remember this being an issue I thought it was fixed, thx for report!
