### ISSUE TITLE
"Free Space" bar in Mod list is bugged and shows, I have negative space left.

### ISSUE THREAD

**Issue by JoeJoeTV** [tModLoader/tModLoader#879]
### Description

The "free space" bar in the Mod Menu shows, I have negative space left(even though there is enough free space on that drive) and the tooltip is drawn incorrectly.

### Log file

[client.log](https://github.com/tModLoader/tModLoader/files/4638634/client.log)

### Steps to reproduce

1. Open the Mod Menu

### Expected behavior 

Well, it should show the correct amount of available space and show the bar and the tooltip correctly

### Actual behavior

It shows the wrong amount of available space and the bar is being drawn to the left(negative I presume) and the tooltip is not being shown correctly.

### Reproduction frequency

Every time I go into the mod menu

### Additional Information

- Linux Mint 19.3 Cinnamon 64 bit
- Steam
- Note: I put the tModLoader files into another folder, so I can start it separate from vanilla Terraria.(I copied the vanilla files beforehand and then installed tModLoader into that folder; Then I added it to Steam as a non-Steam game; this has worked for me so far)
- Screenshot: (the red bar was also shown going from the left side of the menu to the left side of the screen sometimes, but I did't get a screenshot of that)
![Bildschirmfoto vom 2020-05-16 17-47-03](https://user-images.githubusercontent.com/34209417/82124140-62b65e80-979d-11ea-89bf-4c87f1af91c5.png)
![Bildschirmfoto vom 2020-05-16 17-50-07](https://user-images.githubusercontent.com/34209417/82124188-b0cb6200-979d-11ea-88c4-3338b26106ad.png)

EDIT: Got picture of bar going to the left:
![Bildschirmfoto vom 2020-05-16 17-53-35](https://user-images.githubusercontent.com/34209417/82124271-39e29900-979e-11ea-8207-144bf76a8f38.png)

**Comment by GoodPro712** [comment]
Does this still happen with 0.11.7

**Comment by JoeJoeTV** [comment]
Yes, it does happen in 0.11.7 too and 0.11.7 on Steam is in general a bit buggy.

**Comment by Jofairden** [comment]
That's odd, I cannot reproduce this

**Comment by Chicken-Bones** [comment]
If you can provide us with some instructions to replicate, using as few enabled mods as possible, we can probably fix it

**Comment by JoeJoeTV** [comment]
It still happens when I disable all mods or when I delete all tmod files, though it the shows like 500 mb available and 3 gb used still, so the bar isn't showing up again. I've also noticed, that the bar going to the left shows sometimes when I hover over some buttons, sometimes it stays, other times it doesn't.

To replicate, just start tModLoader and go to the Mods list. It happened on a fresh install on both steam and non-steam, also in 0.11.6.

**Comment by Chicken-Bones** [comment]
`[17:04:31] [1/INFO] [tML]: Running on Mono 4.6.1` might be a linux bug, will test

**Comment by JoeJoeTV** [comment]
I have mono 4.6.2 installed on my machine, but tModLoader uses it's own installation I presume. The installation this log is from, is a custom(no steam) install of 0.11.6, but when I start the Steam version 0.11.7.2, it also says that it runs on mono 4.6.1.

**Comment by Chicken-Bones** [comment]
Can you try updating your system mono and then clicking enable developer mode and update mono start scripts?

**Comment by JoeJoeTV** [comment]
I'm gonna try to install the newest version of mono via a repo. 
But tModLoader should work without a system mono, right, because I just uninstalled my system mono and it still shows as using mono 4.6.1, so that'll have to be the included one right?

**Comment by JoeJoeTV** [comment]
Ok, so I have now installed mono 6.8.0.123 and updated the scripts, but the problem is still there, nothing changed. There is also the problem, that I always have to kill tModLoader from system monitor, because the process keeps running, even when I hit exit in the menu and the Stop button in Steam doesn't work either.

**Comment by Mirsario** [comment]
Please check if this happens in 1.4 TML Alphas. You can find them in [our discord](https://discord.gg/RMZCqq6), or on the github actions tab.

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
