### ISSUE TITLE
0.11.7 GoG install doesn't work.

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#882]
Due to certain checks, the gog install will not work unless the user puts their Terraria_v1.3.5.3.exe file in the tModLoader install folder after installation.

We'll need to update the checks as Terraria bug-fix releases update.

Workaround:

To get Terraria_v1.3.5.3.exe, you'll need to downgrade to 1.3.5.3 in the GOG client, copy the Terraria.exe to a separate folder and rename it to Terraria_v1.3.5.3.exe, then update back to 1.4 and then install tModLoader. After that copy Terraria_v1.3.5.3.exe to the tModLoader folder. Finally, delete steam_api.dll. (Mac and Linux users see next post)

Pictures:
1: Click on this
![unknown (1)](https://user-images.githubusercontent.com/4522492/82128848-92546f00-977b-11ea-8ae0-da0b1da19c17.png)
2. Click on this, then uncheck "Automatically update to newest version". An option to download the 1.3.5.3 version should appear. Once this finishes, you are ready to back up the Terraria.exe as mentioned in the instructions above.
![unknown (2)](https://user-images.githubusercontent.com/4522492/82128845-85378000-977b-11ea-8cb7-a1f94f05be1b.png)

**Comment by JavidPack** [comment]
Linux users should delete lib/libsteam_api.so
Mac users should delete osx/libsteam_api.dylib

**Comment by Onyxeagle** [comment]
This still does not work for me, just directs me to the steam page, despite having GOG terraria.

**Comment by JavidPack** [comment]
We don't have any code in the game that opens the steam page. Not sure what is up there. We do have the terraria homepage opening up if the game was pirated, but not the steam page. Maybe the steam dll opens the page? Are you positive you deleted the files mentioned?

**Comment by Onyxeagle** [comment]
> We don't have any code in the game that opens the steam page. Not sure what is up there. We do have the terraria homepage opening up if the game was pirated, but not the steam page. Maybe the steam dll opens the page? Are you positive you deleted the files mentioned?

I probably should have added some clarification lol. It opens up the steam tmodloader's homepage. There was not any files to delete as I am on windows. (I could be mistaken on that, but I thought that you only deleted file on Linux and Mac?)

**Comment by Theo5607** [comment]
Same error here :( It's open steam...

**Comment by joeb2000** [comment]
Even after following all instructions it launches terraria 1.3.5.3 not 1.4. Am I missing something?

My folder structure is as so.

Terraria 1.4 install folder
\all normal installed stuff from 1.4
\Tmodloaderfolder
-\stuff from tmod zip (minus steam_api.dll)
-\renamed terraria 1.3.5.exe

But when launching tmodloader it launches 1.3.5.3, not 1.4. How do you launch 1.4 with mods?

**Comment by Jofairden** [comment]
> 
> 
> Even after following all instructions it launches terraria 1.3.5.3 not 1.4. Am I missing something?
> 
> My folder structure is as so.
> 
> Terraria 1.4 install folder
> \all normal installed stuff from 1.4
> \Tmodloaderfolder
> -\stuff from tmod zip (minus steam_api.dll)
> -\renamed terraria 1.3.5.exe
> 
> But when launching tmodloader it launches 1.3.5.3, not 1.4. How do you launch 1.4 with mods?

1.4 with mods does not exist yet, that comes at a later date..

**Comment by musicus-yn** [comment]
I have after unpacking modloader files opens a Terrarium, on top of the inscription "One player" there is a picture of a gear and the inscription "tmodloader", but I do not see either the section "Mods" or the section "Browser mods". What to do?

**Comment by 19928-po2** [comment]
Downgrading to 1.3.5.3 is no longer possible, as it is no longer an option in the installation configuration:

![print](https://user-images.githubusercontent.com/64035187/83004589-bf204600-a007-11ea-873f-ffd7e4c9b1c6.PNG)

**Comment by Jofairden** [comment]
I see. We do have updated hashes for the new 1.4 update. Stay tuned for a TML update, it should fix your install for GOG I think.

**Comment by Jofairden** [comment]
Should be fixed since 0.11.7.3
