### ISSUE TITLE
0.11.7 Dyes incorrect

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#884]
Looks like the shaders for dyes aren't matching up correctly. An example is Rainbow Dye, which appears green in-game.

We'll have to include the shader files most likely.

**Comment by Mirsario** [comment]
@JavidPack This is fixed by pasting PixelShader.xnb (and other shader .xnb files just in case) from 1.3.5.3 into tML's Content folder. Go do it for the next hotfix, can't just PR that myself.
