### ISSUE TITLE
How do you start TML 0.11.7 on GOG?

### ISSUE THREAD

**Issue by toshnika** [tModLoader/tModLoader#887]
There is no specified procedure in the installation instructions on how to launch. I tried to use the tModLoader script, which simply redirected me to the steam page for tModLoader, and both wine and mono failed to have any luck with opening the EXE directly

**Comment by perfiction** [comment]
If you are using GOG, just remove steam_api.dll from tModLoader directory, it should work afterwards.

**Comment by JavidPack** [comment]
See https://github.com/tModLoader/tModLoader/issues/882
