### ISSUE TITLE
Server Not Working

### ISSUE THREAD

**Issue by JuniorOdin** [tModLoader/tModLoader#888]
Hello, I am attempting to join a friend's server via the tmodloader on Steam. The issue is that the tmodloader runs in version 11.7 while the server runs in 11.6.2. Is there a way to fix this issue? Any help is appreciated.

**Comment by JavidPack** [comment]
Yes, your friend needs to update to the 0.11.7 server.

**Comment by Jofairden** [comment]
As said, you should update the server (if you want to play together, the versions should always match)
