### ISSUE TITLE
Can't enable developer mode

### ISSUE THREAD

**Issue by Tris5** [tModLoader/tModLoader#889]
nothing happens when I click enable developer mode

**Comment by Clickyz** [comment]
Same Here That's A Weird Gltich

**Comment by Ionta** [comment]
similarly, all day the developer tried to turn on the mode and failed

**Comment by Zauberfaedenpony** [comment]
same here

**Comment by GoodPro712** [comment]
Pressing 'Enable Developer Mode' is currently broken. A workaround you can do is create a folder names `Mod Sources` in `...\Documents\My Games\Terraria\ModLoader` then reload Terraria.

**Comment by Jofairden** [comment]
This is known, fixed in next update (soon)
