### ISSUE TITLE
Automatically Deletes Characters When I Return To The Title Screen

### ISSUE THREAD

**Issue by Clickyz** [tModLoader/tModLoader#891]
Well, I Was Working On My Calamity Playthrough When I Noticed A Bunch Of My Items Were Gone I Wasnt To Worried And I Went To Get Them Back I Went To The Jungle To Get A Boom Stick For One Of The Items And I Walk In The Jungle And BOOM All Of The Tiles In My World Is Gone All There Is, Is A Background I Went To Look For A Backup But It Was To Late All Of The Backups Were Corrupted And I Couldn't Get Them Back And I Was Not Too Sad Because I Thought My Character Was Fine But I Start A New World And I Can't Load It I Sesecpited It Was The Player Then I Went On Another Player And It Was Fine Then I Quit To The Title Screen Waiting For My Friend To Get On And I Look For My Character And It's Gone! It's Not There I Tried Again And Again I Reinstalled Uninstalled Deleted And Restored Original MyGame/Terraira Folder And Nothing Seems To Work And I Turned Off Steam Cloud Sync To See If That Worked Nothing Validated Files Nothing I've Been Trying For Hours At This Point, I Can Only Play Vanilla Terraria. Help plz

**Comment by Mirsario** [comment]
A translation:
> Well, I was working on my Calamity playthrough when I noticed a bunch of my items were gone. I wasn't too worried, so I went to get them back. I went to the jungle to get a boomstick for one of the items, and so I walked in the jungle, and BOOM! All of the tiles in my world were gone, there was nothing but a background. I went to look for a backup, but it was too late, all of the backups were corrupted and I couldn't get them back.I was not too sad, because I thought my character was fine, but I started a new world and I couldn't load it. I suspected it was the player then, I chose another player and it was fine. Then, I quit to the title screen, waiting for my friend to get on, and I looked for my character, and it was gone! It wasn't there. I tried again and again, I reinstalled, uninstalled, deleted and restored original `My games/Terraria` folder, but nothing seemed to work. I event turned off steam cloud sync to see if that worked, but no. Validating files didn't work either. I've been trying for hours at this point, I can only play vanilla Terraria. Please help.

**Comment by Mirsario** [comment]
Put the `My games/Terraria/ModLoader/Logs` folder into 1 archive (if you don't know how - use winrar or 7zip for that) and attach it here. This is most likely a mod issue.

**Comment by Clickyz** [comment]
@Mirsario Ok Does It Matter If The Mods Are Not Compiled Yet

**Comment by Jofairden** [comment]
Please upload logs

**Comment by Clickyz** [comment]
> Please upload logs

I Have Lost The Logs But I Think You Have Addressed This Once Or Twice Its Steam Cloud Seeming Delete Characters If I Don't Move It To Cloud Then It's Fine I Know Programming But No Networking So I'm Not Able To Catch A Hint But It's A Good Thing To Look Into

**Comment by Mirsario** [comment]
Duplicate #956 has way more information.
