### ISSUE TITLE
Stoping Mod Load Causes Boolean Override Instead Of Creating A Restore Point Then Returning

### ISSUE THREAD

**Issue by Clickyz** [tModLoader/tModLoader#892]
Read The Title

**Comment by JavidPack** [comment]
Can you explain this? I don't understand what this is talking about.

**Comment by Jofairden** [comment]
Very unclear and saying " read the title"  with a title that makes no sense and isn't clear does not help at all. Closing now, but if you can elaborate further than feel free to re-open.
