### ISSUE TITLE
Terraria: Error (tModLoader v0.11.7) steam version

### ISSUE THREAD

**Issue by alexandrage** [tModLoader/tModLoader#894]
Terraria: Error (tModLoader v0.11.7) steam version

System.0verf|owException:

a
MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETPlatform.GetFu
nctionPointermlethodBase method, RuntimeMethodHandle handle)

5
MonoMod.RuntimeDetour.Platforms.DetourRuntimelLPlatform.GetNativ
eStart[MethodBase method)

a MonoMod.RuntimeDetour.Detour._TopApply[)

5 MonoMod.RuntimeDetour.Detour.-RefreshChain[MethodBase
method)

5 MonoMod.RuntimeDetour.Detour.Applyl)

a MonoMod.RuntimeDetour.Hook.Apply0

5 MonoMod.RuntimeDetour.Hook..ctor[MethodBase from,
Methodlnfo to, Object target, HookConfigBL config)

5Terraria.ModLoader.Core.LoggingHooks.HookProcessStart[)

aTerraria.ModLoader.Logging.lnit[)

BTerraria.Program.LaunchGame[Stringfl args, Boolean monoArgs)

**Comment by GoodPro712** [comment]
If you are getting the `Arithmetic operation resulted in an overflow.` error and would like to help test a fix, download this zip, and place the files from within this zip into your `C:\Program Files (x86)\Steam\steamapps\common\tModLoader` folder, then try to launch tModLoader.
[Test.zip](https://cdn.discordapp.com/attachments/436261997416546305/711513703287095317/20051401Test.zip)

**Comment by Jofairden** [comment]
You can try what GoodPro said (I checked the files, they should be safe), fixed in next ver
