### ISSUE TITLE
Which Folder Should tModLoader be Placed in | GOG Version Mac

### ISSUE THREAD

**Issue by ajaygandecha** [tModLoader/tModLoader#895]
What folder should the tModLoader.app file be placed into to run on v1.4 GOG Version on MacOS?
When I export the .zip folder, it only creates the tModLoader.app file rather than multiple files, and this information isn't on the instruction page.

Thank you!

**Comment by Jofairden** [comment]
I does not matter, it can be placed anywhere (v0.11.7), you should run the tModLoader file inside tModLoader.app\Contents\MacOS

**Comment by Jofairden** [comment]
Also, read this: https://github.com/tModLoader/tModLoader/issues/882

**Comment by ajaygandecha** [comment]
Thank you! I’ll try it out, appreciate it
