### ISSUE TITLE
[Steam DLC] Cannot click the "Enable Developer Mode" button

### ISSUE THREAD

**Issue by rozbrajaczpoziomow** [tModLoader/tModLoader#898]
### Description
Cannot click the "Enable Developer Mode" button on homescreen.

### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [And so on...]

### Expected behavior 
Being able to click it

### Actual behavior
Well, I move the mouse over, click and nothing's happening
Tried also to create a new world, reinstall, etc., and nothing

### Reproduction frequency
Always

### Additional Information

![Screenshot](https://user-images.githubusercontent.com/58668179/82152164-c0ab7a80-985f-11ea-9d9b-2010ce5bc4db.png)

**Comment by Jofairden** [comment]
Duplicate: #886
Please check if an issue exists before posting

**Comment by Mirsario** [comment]
> A workaround you can do is create a folder named Mod Sources in ...\Documents\My Games\Terraria\ModLoader then restart tML.
