### ISSUE TITLE
Developer Mode won't work on Steam Version.

### ISSUE THREAD

**Issue by Glitchy-2** [tModLoader/tModLoader#900]
I recently got the Steam version of Tmodloader. I wanted to make my first mod, so I tried to click on the "Enable Developer Mode" button. Unfortunately, it didn't do anything when I clicked on it. The text didn't even turn yellow. I would like you to fix this because I had a great idea for my mod and I want to be able to make it.

**Comment by Jofairden** [comment]
Fixed next version, see https://github.com/tModLoader/tModLoader/issues/889 for a workaround.
