### ISSUE TITLE
Stoping Mod Load Causes Boolean Override Instead Of Creating A Restore Point Then Returning #892

### ISSUE THREAD

**Issue by Clickyz** [tModLoader/tModLoader#902]
When I Close Stop The Mod Compile It Causes A Boolean Override (Basically Crashing The Game) It Would Be Better If Tmodloader Went And Created A Restore Point Before The Compilation Causes An Assert So Quick Run Down The Tmodloader Creates A Restore Point Before The Mods Compile So If You Stop The Compile It Doesn't Crash So Sorry For The Last Description Of This Post I Thought I Put The Context I Need But Yeah Hope This Helps

**Comment by Jofairden** [comment]
Can you please not make duplicates? You already made an issue for this: https://github.com/tModLoader/tModLoader/issues/892 It's unclear in this issue for us what problem you're having, so you need to elaborate..

**Comment by Clickyz** [comment]
> Can you please not make duplicates? You already made an issue for this: #892 It's unclear in this issue for us what problem you're having, so you need to elaborate..

Sorry I Don't Really Know How To Do That I'll Research Sorry For That

**Comment by Jofairden** [comment]
Do you prefer speaking in another language? I can use a translator if you want

**Comment by Clickyz** [comment]
> Do you prefer speaking in another language? I can use a translator if you want

Its Ok I Only Know English

**Comment by Clickyz** [comment]
> Do you prefer speaking in another language? I can use a translator if you want

Sorry About The Inconvenience I'm Really Cocky

**Comment by Clickyz** [comment]
I'll Close This Issue

**Comment by JavidPack** [comment]
If you have a question, please come to the discord, we never understood what you were asking. tModLoader.com/discord
