### ISSUE TITLE
Couldn't find "Wave Bank.xwb" in the Steam tModLoader version

### ISSUE THREAD

**Issue by CircleCly** [tModLoader/tModLoader#905]
I was trying to replace the wave bank of the Steam tModLoader with my custom wave bank. However, I could not find the "Wave Bank.xwb" in the tModLoader game files. Assuming that tModLoader uses the vanilla soundbank stored locally, the wave bank should be somewhere on my computer. However, I could not locate it.

Maybe the soundbank is stored in some other way?

**Comment by JavidPack** [comment]
It uses the one in the Terraria install folder

**Comment by CircleCly** [comment]
@JavidPack I tested. The wave bank, if put in the tModLoader Content folder, will not be recognized by tModLoader.
But considering the fact that my Terraria has been updated to 1.4, how could tModLoader, based on version 1.3, still use the wave bank from a newer version? There certainly are new soundtracks added.

**Comment by Jofairden** [comment]
The new TML releases use the new content files from 1.4, so it'll use it from there. You'll have to replace it in the Terraria folder.

**Comment by JavidPack** [comment]
Maybe it would work if you copied in TerrariaMusic.xgs and Sound Bank.xsb from vanilla as well

**Comment by CircleCly** [comment]
I replaced the "Wave Bank.xwb" and it worked. Thanks!
