### ISSUE TITLE
Display offending mod name when a fatal exception happens

### ISSUE THREAD

**Issue by PoroCYon** [tModLoader/tModLoader#906]
### Description

A `StackTrace` can be [constructed from an `Exception`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.stacktrace.-ctor?view=netframework-4.0#System_Diagnostics_StackTrace__ctor_System_Exception_), of which the [frames can be walked](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.stacktrace.getframes?view=netframework-4.0), from where one can get the [Reflection MethodInfo](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.stackframe.getmethod?view=netframework-4.0) and thus the `Assembly`. From that, an `Assembly` -> mod lookup can be done. Inner exceptions may also have to be investigated.

I can make a PR if needed.

### What does this proposal attempt to solve or improve?

[This situation](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#begin-cannot-be-called-again-until-end-has-been-successfully-called) will become much easier to resolve.

### Which (other) solutions should be considered?

Leaving things as-is?

**Comment by Jofairden** [comment]
A PR would definitely be nice

**Comment by Jofairden** [comment]
You can look inside the LoggingHooks.cs file, it shouldnt be hard to add

**Comment by JavidPack** [comment]
Not every exception puts the game in a crash state, so the user will still need to check the logs, and the exception that caused the "Begin cannot be called again until End" exception will have already been logged, with the stacktrace mentioning the mod at fault already. Basically, the information is already in the logs, and that information wouldn't be around for these troublesome messages.

**Comment by PoroCYon** [comment]
Wouldn't `Logging.previousException` contain the relevant info?

**Comment by JavidPack** [comment]
We could probably just catch and handle these exceptions (and close spritebatch). Earlier before the exception logging was implemented to be on by default for all users, it was helpful to crash so modders would know that their bugs were important to fix, but now maybe it would be better to handle these errors more gracefully. 

previousException most likely has the correct exception, I'm not sure if there is a path where it might be wrong.

**Comment by Chicken-Bones** [comment]
I wish there was a better solution, but there's no way to _reliably_ detect the mod at fault when a crash happens, other than looking at the logs

**Comment by JavidPack** [comment]
Nothing actionable here, the current flow is fine, but other issues improving mod error logging might help with other side cases. Closing
