### ISSUE TITLE
tModLoader (Linux - Steam) - MissingMethodException from clicking Open Mod Sources

### ISSUE THREAD

**Issue by CDAGaming** [tModLoader/tModLoader#909]
### Description
On a new Installation of tModLoader in Steam, running on an NTFS External HDD for reference, on Ubuntu 20.04 LTS, a MissingMethodException is thrown when clicking Open Mod Sources for a newly created mod via the in-game gui.

Additionally, while not in the context of this specific error, at times the mono version being reported is inaccurate and requires a reboot of the game in order to display/detect properly.

### Log file
[client.log](https://github.com/tModLoader/tModLoader/files/4645628/client.log)

### Steps to reproduce
Steps to reproduce as well as the circumstances at which it occurs are noted in the description.

### Reproduction frequency

Both Issues occurring frequently, though the Mono Version inaccuracy is infrequent, only appearing for one session every so often.

### Additional Information

Attached System Information if needed, reported from Steam:
Computer Information:
    Manufacturer:  Unknown (Edit: Should be Acer)
    Model:  Unknown (Edit: Should be Acer Predator Helios 300 2018)
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    CPU Family:  0x6
    CPU Model:  0x9e
    CPU Stepping:  0xa
    CPU Type:  0x0
    Speed:  4100 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Ubuntu 20.04 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.4.0-29-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12008000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime_0.20200417.0

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 1060/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 440.64
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 144 Hz
    VendorID:  0x10de
    DeviceID:  0x1c20
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  2
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 13.54" x 7.60" (15.51" diag)
                                            34.4cm x 19.3cm (39.4cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 6144 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC255

Memory:
    RAM:  31955 Mb

VR Hardware:
    VR Headset: None detected

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  46677 Mb
    Largest Free Hard Disk Block:  18237 Mb

**Comment by Jofairden** [comment]
Very odd issue, will look into. Thx

**Comment by Chicken-Bones** [comment]
The log you've posted doesn't appear to be the one where you opened the mod sources menu. 
This looks like an issue with the newest Mono. We're working on a better way to handle which mono version runs, but can you try starting the `tModLoader-kick` file via cmd line?

If this works, I suggest downgrading your mono version (try 5.20)

It will be difficult for us to test Mono 6.13 at this time.

**Comment by CDAGaming** [comment]
@Chicken-Bones It appears that the actual error is much different then the one in the description, maybe due to running a newer tModLoader (As Issue was originally reported in 0.11.7, and this log is in 0.11.7.1)
[client.log](https://github.com/tModLoader/tModLoader/files/4651958/client.log)

**Comment by Chicken-Bones** [comment]
Ahh I see, can you check if the path `"/home/cdagaming/.local/share/Terraria/ModLoader/Mod Sources" ` exists?

**Comment by CDAGaming** [comment]
Yes, that path exists, lately I've been using Rider manually at that path to develop my mod

Additionally, in other findings this same bug, is present when clicking Open Mod Folder as well, and I can upload the log for that if needed

**Comment by JavidPack** [comment]
So, I'm not sure if linux has a consistent way to open folders. In tModLoader on linux, there is a script called `open-folder` that the game uses on linux to open your file browser. You can try the command in your terminal and see what it does, and possibly edit it to fit your linux distribution:

```
#!/bin/bash
export LD_LIBRARY_PATH="/usr/lib:/lib"
xdg-open $@
```

If we can figure out a fix and a way to detect which distribution it is, maybe we can add branching logic to this script to support more distributions. A quick google suggest that `nautilus` or `caja` commands might be what needs to be used on Ubuntu. 

Let us know what works, and if you know how to write the script, if you could figure that out too, that would be great.

**Comment by CDAGaming** [comment]
Since Terraria 1.4 was able to implement a way to open folders on Linux (For example via the Open Texture Packs folder button), maybe that implementation could be used within tModLoader?

Either way, I'll let you know the script results in a bit

**Comment by CDAGaming** [comment]
As for detecting with distribution is in use, while I don't have much experience with bash scripts, perhaps this could be of some use: https://askubuntu.com/questions/459402/how-to-know-if-the-running-platform-is-ubuntu-or-centos-with-help-of-a-bash-scri

**Comment by JavidPack** [comment]
I looked at the latest Linux release and the `open-folder` code is still the same. Can you check the execute permissions of the Terraria and tModLoaders copies of `open-folder`? Maybe we need to make sure open-folder is executable in our releases, if it isn't already

**Comment by CDAGaming** [comment]
Update: Initially when running open-folder, it didn't run, but not because of a permission issue:
bash: ./open-folder: /bin/bash^M: bad interpreter: No such file or directory

Looking this up described this as being unable to run because of failing to interpret **Windows** line endings (CR LF). Installing dos2unix and running the command "dos2unix ./open-folder" converted the file to the proper line endings and allowed it to be run

Will test if it now works in tModloader, but this may be the solution to this @JavidPack

**Comment by CDAGaming** [comment]
Update 2: Unfortunately it still fails in tModLoader, but running an example command, "./open-folder /", does work properly.

The short version of the current error is as follows:
[18:13:50] [1/DEBUG] [tML]: Process.Start (UseShellExecute = True): "/home/cdagaming/.local/share/Terraria/ModLoader/Mod Sources" 
[18:13:50] [1/ERROR] [Terraria]: System.ComponentModel.Win32Exception (0x80004005): Cannot find the specified file

**Comment by JavidPack** [comment]
Ok, so just to confirm, did you need to set it as executable to run `./open-folder`, after fixing the line endings?

**Comment by CDAGaming** [comment]
Yes, both Terraria's and TModLoader's open-folder are marked as executable and have read and write permissions beforehand. There was no further adjustment to permissions or the contents of the file besides line endings to make it function in terminal

**Comment by CDAGaming** [comment]
@JavidPack Please reopen this issue. In 0.11.7.2, this issue is still present. While it no longer crashes, the Open Mod Sources Button now just does nothing at all, which isn't really a resolution.

**Comment by CDAGaming** [comment]
There also isn't any logging anymore besides [12:05:22] [1/DEBUG] [tML]: Process.Start (UseShellExecute = True): "open-folder" /home/cdagaming/.local/share/Terraria/ModLoader/Mod Sources

**Comment by CDAGaming** [comment]
However, in further testing, the Open Mods Folder DOES now work, so it is partially resolved

**Comment by CDAGaming** [comment]
Edit:

Running the exact command from terminal, 
"./open-folder /home/cdagaming/.local/share/Terraria/ModLoader/Mod Sources"

Produced this error:
xdg-open: unexpected argument 'Sources'

**Comment by Jofairden** [comment]
This is likely due to the space in the folder name, and there is a similar issue for this: https://github.com/tModLoader/tModLoader/issues/624
