### ISSUE TITLE
UpdateMonoStartScripts outdated, prevents making mods on mac/linux

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#911]
UpdateMonoStartScripts assumes we still have the old install approach, since we are a separate program now, we can simplify the logic.

**Comment by JavidPack** [comment]
Turns out it was all fine, I just cleaned up a little in the last commit.

**Comment by Chicken-Bones** [comment]
Might want to make sure the manual install instructions still work, or specify to install tML to a different directory

**Comment by JavidPack** [comment]
It should, our install instructions are clear not to merge the folders and to install in a separate folder.
