### ISSUE TITLE
Cloud Saves not working

### ISSUE THREAD

**Issue by JavidPack** [tModLoader/tModLoader#913]
We are looking into this. In the meantime, don't use cloud save or your character or player will disappear.

**Comment by Jofairden** [comment]
I think it might be because of steam_appid.txt having the TML id, in Steamworks we are coupled to Terraria.. We should fix this asap

**Comment by Jofairden** [comment]
"C:\Program Files (x86)\Steam\logs\steam_api_log.txt"
[2020-05-19 22:19:06] [S_API WARN] CUserRemoteStorage::FileWriteStreamOpen( ModLoader/players\qqqq.plr ) - Max files exceeded. Can only store 80 files, tried to store 105

Fix: take over Terraria settings. Mailing Valve directly.
