### ISSUE TITLE
I am using GOG and it says to download steam to run it :(

### ISSUE THREAD

**Issue by GamerNinja123** [tModLoader/tModLoader#914]

**Comment by Jofairden** [comment]
I think we have to update GOG hashes, what OS are you on? Maybe you could help us out.

**Comment by Moreonenight** [comment]
> 
> 
> I think we have to update GOG hashes, what OS are you on? Maybe you could help us out.

I am using Win10 with GoG, and it seems that the tmodloader requires Terraria v1.3.5.3 to launch (with a workaround mentioned in this [issue](https://github.com/tModLoader/tModLoader/issues/882)). 

However, with this workaround I will be launching Terraria v1.3.5.3 with tmodloader, not 1.4.x. Is there any way to start a Terraria v1.4.x with tmodloader?

**Comment by JavidPack** [comment]
No tmodloader for 1.4 doesn't exist, that is coming in a few months.

**Comment by Moreonenight** [comment]
> 
> 
> No tmodloader for 1.4 doesn't exist, that is coming in a few months. We haven't made that yet.

OK. Thank you very much.

**Comment by Jofairden** [comment]
This should be fixed since 0.11.7.3
