### ISSUE TITLE
Reintegrating throwing into 1.4 TMODLoader?

### ISSUE THREAD

**Issue by IDGCaptainRussia94** [tModLoader/tModLoader#915]
### Description
While we all knew Throwing was getting thrown out the window in 1.4, many of us thought that thrown gear were just getting changed to ranged and we'd still have access to the code left in to mods for throwing gear, however I got curious and came across that the entire throwing code in Terraria was thrown out the window in 1.4. There is nothing left.
I and many people thought Relogic wouldn't do this as this is going to massively break alot of mods and doesn't really impact the game much to just leave the code in for backwards compatibility.

So I'm wondering, does TMODLoader have any plans to reintegrate the throwing code for all the mods that do use it? Or are we going to have to go the ways of Ranged damage or make our own throwing classes.

### What does this proposal attempt to solve or improve?
Many mods still use the internal throwing code and while of course these mods are going to have to be updated to 1.4 it would help the process alot especially all the mods that do use Throwing.

### Which (other) solutions should be considered?

I mostly just want to know what is going on so I and others can prepare our mods for 1.4, but I propose reintegrating the code if at all possible.

**Comment by Jofairden** [comment]
No plans as of yet no, but that won't mean mods can't do it. I personally don't think it's TML's place to re-add removed content, we should simply be a provider to make and play mods. Someone could make a mod and re-introduce throwing damage though.

**Comment by IDGCaptainRussia94** [comment]
Good to know, but if everyone mod makes their own version of throwing, this will get messy
I guess we wait and see

**Comment by Chicken-Bones** [comment]
Get a bunch of mod authors together, and work on a collaborative mod which brings back throwing, and you can all add it as a dependency!

**Comment by AmyMialee** [comment]
Yea it doesn't make sense for a modloader to do the work of mods

**Comment by IDGCaptainRussia94** [comment]
Understand, I've started work on mod to recreate throwing, and will update my mod and share it around soon enough for others to use
