### ISSUE TITLE
Mac TML not working, will windows 10?

### ISSUE THREAD

**Issue by Fuzzypants27** [tModLoader/tModLoader#920]
So I have a 9 tear old Mac OS, and me and my dad have decided to get a gaming pc to play terraria on. But I decided while I wait I’ll still get terraria.and I did and also downloaded TML with it, is why the mods wouldn’t download cause it’s old, or because I need windows? Please help me.

**Comment by Fuzzypants27** [comment]
Ok I made a error, I meant to say “I got TML with it and tried to download calamity and thourhim (sorry if I spelled it wrong) but it would say it’s download but no matter how many times I reloaded it it still wouldn’t say it’s downloaded or even download, it wouldn’t.” Ok well that’s the error if you do know why it wasn’t downloading or if I asked for any help on anything else, again I was downloading calamity and thourhim (sorry if I spelled it wrong again) thanks and have a good night or day, bye!

**Comment by Fuzzypants27** [comment]
Anther error I meant to say “but it wouldn’t say that it downloaded” 
Ok bye 100%for the last time.

**Comment by Jofairden** [comment]
In the meantime if the browser doesn't work for you then you can try this site: https://mirror.sgkoi.dev/
You'll have to place the .tmod files in the mods folder, ` /Users/account/Library/Application Support/Terraria`

**Comment by Jofairden** [comment]
Closed for inactivity. TML should work with Mac. Just make sure to download the Mac release if you aren't using Steam. Read the README if you install manually.
