### ISSUE TITLE
tModLoader can't be downloaded on a Steam account which has Terraria family-shared.

### ISSUE THREAD

**Issue by k1malex** [tModLoader/tModLoader#922]
If you try and download the tModLoader free DLC from Steam, it doesn't download as it needs you to own Terraria ON your account. The game is owned by my Brother and we family-share it so we both can enjoy it but as I want a modded experience I sadly can't due to family-sharing.
![image](https://user-images.githubusercontent.com/45134648/82503045-e8544a00-9ace-11ea-9b96-36766c116cf2.png) 
![image](https://user-images.githubusercontent.com/45134648/82503074-f904c000-9ace-11ea-9510-23192469e9de.png)

**Comment by Jofairden** [comment]
Duplicate: https://github.com/tModLoader/tModLoader/issues/881
Please follow the provided thread and search if a similar issue exists next time.
