### ISSUE TITLE
My

### ISSUE THREAD

**Issue by NirThod** [tModLoader/tModLoader#924]

**Comment by NirThod** [comment]
My 1.4 plr file dosen’t work on,tmodloader,but I copied a plr file from my android phone(It’s still 1.3).
So now the problem is solved. Sorry to disturb you. My sincere!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: JavidPack<mailto:notifications@github.com>
发送时间: 2020年5月21日 15:58
收件人: tModLoader/tModLoader<mailto:tModLoader@noreply.github.com>
抄送: NirThod<mailto:tencentkiller@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [tModLoader/tModLoader] My (#924)


Closed #924<https://github.com/tModLoader/tModLoader/issues/924>.

―

**Comment by Jofairden** [comment]
Correct, 1.4 uses new saves and there is no backwards compatibility. Glad the problem is solved.
