### ISSUE TITLE
Crash when rendering lunar pillar sprites on Mac/Linux with Mono 6.6.0.1

### ISSUE THREAD

**Issue by Shardion** [tModLoader/tModLoader#925]
### Description

Crash when rendering (presumably any of the) lunar pillar sprites on tModLoader v0.11.7.1 without any mods when running with Mono 6.6.0.1 on Mac/Linux.

### Log file

[client.log](https://github.com/tModLoader/tModLoader/files/4661348/client.log)

### Steps to reproduce

1. Kill the Lunatic Cultist
2. Enter the in-game Settings menu (the one with the `Save and Quit` button)

### Expected behavior 

In-game settings menu works like normal.

### Actual behavior

In-game settings menu appears to load like normal, yet crashes after a very short period of time.

### Reproduction frequency

100% of the time.

### Additional Information

This issue was tested using Cheat Sheet, and when you search `pillar` using Cheat Sheet, the game crashes. This leads me to think that it is a bug rendering the Lunar Pillars. I will test with no mods at all if asked.

This bug is **not** present on the version of Mono included with tModLoader.

**Comment by Jofairden** [comment]
@JavidPack  could you check if there is indeed something wrong?

**Comment by JavidPack** [comment]
On windows, cheat sheet spawning and viewing the pillars is working with no issues. Since the issue only happens on the updated mono, it's likely there is an issue there, not with cheat sheet or the content files. Maybe someone with linux experience will be able to determine the issue, but since we can't log all exceptions on mono, it's hard.

**Comment by CDAGaming** [comment]
While a Crash itself was not reproducable on my end (Linux with Mono 6.8.0.123), there was a bug found where when hovering over the Sola Pillar, the Cheat Screen UI would disappear until you moved your mouse away from it

**Comment by Chicken-Bones** [comment]
Sounds like a silently caught rendering exception, would really need to use Rider to debug it :/

Can you try running regular Terraria with system mono and see if you get the bug?

**Comment by TheAlcanian** [comment]
On it.

**Comment by TheAlcanian** [comment]
I have no idea how to run vanilla Terraria with my system Mono. I've tried things like `mono ./Terraria.exe` but nothing works. Is there some dark magic I have to do to use my system Mono with Terraria?

**Comment by direwolf420** [comment]
Funny coincidence, but might be related: Terraria 1.4.0.4 update had a fix:
Fixed Solar Pillar enemy’s bestiary page crashing the game on Linux.

**Comment by TheAlcanian** [comment]
It doesn't seem like we're getting anywhere with this, and it's not reproducible for others. Close?

**Comment by Mirsario** [comment]
Please check if this happens in 1.4 TML Alphas. You can find them in [our discord](https://discord.gg/RMZCqq6), or on the github actions tab.

If it does - make a new issue.

**Comment by flarn2006** [comment]
Can someone please reopen this? I can confirm this happens to me on Linux, tModLoader v0.11.8.5. Both the "Save & Quit" issue as well as searching Cheat Sheet for "pillar".

[client.log](https://github.com/tModLoader/tModLoader/files/7866545/client.log)
