### ISSUE TITLE
tmodloader not installing/initializing

### ISSUE THREAD

**Issue by BushyKitty** [tModLoader/tModLoader#926]
TModLoader isn't installing/initializing if your terraria is in a shared library, when you try do install or start, it goes to the store page of tmodloader.

**Comment by nihilisticzebra** [comment]
It’s been driving me nuts, I’m on Linux I have to manually install mods

**Comment by 41D4N** [comment]
> It’s been driving me nuts, I’m on Linux I have to manually install mods
I'm pretty sure you need to have Mono installed on Linux for the browser to work. It might have changed with the DLC but last time I was using Linux that was the case.

**Comment by Jofairden** [comment]
We're aware of the issue, follow #881 for progress
