### ISSUE TITLE
Vanilla green slimes and zombies acting weird after modding.

### ISSUE THREAD

**Issue by Tarzanell** [tModLoader/tModLoader#935]
### Description
 Hi everyone. I'm new to modding and i made my first big mistake. I'm not sure this is the right place to ask for help, so if this is the case, feel free to delete the request.
After testing one NPC i coded, all the vanilla green slimes and zombies started acting weird, completely ignoring the player and moving in only one direction. I tried disabling the mod, deleting the documents/terraria folder and even uninstalling and then installing again both terraria and tmodloader, but the bug persist.

### Code:
namespace Spaccas.NPCs
{
    public class Piskel : ModNPC
    {
        private const int sputa = 2;
        private const int corri = 1;
        private const int fermo = 0;
        private const int AI_State_Slot = 0;
        private const int AI_Timer_Slot = 1;
       private Vector2 pos;

        public float AI_State
        {
            get => npc.ai[AI_State_Slot];
            set => npc.ai[AI_State_Slot] = value;
        }

        public float AI_Timer
        {
            get => npc.ai[AI_Timer_Slot];
            set => npc.ai[AI_Timer_Slot] = value;
        }

        public override void SetStaticDefaults()
        {
            DisplayName.SetDefault("Goblo");
            Main.npcFrameCount[npc.type] = 18; // make sure to set this for your modnpcs.
        }

        public override void SetDefaults()
        {
            npc.width = 32;
            npc.height = 32;
            npc.aiStyle = -1; // This npc has a completely unique AI, so we set this to -1. The default aiStyle 0 will face the player, which might conflict with custom AI code.
            npc.damage = 7;
            npc.defense = 2;
            npc.lifeMax = 25;
            npc.HitSound = SoundID.NPCHit1;
            npc.DeathSound = SoundID.NPCDeath1;
            //npc.alpha = 175;
            //npc.color = new Color(0, 80, 255, 100);
            npc.value = 25f;
            npc.buffImmune[BuffID.Poisoned] = true;
            npc.buffImmune[BuffID.Confused] = false; // npc default to being immune to the Confused debuff. Allowing confused could be a little more work depending on the AI. npc.confused is true while the npc is confused.
        }

        public override float SpawnChance(NPCSpawnInfo spawnInfo)
        {
            return SpawnCondition.OverworldNightMonster.Chance * 0;
            //return SpawnCondition.OverworldDaySlime.Chance;
        }

        public override void HitEffect(int hitDirection, double damage)
        {
            for (int i = 0; i < 40; i++)
            {
                int dustType = Main.rand.Next(139, 143);
                int dustIndex = Dust.NewDust(npc.position, npc.width, npc.height, dustType);
                Dust dust = Main.dust[dustIndex];
                dust.velocity.X = dust.velocity.X + Main.rand.Next(-50, 51) * 0.1f;
                dust.velocity.Y = dust.velocity.Y + Main.rand.Next(-50, 51) * 0.1f;
                dust.scale *= 1f + Main.rand.Next(-30, 31) * 0.01f;
            }
        }

        public override void AI()
        {

            // Main.PlaySound(2, -1, -1, 59, 1f, +.2f);
            Lighting.AddLight(npc.position, 1f, 1f, 1f);
            Main.PlaySound(mod.GetLegacySoundSlot(SoundType.Custom, "Sounds/Custom/David3"), npc.position);

            if (AI_State == fermo)
            {
                npc.TargetClosest(true);
                AI_Timer++;
                if (AI_Timer == 20)
                {
                    Main.PlaySound(mod.GetLegacySoundSlot(SoundType.Custom, "Sounds/Custom/David3"), npc.position);
                    AI_Timer = 0;
                }

                if (npc.HasValidTarget && Main.player[npc.target].Distance(npc.Center) < 200f)
                {
                    AI_State = corri;
                    AI_Timer = 0;
                    //dir = npc.direction;

                }
            }
            if (AI_State == corri)
            {
                npc.TargetClosest(true);
                if (npc.HasValidTarget && Main.player[npc.target].Distance(npc.Center) < 200f)
                {

                    if(npc.position != pos)
                        npc.velocity.X = new Vector2(npc.direction * 2f, 0).X;
                    else
                        npc.velocity = new Vector2(npc.direction * 0, -3f);
                    pos = npc.position;

                    AI_Timer++;
                    if (AI_Timer == 50)
                    {
                        npc.frameCounter = 0;
                        AI_State = sputa;
                        AI_Timer = 0;
                    }

                 }
                else
                {
                    npc.velocity = new Vector2(0, 0);
                    AI_State = fermo;
                    AI_Timer = 0;
                }

            }
            if (AI_State == sputa)
            {
                npc.velocity = new Vector2(0, 0);
                AI_Timer++;
                if(AI_Timer == 60)
                    NPC.NewNPC((int)npc.position.X + Main.rand.Next(-100, 101), (int)npc.position.Y - 12, NPCType<Davidegg>());
                if (AI_Timer == 100)
                {
                    AI_State = fermo;
                    AI_Timer = 0;
                }
            }
        
        }

        public override void FindFrame(int frameHeight)
        {
            npc.spriteDirection = -npc.direction;
            npc.frameCounter++;

            if (AI_State == fermo)
            {
                if (npc.frameCounter < 10)
                    npc.frame.Y = 1 * frameHeight;
                else if (npc.frameCounter < 20)
                    npc.frame.Y = 2 * frameHeight;
                else if (npc.frameCounter < 30)
                    npc.frame.Y = 10 * frameHeight;
                else
                    npc.frameCounter = 0;
            }

            if (AI_State == corri)
            {
                if (npc.frameCounter < 10)
                    npc.frame.Y = 12 * frameHeight;
                else if (npc.frameCounter < 20)
                    npc.frame.Y = 13 * frameHeight;
                else if (npc.frameCounter < 30)
                    npc.frame.Y = 14 * frameHeight;
                else if (npc.frameCounter < 40)
                    npc.frame.Y = 15 * frameHeight;
                else if (npc.frameCounter < 50)
                    npc.frame.Y = 16 * frameHeight;
                else if (npc.frameCounter < 60)
                    npc.frame.Y = 17 * frameHeight;
                else
                    npc.frameCounter = 0;
            }

            if (AI_State == sputa)
            {
                
                if (npc.frameCounter < 10)
                    npc.frame.Y = 1 * frameHeight;
                else if (npc.frameCounter < 20)
                    npc.frame.Y = 2 * frameHeight;
                else if (npc.frameCounter < 30)
                    npc.frame.Y = 3 * frameHeight;
                else if (npc.frameCounter < 40)
                    npc.frame.Y = 4 * frameHeight;
                else if (npc.frameCounter < 50)
                    npc.frame.Y = 5 * frameHeight;
                else if (npc.frameCounter < 60)
                    npc.frame.Y = 6 * frameHeight;
                else if (npc.frameCounter < 70)
                    npc.frame.Y = 7 * frameHeight;
                else if (npc.frameCounter < 80)
                    npc.frame.Y = 8 * frameHeight;
                else if (npc.frameCounter < 90)
                    npc.frame.Y = 9 * frameHeight;
                else if (npc.frameCounter < 100)
                    npc.frame.Y = 10 * frameHeight;
            }

        }
    }
}

### Reproduction frequency
100%

### Additional Information
Only the basic slimes and zombies seems to be affected by the bug. The custom npc "Piskel", instead, works properly. Thank you in advance for the help.

**Comment by GoodPro712** [comment]
This is not the right place. A better place would be in tModLoader's Discord server in the #help-with-code channel.
