### ISSUE TITLE
Zoom problems

### ISSUE THREAD

**Issue by superericito** [tModLoader/tModLoader#939]
### Steps to reproduce

1. [First Step]
start up the game
2. [Second Step]
select character
3. [And so on...]
enter a world

### Expected behavior 

The zoom should be at 100 when set at 100

### Actual behavior

the zoom is set at 150 when set at 100

### Reproduction frequency

always

**Comment by Jofairden** [comment]
I cannot reproduce

**Comment by superericito** [comment]
I think it only happens to me but literally none in the discord responds ):

**Comment by Chicken-Bones** [comment]
please attach a client.log file, it's helpful to us in many ways. Also please test without any mods enabled and send screenshots.

**Comment by superericito** [comment]
nevermind, I managed to resolve it, to resolve it ytou just have to delete the my games terraria folder and install it again

**Comment by Jofairden** [comment]
Probably a broken config file
