### ISSUE TITLE
Mod Browser error on v0.11.7.3

### ISSUE THREAD

**Issue by Soulsparks** [tModLoader/tModLoader#942]
Even without any mods installed, entering the mod browser always gives this error:
```
Bad JSON: IncrementVersionTracking Query failed: Unknown column '0.11.7.3' in 'field list'
   em Terraria.ModLoader.UI.ModBrowser.UIModBrowser.PopulateFromJson(LocalMod[] installedMods, String json)
```

(using the Steam tModLoader version)
[client.log](https://github.com/tModLoader/tModLoader/files/4703510/client.log) for analysis.

**Comment by Yonoxyt** [comment]
same error. i sorta need help also

help pleaz

**Comment by saschahi** [comment]
just wait it out. it'll be fixed in the next few hours.

**Comment by Zemogiter** [comment]
Already fixed
