### ISSUE TITLE
"Mono.Cecil.AssemblyResolutionException" using specific DLL(s) while creating Mod

### ISSUE THREAD

**Issue by saschahi** [tModLoader/tModLoader#943]
### Description
With some specifc DLLs (see link in steps to reproduce) you get a Mono.Cecil.AssemblyResolutionException 
But only if not compiled/started through Visual Studio

### Log file
https://pastebin.com/jtW0h9Ek

### Steps to reproduce
https://github.com/saschahi/assemblytest
1. Download
2. Start/Compile from VS
3. See it works
4. Close game
5. Start tModLoader normally (With mod active)
6. Error

### Expected behavior 
Loading the Mod shouldn't Error out

### Actual behavior
The Mod errors out ONLY if tModLoader isn't started through Visual Studio.
Reloading while started through visual studio also doesn't error out.
Also doesn't error out if you start/compile a different mod and then activate it ingame.
If started through Visual Studio functionality of the assemblies is 100% there.

### Reproduction frequency
100%

### Additional Information
Running .Net 4.7.2

**Comment by saschahi** [comment]
Additionally to make it clear: it's not the DLLs that are broken. Using them to make mods for other games (for example Rimworld, they also use Mono) works fine.

**Comment by saschahi** [comment]
I now manually edited the Assembly I'm trying to use because of what I've been reading here: #896 

editing it so that the 2 other DLLs I'm using aren't reliant on this one anymore: https://github.com/TwitchLib/TwitchLib.Client/tree/1dc45145654ac467a7568c88770c0df258a2bedb/TwitchLib.Client.Enums

fixed it completely.

so what hamstar said here: https://github.com/tModLoader/tModLoader/issues/896#issuecomment-630698447

is 100% the case.

**Comment by Chicken-Bones** [comment]
Did you see https://github.com/saschahi/assemblytest/pull/1

**Comment by saschahi** [comment]
ooookay. that makes a lot more sense now.
