### ISSUE TITLE
Rename SoundType

### ISSUE THREAD

**Issue by Metacinnabar** [tModLoader/tModLoader#948]
### Description

Rename Terraria.ModLoader.SoundType as there is already an enum named SoundType at Terraria.Audio.SoundType

### What does this proposal attempt to solve or improve?

It's generally not good to have two of the same type names in one project. This can cause ambiguous reference errors which leaves the modder to use the namespace which may break consistency for their mod.

### Which (other) solutions should be considered?

Rename the Terraria.Audio enum

**Comment by Jofairden** [comment]
This is any issue in almost every codebase, as you can simply not avoid the name conflicts.... I'll see you again once you develop in PHP/Java... 😅

**Comment by JavidPack** [comment]
Recent sound changes have removed this.
