### ISSUE TITLE
Increase various low ID caps

### ISSUE THREAD

**Issue by gamrguy** [tModLoader/tModLoader#949]
### Description

There are several IDs with very low caps on them. Currently considered ones are:
- [x] Armor dyes (`Item.dye`, `byte` -> `int`)
- [x] Hair dyes (`Player.hairDye`, `byte` -> ~~short~~ `int`)
- [x] Item prefixes (`Item.prefix`, `byte` -> `int`)

(List may expand as more IDs come under our attention)
These IDs would be expanded as part of the 1.4 update to remove unnecessary limits on modding potential, and to avoid shakeups to existing 1.3 mods (as 1.4 is likely to require updates anyway).
### What does this proposal attempt to solve or improve?

Removes unnecessary limits on modding potential.
### Which (other) solutions should be considered?

It is possible to circumvent these limits through the creation/use of extra libraries (such as ShaderLib), though these solutions are not guaranteed to be compatible with everything.

**Comment by Mirsario** [comment]
Solved.

**Comment by XenonZe** [comment]
I still have prefix ID limits. What do I do to get around this

**Comment by Mirsario** [comment]
> 
> 
> I still have prefix ID limits. What do I do to get around this

The limit is only raised in 1.4 Alphas. Are you using them?

**Comment by XenonZe** [comment]
Sorry to comment after closure but I am having this issue too with prefixes. What were they raised to in the 1.4 alphas?

**Comment by JavidPack** [comment]
int, so about 2 million.

**Comment by genderneutralnoun** [comment]
Many people still play on 1.3. There needs to be a way to bypass the limit in 1.3, please.

**Comment by JavidPack** [comment]
1.3 won't receive this change, it would break the mods.
