### ISSUE TITLE
Remove Build All

### ISSUE THREAD

**Issue by GoodPro712** [tModLoader/tModLoader#953]
### Description

Remove the build all button in mod sources as it serves no real use.
I personally have never used the button in my year of modding.

### What does this proposal attempt to solve or improve?

This will improve tModlLoader by allowing space for a more useful button to put in its place.

### Which (other) solutions should be considered?

Keep it.

**Comment by Chicken-Bones** [comment]
Cast your votes people. I vote for keep.

**Comment by JavidPack** [comment]
I would never use it, and I hear a lot of people in the past lamenting accidentally clicking it.

**Comment by direwolf420** [comment]
I curse that and the "Build + Reload All" button each time I click it (which is rare), but I just Alt + F4 when that happens. Wouldn't be a problem if I only had a handful of mods there, but its something like 40.
People who maintain multiple mods (and possibly libraries), already use VS + csproj to handle building the libraries and mods for testing. For publishing, you would build each mod separately anyway to doublecheck that it works as intended, and then publish.
For tml version migration: You would have to go through each mod separately again, to fix/update the code necessary. 

Just my two cents

**Comment by Jofairden** [comment]
> I curse that and the "Build + Reload All" button each time I click it (which is rare)

Build + Reload all is very useful in my opinion, I use it all the time.

**Comment by GoodPro712** [comment]
I also meant this for Build + Reload All. Anything that builds all is pretty useless in my opinion.

**Comment by Jofairden** [comment]
> I also meant this for Build + Reload All. Anything that builds all is pretty useless in my opinion.

You always have to reload all mods when a mod is built, you cannot reload just one mod, it doesn't work like that.

**Comment by GoodPro712** [comment]
That's not what I said. I was meaning both these buttons were useless
![image](https://user-images.githubusercontent.com/45357714/83867279-85201400-a76c-11ea-8a87-248ae2b895e4.png)

**Comment by Jofairden** [comment]
Ah I see. Sorry I misunderstood

**Comment by Chicken-Bones** [comment]
Looks like the votes are in! Lets remove it.

**Comment by Steviegt6** [comment]
I wouldn't mind if it was removed, but TBH it doesn't really have to be removed if you just added a cancel button. I'm sure someone out there uses the button actively and we have nothing to replace it with as of now. Just my two cents though, IDRC either way, though.

**Comment by direwolf420** [comment]
Cancel button might work in a way where it will prevent the next mods' build, as iirc interrupting the build process of one mod isn't possible

**Comment by Jofairden** [comment]
Cancel will work, but the thing is if 99.99% of people don't use it, it's a dead useless feature. Let's remove it. (I mean I have never used it myself either)
