### ISSUE TITLE
[Enhancement] Make MessageBox texts localizable

### ISSUE THREAD

**Issue by sgkoishi** [tModLoader/tModLoader#955]
Some of the hardcoded texts should be localizable for translation.
Samples:
https://github.com/tModLoader/tModLoader/blob/4b1c029242e41ae822bf657db68edc7bdc75a877/patches/tModLoader/Terraria/Main.cs.patch#L802
https://github.com/tModLoader/tModLoader/blob/bdcd2e936692f36baf765c3dd752794b1d986824/patches/tModLoader/Terraria/Program.cs.patch#L225
Find more by searching `MessageBox`/`MessageBoxShow`/etc..

### What does this proposal attempt to solve or improve?
Add resources for those strings.
`LanguageManager` is loaded pretty early (at least before `SocialAPI`, and this sample is loaded after it), so we can simply add them to `Terraria.Localization.Content.[language].tModLoader.json`

**Comment by Chicken-Bones** [comment]
Sounds good. Hit us with that PR

**Comment by sgkoishi** [comment]
> 
> 
> Gonna do the same for the install verifier.

Here's a list of messages included in the PR:
* `ContentFolderNotFound` (`Main.PostSocialInitialize`)
* `MissingServerExecutable` (`Program.DisplayException`)
* `GraphicsEngineFailure` (`HiDefGraphicsIssues.ReportFatalEngineReload`)
* `GraphicsEngineReportUnknown`
* `GraphicsEngineReportFailure`
* `GraphicsEngineFailureMessage`
* `ContentFolderNotFoundInstallCheck` (`InstallVerifier.InstallCheck`)
* `VanillaSteamInstallationNotFound` (`InstallVerifier.CheckSteam`)
* `SteamAPIHashMismatch`
* `VanillaGOGNotFound` (`InstallVerifier.CheckGOG`)
* `GOGHashMismatch`
* Out of memory
