### ISSUE TITLE
Calamity Mod Characters Gone

### ISSUE THREAD

**Issue by Bigboipapa** [tModLoader/tModLoader#956]
### Description

When I deleted one calamity character, my other calamity character disappeared
### Log file

[client.log](https://github.com/tModLoader/tModLoader/files/4717509/client.log)

### Steps to reproduce

1. [First Step] Make a new character with the calamity mod, calamity mod music, FK Another boss health bar, and boss checklist
2. [Second Step] Open the bag that you get from calamity mod and put potions and the king slime summoner in a chest
3. [And so on...] Leave that world and delete the character you just made.
4. Then, Any previous character with those same mods enabled should disappear.

### Expected behavior 
 Only the character you delete should be gone.

### Actual behavior
 All characters made with the same mod enabled are gone.

### Reproduction frequency
 I wouldn't reproduce this because I would have to make progress on one character just to lose it all.

### Additional Information
 I have and extra hard drive which might be related. Good Luck! I hope that this gets fixed!

**Comment by Clickyz** [comment]
Same For Me What Fixed It Was The Steam Cloud If You Don't Move Your Character To Cloud Everything Should Be Fine Then You Can Store Your Character On Google Drive Or Something Hope This Helps

**Comment by JavidPack** [comment]
Stale issue, assumed to be fixed, closing.
