### ISSUE TITLE
Can't migrate vanilla character on latest version

### ISSUE THREAD

**Issue by devonpmack** [tModLoader/tModLoader#960]
### Description

When I click the migrate character button in the tmodloader to import vanilla characters from terraria, it correctly copies my character but it is corrupted and I can't load the character. Clicking play does nothing.

### Log file
[client.log](https://github.com/tModLoader/tModLoader/files/4725305/client.log)

### Steps to reproduce

1. Create vanilla character in vanilla terraria
2. Open tmodloader, copy over character files (or use the migrate button)
3. Characters are corrupted / can't be loaded
![image](https://user-images.githubusercontent.com/21130966/83671802-45f29700-a5a3-11ea-940b-a0d2065635e2.png)

### Expected behavior 

Should be able to open / load character

### Actual behavior

Can't open / load character from vanilla

### Reproduction frequency

Every time

### Additional Information

When I create a character through tmodloader it works as expected

**Comment by sgkoishi** [comment]
This is expected since you can see `v1.3.5.3`, which is the old version comparing to vanilla `v1.4.0.4`.
Just wait for tModLoader for 1.4.

**Comment by Jofairden** [comment]
Yeah this feature broke with the 1.4 update, I recommend not using it until we've updated.

**Comment by Jofairden** [comment]
There is a warning in the new release. Obviously migrating 1.4 saves will work again once we have updated TML to 1.4
