### ISSUE TITLE
When i load into a world i can not do anything

### ISSUE THREAD

**Issue by LethalMagikarp** [tModLoader/tModLoader#961]
### Description

whenever i load into a world, singleplayer or multiplayer, with mods enabled, i can't do anything.
### Log file

[client.log](https://github.com/tModLoader/tModLoader/files/4726602/client.log)

### Steps to reproduce

1. [First Step] open game
2. [Second Step] download mods
3. [And so on...] join any singleplayer or multiplayer world

### Expected behavior 
I should be able to play the game.

### Actual behavior
i can't move, i can't open my inventory or settings, nothing. also, if enemies try to attack me, they'd just phase right through me and do nothing. the only thing i can do is press alt+f4 to close the game  and talk in ingame chat.

### Reproduction frequency
every single time i load into the game. i've been able to fix it temporarily a few times so that i could play (more info below), but those only last for like a single login, then the issue returns

### Additional Information
mod list: https://pastebin.com/aagcpEmK
the bug doesn't happen when all of my mods are disabled.

what i've tried to fix the problem: restarting the game, reinstalling tmodloader, reinstalling both tmodloader and terraria, uninstalling all mods, installing mods one by one, restarting steam, rebooting my pc multiple times. i've tried with new characters, old characters, new worlds, old worlds, singleplayer, multiplayer. 

here's the times i actually got it working temporarily:
at first, i got it working by disabling everything, reenabling everything, and reloading by restarting the game instead of clicking "reload mods" in the mod browser. then that fix stopped working.

whenever i reinstalled both tmodloader and terraria, it worked for the rest of that day, then broke again the next day. but that fix is starting to not work. 

i've tried disabling and reenabling all mods one by one 3 times. (disable all, reenable the mods one by one, leaving them enabled until at the end, all mods are enabled). the first time, the game broke after i enabled item checklist. the second time, the game broke after enabling the last mod in the list, which happened to be alchemist npc. the third time, it actually worked and i was able to play, but then the bug happened again the next day.

this has also happened to 2 out of the 5 other people i'm playing with. it happened to the first guy once, and he fixed it by restarting his game. it happened to the second guy a few times, and he fixed it by reinstalling both tmodloader and terraria.

**Comment by syntience** [comment]
hi, friend of OP here. i'm the second guy mentioned in the post (bug happened to me a few times, fixed by reinstalling tml and terraria). i can help answer questions or test things if needed.

**Comment by sgkoishi** [comment]
Unable to repro. You may download the [pdbs](https://github.com/tModLoader/tModLoader/releases/download/v0.11.7.4/pdbs.zip) from the `Releases` page, which may help the developers find the error. 
Using these pdbs will add more details to your `client.log` (e.g. exact line number of crashing).

~~You can also try to remove `RecipeBrowser` since all exceptions in your log come from it~~

**Comment by syntience** [comment]
> 
> 
> Unable to repro. You may download the [pdbs](https://github.com/tModLoader/tModLoader/releases/download/v0.11.7.4/pdbs.zip) from the `Releases` page, which may help the developers find the error.
> Using these pdbs will add more details to your `client.log` (e.g. exact line number of crashing).
> 
> ~You can also try to remove `RecipeBrowser` since all exceptions in your log come from it~

where do we put the pdbs?

**Comment by JavidPack** [comment]
The error in the log seems to be RecipeBrowser, try without it

**Comment by LethalMagikarp** [comment]
> The error in the log seems to be RecipeBrowser, try without it

tried that. made a new character and world, but this time, the game breaks during world creation. if recipe browser is disabled, it broke when generating the jungle. when it was enabled, it broke when generating the dungeon. here's the log file from when it broke while generating the jungle (recipe browser disabled, but otherwise same mod list as above)


[client.log](https://github.com/tModLoader/tModLoader/files/4732792/client.log)

**Comment by sgkoishi** [comment]
> 
> 
> > Unable to repro. You may download the [pdbs](https://github.com/tModLoader/tModLoader/releases/download/v0.11.7.4/pdbs.zip) from the `Releases` page, which may help the developers find the error.
> > Using these pdbs will add more details to your `client.log` (e.g. exact line number of crashing).
> > ~You can also try to remove `RecipeBrowser` since all exceptions in your log come from it~
> 
> where do we put the pdbs?

You can copy the `WindowsRelease.pdb` and copy it to where `tModLoader.exe` is (something like `steamapps\common\tModLoader`), and rename it to `tModLoader.pdb`.

A quick note to @LethalMagikarp: You can enter the previous world with RecipeBrowser disabled - skip the world generation part (it's probably another problem).

**Comment by syntience** [comment]
sorry for taking so long. we downloaded the pdb files, and here's what we got:
recipebrowser enabled:
[client.log](https://github.com/tModLoader/tModLoader/files/4741309/client.log)
recipebrowser disabled (existing bug was fixed, but now his game runs at 5-10fps when it's usually at 50-60):
[client.log](https://github.com/tModLoader/tModLoader/files/4741310/client.log)

**Comment by JavidPack** [comment]
It seems that there are errors happening, probably every update, which would explain the FPS issue. I suggest narrowing your issue down by following the flowchart: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#flowchart

Also make sure to restart the game between tests, since bad mods can still break things after being disabled. 

This conversation will probably be better suited for the discord chat: tModLoader.net/discord

**Comment by FNGApex** [comment]
I had the same issue about 3 months ago, It is an Issue cause by Alchemist NPC Potions after drinking one my game would effectively become an image. Don't if it's the same issue here.
