### ISSUE TITLE
UICommon Internal Fields

### ISSUE THREAD

**Issue by GoodPro712** [tModLoader/tModLoader#969]
### Description

Make these fields in `UICommon` `public`.

![image](https://user-images.githubusercontent.com/45357714/83870991-8f451100-a772-11ea-9fe2-60473fbadde2.png)

### What does this proposal attempt to solve or improve?

Modders currently have to load the textures themselves or using reflection to access these fields which both can be avoided if they were `public`.

### Which (other) solutions should be considered?

Nope.

### Notes
I am happily able to PR this.

**Comment by Jofairden** [comment]
Not a bad idea.

**Comment by Jofairden** [comment]
I think they're internal in case modders make them null or whatever, so it's just a safety concern

**Comment by Jofairden** [comment]
Made them public, but with an internal setter.
