### ISSUE TITLE
Controller Issues - XB360, Steam Controller

### ISSUE THREAD

**Issue by grillinterrupted** [tModLoader/tModLoader#971]
Unable to play with xbox 360 controller or steam controller either locally or via steam link. unable to play with keyboard and mouse via steam link.

### Log file

No log was produced

### Steps to reproduce

1. plug in controller
2. load tmodloader
3. lose control

### Expected behavior 

controller should function

### Actual behavior

controller not recognized by game

### Reproduction frequency

100% of the time

### Additional Information

windows 10 pro. I also attempted to use via steam link and no control methods, including keyboard and mouse, or steam controller, worked.

**Comment by grillinterrupted** [comment]
update: I was able to get the xbox 360 controller working locally by disabling the steam overlay in the tmodloader settings in steam. steam controller still not working though.

**Comment by Jofairden** [comment]
I have a controller, I'll see if I can test this sometime

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
