### ISSUE TITLE
Missing Textures error even when using buildIgnore

### ISSUE THREAD

**Issue by GoodPro712** [tModLoader/tModLoader#972]
### Description

tModLoader still looks for images from a ModItem even if the folder that moditem is in is ignored via `buildIgnore`.

### Log file

N/A

### Steps to reproduce

Make a mod with a folder and put a class deriving from ModItem in it. Set buildIgnore in build.txt to ignore that folder.

### Expected behavior 

Throws error because no image was found with the ModItem.

### Actual behavior

The ModItem shouldn't be seen and thus shouldn't need an image.

### Reproduction frequency

100%

### Additional Information

This most likely works with other ModX classes.
I can get a test mod later if need be.

**Comment by JavidPack** [comment]
Yes, a test mod is necessary.

**Comment by Jofairden** [comment]
If this is true, good find. But yeah, a test mod would be neat. Can you get one for us?

**Comment by GoodPro712** [comment]
I've been a little busy but i'll get to it

**Comment by JavidPack** [comment]
The build.txt documentation has been updated to better show the correct patterns for ignoring a folder.
