### ISSUE TITLE
Cursor hidden in message boxes

### ISSUE THREAD

**Issue by Metacinnabar** [tModLoader/tModLoader#973]
### Description

When a message box shows up (most likely showing an error) the cursor becomes invisible.

### Log file

N/A

### Steps to reproduce

Make the game crash: `Main.instance = null`.
Hover over the message box
Wonder where your cursor went

### Expected behavior 

I should be able to see my cursor :)

### Actual behavior

I can't see my cursor :(

### Reproduction frequency
100.1%

### Additional Information

Probably caused by how Main.DrawCursor is unable to run when an error happens?

**Comment by GoodPro712** [comment]
Ahh my macro went wild

**Comment by Steviegt6** [comment]
Always figured that was just a quirk with my computer or something. :v
Didn't realize it was an actual issue.

**Comment by GoodPro712** [comment]
Ok, edited sorry for that

**Comment by Jofairden** [comment]
I know this issue, though it's not really an issue that causes a lot of trouble, I also don't know if we can do much about it? Not sure

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
