### ISSUE TITLE
Banner Buff doesn't Display Modded NPC Names

### ISSUE THREAD

**Issue by Steviegt6** [tModLoader/tModLoader#977]
### Description

The Banner buff doesn't display modded NPC names.

### Steps to reproduce

1. Place a banner from a mod (or make your own banner).
2. Hover over the Banner buff.

### Expected behavior 

The modded NPC's name should appear.

### Actual behavior

The modded NPC's name does not appear.

### Reproduction frequency

100%

**Comment by JavidPack** [comment]
Fixed in c9c172583dec4c5ffb5062251323ef652a6f3f55
