### ISSUE TITLE
Player clothes style flaps appear on legs while wearing modded body armor

### ISSUE THREAD

**Issue by gamrguy** [tModLoader/tModLoader#981]
### Description

**ALL** modded body armors show clothes flaps on the lower half of the body when worn with specific player clothes styles (male styles 4 and 5 and female style 4)
### Log file

Not something that appears in the log. No, really, it won't tell you anything, I looked.
But here's one anyway, I suppose. 
[client.log](https://github.com/tModLoader/tModLoader/files/4761294/client.log)

### Steps to reproduce

Equip literally any body armor from any mod (including tModLoader itself) while using player clothes style 4 or 5 (male) or 4 (female).

### Expected behavior 

Clothes flaps should not show.
### Actual behavior

Clothes flaps show.
### Reproduction frequency

100%
### Additional Information

Image of the bug in action:
![Annotation 2020-06-10 171709](https://user-images.githubusercontent.com/577969/84319754-84a5c580-ab3e-11ea-87c6-6f10b4cd0d49.png)

**Comment by Variable-X** [comment]
This same issue happens to me.

**Comment by direwolf420** [comment]
https://github.com/tModLoader/tModLoader/blob/8817b4e9da94bc13f8cca1b0ff7be605e9e0371a/patches/tModLoader/Terraria/Main.cs.patch#L3287

These patches are unreachable code, most likely causing this behavior

**Comment by JavidPack** [comment]
I can't seem to confirm this bug. When I equip a chest item, the robe flaps properly disappear. Send a .plr file I guess.

**Comment by cozykoko** [comment]
Have the same issue on my character. Can send my plr if still needed.

**Comment by Spoldozer** [comment]
Hello.
I couldn't help but notice how this thread hasn't been used for quite some time, and that the problem still requires solving. I am on a Windows 10 and have the latest version of tModLoader that is on steam (for Terraria 1.3.5), and I noticed while I was doing a Calamity Mod playthrough that I had inadverdently caused the same problem. I noticed this, and it made me think of this issue. I have provided a .plr file as has yet to be provided in this thread. It is in a .zip file due to the fact that Github does not support sending .plr files. I apologize in advance if this causes any problems.

[The_Expert.zip](https://github.com/tModLoader/tModLoader/files/6835444/The_Expert.zip)

**Comment by Steviegt6** [comment]
> 
> 
> Hello.
> I couldn't help but notice how this thread hasn't been used for quite some time, and that the problem still requires solving. I am on a Windows 10 and have the latest version of tModLoader that is on steam (for Terraria 1.3.5), and I noticed while I was doing a Calamity Mod playthrough that I had inadverdently caused the same problem. I noticed this, and it made me think of this issue. I have provided a .plr file as has yet to be provided in this thread. It is in a .zip file due to the fact that Github does not support sending .plr files. I apologize in advance if this causes any problems.
> 
> [The_Expert.zip](https://github.com/tModLoader/tModLoader/files/6835444/The_Expert.zip)

Issue was fixed a while ago, you're probably using some mod that messes with stuff or an outdated version of tML.

**Comment by cozykoko** [comment]
No this is not fixed in 1.3.5 TMod. Only the 1.4 branch fixed this.

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
