### ISSUE TITLE
Current Windows download contains older files?

### ISSUE THREAD

**Issue by LNBZero** [tModLoader/tModLoader#983]
Hello,

I've just wanted to update my tModLoader for the GoG version of Terraria which I've always done by just downloading the latest zip and extract it in the installation directory. Usually this is without any problems. But seems the current download:

https://github.com/tModLoader/tModLoader/releases/download/v0.11.7.5/tModLoader.Windows.v0.11.7.5.zip

... contains the files of tModLoader 11.6.3? Am I forgetting a step this time around? Or is there truly older files in the zip?

Thanks in advance!

**Comment by JavidPack** [comment]
I just double checked, the files are correct. You likely just didn't overwrite the existing files you had in the directory, or maybe you put them in a different folder than your previous tmodloader install. I'd check those things

**Comment by LNBZero** [comment]
I've done that right. Also just found the problem probably. Ever since 11.7 there's no Terraria.exe included in the zip anymore.

**Comment by JavidPack** [comment]
Yes, we've completely changed how install is done, now that the recommended install is through steam.

**Comment by LNBZero** [comment]
Ok, I understand that part. But how is the current procedure for GoG?

In the end I guess I could move my mods to the Steam version as I own both... However I've always kept mods on the GoG release since that one wasn't getting forced updates from Steam breaking all the mods.

**Comment by Jofairden** [comment]
Did you read the README file yet? The instructions are laid out there

**Comment by LNBZero** [comment]
The zip file contains no readme.

To clarify what I did:

1. In the past I downloaded the zip of an older version.
2. I renamed Terraria.exe to Terraria_v1.3.5.3.exe.
3. Mods worked fine for months.
4. I finished all the new content in 1.4 on Steam where I played unmodded with friends and decided to get back into mods.
5. I downloaded the zip of tModLoader for 11.7.5.
6. Extracted this in the installation folder of my GoG installation.
7. Confirmed to overwrite files.
8. In the game on the main menu it claims to still run on 11.6.3 and the mod browser mods all state I need 11.7.5.

And that's where we are now. I probably should've write this detailed before in my first post. It was late last night...

Thanks for the help and patience so far!

**Comment by JavidPack** [comment]
Sounds like you are installing into the Terraria folder, that is no longer the case: https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#manual-installation

But, since you mentioned that you have it on steam, just search steam for tModLoader, that is the recommended way, it'll keep your modded install separate from terraria.

**Comment by Jofairden** [comment]
Yeah we changed install steps, read the link that was posted above. Right now it's best to make a tModLoader folder in the Terraria dir and place all the files there. Also odd there's no README, there should be.

**Comment by LNBZero** [comment]
Finally weekend, sorry for the radio silence past days, work has been hectic trying to reboot after the lockdown period. I'm sure many can relate.

> 
> 
> Sounds like you are installing into the Terraria folder, that is no longer the case: https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#manual-installation
> 
> But, since you mentioned that you have it on steam, just search steam for tModLoader, that is the recommended way, it'll keep your modded install separate from terraria.


> 
> 
> Yeah we changed install steps, read the link that was posted above. Right now it's best to do a side-by-side install or nested. Also odd there's no README, there should be.

My apologies, it seems I was too hasty and just went business as usual not being aware of the new method. Great it can be side-by-side now!

That said however running tModLoader.exe I get an error saying the exe is invalid even after a clean install. I assume the newer versions of tModLoader are only for 1.4.x? Then again I also keep reading there's no tModLoader for 1.4.x yet which is why I been using the GoG version as it's not being forced to update to 1.4.x. Maybe I'm mixing up things somewhere so my apologies for that in advance.

**Comment by JavidPack** [comment]
The tModLoader on steam only works if your steam install has updated to 1.4. Same with manual install. Every way you can install tModLoader currently expects an existing up to date Terraria install. 

Again, all you need to do is install tModLoader via steam (assuming you haven't forced Terraria to not update)

**Comment by Jofairden** [comment]
Yeah I know it's a bit confusing, but TML isn't 1.4 yet, but it does need the 1.4 vanilla install. It just means TML is 1.3 when you launch it.

**Comment by LNBZero** [comment]
Last night got things to work. Thanks again to the both of you!
