### ISSUE TITLE
Anyone know what is going on?

### ISSUE THREAD

**Issue by Nuhbe** [tModLoader/tModLoader#986]
Hello, 

I have installed tModLoader on steam since the 1.4 Terraria release. Every time I try to load tModLoader, I get the same error message: 

https://imgur.com/uXja0BZ

Anyone know what's going on?

**Comment by JavidPack** [comment]
Seems like the Windows Defender issue: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#systemunauthorizedaccessexception-access-to-the-path-is-denied

**Comment by Nuhbe** [comment]
My Windows Defender is turned off. I use Bitdefender for antivirus. 
Even if I add an exception for tModLoader, I get the same error message.

**Comment by Nuhbe** [comment]
Oh! I found how to add the right exception in Bitdefender. 

Thank you.
