### ISSUE TITLE
Terraria crash when ever I click Single Player

### ISSUE THREAD

**Issue by Nuhbe** [tModLoader/tModLoader#988]
Hello, 

Even though all mods are disabled, when ever I click on Single Player, Terraria will crash, and will display Not Responding in the task manager.

I tried deleting all mods manually, but it still crashes every time I click Single Player.

Not sure what's up here.

**Comment by JavidPack** [comment]
Not sure, you can try temporarily moving the player files out of the ModLoader/Players folder, maybe one of the player files you have is crashing the game somehow. You will also want to disable all mods when you test, just to rule that out as well. You can post a client.log here or on discord if you can't figure it out from those tests.

**Comment by Nuhbe** [comment]
You where right! It works perfectly now. 

Thank you.
