### ISSUE TITLE
cant open tmodloader

### ISSUE THREAD

**Issue by hony9999** [tModLoader/tModLoader#989]
### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [And so on...]

**Comment by hony9999** [comment]
when i pused start game on steam , it just shows in game,then it will shut off in sveral seconds

**Comment by hony9999** [comment]
i have the legal version,but it also doesnt work

**Comment by JavidPack** [comment]
Can you post client.log? it might have a clue. You can also visit the discord chat for live support, which may be a lot quicker since this might take a lot of back and forth to figure out: tModLoader.net/discord

**Comment by hony9999** [comment]
thanks

**Comment by hony9999** [comment]
client -crashlog 



oComponent .FDoIdle (Int32grfidlef )
 
in

System .Windows .Forms .Application .ComponentManager .System .Windows .Forms .UnsafeNativeMethods .

IMsoComponentManager .FPushMessageLoop (IntPtrdwComponentID ,Int32 reason ,Int32 pvLoopData )

System .Windows .Forms .Application .ThreadContext .RunMessageLoopInner ( Int32reason ,

ApplicationContext context )

System .Windows .Forms .Application .ThreadContext .RunMessageLoop ( Int32reason ,

ApplicationContext context )

System .Windows .Forms .Application .Run (FormmainForm )

Microsoft .Xna .Framework .WindowsGameHost .Run

Microsoft .Xna .Framework .Game .RunGame ( BooleanuseBlockingRun )
Terraria .Program .LaunchGame _(

**Comment by hony9999** [comment]
this is the client log

**Comment by JavidPack** [comment]
This is not client.log. Look in the `%UserProfile%\Documents\My Games\Terraria\ModLoader\Logs` folder for the file named exactly client.log

**Comment by hony9999** [comment]
oh,i see

**Comment by hony9999** [comment]
i have fixed this issue by asking one of my friends a few minites ago ,But I still want to thank you for your enthusiasm.
