### ISSUE TITLE
tmodloader server wont start on linux

### ISSUE THREAD

**Issue by bgkillas** [tModLoader/tModLoader#990]
### Description
tmodloader server wont start on linux

### Log file
no log file seems to be created so terminal output
$ ./tModLoaderServer.bin.x86_64 
Can't find custom attr constructor image: data-0x1c639d0 mtoken: 0x0a000017 due to Could not load file or assembly or one of its dependencies. assembly:System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:<unknown type> member:<none>

Unhandled Exception:
System.TypeLoadException: Could not load type 'Terraria.ModLoader.Logging' from assembly 'Terraria, Version=1.3.5.3, Culture=neutral, PublicKeyToken=null'.
  at MonoLaunch.Main (System.String[] args) [0x00038] in <6b76d8833819447c82eb3fd94254f1f0>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'Terraria.ModLoader.Logging' from assembly 'Terraria, Version=1.3.5.3, Culture=neutral, PublicKeyToken=null'.
  at MonoLaunch.Main (System.String[] args) [0x00038] in <6b76d8833819447c82eb3fd94254f1f0>:0 

### Steps to reproduce
i assume every arch linux install is like this

### Expected behavior 
the server should run

### Actual behavior
the server is not running

### Reproduction frequency
everytime i launch the server

### Additional Information
um ig what packages i have installed would be useful
[packages.txt](https://github.com/tModLoader/tModLoader/files/4795829/packages.txt)

**Comment by Chicken-Bones** [comment]
Please make sure you have vanilla Terraria server installed in the same directory. For dedicated servers consider the following instructions https://github.com/tModLoader/tModLoader/wiki/Command-Line#linux

I also suggest you use `./tModLoaderServer` to run the server, rather than invoking the .bin file directly

**Comment by bgkillas** [comment]
oh it seems like i just needed to verify game files idk what happened
