### ISSUE TITLE
I can´t start tMod

### ISSUE THREAD

**Issue by Pyote8** [tModLoader/tModLoader#991]
[client-crashlog.txt](https://github.com/tModLoader/tModLoader/files/4810058/client-crashlog.txt)
When I try to star the game this message appears

**Comment by Jofairden** [comment]
It seems your install is invalid.
Make sure you have 1.4 Terraria (vanilla). If you are doing a manual install, read the README file for install instructions. You have to make a tModLoader folder and place all files inside.
