### ISSUE TITLE
Load error message goes off-window after a resize to a window size

### ISSUE THREAD

**Issue by pbone64** [tModLoader/tModLoader#994]
### Description
When a error is thrown during mod load, an error message appears. On tiny window sizes, this is cut off by the end of the window
![image](https://user-images.githubusercontent.com/47093312/85437136-ba3fab00-b54f-11ea-8cf4-b77d05f7eb24.png)

### Log file
Not applicable

### Steps to reproduce
* Open tModLoader
* Find a way to throw an error on load, such as making a dummy mod that's missing textures
* Resize the tModLoader window to a smaller size while the error is on screen

### Expected behaviour
The text should wrap so that it's all on screen

### Actual behaviour
The text goes off-window

### Reproduction frequency
All the time

### Additional Information
Not a very high priority issue, but a bug nonetheless

**Comment by JavidPack** [comment]
These menus all now properly resize the text content on window resize I believe. Closing.
