### ISSUE TITLE
Tmodloader Ancients Awakened and Beam Drill

### ISSUE THREAD

**Issue by ToLegitNames** [tModLoader/tModLoader#995]
Hello. I found out that if you use both (Ancients Awakened and Beam Drill Pack) then you cant craft the Beam Drills. If you do the game freezes and it will close. I hope it will get fixed soon because both mods are great!

**Comment by ToLegitNames** [comment]
Hi

**Comment by zauberparacelsus** [comment]
You should report that to the authors of those mods, that's not a tModLoader issue.

**Comment by ToLegitNames** [comment]
but how?

**Comment by zauberparacelsus** [comment]
Go to the threads for those mods on the Terraria forums and write a post about the bug.
