### ISSUE TITLE
removal of tremor mod resulted in all the mods items deloading but not disappering

### ISSUE THREAD

**Issue by aow-lizardshaman** [tModLoader/tModLoader#997]
dear reader. 
when tremor was removed from tmodloader v0.11.7.5 it left 10k+ in unloaded items in my magic storage system and im unsure of how to remove them help would be appreciated.

![20200625140004_1](https://user-images.githubusercontent.com/28312288/85795313-e6dcf980-b6ec-11ea-8cd7-e9ece78809aa.jpg)

**Comment by JavidPack** [comment]
This is a question for Magic storage, not tModLoader. Please direct your question to their github or website.
