### ISSUE TITLE
No Sound on Steam Native Linux Version

### ISSUE THREAD

**Issue by Ahndrek-LiCyri** [tModLoader/tModLoader#998]
### Description

As the title says, there is no music or sound at all when playing through the Native Linux version through steam.

### Log file

[client.log](https://github.com/tModLoader/tModLoader/files/4838947/client.log)
### Steps to reproduce

1. Open TModLoader using the "Native Linux" version

### Expected behavior 

There should be music and sound.
### Actual behavior

There is no music or sound.
### Reproduction frequency

Can reproduce every single time the game is opened.
### Additional Information

I have already confirmed that the system isn't muting TML and it should have access to all files needed.
I use Linux Mint 19.3 and have a Linux kernel version of 5.4.0-39-generic.

**Comment by direwolf420** [comment]
Do you have a sound device plugged in?

**Comment by Yayq** [comment]
I am also having the same issue. Did you manage to fix this?

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
