### ISSUE TITLE
ModConfig Sync Problem

### ISSUE THREAD

**Issue by zzp198** [tModLoader/tModLoader#999]
Now I'm writing a multiplayer mod with side is Both.
Many configurations are on the ServerSide;
My original idea is to use local configuration in single mode and server configuration in multi mode.But I had a problem.

In the [ModConfig document](http://tmodloader.github.io/tModLoader/html/class_terraria_1_1_mod_loader_1_1_config_1_1_mod_config.html)，It says '_ModConfigs can either be Client specific or Server specific. When joining a MP server, Client configs are kept but Server configs are synced from the server._'

According to the meaning of the document, the configuration of the server will be synchronized automatically when the load enters the multi mode.

But in fact, when I use GetInstance\<ServerConfig\> to get configuration, the configuration value is not server-side, but local. This causes the server configuration and local configuration to be out of sync.

The server configuration of each player cannot be unified. And even if I set AcceptClientChanges to false, they can still modify the configuration in the main interface and to enter the game with this configuration.

Maybe I can synchronize the configuration through ModPacket, but I want to use ModConfig to solve this problem  _(:з」∠)_.

Who can help me solve this problem? I can't get the configuration of the server.┭┮﹏┭┮

**Comment by zzp198** [comment]
I have also tested the server configuration of other mods. They are also out of sync with the local configuration. It seems that it is impossible to get the server configuration through ModConfig, but server.log Record _[1 / Info] [terraria]: sending server config_

**Comment by JavidPack** [comment]
This kinda thing is better suited for the discord chat, since it's likely an issue with your code. My guess, without seeing your code, is you forgot to set Mode to ConfigScope.ServerSide.

**Comment by zzp198** [comment]
I wrote a simple test based on ExampleWings.cs.

[ModConfigTest.zip](https://github.com/tModLoader/tModLoader/files/4842146/ModConfigTest.zip)

In this test, the server configuration is not synchronized normally and there is no error message in the log, which makes me confused.

It seems that I called GetInstance too early or in the wrong function.Can you give me more information? There is too little information about ModConfig on the wiki.

![LXZ58(C`W6DZ$@JE)5HX57](https://user-images.githubusercontent.com/43930552/85946350-6e896900-b976-11ea-8edd-dcf03fdb291d.png)
![GZJUC$5$0B4W~FI)U7OOA8X](https://user-images.githubusercontent.com/43930552/85946352-70ebc300-b976-11ea-9e7a-2f3166700b80.png)
![6JP5@2EPJFT3HMD0PLM)IHX](https://user-images.githubusercontent.com/43930552/85946354-72b58680-b976-11ea-8404-54c869c9ba9c.png)

**Comment by JavidPack** [comment]
Everything is working perfectly on my end. I would double check that you rebuilt the mod after your last changes and that you don't have an extra misnamed .tmod file in the Mods folder

**Comment by zzp198** [comment]
I found the cause of the problem. Once ReloadeRequired is added to the server configuration field, the client will initialize once after the configuration is completed, and the synchronized configuration will be lost. Here is my test video. This synchronization problem is driving me crazy.
[https://drive.google.com/file/d/1Gii7RrZeckMZ4mqBlk4Yj0Kr5nrXpl0W/view?usp=sharing](url)

**Comment by JavidPack** [comment]
interesting. We might have accidentally deleted something I guess. We'll look into this.
